/**
Copyright (c)2013 Instart Logic Inc

This software code is the property of Instart Logic, Inc and is subject to the
governing Terms of Use. Any use or copying requires the express written approval
of and/or license from Instart Logic. Instart Logic retains all proprietary
rights in the software code, and any use without Instart Logic's express
approval is regarded as a violation and misappropriation of its intellectual
property.

weekly-js-160-16493-cd89ab5
*/
if (typeof INSTART == 'undefined') {(function(){INSTART={};var __extends;function l(){return function(){}}function A(b){return function(){return this[b]}}(function(b){b.n;b.console;(function(b){(function(a){a.t})(b.a||(b.a={}));(function(a){a.ub;a.Pa})(b.xa||(b.xa={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));__extends=__extends||function(b,e){function a(){this.constructor=b}for(var d in e)e.hasOwnProperty(d)&&(b[d]=e[d]);a.prototype=e.prototype;b.prototype=new a};
(function(b){var e=function(){function a(b,m){this.Q=b;this.e=m}a.prototype.i=function(a){this.e=a};return a}();b.Oa=e;var a=function(a){function b(){a.apply(this,arguments)}__extends(b,a);b.prototype.i=function(b){a.prototype.i.call(this,"string"===typeof b?"true"===b:b)};return b}(e);b.La=a;var d=function(a){function b(){a.apply(this,arguments)}__extends(b,a);b.prototype.i=function(b){a.prototype.i.call(this,"string"===typeof b?parseInt(b):b)};return b}(e);b.zb=d;var h=function(a){function b(){a.apply(this,
arguments)}__extends(b,a);return b}(e);b.Lb=h;var g=function(a){function b(){a.apply(this,arguments)}__extends(b,a);return b}(e);b.Kb=g;e=function(){function b(a){function d(a,b){return"undefined"!==typeof a?a:b}b.r("ver");b.B("rId");b.B("iframeCommunicationTimeout",3E3);this.I=b.c("enableInterception");this.ba=b.c("enableOptimizedInterceptors",!0);this.v=b.c("enableCustomInterceptors",!0);this.da=b.c("useWrapper");this.ca=b.c("partialImage");this.$=b.c("aisao");b.r("apiDomain");b.c("enableHtmlStreaming");
b.r("htmlStreamingVersion");b.c("enable_hts_exec_script_in_head");b.c("enableInstantLoad");b.c("rum",!1);b.B("m_meb",0);b.c("enableMonitorData");b.c("enableProfiling");this.aa=b.c("enableHardAssert");b.q=this;this.qa=a;this.sa(a);for(var r=Object.getOwnPropertyNames(a),q=r.length-1;0<=q;--q){var e=r[q],h=a[e];(e=b.p[e])&&e.i(h)}b.p=null;this.w=d(this.w,this.$.e||this.ca.e);this.J=d(this.J,this.w);this.v.i(d(this.v.e,this.da.e||this.J));this.I.i(d(this.I.e,this.ba.e||this.v.e))}b.m=function(a){b.q?
a.i(b.q.qa[a.Q]):(b.p||(b.p={}),b.p[a.Q]=a);return a};b.c=function(d,e){return b.m(new a(d,e))};b.B=function(a,e){b.m(new d(a,e))};b.r=function(a){return b.m(new h(a,void 0))};b.va=function(){return b.m(new g("virtualizeDomains",void 0))};b.prototype.sa=function(a){var b=a.devJsExtraFlags;if(b&&b.trim()){for(var b=b.split(","),d=0;d<b.length;++d){var e=b[d].split(/=|:/);a[e[0].trim()]=e[1].trim()}a.devJsExtraFlags=""}};return b}();b.g=e})(INSTART||(INSTART={}));(function(b){(function(b){(function(a){var b=function(){return l()}();a.D=b})(b.A||(b.A={}))})(b.platform||(b.platform={}))})(INSTART||(INSTART={}));(function(b){(function(b){(function(a){a.Ka=function(){return function(){new a.D;new a.D}}()})(b.A||(b.A={}))})(b.platform||(b.platform={}))})(INSTART||(INSTART={}));(function(b){function e(a,b){a&&g.push(a);b&&m.push(b)}function a(a){if(n)b.console.warn("Init is already called");else if(n=!0,a=new b.g(a),b.g.c("skipInit").e)b.console.warn("Init is skipped by skipInit flag");else{for(var d=0;d<g.length;++d){var e=g[d];e&&e(a)}for(d=0;d<m.length;++d)(e=m[d])&&e(a)}}function d(a,e){var h=[],n=!1;if(!e)try{throw Error("error");}catch(f){return d(a+1,f)}try{if(e.stack){for(var g=e.stack.split("\n"),k=0,c=g.length;k<c;k++)g[k].match(/^\s*[A-Za-z0-9\-_\$\.\s]+\(/)&&
h.push(g[k]);n=!0}else if(window.opera&&e.message){g=e.message.split("\n");k=0;for(c=g.length;k<c;k++)if(g[k].match(/^\s*[A-Za-z0-9\-_\$]+\(/)){var p=g[k];g[k+1]&&(p+=" at "+g[k+1],k++);h.push(p)}n=!0}if(!n)for(var w=arguments.callee;w&&15>h.length;){var m=w.toString();h.push(m.substring(m.indexOf("function")+9,m.indexOf("("))||"anonymous");w=w.caller}h=h.slice(a)}catch(x){b.console.error(x)}return h}function h(){return window.console?window.console:{log:l(),warn:function(a){this.log("WARNING! "+
a)},error:function(a){this.log("ERROR! "+a)}}}b.Gb=l();var g=[],m=[];b.ib=!1;b.C=e;var n=!1;b.hb=a;if(window){var p=window.INSTART;p||(p=window.INSTART={});p.Init=a}e(l());b.Za=function(a,b){return b instanceof Object?a.replace(/\${(\w*)}/g,function(a){for(var d=[],f=1;f<arguments.length;f++)d[f-1]=arguments[f];d=d[0];return d in b?b[d]:a}):a};b.n=function(a,e,h){if(!a&&(b.console.error(e),a=2,void 0===a&&(a=1),a=d(a),b.console.log(a),b.g.q&&b.g.q.aa.e&&!h))throw e;};b.Ia=l();b.ab=d;b.Jb=h;b.console=
h()})(INSTART||(INSTART={}));(function(b){(function(b){(function(a){(function(a){a[a.Unknown=0]="Unknown";a[a.Chrome=1]="Chrome";a[a.Firefox=2]="Firefox";a[a.Msie=3]="Msie";a[a.Safari=4]="Safari"})(a.W||(a.W={}));(function(a){a[a.Unknown=0]="Unknown";a[a.Android=1]="Android";a[a.IOS=2]="IOS"})(a.ra||(a.ra={}));var b=function(){function a(b){b=b||navigator.userAgent;this.a=this.M(b,[{h:/MSIE\s([\d]+)(\.([\d]+))?(\.([\d]+))?/,d:3},{h:/Edge\/([\d]+)(\.([\d]+))?(\.([\d]+))?/,d:3},{h:/Trident.*rv:([\d]+)(\.([\d]+))?(\.([\d]+))?/,
d:3},{h:/Chrome\/([\d]+)(\.([\d]+))?(\.([\d]+))?/,d:1},{h:/Firefox\/([\d]+)(\.([\d]+))?(\.([\d]+))?/,d:2},{h:/Version\/([\d]+)(\.([\d]+))?(\.([\d]+))?.*Safari/,d:4}])||{d:0,N:0,P:0,O:0};this.R=this.M(b,[{h:/Android\s([\d]+)(\.([\d]+))?(\.([\d]+))?/,d:1},{h:/CPU OS ([\d]+)(_([\d]+))?(_([\d]+))?/,d:2},{h:/CPU iPhone OS ([\d]+)(_([\d]+))?(_([\d]+))?/,d:2}])||{d:0,N:0,P:0,O:0}}a.prototype.M=function(a,b){for(var d,e=0;e<b.length;++e){var r=b[e],h=r.h.exec(a);if(null!=h){d={d:r.d,N:parseInt(h[1])||0,P:parseInt(h[3])||
0,O:parseInt(h[5])||0};break}}return d};return a}();a.Ob=b;b=new b;a.a=b.a;a.R=b.R})(b.l||(b.l={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(e){(function(a){function d(a,b){var e=Object.getOwnPropertyDescriptor(a,b);if(!e){var h=Object.getPrototypeOf(a);if(h)return d(h,b)}return e}function h(){return 1===e.l.a.d}function g(){return 2===e.l.a.d}function m(){return 3===e.l.a.d}a.t=window;a.vb=window.localStorage;a.Ib=window.sessionStorage;a.u=document;a.Ja=window.Attr;var n=JSON,p=function(){function a(){}a.prototype.parse=function(a,b){return n.parse(a,b)};return a}();a.kb=p;a.H;a.pa;a.ua;a.S;a.ea;a.L;a.Node;a.V;
a.o;a.ia;a.Z;a.ga;a.j;a.ha;a.ja;a.ka;a.Ma;a.Y;a.X;a.Mb;a.yb={MODIFICATION:window.MutationEvent.MODIFICATION};a.XMLHttpRequest;a.cb=d;a.mb=h;a.sb=function(){return 4===e.l.a.d};a.pb=g;a.rb=m;a.na;a.ma;a.f=function(d,e){for(var h=d.split("."),g=a.t,f,n=0;n<h.length-1;n++)f=h[n],g[f]=g[f]||{},g=g[f];f=h[h.length-1];b.n(!!g&&!!f,"In ExportCall, obj or name not defined");g[f]=e};b.C(function(){function b(c){var d=c instanceof v;d||c.ownerDocument===a.u||(d=e(c));return d}function e(b){return b&&"object"===
typeof b&&b.nodeType===a.Node.ELEMENT_NODE&&"string"===typeof b.nodeName}function n(b){var c=b instanceof u;c||b.ownerDocument===a.u||(c=t(b));return c}function t(a){return a&&"object"===typeof a&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName}var f=document.head||document.createElement("a"),u=a.t.Node;a.H={addEventListener:document.addEventListener,createAttribute:document.createAttribute,createComment:document.createComment,createDocumentFragment:document.createDocumentFragment,createElement:document.createElement,
createEvent:document.createEvent,createNodeIterator:document.createNodeIterator,createTextNode:document.createTextNode,getElementsByTagName:document.getElementsByTagName,createTreeWalker:document.createTreeWalker,write:document.write,Tb:(c=d(document,"body"),c&&c.get)||A("body"),Yb:(c=d(document,"documentElement"),c&&c.get)||A("documentElement")};a.pa={key:window.localStorage.key,getItem:window.localStorage.getItem,setItem:window.localStorage.setItem,removeItem:window.localStorage.removeItem,clear:window.localStorage.clear};
a.ua={key:window.sessionStorage.key,getItem:window.sessionStorage.getItem,setItem:window.sessionStorage.setItem,removeItem:window.sessionStorage.removeItem,clear:window.sessionStorage.clear};a.S={addEventListener:window.addEventListener,getComputedStyle:window.getComputedStyle,removeEventListener:window.removeEventListener,gb:window.Image,JSON:new p,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,XMLHttpRequest:window.XMLHttpRequest};
a.L={addEventListener:f.addEventListener,dispatchEvent:f.dispatchEvent,removeEventListener:f.removeEventListener};var k=document.createEvent("Event");a.ea={wc:(c=d(k,"target"),c&&c.get)||A("target")};var c;a.Node={ELEMENT_NODE:u.ELEMENT_NODE,DOCUMENT_NODE:u.DOCUMENT_NODE,cloneNode:f.cloneNode,appendChild:f.appendChild,Qb:(c=d(f,"attributes"),c&&c.get)||A("attributes"),gc:(c=d(f,"nodeType"),c&&c.get)||A("nodeType"),fc:(c=d(f,"nodeName"),c&&c.get)||A("nodeName"),lc:(c=d(f,"parentNode"),c&&c.get)||A("parentNode"),
Zb:(c=d(f,"firstChild"),c&&c.get)||A("firstChild"),ac:(c=d(f,"lastChild"),c&&c.get)||A("lastChild"),nc:(c=d(f,"previousSibling"),c&&c.get)||A("previousSibling"),ec:(c=d(f,"nextSibling"),c&&c.get)||A("nextSibling")};k=document.createAttribute("src");c=d(k,"value");a.V={dc:(c=d(k,"name"),c&&c.get)||A("name"),xc:(c=d(k,"value"),c&&c.get)||A("value"),Nc:(c=d(k,"value"),c&&c.set)||function(a){return this.value=a},kc:(c=d(k,"ownerElement"),c&&c.get)||A("ownerElement")};a.o={getElementsByTagName:f.getElementsByTagName,
getAttribute:f.getAttribute,setAttribute:f.setAttribute,getAttributeNode:f.getAttributeNode,setAttributeNode:f.setAttributeNode,getAttributeNodeNS:f.getAttributeNodeNS,removeAttributeNode:f.removeAttributeNode};a.ia={vc:(c=d(f,"style"),c&&c.get)||A("style"),Fc:(c=d(f,"innerHTML"),c&&c.set)||function(a){return this.innerHTML=a},Wb:(c=d(f,"children"),c&&c.get)||A("children")};c=document.createElement("img");c=d(c,"src");a.ja={tc:c&&c.get||A("src"),Mc:c&&c.set||function(a){return this.src=a},getAttribute:a.o.getAttribute,
dispatchEvent:a.L.dispatchEvent,getElementsByTagName:a.o.getElementsByTagName};k=document.createElement("a");a.j={Ba:(c=d(k,"href"),c&&c.get)||A("href"),Ea:c&&c.set||function(a){return this.href=a},Aa:(c=d(k,"host"),c&&c.get)||A("host"),$b:(c=d(k,"hostname"),c&&c.get)||A("hostname"),Ca:(c=d(k,"protocol"),c&&c.get)||A("protocol"),Da:(c=d(k,"search"),c&&c.get)||A("search")};a.ha={getElementsByTagName:a.o.getElementsByTagName};k=document.createElement("style");a.ka={sc:(c=d(k,"sheet"),c&&c.get)||A("sheet")};
k=document.createElement("canvas");a.ga={getContext:k.getContext,toDataURL:k.toDataURL};k=k.getContext("2d");a.Z={drawImage:k.drawImage,getImageData:k.getImageData};f=f.style;a.Y={Xb:(c=d(f,"cssText"),c&&c.get)||A("cssText"),Ec:c&&c.set||function(a){return this.cssText=a},mc:(c=d(f,"parentRule"),c&&c.get)||A("parentRule"),getPropertyValue:f.getPropertyValue,setProperty:f.setProperty,getPropertyPriority:f.getPropertyPriority};a.X={Sb:(c=d(f,"backgroundImage"),c&&c.get)||A("backgroundImage"),Bc:c&&
c.set||function(a){return this.backgroundImage=a},Rb:(c=d(f,"background"),c&&c.get)||A("background"),Ac:c&&c.set||function(a){return this.background=a},Vb:(c=d(f,"borderImageSource"),c&&c.get)||A("za"),Dc:c&&c.set||function(a){return this.za=a},Ub:(c=d(f,"borderImage"),c&&c.get)||A("ya"),Cc:c&&c.set||function(a){return this.ya=a},cc:(c=d(f,"listStyleImage"),c&&c.get)||A("listStyleImage"),Hc:c&&c.set||function(a){return this.listStyleImage=a},bc:(c=d(f,"listStyle"),c&&c.set)||A("listStyle"),Gc:c&&
c.set||function(a){return this.listStyle=a}};f=new a.S.XMLHttpRequest;a.XMLHttpRequest={open:f.open,send:f.send,abort:f.abort,getResponseHeader:f.getResponseHeader,getAllResponseHeaders:f.getAllResponseHeaders,setRequestHeader:f.setRequestHeader,jc:(c=d(f,"onreadystatechange"),c&&c.get)||A("onreadystatechange"),Kc:c&&c.set||function(a){return this.onreadystatechange=a},ic:(c=d(f,"onload"),c&&c.get)||A("onload"),Jc:c&&c.set||function(a){return this.onload=a},hc:(c=d(f,"onerror"),c&&c.get)||A("onerror"),
Ic:c&&c.set||function(a){return this.onerror=a},uc:(c=d(f,"status"),c&&c.get)||A("status"),oc:(c=d(f,"readyState"),c&&c.get)||A("readyState"),qc:(c=d(f,"responseText"),c&&c.get)||A("responseText"),rc:(c=d(f,"responseType"),c&&c.get)||A("responseType"),Lc:c&&c.set||function(a){return this.responseType=a},pc:(c=d(f,"response"),c&&c.get)||A("response"),yc:(c=d(f,"withCredentials"),c&&c.get)||A("withCredentials"),Oc:c&&c.set||function(a){return this.withCredentials=a}};a.na=(h()||g())&&"function"===typeof u||
m()&&"object"===typeof u?n:t;var v=a.t.HTMLElement;a.ma=(h()||g())&&"function"===typeof v||m()&&"object"===typeof v?b:e})})(e.a||(e.a={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(b){(function(a){function b(a,e,m){if(!a||"object"!==typeof a)return a;e=Object.create(e||null);for(var n=Object.keys(a),p=0;p<n.length;p++){var r=n[p];m&&-1!==m.indexOf(r)||(e[r]=b(a[r]))}return e}a.zc;a.Na=b})(b.wa||(b.wa={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(b){(function(a){for(var b=[],e=[],g=0;127>g;g++)b.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)),e.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(String.fromCharCode(g)));a.K=function(a){for(var e="",g=0,h=0,q=0;q<a.length;q++)for(g=g<<8|a[q],h+=8;6<=h;)var s=g>>h-6&63,h=h-6,e=e+b[s];2==h?(e+=b[(g&3)<<4],e+="=="):4==h&&(e+=b[(g&15)<<2],e+="=");return e};a.G=function(a){var b,d,g=0,q,s=0,t=0;a=a.replace(/[^A-Za-z0-9\+\/\=]/g,
"");var f=[];do b=e[a.charCodeAt(t++)],d=e[a.charCodeAt(t++)],q=e[a.charCodeAt(t++)],s=e[a.charCodeAt(t++)],b=b<<2|d>>4,d=(d&15)<<4|q>>2,g=(q&3)<<6|s,f.push(b),64!=q&&f.push(d),64!=s&&f.push(g);while(t<a.length);return f}})(b.k||(b.k={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(e){(function(a){function d(a){B||(B=e.a.H.createElement.call(e.a.u,"A"));e.a.j.Ea.call(B,a);return B}function h(a){return/^[a-z]+:\/\/|^\//.test(a)}function g(a){return a&&"data:"===a.substr(0,5)}function m(a){a=e.a.j.Aa.call(a);""===a&&(a=location.host);return a=a.replace(/:\d+$/,"")}function n(a){a=e.a.j.Ca.call(a);if(":"===a||""===a)a=location.protocol;return a}function p(a){a=d(a);return m(a)}function r(a){a=d(a);return e.a.j.Ba.call(a)}function q(a){var b;a&&"url"===a.substr(0,
3)&&(b=(b=a.match(/url\s*\([\"]?([^\"]*)[\"]?\s*\)|url\s*\([\']?([^\']*)[\']?\s*\)/))&&(1<b.length&&b[1]||2<b.length&&b[2]));return b||a}function s(a){a&&"url"!==a.substr(0,3)&&(a="url("+a+")");return a}function t(a){var b=y[a];b||(b=y[a]=x++,C[b]=a);return b}function f(a){a=c(a);return C[a]}function u(a){if(a)if(g(a))a=f(a);else{var b=a;try{var c=JSON.parse(decodeURIComponent(a.substr(a.lastIndexOf("/")+1))).resource_id;"absolute"===c.id_type&&(b=c.absolute_id.url)}catch(d){}a=b}return a}function k(a,
b){var c=131313131,c=(c<<5)-c+a,c=(c<<5)-c+b,c=(c<<5)-c+131,c=(c<<5)-c+131313131,c=(c<<5)-c+13131,c=(c<<5)-c+1313131;return c&c&2147483647}function c(a){var b=a.length;if(8>b)return null;a=a.substring(b-12);if("SU5T"!==a.substring(8))return null;a=e.k.G(a.substring(0,8));var b=a[4],c=a[5],d=k(b,c);return(d>>24&255)!=a[0]||(d>>16&255)!=a[1]||(d>>8&255)!=a[2]||(d&255)!=a[3]?null:c<<8|b}function v(a,b){for(var c=0,d=0,e=b.length;d<e;++d)c+=b[d].length;for(var f=c%3,g=0===f?0:3-f,c=new Uint8Array(c+g+
9),d=f=0,e=b.length;d<e;++d)c.set(b[d],f),f+=b[d].length;for(d=0;d<g;++d)c[f++]=0;d=a&255;e=a>>8&255;g=k(d,e);c[f++]=g>>24&255;c[f++]=g>>16&255;c[f++]=g>>8&255;c[f++]=g&255;c[f++]=d;c[f++]=e;c[f++]=73;c[f++]=78;c[f++]=83;return c}function w(a,b){var c=b.length-4,d=b.substring(c);if("="!=d[3])c=b,d=v(a,[]);else{for(var c=b.substring(0,c),d=e.k.G(d),f=new Uint8Array(d.length),g=0,h=d.length;g<h;++g)f[g]=d[g];d=v(a,[f])}d=e.k.K(d);return c+d}var B;(function(a){a[a.Unknown=0]="Unknown";a[a.Data=1]="Data";
a[a.Http=2]="Http";a[a.Https=3]="Https"})(a.ta||(a.ta={}));a.U=function(a,b){var c=b+"=true",f=d(a),g=e.a.j.Da.call(f),g=g+(""===g?"?":"&")+c;f.search=g;return f.href};a.eb=function(a){if(g(a))return 1;a=d(a);a=n(a);return"http:"===a?2:"https:"===a?3:0};a.qb=h;a.nb=g;a.tb=function(a){return a&&!g(a)};a.lb=function(a){return/^\/\/assets[0-9]*\.insnw\.net\/instart\/image/.test(a)};a.fa=p;a.bb=p;a.fb=function(a){var b=d(a);a=n(b);b=m(b);return a+"//"+b};a.Ga=r;a.Eb=q;a.Ha=s;a.Fa=function(a){return r(q(a))};
a.Hb=function(a,b){if(g(b)||h(b))return b;var c=a.indexOf("?");-1==c&&(c=a.length);return r(a.substring(0,a.lastIndexOf("/",c)+1)+b)};var x=0,y={},C=[];a.Sa=f;a.Ta=u;a.Qa=function(a){if(!a)return a;var b=q(a);if(b===a)return a;b=u(b);return b=s(b)};a.Ya=function(a,b){var c=t(a);return v(c,b)};a.Xa=function(a,b){var c=t(a);return w(c,b)};a.Ra=c;a.Wa=v;a.Va=w;a.$a=function(a,b){return"data:"+b+";base64,"+e.k.K(a)};var z=[/.*/];a.oa=function(a){a=e.s.fa(a);for(var b=!1,c=0;c<z.length;c++)if(z[c].test(a)){b=
!0;break}return b};a.F;a.Pb=function(){return a.F.wrap};b.C(function(c){try{var d=b.g.va().e;if(d)if(z.length=0,"object"===typeof d)for(var e=0;e<d.length;e++){var f=d[e];if("string"===typeof f)z.push(RegExp(f));else throw"Invalid virtualizeDomains value type: "+typeof f;}else throw"Invalid value for virtualizeDomains";}catch(g){b.console.log("virtualizeDomains config error: "+g)}a.F=c})})(e.s||(e.s={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(e){(function(a){function d(a,b,c,d){u(c," Intercepted function: "+b+" On: "+a+" of type: "+a.nodeName+" with args: "+Array.prototype.join.call(d," "))}function e(a,b,c,d){void 0===d&&(d="");d||(d=" Accessed attribute: "+b+" from Node: "+a+" of type: "+a.nodeName);a.Used=!0;u(c,d)}function g(a,c){var d=document.getElementsByTagName(a);b.n(0<d.length,a+" tag not found while removing attributes");for(var d=d[0],e=Object.keys(c),f=0,g=e.length;f<g;++f)d.removeAttribute(c[e[f]])}
function m(a,c){var d=document.getElementsByTagName(a);b.n(0<d.length,a+" tag not found while updating attributes");for(var d=d[0],e=Object.keys(c),f="<test ",g=0,h=e.length;g<h;++g)var k=e[g],f=f+k,f=f+"='",f=f+c[k],f=f+"'";g=f+"/>";h=document.createElement("div");h.innerHTML=g;e=h.childNodes[0];g=0;for(h=e.attributes.length;g<h;++g)f=e.attributes[g],f.specified&&d.setAttribute(f.name,f.value)}function n(a,b){b||(b=document.scripts[document.scripts.length-1]);y.replaceChild(b,document.getElementById(a))}
function p(a,b,c,d){var e=document.getElementById(a);n(b,e);a==c&&e.removeAttribute("id");a=document.getElementById(d);a.parentNode.removeChild(a)}function r(a,b){var c=C[a];c&&y.contains(c)?y.insertBefore(b,c):y.appendChild(b)}function q(a,c){var d=document.createElement("div");for(d.innerHTML=c;d.firstChild;){var e=d.firstChild;d.removeChild(e);if("SCRIPT"==e.nodeName)if(b.g.c("enable_hts_exec_script_in_head").e){var f=a,g=e;x++;var h=document.createElement("scriptplaceholder"),e="instart_placeholder_"+
x;h.setAttribute("id",e);r(f,h);h=f="instart_tmp_"+x;g.hasAttribute("src")||(g.id?h=g.id:g.setAttribute("id",h));document.write(g.outerHTML);g.hasAttribute("src")?n(e):(g=document.getElementById(h),h==f&&g.removeAttribute("id"),g.innerHTML=g.innerHTML.replace('INSTART.Streaming.MoveTag("instart_placeholder_'+x+'");',""))}else{g=a;x++;var f=document.createElement("scriptplaceholder"),h="instart_placeholder_"+x,k="instart_tmp_"+x,p=k+"_"+x,m=k;f.setAttribute("id",h);r(g,f);e.id?m=e.id:e.setAttribute("id",
m);document.write(e.outerHTML);document.write("<script id ='"+p+"' type='text/javascript'>INSTART.Streaming.MoveTagAndCleanUp('"+m+"','"+h+"','"+k+"','"+p+"'); \x3c/script>")}else r(a,e)}}function s(a,b){for(var c=a+b-1;c>=a;--c){var d=C[c];d&&y.contains(d)&&(d.Used&&u(z," Removing intercepted node: "+d),y.removeChild(d))}}function t(){return!!document.cookie.match("instart_html_streaming=false")}function f(a,b){void 0===a&&(a="");void 0===b&&(b="");var c=new Date;c.setTime(c.getTime()+5E3);document.cookie=
"instart_html_streaming=false; Max-Age=5; expires="+c.toString()+";";document.cookie="instart_reload_reason="+a+"; Max-Age=5; expires="+c.toString()+";";document.cookie="instart_reload_additional_info="+b+"; Max-Age=5; expires="+c.toString()+";"}function u(a,b){void 0===a&&(a="");void 0===b&&(b="");t()||(f(a,b),window.location.reload())}function k(a){e=l();d=l();a&&(y=a);C=Array(y.children.length);for(a=y.firstChild;a;a=a.nextSibling)if(a.nodeType===document.ELEMENT_NODE){var b=a,c=b.getAttribute("instart_patch_id");
c&&(C[c]=b)}}function c(a,b){var c={get:function(){return a.getAttribute(b.name)},set:function(c){return a.setAttribute(b.name,c)}};Object.defineProperty(b,"value",c);b.name in a&&Object.defineProperty(a,b.name,c)}function v(){return document.currentScript||document.scripts[document.scripts.length-1]}function w(a){a||(a=v());a.parentElement.removeChild(a)}function B(a,b){void 0===a&&(a="");void 0===b&&(b="");z=a;var c=v();if(!D.e){var e=function(a,c){var e=a.prototype[c];e&&(a.prototype[c]=function(){d(this,
c,b,arguments);return e.apply(this,arguments)})};e(Element,"querySelector");e(Document,"querySelectorAll");e(Document,"evaluate")}w(c)}var x=0,y=document.head,C,z="";a.Db=g;a.Nb=m;a.wb=n;a.xb=p;a.jb=q;a.Fb=s;a.ob=t;a.Ua=f;a.Bb=k;var D=b.g.c("disableQuerySelectorInterception");a.Cb=B;b.b.a.f("INSTART.Streaming.RemoveAttributes",g);b.b.a.f("INSTART.Streaming.UpdateAttributes",m);b.b.a.f("INSTART.Streaming.MoveTag",n);b.b.a.f("INSTART.Streaming.MoveTagAndCleanUp",p);b.b.a.f("INSTART.Streaming.InsertTags",
q);b.b.a.f("INSTART.Streaming.RemoveTags",s);b.b.a.f("INSTART.Streaming.PatchBegin",k);b.b.a.f("INSTART.Streaming.PatchInit",B);b.b.a.f("INSTART.Streaming.PatchEnd",function(){w()});b.b.a.f("INSTART.Streaming.RemoveCurrentScript",w);b.b.a.f("INSTART.Streaming.InterceptNode",function(){var a=v(),b=a.previousSibling,d=b.getAttribute("instart_patch_id");if(b){var f=b.getAttribute;b.getAttribute=function(a){var c=f.call(this,a);c||e(this,a,z,"GET attribute: "+a+" from Node: "+b+" of type: "+b.nodeName+
" with patch_id: "+d);return c};b.setAttribute=function(a){e(this,a,z,"SET attribute: "+a+" from Node: "+b+" of type: "+b.nodeName+" with patch_id: "+d)};for(var g=b.attributes,k=g&&g.length||0;k--;)c(b,g[k])}w(a)});b.b.a.f("INSTART.Streaming.ReloadWithNoHtmlStreaming",u)})(e.la||(e.la={}))})(b.b||(b.b={}))})(INSTART||(INSTART={}));(function(b){(function(e){(function(a){var d=b.g.c("disableInjectionXhr"),e=b.g.r("disableInjectionXhrQueryParam");a.Ab=!1;a.open=function(a,m,n,p,r,q,s){d.e&&b.b.s.oa(p)&&"GET"===n.toUpperCase()&&(p=b.b.s.U(p,e.e));m.call(a,n,p,r,q,s)};b.C(function(a){if(!a.w){var d=window.XMLHttpRequest.prototype.open;window.XMLHttpRequest.prototype.open=function(a,e,g,h,s){b.T.XMLHttpRequest.open(this,d,a,e,g,h,s)}}})})(e.XMLHttpRequest||(e.XMLHttpRequest={}))})(b.T||(b.T={}))})(INSTART||(INSTART={}));})();}
