(function(){if(window.dT_)return;var f=void 0,g=!0,l=null,n=!1;function p(){return(new Date).getTime()}var aa=p(),q=window,s=q.setTimeout,ba=q.XMLHttpRequest,ca=q.ActiveXObject,t=q.parent,u={version:"8105"};q.dT_||(document.dT_=window.dT_,q.dT_=u);function da(){if("string"!==typeof document.title){var a=document.getElementsByTagName("title")[0];return a.innerText||a.textContent}return document.title}
function ea(){return ba?new ba:ca?new ca("MSXML2.XMLHTTP.3.0"):window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("MSXML2.XMLHTTP.3.0")}function v(a,b){return parseInt(a,b||10)}function w(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].indexOf("\x3d"),d=e[b].substring(0,c),c=e[b].substring(c+1),d=d.replace(/^\s+|\s+$/g,""),d===a)return"DTSA"===a.toUpperCase()?decodeURIComponent(c):c;return l}
function fa(a){document.cookie=a+'\x3d"";path\x3d/'+(y.domain?";domain\x3d"+y.domain:"")+"; expires\x3dThu, 01-Jan-70 00:00:01 GMT;"}function z(a,b){b?(b="DTSA"===a.toUpperCase()?ga(b):b,document.cookie=a+"\x3d"+b+";path\x3d/"+(y.domain?";domain\x3d"+y.domain:"")):fa(a)}function A(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}u.dC=fa;u.sC=z;u.gC=w;u.gx=ea;u.st=function(a,b){return s(a,b)};u.nw=p;u.pn=v;var B=[],C=navigator.userAgent;
try{var ha=/Firefox[\/\s](\d+\.\d+)/,ia=/(iPod|iPhone|iPad)/,ja=/AppleWebKit/;if(0<=C.indexOf("MSIE"))B.ie=v(C.substr(C.lastIndexOf("MSIE")+5,3));else if(0<=C.indexOf("Trident"))0<=C.indexOf("rv:")?B.ie=v(C.substr(C.lastIndexOf("rv:")+3,2)):0<=C.indexOf("rv ")&&(B.ie=v(C.substr(C.lastIndexOf("rv ")+3,2)));else if(0<=C.indexOf("Android"))B.ab=parseFloat(C.substr(C.indexOf("Android")+8,1));else if(C.match(ia)&&C.match(ja)){var ka=/Version\/([0-9]*\.[0-9]*)/;C.match(ka)||(ka=/OS ([0-9]*_[0-9]*)/);B.msf=
parseFloat(C.match(ka)[1])}else if(("Safari"===navigator.appName||-1<C.indexOf("Safari"))&&-1===C.indexOf("Chrom"))B.sf=v(C.substr(C.lastIndexOf("Version/")+8,1));else if(q.opera)B.op=v(q.opera.version().split(".")[0]);else if(0<=C.indexOf("OPR/"))B.op=v(C.match(/OPR\/([0-9]*\.[0-9]*)/)[1]);else if(ha.test(C)){var la=v(C.match(ha)[1]);B.ff=-1===la?0:la}else{var ma=C.indexOf("Chrom");-1<ma&&(B.ch=v(C.substring(ma+7,ma+9)))}}catch(na){}u.gBI=function(){return B};u.hyb=function(){return 0===document.location.href.indexOf("file")};
var y={reportUrl:"dynaTraceMonitor",m:"",csu:"dtagent"},oa=document.getElementsByTagName("script"),qa=pa(oa);
if(0<qa)for(var ra,sa=qa-1;0<=sa;sa--)if(ra=oa[sa],ra.attributes){var ta=ra.attributes.getNamedItem("data-dtconfig");if(ta){var ua=ra.src,va=ta.value;if(ua){var wa=/([a-zA-Z]*)[0-9]{0,3}_[a-zA-Z_0-9]*_[0-9]+/g.exec(ua);if(wa&&wa.length){var xa=wa[0];y.csu=wa[1];y.r=xa.split("_")[1]}}if(va)for(var ya=va.split("|"),za=0;za<ya.length;za++){var Aa=ya[za].indexOf("\x3d");-1===Aa?y[ya[za]]=g:y[ya[za].substring(0,Aa)]=ya[za].substring(Aa+1,ya[za].length)}break}}u.gAN=function(){return y.csu};
u.smbi=function(a){var b=q.dT_;if(b.ism(a)&&-1===b.iMod().indexOf(a))return b.iMod(a),g;b.ism(a)&&q.console&&q.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return n};u.isc=function(a){return a&&383<=a};u.cfg=function(a){return y[a]};u.ism=function(a){return!a||1!==a.length||y.r===f?n:-1!==y.r.indexOf(a)};u.iMod=function(a){a&&(y.m+=a);return y.m};var Ba="\t\n\r";function Ca(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):l}
function Da(a,b){if(a.indexOf)return a.indexOf(b);for(var c=a.length;c--;)if(a[c]===b)return c;return-1}var Ea=[];function D(a,b,c){a.addEventListener?a.addEventListener(b,c,g):a.attachEvent&&a.attachEvent("on"+b,c);A(Ea,{object:a,event:b,D:c})}function Fa(a){try{var b=a.tagUrn;return b&&-1!==b.indexOf("schemas-microsoft-com:vml")}catch(c){return g}}function Ga(a){var b=0;if(a)for(var c=a.length,d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}
function Ha(a,b){try{q.sessionStorage[a]=b}catch(c){z(a,b)}}function Ia(a){return q.sessionStorage?q.sessionStorage[a]:w(a)}var Ja={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Ka={"^":"^^","|":"^p",",":"^c",";":"^s"};function ga(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Ja[d];e?A(b,e):A(b,d)}return b.join("")}
function E(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Ka[d];e?A(b,e):A(b,d)}return b.join("")}function pa(a){var b=a.length;if("number"===typeof b)a=b;else{for(var b=0,c=2048;a[c-1];)b=c,c+=c;for(var d=7;1<c-b;)d=(c+b)/2,a[d-1]?b=d:c=d;a=a[d]?c:b}return a}function La(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c),e=y.spc;e||(e="");e+=Ba;-1===e.indexOf(d)&&A(b,d)}a=b.join("")}return a}
function Ma(){var a=document.location.href,b=a.indexOf("#");0<=b&&(a=a.substr(0,b));return a}function Na(a){var b=w("dtLatC"),c=0,d=[],e=0;if(b&&0<b.length){b=b.split("p");1<b.length&&(e=b.length-1);9<e&&(e=9);for(var h=1;h<=e;h++)c+=parseFloat(b[h]),d[h+1]=b[h]}e++;d[0]=v((c+a)/e);d[1]=a;z("dtLatC",d.join("p"));return d[0]}function Oa(){return q.performance&&q.performance.timing&&(!B.ff||9<B.ff)?q.performance:l}var Pa={};
function Qa(a,b,c,d){if(Object.defineProperty&&(!B.ie||8<B.ie)){Pa[b]=a[b];var e=function(c){Pa[b]=c;d&&d.apply(a,[c]);return Pa[b]};try{Object.defineProperty(a,b,{get:function(){return c?c.apply(a,l):Pa[b]},set:e,configurable:g})}catch(h){}}}function Ra(a,b){if(a[b]&&Object.defineProperty&&(!B.ie||8<B.ie)){var c=a[b];try{delete a[b],Pa[b]=l,a[b]=c}catch(d){Object.defineProperty(a,b,{get:function(){return Pa[b]},set:f,configurable:g})}}}
u.icr=function(a){return(0==a.indexOf("http")||0==a.indexOf("//"))&&location.href.indexOf(location.host)!=a.indexOf(location.host)&&-1==a.indexOf("..")};u.aIOf=Da;u.ael=D;u.lv=Ia;u.sv=Ha;u.gh=function(a){return-1===a.indexOf("://")?l:a.split("/")[2].split(":")[0].toLowerCase()};
u.cvs=function(a,b,c,d){if(y.ffi)return g;for(var e=n,h=e,k=e,m=0;m<a.length&&(!e||!h);m++)a[m]=a[m].split("."),e=a[m][0]==b,h=a[m][1]==c,!k&&e&&(k=g);a=e&&h||k;if(!e||!h)k?Sa(d+" version ("+b+"."+c+") official not supported. Instrumentation active nonetheless, because major version is supported."):Sa(d+" not instrumented because version ("+b+"."+c+") not supported.");return a};u.esc=ga;u.aesc=E;u.tpesc=function(a){a=a.replace(/_/g,"_5F").replace(/%/g,"_25");return E(a)};u.ulc=Na;u.gP=Oa;u.apl=Qa;
u.rpl=Ra;u.dbg=function(a){z("dtUseDebugAgent",a)};u.dbc=function(a){z("dt_dbg_console",a)};u.gEL=pa;var Ta=6E8,Ua="dtPC",Va="dtCookie",G=p()%Ta+"_"+v(1E3*Math.random());u.c=G;function Wa(){var a=w(Ua),b=[];if(a&&"-"!==a)for(var a=a.split("p"),c=0;c<a.length;c++){var d=a[c].split("h");if(2===d.length&&d[0]&&d[1]){var e=d[0],h=v(e.split("_")[0]),k=p()%Ta;k<h&&(k+=Ta);h+9E5>k&&A(b,{c:e,b:d[1]})}}return b}
function Xa(){var a=Wa();if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].c!==G&&A(b,a[c]);Ya(b)}}function Ya(a){var b="";if(a){for(var b=[],c=0;c<a.length;c++)0<c&&0<b.length&&A(b,"p"),A(b,a[c].c),A(b,"h"),A(b,a[c].b);b=b.join("")}b||(b="-");z(Ua,b)}u.gFId=function(){return G};u.gDtc=function(){var a=w(Va);if(a){var b=a.indexOf("|");-1!==b&&(a=a.substring(0,b))}return a};u.gPAH=function(a){a=G+"h"+u.esc(a);var b=w(Ua);return b&&0<=b.indexOf(a)&&!u.hyb()?l:a};u.g=l;u.n=l;u.B=0;
var Za=l,$a,ab,bb={};try{t&&(t!==self&&t.dT_&&t.dT_.version===u.version)&&(ab=t.dT_,Za=t.dT_.tdto())}catch(cb){}Za?(u.g=Za.g,u.n=Za.n,$a=ab.c,ab.B++):(u.g=G,u.n=da());u.tp=function(){return!Za};u.tdto=function(){try{for(var a=t;a&&a!==self;){if(a.dT_)return a.dT_.tdto();a=a!==a.parent?a.parent:n}}catch(b){}return u};u.aFU=function(a){a=E(a);bb[a]||(bb[a]="1")};u.iRO=function(a){return"1"===bb[a]};
function db(a,b,c,d){function e(a){Na((p()-d)/2);a=a&&a.split("|");for(var b=1;b<a.length;b++){var c=a[b].indexOf("dtCookie\x3d");if(-1<c){z("dtCookie",decodeURIComponent(a[b].substr(c+9)));break}}}"onreadystatechange"in a||(a.onload=function(){e(a.responseText)});a.onreadystatechange=function(){4==a.readyState&&(200==a.status?e(a.responseText):eb&&B.sf&&fb.push({path:b,data:c}),a=l)}}
function gb(a,b,c,d,e){for(var h=3,k=0;0<h;)try{var m,r=y.cors,x;if(r){var V=ea();"withCredentials"in V||(V=window.XDomainRequest?new XDomainRequest:l);x=V}else x=ea();m=x;if(!m)break;k=p();a&&a(m,b,d,k);"onreadystatechange"in m?m.open("POST",b,c):m.open("POST",b);"setRequestHeader"in m&&(m.setRequestHeader("Content-Type","text/plain;charset\x3dUTF-8"),e&&!r&&m.setRequestHeader("x-dtreferer",e));m.send(d);h=0}catch(F){h--}}
function hb(a,b){try{y.markSendBeacon&&(a+=(0<=a.indexOf("?")?"\x26":"?")+"VIASENDBEACON\x3d1"),navigator.sendBeacon(a,b||"")}catch(c){}}var ib=navigator&&"sendBeacon"in navigator;function jb(a,b){return ib&&!y.dsndb&&!b&&(a||!(y.bandwidth&&u.tp()&&u.ism("b")))}var H=l,kb=[],lb=n,mb=n,nb,pb=g,qb=n,rb,sb,fb=[];function tb(){var a=this;a.f=[];a.a=function(b,c){A(a.f,[b,c])}}function ub(a,b,c){a=vb(a,b,n);H&&wb(n,c,a)}
function vb(a,b,c){var d="",e=l;if(a){c="";xb=0;var h=n,k;for(k in I)I.hasOwnProperty(k)&&(b=I[k],yb(b)?h||(h=g,Sa("Maximum open actions exceeded configured amount of "+(y.moa||30)+", dropping action "+b)):(c=c?c+",":c,c+=zb(I[k],n,n,g)));d=c}else{e="";k=J.length;b&&(I=[]);b="";if(0<k){for(d=0;d<k;d++){b||(b=J[d].l());var m=zb(J[d],g,c,n);m&&0<m.length&&("_load_"==J[d].type&&(Ab=g,K&&(e=K.w?"d|"+K.b+"|"+K.name+"|"+K.type+"|"+K.info+"|"+K.c+"|"+K.start+"|"+K.location+"|"+K.title:"s|"+K.b+"|"+K.name+
"|"+K.type+"|"+K.info+"|"+K.c+"|"+K.start,K=l)),0<e.length&&(e+=","),e+=m)}J=[];for(h in I)I.hasOwnProperty(h)&&A(J,I[h])}e={actions:e,referer:b};d=e.actions;e=e.referer}H=l;if(0<d.length){c=d;H||(H=new tb);H.a("a",ga(c));H.a("v",u.version);H.a("fId",G);a&&H.a("PV",1);u.g!==G&&H.a("pId",u.g);$a&&H.a("pFId",$a);H.a("rId",y.rid);H.a("rpId",y.rpid);if(!a){mb||H.a("title",ga(La(da())));a:{c=(h=Oa())?h.timing:n;if(h&&c&&(h=c.domComplete,c=c.domContentLoaded,h||c)){c=h?h:c;break a}c=nb}c&&H.a("domR",c);
mb=g}Bb()&&H.a("unload","xhr");Cb(a);pb=n}else pb===n&&(H||(H=new tb),c=H.f.length,Cb(a),H.f.length>c?(H.a("fId",G),H.a("v",u.version)):H=l);return e}function Cb(a){for(var b=0;b<kb.length;b++)kb[b](H,a)}function Db(){for(var a=[],b=0;b<H.f.length;b++)0<b&&A("$"),A(a,"$",H.f[b][0],"\x3d",H.f[b][1]);return a.join("")}function Eb(){var a=Db(),b=B.ie?1500:7E3;y.msl&&(b=Math.min(b,v(y.msl)));return 0===a.length%b?v(a.length/b):v(a.length/b)+1}
function Fb(a,b,c){var d=document.createElement("img");d.onerror=function(){Na((p()-b)/2)};d.setAttribute("src",c+"?"+a)}
function wb(a,b,c){var d=p();H.a("time",d);u.hyb()&&H.a("url",encodeURIComponent(document.location.href));var e=B,h,k,m=jb(a,!!c);if(m)h=g,b=n;else{var r=y.fsc;h=y.fso;var x=e.op&&15<=e.op&&!h;k=Eb();h=!a||a&&!(e.sf||e.op&&!x||e.ff&&(1<k||y.sffs||17<e.ff)||e.ie&&(9>e.ie||y.sies)||e.msf||e.ab||e.ch&&(22<e.ch||r));b&&(h=n);b=(1==k||x)&&a&&(e.ie&&9>e.ie||e.ch&&!r||x)}a=h;e=Db();h=l;if(y.spl||b){r=B.ie?1500:7E3;y.msl&&(r=Math.min(r,v(y.msl)));k=Eb();var V=p(),F=0;if(1<k){if(100>k){h=[];for(var ob=0;ob<
k;ob++){var pd="sid\x3d"+V+"\x26p"+(ob+1)+"_"+k+"\x3d";F+r<=e.length?(x=e.slice(F,F+r),"%"==x.charAt(x.length-1)&&e.length>=F+r+1&&(x+=e.charAt(F+r),x+=e.charAt(F+r+1),F+=2),"%"==x.charAt(x.length-2)&&e.length>=F+r+2&&(x+=e.charAt(F+r),F+=1)):x=e.slice(F);A(h,pd+x);F+=r}}}else h=[e]}else h=[e];e=h;if(e!==l)if(h=y.reportUrl?y.reportUrl:"dynaTraceMonitor",b)for(c=0;c<e.length;c++)Fb(e[c],d,h);else if(d=h,b=e[0],h=n,y.cors?(d=d+"?"+("dtCookie\x3d"+encodeURIComponent(w(Va))+";"),d+="dtLatC\x3d"+w("dtLatC")+
";",d+="referer\x3d"+encodeURIComponent(c||document.location.href),h=g):m&&(c&&c!==document.location.href)&&(d+="?referer\x3d"+encodeURIComponent(c),h=g),y.spl)for(r=0;r<e.length;r++)k=d,b=l,h||(k+="?"),k+=e[r],m?hb(k,b):gb(db,k,a,b,c);else m?hb(d,b):gb(db,d,a,b,c)}function Gb(a){if(lb){var b=n;a?p()+a<sb&&(b=g):b=g;b&&(clearTimeout(rb),lb=n)}lb||(sb=p()+(a?a:0),a==f||0==a?Hb():(rb=s(Hb,a!=f?a:0),lb=g))}function Hb(){lb=n;ub(n,n,n)}u.ss=function(a,b,c){ub(b,c,a)};u.asl=function(a){A(kb,a)};
u.sMPS=function(a){Gb(a)};var L=l,Ib=l,J=[],I=[],xb=0,Jb=0,M=[],N=[],O,Ab=n,Kb=1;u.J=Lb;var Mb=[];function P(){for(var a=0;a<Mb.length;a++)Mb[a]()}function Lb(){return I}
function Nb(a,b,c,d,e,h,k){var m={b:Kb++,start:c,stop:d,type:a,name:b,info:k,i:e,next:[],e:l,p:l,s:l,o:l,I:l,q:h?v(2147483647*Math.random())+1:0,parent:l,F:location.href,l:function(){return m.parent?m.parent.l():m.F},add:function(a){a&&a.name&&A(m.next,a)}};m.u=s(function(){m&&(m.H=g,!m.stop&&!Ob(m)&&Pb(m.b))},1E3*v(y.oat||180));return m}function Ob(a){for(var b=n,c=0;c<a.next.length;c++)if(!a.next[c].stop||Ob(a.next[c])){b=g;break}return b}
function Qb(){var a=n,b=[],c;for(c in I)if(I.hasOwnProperty(c)){var d=I[c];0<d.p&&(p()>d.e&&(d.e+=6E4,A(b,d)),a=g)}0<b.length&&ub(g,g,n);for(c=0;c<b.length;c++)b[c].p--;a&&s(Qb,1E3)}function Rb(a,b){if(a)for(var c=l,d=0;d<a.length;d++){c=a[d];if(c.b==b)return c;if(c.next&&(c=Rb(c.next,b),c!==l))return c}return l}function Sb(a){var b=l;J&&(b=Rb(J,a));return b}
function Tb(a,b,c,d,e,h){c||(c=p());a=Nb(b,a,c,l,l,e,h);"boolean"==typeof d&&d&&(d=L);if(d){if(b=l,b="number"==typeof d?Sb(d):"object"==typeof d?d:L){b.add(a);a.parent=b;Ub(a);for(var k in I)I.hasOwnProperty(k)&&(I[k]&&I[k].e>a.start+1E4)&&(I[k].e=a.start+1E4)}}else Ub(a),Vb(a),A(I,a),L=a,A(J,a),a.e=a.start+1E4,a.p=100,s(Qb,5E3);return a}function Ub(a){if(L!=a)if(L&&(Ib=L),L=a){a=a.b;for(var b=Wa(),c=n,d=0;d<b.length;d++)b[d].c===G&&(b[d].b=ga(a),c=g);c||A(b,{c:G,b:ga(a)});Ya(b)}else Xa()}
function Pb(a,b,c){b||(b=p());var d=[];if(J)for(var e=0;e<J.length;e++){var h=Wb(J[e],a,b,c);"string"!==typeof h&&(d[e]=h)}a=n;c=[];for(b=0;b<J.length;b++)d[b]?a=d[b]:(Ob(J[b])||A(c,J[b].b),Q=l);d=[];for(b in I)I.hasOwnProperty(b)&&(e=I[b],0<=Da(c,e.b)?A(d,b):O&&(h=ab.gca(),e.s=t&&h[h.length-1]==O?"S":"A",O=l));for(b=0;b<d.length;b++)c=d[b],e=I,e.splice(c,c-(c||NaN)+1||e.length);d=a;Gb();Ub(d)}
function Wb(a,b,c,d){var e,h=a.b==b;if(h){a.stop=c;d&&(a.start=d);a.i=pa(document.getElementsByTagName("*"));a.u&&window.clearTimeout&&window.clearTimeout(a.u);var k=a.parent;if(k&&!k.stop&&k.H){for(var m=n,r=0;r<k.next.length;r++)if(!k.next[r].stop&&k.next[r].b!=b){m=g;break}m||s(function(){k.stop||Pb(k.b)},0)}}else a.stop||(e=a);m=n;if(a.next&&a.next.length)for(r=1;r<=a.next.length;r++){var x=Wb(a.next[a.next.length-r],b,c,d),V="string"===typeof x,m=m||V||x&&x.A===b;V||(e=x||e);if((m||h)&&e)break}if(h||
m)"object"===typeof e?e.A=b:e="found";return e}function zb(a,b,c,d){if(a.o){var e=[],h=["0"];h[1]=a.b;h[2]=a.o;h[3]=a.s;e[0]=h.join("|");e[1]=Xb(a,1,b,c,d).result;return!e[1]?l:e.join(",")}return Xb(a,1,b,c,d).result||l}
function Xb(a,b,c,d,e){a.i||(a.i=pa(document.getElementsByTagName("*")));var h=[];if(a.next&&0<a.next.length){for(var k=0;k<a.next.length;k++){var m=a.next[k],m=Xb(m,b+1,c,d,e),r=m.result;if(r)h.push(r);else if(!m.z)return{}}if(c)for(k=0;k<a.next.length;k++)if(m=a.next[k],m.stop)a.stop&&m.stop>a.stop&&(a.stop=m.stop);else{a.stop=f;break}}if(!d&&!e&&(!a.stop||0==a.stop))return{};c=[];c[0]=b.toString();c[1]=a.b;c[2]=E(a.I||a.name);c[3]=E(a.type);c[4]=a.info?E(a.info):"-";c[5]=a.start;c[6]=a.stop||0;
c[7]=a.i;1==b&&a.h&&(c[8]=a.h);a.q&&(c[8]||(c[8]="-"),c[9]=a.q);b=n;a.stop||d||a.next&&a.next.length||!yb(a)?(h.unshift(c.join("|")),xb++):yb(a)&&(b=g);a={z:b};1<h.length?a.result=h.join(","):h[0]&&(a.result=h[0]);return a}function yb(a){var b=["_warning_","_error_","_log_","_rv_","_rs_"];return xb+1>(v(y.moa)||30)&&-1==Da(b,a.type)}function Bb(){if(0<Jb){var a=M.length;if(0<a)return M[a-1]}return l}
function Yb(a,b,c){var d=l;1==arguments.length&&(b=3);var e=Zb(),h="";e&&(e.info=a||"-",h=e.info);var k=Bb();!k&&(e&&e.b)&&(k=e.b);k?d=$b(k):e?3<=b&&(d=ac(e.getName(),e.type,e.start,l,c,h),e.b=d):L?1<=b&&(d=$b(L.b,a,"xhr",p(),c,h)):y.cux&&(d=ac("Unlinked XHR","xhr",p(),l,c,h));return d}function ac(a,b,c,d,e,h){a=Tb(a,b,c,d,e,h);a.k=1;N[a.b]=a;return a.b}function $b(a,b,c,d,e,h){a=N[a];var k;a?(a.k++,k=a.b):L&&(k=ac(b,c,d,L.b,e,h));return k}
function bc(a){var b=0;if(b=N[a])b.k--,b=b.k,0>=b&&(Pb(a),N[a]=l,delete N[a])}function cc(){var a=0,b;for(b in N)if(b&&N.hasOwnProperty(b))try{a+=N[b].k}catch(c){}return a}function Vb(a){O=l;if(ab){var b=ab.gca();if(O=b[b.length-1])a.o=O.name,O.h?O.h++:O.h=1}}function R(a,b,c){var d=p();a=La(a);b=Nb(b,a,d,d,-1);(c=dc(b,c))&&Gb();return c}function dc(a,b){var c;if(c="undefined"==typeof b?L:Sb(b))return c.add(a),n;Vb(a);A(J,a);return g}function Sa(a,b){R(a,"_warning_",b)}
function ec(){return L?L.name:l}u.ea=function(a,b,c,d,e){if(4>arguments.length||"undefined"==typeof d)d=g;return Tb(a,b,c,d,e).b};u.la=function(a,b,c){P();Pb(a,b,c)};u.lx=function(a){if(1<cc())s(function(){bc(a)},0);else return s(function(){bc(a)},0),P(),g;return n};u.ex=Yb;u.ec=function(a){a&&(A(M,a),Jb++)};u.lc=function(a){a&&(Jb--,s(function(){for(var b=-1,c=M.length-1;-1==b&&0<=c;)M[c]==a&&(b=c),c--; -1!=b&&(b==M.length-1?M.pop():M.splice(b,1))},0))};u.eV=function(){R("visit end","_endVisit_")};
u.pe=function(a,b){if(u.gne()<=(u.cfg("mepp")||10))u.iet(),R(a,"_error_",b)};u.pw=Sa;u.pl=function(a,b){R(a,"_log_",b)};u.rv=function(a,b){var c=p(),c=Nb("_rv_",a+"\x3d"+b,c,c,0);dc(c);Gb()};u.rs=function(a,b,c){var d=p();a=Nb("_rs_",a+"\x3d"+b,d,d,0);dc(a,c);Gb()};u.pcn=R;u.ewa=function(a){a=Yb(a,3,g);return Sb(a)};u.gWRI=function(a){return a.q};u.gAID=function(a){return a.b};u.ca=function(){return L};u.can=ec;
u.isci=function(a){var b=a==ec();if(!Ib)return!b;a=a===Ib.name&&3E3>=p()-Ib.start;return!b&&!a};u.noa=function(){return!L||0<L.stop};u.ti=P;u.las=function(){return Ab};u.gca=Lb;u.gAR=function(a){isNaN(a)||(a=N[a]);return a?a.l():l};u.gAA=function(a){return N[a]};var fc,gc=n,hc=y.mepp;!hc&&0!=hc&&(hc=10);var ic=0;
function jc(a){try{if(q.event.errorUrl||a.filename)ic++,ic<=hc&&(11>B.ie?R(q.event.type+":"+q.event.errorUrl+"["+q.event.errorLine+"] Code: "+q.event.errorCode+": "+q.event.errorMessage,"_error_"):R(a.type+":"+a.filename+"["+a.lineno+":"+a.colno+"] "+a.message,"_error_"))}catch(b){}}
function kc(a,b,c){var d=n;if(!gc){gc=g;try{fc&&(fc!=kc&&"function"==typeof fc)&&(d=fc(a,b,c));var e=l;if(e="object"==typeof a?a.srcElement?a.srcElement.outerHTML&&200>a.srcElement.outerHTML.length?document.URL.split("#")[0]+"[-]: Error at '"+a.srcElement.outerHTML+"'":document.URL.split("#")[0]+"[-]: Error at tag: '"+a.srcElement.tagName+"'":"unknown error":"undefined"==typeof b||"undefined"==b?a:b+"["+c+"]: "+a){var h=Zb();h&&(e+=", user action: "+h.getName());ic++;ic<=hc&&!d&&R(e,"_error_")}}catch(k){}gc=
n}return d}B.ie?D(q,"error",jc):q.onerror!=kc&&(q.onerror&&(fc=q.onerror),q.onerror=kc);try{B.ie||Qa(window,"onerror",function(){return kc},function(a){fc=a})}catch(lc){}D(q,"unload",function(){Ra(window,"onerror");q.onerror=l});u.gne=function(){return ic};u.iet=function(){ic++};
var mc="BUTTON",nc="INPUT",oc="HIDDEN",pc="SUBMIT",qc="RESET",rc="IMAGE",sc="IMG",tc="A",uc="FORM",vc="#DOCUMENT",wc="HTML",xc="BODY",yc="HEAD",zc="SELECT",Ac="unknown",Bc="TEXTAREA",Dc=Cc(q.location.href),Ec=l,Fc=0,Gc=1,Hc=2,Ic=3,Jc=4,Kc=0;function Lc(a){if(a)for(var b=document.getElementsByTagName("LABEL"),c=pa(b),d=0;d<c;d++)if(b[d].htmlFor==a)return a=b[d],S(a.innerText,a.textContent);return l}
function S(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&"string"==typeof c&&Ca(c))return Ca(c)}return l}function Mc(a){if(a){if(0===a.indexOf("data:"))return l;a=a.split("/");if(0<a.length)return a[a.length-1].split(".")[0]}return l}function Cc(a){if(a){var b=a.split("/");if(0<b.length&&(b=Ca(b[b.length-1]),b!==l))return b}return a}
function Nc(a,b){var c=b.nodeName?b.nodeName.toUpperCase():Ac,d=b.type&&"string"===typeof b.type?b.type.toUpperCase():l,e=l;switch(a){case Fc:c==nc&&d!=oc&&(c=d&&(d==mc||d==pc||d==qc||d==rc)?b.value:l,e=Lc(b.id),e=d&&(d==mc||d==pc||d==qc)?S(c,e):S(e,c));e||(e=S(b.textContent,b.innerText));break;case Gc:if(c==nc&&d!=oc||c==mc)e=S(b.name,b.title,d&&d==rc?b.alt:l);break;case Hc:c==nc&&d==rc?e=Mc(b.src):c==tc?e=S(b.title,Cc(b.href)):c==sc?e=S(b.name,b.title,b.alt,Mc(b.src)):c==uc&&(e=S(b.name,b.id,b.action));
e||(e=S(b.title,b.data,b.wholeText,b.id));break;case Ic:e="object"==typeof b.className?b.baseVal||b.animVal:b.className;break;case Jc:c==nc&&d!=oc?e=nc+": "+d:c==tc?e="LINK":Ec||(Ec=e=c)}return e}function Oc(a){if(!a)return l;if(B.ie&&Fa(a))return"VML Node";var b=a.nodeName?a.nodeName.toUpperCase():Ac;if(b==wc||b==xc||b==yc||b==vc)return Ec;for(b=0;4>=b;b++){var c=Nc(b,a);if(c&&c!==Ec)return c}return Oc(a.parentNode)}
function Pc(a,b){if(!b)return l;var c=pa(b);if(0>=c||20<Kc)return l;for(var d=0;d<c;d++){var e=b[d];if(B.ie&&Fa(e))return"VML Node";var h=l;Kc++;if(h=Pc(a,e.childNodes))return h;Kc--;if(h=Nc(a,e))return h}return l}
function Qc(a){Ec=l;if(B.ie&&Fa(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtName"];if(b&&b.value)return b.value}b=a.nodeName?a.nodeName.toUpperCase():Ac;if(b==wc||b==xc||b==yc||b==vc)return"Page: "+Dc;if(b==zc){if(a)if(b=a.nodeName?a.nodeName.toUpperCase():l,b!=zc)a=l;else{var c=Lc(a.id),b=S(c,a.name,b),c=l;a.multiple||(a=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:l)&&(c=S(a.label,a.innerText,a.textContent));a=c?"["+b+"] to value ["+
c+"]":b}else a=l;return a}if(b==Bc)return a?(b=a.nodeName?a.nodeName.toUpperCase():l,b!=Bc?a=l:(c=Lc(a.id),a=S(c,a.name,b)||a.nodeName)):a=l,a;if(b=Ca(S(a.innerText,a.textContent)))return b;Kc=0;if(a.childNodes&&0<pa(a.childNodes))a:{a=[a];b=Pc;for(c=0;4>=c;c++){var d=b(c,a);if(d){a=d;break a}}a=l}else a=Oc(a);return a}var T,Rc=l,Sc=0,Tc=g,U=u.tdto();
function Uc(a,b,c,d){if(u!=U)return U.bi(a,b,c,d);try{d||(d=30);var e={id:Sc++,d:a,name:l,type:b,info:c?c:"-",start:p(),t:n,v:p()+d,getName:function(){if(!e.name){var a="";(a=y.uam?"dTMasked_"+e.d.nodeName:La(Qc(e.d)))||(a="-");var b=y.sl||100;a.length>b&&(a=a.substring(0,b-3)+"...");e.name=a}return e.name},C:function(){return e.t},G:function(){var a=e;do a.t=g,a=a.next;while(a)}};Tc&&(e.next=T,e.next&&(e.next.j=e),T=e);return e}finally{e&&(a=e.v-p(),0>=a?Vc(e):s(function(){Vc(e)},a))}}
function Zb(){if(u!=U)return U.gci();try{if(T){for(var a=T,b=T.next;b;){var c;if(c=b.d!=a.d)a:{for(var d=b.d.parentNode;d;){if(d==a.d){c=g;break a}d=d.parentNode}c=n}c&&(a=b);b=b.next}return a}return l}catch(e){return l}}function Wc(){return u!=U?U.ci():Zb()?T.getName():l}function Xc(){return u!=U?U.gpi():Rc}function Yc(){return u!=U?U.pi():Xc()?Rc.getName():l}function Zc(){return u!=U?U.piv():Xc()?Rc.v:l}function $c(){for(var a=T;a;)a.d=l,a=a.next;T=l}
function Vc(a){if(u!=U)return U.ei(a);if(T){for(var b=T;b.next&&b!==a;)b=b.next;b===a&&(Wc()&&(Rc=T),b.d=l,b.j?b.j.next=b.next:T=b.next,b.next&&(b.next.j=b.j))}}
function W(a,b,c){var d=n,e=y.doNotDetect?y.doNotDetect.split(","):l;if(c&&e)for(var h=0;h<e.length;h++)e[h]==c&&(d=g);d||(b||(b=a),D(document,a,function(a){var c=l;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if(("KD"==d||"KU"==d)&&"password"!==c.type)if(a=a.keyCode?a.keyCode:a.charCode)if(y.uam){var e=String.fromCharCode(a);"a"<=e&&"z">=e||("A"<=e&&"Z">=e||"0"<=e&&"9">=e)||(d+=a)}else d+=a;Uc(c,d,l,30)}))}W("click","C","clk");W("mousedown","D","mdw");W("mouseup","U","mup");
W("dblclick","CC","dcl");W("keydown","KD","kyd");W("keyup","KU","kyu");W("scroll","S","scr");W("touchstart","TS","tcs");W("touchend","TE","tce");if(y.ade){var ad=y.ade.split(",");if(ad&&0<ad.length)for(var bd=0;bd<ad.length;bd++)W(ad[bd])}u.bi=Uc;u.ei=Vc;u.gci=Zb;u.ci=Wc;u.cit=function(){return u!=U?U.cit():Zb()?T.type:l};u.cih=function(){return u!=U?U.cih():Zb()?T.d:l};u.gpi=Xc;u.pi=Yc;u.pit=function(){return u!=U?U.pit():Xc()?Rc.type:l};u.piv=Zc;u.aad=function(a){(Tc=a)||$c()};
var cd=n,dd=n,ed=n,K=l,Q=l,fd=Ia("dtSa");Ha("dtSa","-");if(fd&&"-"!=fd){var X=fd.split("|");if(9==X.length){var gd={w:"true"==X[0],type:X[1],b:X[2],name:X[3],info:X[4],start:X[5],c:X[6],location:X[7],title:X[8]},hd=n;u!=u.tdto()&&(hd=u.tdto().iRO(gd.location));if(!document.referrer||gd.location==E(document.referrer)||gd.location==E(document.location)||hd)Q=K=gd}}var id=l,jd=n,kd=[],ld=[],eb=n,md=n,nd=1;u.tdto().aFU(document.location.href);
if(!y.rid){var od=y.ridPath,qd=od?od:q.location.pathname,rd=q.location.search;rd&&(rd.length&&"?"===rd.charAt(0))&&(rd=rd.substring(1));var sd=rd,Y=1,Y=31*Y+Ga(qd),Y=31*Y+Ga(sd),Y=Y&Y;y.rid="RID_"+Y}var Z=l,td,ud=Oa();ud&&(Z=ud.timing);
function vd(){var a=f,a=Z?0<Z.redirectStart?Z.navigationStart+6E4>Z.redirectStart?Z.navigationStart:Z.redirectStart:Z.navigationStart+6E4>Z.fetchStart?Z.navigationStart:Z.fetchStart:q.external&&q.external.pageT?p()-q.external.pageT:q.gtbExternal&&q.gtbExternal.pageT?p()-q.gtbExternal.pageT():q.chrome&&q.chrome.csi?p()-q.chrome.csi().pageT:aa;return a<aa-2E4||a>aa+2E4?aa:Math.floor(a)}
function wd(){nd--;if(0>=nd){var a=Z?Z.loadEventEnd:0,b;b=Z?Z.loadEventStart:0;b=b<vd()?0:b;if(id){if(a&&b){var c=p()-a;if(5E3<(0>c?-1*c:c))a+=c;Pb(id.b,a,b)}else Pb(id.b);id=f}td||xd()}}function xd(){yd&&(Pb(yd.b),yd=l,P())}function zd(){yd&&!id&&(id=Tb("_onload_","_load_",l,yd))}u.sls=function(){};u.sole=wd;u.iolm=function(){nd++};u.solb=zd;u.slem=function(){td=g};u.lst=vd;function Ad(){if(!dd){dd=g;P();for(var a=0;a<kd.length;a++)try{kd[a]()}catch(b){}wd()}}
function Bd(){P();cd||(zd(),cd=g,s(Ad,0))}function Cd(){P();cd||("complete"==document.readyState?ed?ub(n,g,n):(ed=g,s(Cd,3E3)):s(Cd,3E3))}
function Dd(a,b,c,d){var e=Bb();!e&&a&&b&&c?Ha("dtSa","true|"+E(b)+"|-1|"+E(a)+"|"+E(d||"-")+"|"+c+"|"+G+"|"+E(Ma())+"|"+E(La(da()))):e&&Q?(Ha("dtSa","false|"+Q.type+"|"+Q.b+"|"+Q.name+"|"+Q.info||"-|"+p()+"|"+Q.c+"|"+E(Ma())+"|"+E(La(da()))),Q=l):L&&"_load_"!=L.name&&Ha("dtSa","false|"+E(L.type)+"|"+L.b+"|"+E(L.name)+"|"+E(L.info||"-")+"|"+p()+"|"+G+"|"+E(Ma())+"|"+E(La(da())))}function Ed(){Fd()}
function Fd(a){if(!eb){eb=!a;for(a=0;a<ld.length;a++)ld[a](eb);vb(n,g,g);a=Zb();if(!a){var b=Xc();b&&($.isci(Yc())&&3E3>=p()-Zc())&&(a=b)}a&&a.C()===n?(a.G(),Dd(a.getName(),a.type,a.start,a.info)):Dd(l,l,l,l);if(B.sf&&q.frames)for(a=0;a<q.frames.length;a++)try{q.frames[a].dT_&&q.frames[a].dT_.obc()}catch(c){}H&&wb(g,n)}}D(q,"beforeunload",Ed);
D(q,"unload",function(){Fd();var a;if(0<fb.length){a=jb(g,n);for(var b=0;b<fb.length;b++)try{var c=fb[b];a?hb(c.path,c.data):gb(l,c.path,n,c.data)}catch(d){}}if(!md)try{$c();var e;for(e=0;e<Ea.length;e++){var h=Ea[e],k=h.object,m=h.event,r=h.D;k.removeEventListener?k.removeEventListener(m,r,n):k.detachEvent("on"+m,r)}Z=ca=ba=Ea=l;md=g}catch(x){}jd||(jd=g,Xa())});D(q,"pagehide",function(){Fd(g);jd||(jd=g,Xa())});
D(document,"readystatechange",function(){"loaded"==document.readyState&&P();"complete"==document.readyState&&Bd()});s(Cd,3E3);D(q,"load",Bd);(function(){qb||(qb=document.createElement("doc:rdy"));if(qb.doScroll){var a=function(){try{qb.doScroll("left"),qb=l,nb=p(),P()}catch(b){s(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){nb=p();P()},n)})();var yd=Tb("_load_","_load_",vd(),l);P();u.all=function(a){A(kd,a)};u.ail=function(a){A(Mb,a)};u.apll=function(a){A(ld,a)};u.sle=xd;
u.obc=Ed;u.ile=function(){return 0>=nd};var $=window.dT_,Gd=[],Hd=n;function Id(a){Hd?a($.bwsW,$.bwsH):A(Gd,a)}
$.all(function(){var a=document,b=a.documentElement,c=0,d=0,e=a.body;if("number"===typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(e&&(e.clientWidth||e.clientHeight))c=e.clientWidth,d=e.clientHeight;if(0<c&&0<d)a=screen.availWidth,b=screen.availHeight,c=c<a?c:a,d=d<b?d:b;else{var h;$.gBI().ie?h=140:h=10;c=Math.max(c,h);d=Math.max(d,10)}$.bwsW=c;$.bwsH=d;Hd=g;for(a=0;a<Gd.length;a++)Gd[a](c,d)});
$.abwsl||($.abwsl=Id);var Jd=n;$.asl(function(a,b){if(!b&&!Jd&&$.las()){Jd=g;var c=$.tdto(),d=function(a){return 0>a||2147483647<=a||isNaN(a)?0:a};c?(a.a("w",d(c.bwsW)),a.a("h",d(c.bwsH))):(a.a("w",d($.bwsW)),a.a("h",d($.bwsH)))}});
$.asl(function(){var a=$.gC("dtCookie");if("undefined"!=typeof window.sessionStorage){var b=window.sessionStorage.dtCookie;if("undefined"!=typeof b&&(""!=b&&"null"!=b)&&a!=b){var c;if(c=b){var d=c.indexOf("|");-1!=d&&(c=c.substring(0,d))}"undefined"!=typeof a&&a!=l&&""!=a?a&&c&&(b=a.indexOf("|"),a=-1!=b?c+a.substring(b):c):a=b}a!=l&&($.dC("dtCookie"),$.sC("dtCookie",a),window.sessionStorage.setItem("dtCookie",a))}});
})();(function() {
var d=!0,e=null,f=!1,g,h=window.dT_,k,l,m,n,p,q,r,t,u,v,w="onclick",x="onmouseup",y="dT_handler",z=[];function A(b,a){b[y+a]=d;b[y]||(z[z.length]=b,b[y]=d)}function B(){if(z){for(var b=0;b<z.length;b++){var a=z[b];a.onclick&&(a.onclick.toString=e);a.onclick=e;a.onmouseup&&(a.onmouseup.toString=e);a.onmouseup=e;a.onchange&&(a.onchange.toString=e);a.onchange=e;a.onblur&&(a.onblur.toString=e);a.onblur=e;z[b]=e}z=e}}
function D(b,a,c,C){if(c&&(b[a]||a==x&&v)&&!b[y+a]){A(b,a);var s=b[a];b[a]=function(){var c=a.replace("on","");h.bi(b,C,c+" wrapper");c=e;s&&(c=s.apply(this,arguments));return c};r&&(b[a].toString=function(){if(s)return s.toString()})}}
function E(){if(k||l||m||n||p||q)if("function"==typeof document.createTreeWalker&&"undefined"!=typeof NodeFilter)for(var b=document.createTreeWalker(document,NodeFilter.SHOW_ALL,e,f);b.nextNode();)F(b.currentNode);else{var b=document.getElementsByTagName("*"),a=b.length,c;if(!(c=!h.gBI().ie))if(!(c=9<=h.gBI().ie))c=parseInt(h.cfg("mdn"),10),c=a<(isNaN(c)?5E3:c);if(c)for(c=0;c<a;c++)F(b[c]);else t||(t=d,h.pw("Document has "+a+" DOM nodes. Disabling instrumentation!"))}}
function F(b){try{D(b,x,l||v,"U"),D(b,w,k&&!v,"C")}catch(a){}for(var c=0;c<u.length;c++)try{D(b,u[c][0],u[c][1],u[c][2])}catch(C){}}if(h.smbi("a")){g=h.cfg("instr");v=h.cfg("ncw");q=p=n=m=r=l=k=f;var G=0;if(g)for(var H=g.split(","),G=0;G<H.length;G++){var I=H[G];"clk"==I?k=d:"mup"==I?l=d:"tos"==I?r=d:"blr"==I?m=d:"chg"==I?n=d:"tcs"==I?p=d:"tce"==I&&(q=d)}u=[["onblur",m,"B"],["onchange",n,"H"]];h.ael(window,"unload",B);h.ail(E)};
})();(function() {
var h=null,l=window.dT_,n=window.XMLHttpRequest,p=l.gBI().ie&&11>l.gBI().ie;
function q(c){try{var g=c.a,b=g.responseXML;if(p){if(p&&b&&!b.documentElement&&g.getResponseHeader("Content-Type").match(/[^\/]+\/[^\+]+\+xml/)){var a=new window.ActiveXObject("Microsoft.XMLDOM");a.loadXML(g.responseText)}if(a&&!(p&&a.parseError&&0!==a.parseError.errorCode||a.documentElement&&"parsererror"==a.documentElement.tagName))b=a}c.responseXML=b}catch(m){}var g="responseText response status statusText responseBody responseStream".split(" "),d;for(d in g)if(g.hasOwnProperty(d)){b=g[d];try{b in
c.a&&(c[b]=c.a[b])}catch(e){}}}
function r(c,g){function b(a){function e(e,f){try{l.ec(c.c),c.d++,a in{onerror:0,onload:1,onprogress:2}&&q(c),"object"===typeof f&&f.handleEvent?f.handleEvent.apply(f,e):f.apply(c,e)}finally{c.d--,l.lc(c.c)}}try{g[a]=function(){var f=[];if(c.b)for(var g=a.substring(2),b=0;b<c.b.length;b++)c.b[b][0]===g&&f.push(c.b[b][1]);c[a]&&e(arguments,c[a]);for(g=0;g<f.length;g++)e(arguments,f[g])}}catch(f){}}for(var a=["onloadstart","onloadend","onerror","onprogress","onload"],m=0;m<a.length;m++)b(a[m])}
function s(c){c.a.onreadystatechange=function(){};c.headers={}}
function t(c){var g=this;g.b=[];g.addEventListener=function(a,d,e){if(d){for(var f=h,c=g.b,b=0;b<c.length;b++)if(f=c[b],f[0]===a&&f[1]===d&&f[2]===e)return;c.push([a,d,e])}};g.removeEventListener=function(a,d,e){for(var f=h,c=g.b,b=0;b<c.length;b++)if(f=c[b],f[0]===a&&f[1]===d&&f[2]===e){c.splice(b,1);break}};g.dispatchEvent=function(a){for(var d=g.b,e=0;e<d.length;e++){var f=d[e];f[0]===a.type&&!f[2]&&("object"===typeof f[1]&&f[1].handleEvent?f[1].handleEvent.apply(f[1],[a]):f[1].apply(g,[a]))}};
g.h=[];var b="onloadstart onprogress onabort onerror onload ontimeout onloadend".split(" "),a;for(a in b)Object.defineProperty(g,a,{get:function(){return c[a]},set:function(g){c[a]=g},enumerable:!0});g.toString=function(){return"[XMLHttpRequestUpload]"}}
function u(c){function g(a,e,f){a.c=l.ex("x");try{a.async&&(a.a.timeout=a.timeout)}catch(c){}try{a.async&&(a.a.responseType=a.responseType)}catch(g){}a.onsend&&a.onsend.apply(a,arguments);!f&&(e&&e.nodeType)&&(e=e.xml||(new window.XMLSerializer).serializeToString(e),a.headers["Content-Type"]||a.a.setRequestHeader("Content-Type","application/xml"));r(a,a.a);var b=document.location.href;if(a.c){var k=l.gPAH(a.c);k&&!a.headers["x-dtPC"]&&(l.icr(a.url)||a.a.setRequestHeader("x-dtPC",k),l.hyb()&&(a.a.setRequestHeader("x-dtreferer",
b),a.a.setRequestHeader("X-Host",l.gh(a.url))))}(k=l.gAR(a.c))&&(k!=b&&!l.icr(a.url))&&a.a.setRequestHeader("x-dtreferer",k);a.a.withCredentials!==a.withCredentials&&(a.a.withCredentials=a.withCredentials);b=f?a.a.sendAsBinary(e):(b=v(a,"send"))?b.call(a.a,e):a.a.send(e);!a.async&&(a.readyState&&"undefined"!==typeof a.c)&&l.lx(a.c);return b}function b(){a.readyState=a.a.readyState;if(a.readyState!=a.f||100<l.nw()-a.e){q(a);4==a.readyState&&s(a);var d=a,e=d.c;try{l.ec(e),d.d++,d.dispatchEvent({type:"readystatechange",
bubbles:!1,cancelable:!1,timeStamp:new Date+0})}finally{d.d--,l.lc(e),4==d.readyState&&e&&(l.lx(e),d.c=h)}a.e=l.nw()}a.f=a.readyState}var a=this;a.a=arguments.length?new n(c):new n;a.b=[];a.headers={};a.url="";a.UNSENT=0;a.OPENED=1;a.HEADERS_RECEIVED=2;a.LOADING=3;a.DONE=4;a.readyState=0;a.f=-1;a.e=l.nw();a.d=0;try{Object.defineProperty(a,"responseType",{get:function(){return a.a.responseType},set:function(d){a.a.responseType=d}})}catch(m){}a.responseXML=h;q(a);a.onreadystatechange=h;"withCredentials"in
a.a&&(a.withCredentials=a.a.withCredentials);a.timeout=0;"upload"in a.a&&(a.upload=new t(a.a.upload));a.open=function(d,e,f,c,g){function m(b,k){try{try{b.apply(a.a,k)}catch(A){4<k.length?b(d,e,f,c,g):3<k.length?b(d,e,f,c):b(d,e,f)}}finally{a.readyState=a.a.readyState}}a.g=!1;3>arguments.length&&(f=!0);a.async=f;p&&f&&l.ael(window,"unload",function(){4!=a.a.readyState&&(s(a),a.abort())});a.a.onreadystatechange=b;a.onopen&&a.onopen.apply(a,arguments);a.url=e;var k=v(a,"open");k?m(k,arguments):m(a.a.open,
arguments)};a.send=function(d){return g(a,d,!1)};"sendAsBinary"in a.a&&(a.sendAsBinary=function(d){return g(a,d,!0)});a.abort=function(){a.onabort&&a.onabort.apply(a,arguments);0<a.readyState&&(a.g=!0);var d=v(a,"abort");d?d.apply(a.a,arguments):a.a.abort();s(a);if(a.c){for(;0<a.d;)a.d--,l.lc(a.c);l.lx(a.c);a.c=h}};a.getAllResponseHeaders=function(){var d=v(a,"getAllResponseHeaders");return d?d.apply(a.a,arguments):a.a.getAllResponseHeaders()};a.getResponseHeader=function(d){var e=v(a,"getResponseHeader");
return e?e.apply(a.a,arguments):a.a.getResponseHeader(d)};a.setRequestHeader=function(d,e){a.headers[d]=e;var f=v(a,"setRequestHeader");return f?f.apply(a.a,arguments):a.a.setRequestHeader(d,e)};a.a.overrideMimeType&&(a.overrideMimeType=function(d){var e=v(a,"overrideMimeType");return e?e.apply(a.a,arguments):a.a.overrideMimeType(d)});a.a.addEventListener&&(a.addEventListener=function(d,e,f){for(var c=h,b=0;b<a.b.length;b++)if(c=a.b[b],c[0]==d&&c[1]==e&&c[2]==f)return;a.b.push([d,e,f])},a.removeEventListener=
function(d,e,f){for(var c=h,b=0;b<a.b.length&&!(c=a.b[b],c[0]==d&&c[1]==e&&c[2]==f);b++);c&&a.b.splice(b,1)});a.dispatchEvent=function(d){d={type:d.type,target:a,currentTarget:a,eventPhase:2,bubbles:d.bubbles,cancelable:d.cancelable,timeStamp:d.timeStamp,stopPropagation:function(){},preventDefault:function(){},initEvent:function(){}};"readystatechange"==d.type&&a.onreadystatechange&&a.onreadystatechange.apply(a,[d]);for(var c=0;c<a.b.length;c++){var b=a.b[c];b[0]==d.type&&!b[2]&&("object"===typeof b[1]&&
b[1].handleEvent?b[1].handleEvent.apply(b[1],[d]):b[1].apply(a,[d]))}};a.toString=function(){return"[XMLHttpRequest]"}}function w(c){return Object.getPrototypeOf?Object.getPrototypeOf(c):{}.__proto__===Object.prototype&&[].__proto__===Array.prototype?c.__proto__:c.constructor?c.constructor.prototype:void 0}function v(c,g){try{var b=w(c),a=w(c.a);a||(a=n.prototype);return b&&a&&b[g]!=a[g]?b[g]:h}catch(m){return h}}
if(l.smbi("x")){if(window.XMLHttpRequest&&(window.XMLHttpRequest=u,n.prototype))for(var x="open send setRequestHeader getResponseHeader getAllResponseHeaders abort overrideMimeType addEventListener removeEventListener dispatchEvent".split(" "),y=0;y<x.length;y++){var z=x[y];n.prototype[z]&&(u.prototype[z]=n.prototype[z])}l.ael(window,"unload",function(){window.XMLHttpRequest=n;p=n=h})};
})();(function() {
var d=void 0,k=!0,n=null,p=window.dT_,r=n,s=n,t=n,u=n,v=!1,w=n,x,y=!1,z=!1,B={};function C(b){for(var a in b)b.hasOwnProperty(a)&&(B[a]=b[a]);return r.apply(this,arguments)}
function D(b,a){function c(a){q||(q=k,p.st(function(){p.lx(a)},0))}var e=b,q=!1;"object"===typeof b&&(a=b,e=a.url);a=a||{};for(var h in B)B.hasOwnProperty(h)&&!a.hasOwnProperty(h)&&(a[h]=B[h]);"function"===typeof a.data&&(a.type=a.type||a.callback,a.callback=a.data,a.data=d);"string"===typeof a.success&&(a.success=d);var g=p.ex("j"+window.jQuery().jquery,3),A,G=a.beforeSend;a.beforeSend=function(a,b){if(g){var f=document.location.href,m=p.gPAH(g);m&&(p.icr(e)||a.setRequestHeader("x-dtPC",m),p.hyb()&&
(a.setRequestHeader("x-dtreferer",f),a.setRequestHeader("X-Host",p.gh(e))));(m=p.gAR(g))&&(m!=f&&!p.icr(e))&&a.setRequestHeader("x-dtreferer",m)}if(G){f=d;try{f=G.apply(this,arguments)}catch(l){throw"TypeError"==l.name&&c(g),l;}return f}};if(a.async===d||a.async){var f=a.complete;a.complete=function(a,b){"success"!=b&&p.pw('jQuery reported "'+b+'"');p.ec(g);var e=d;try{if(f)if("function"==typeof f)e=f.apply(this,arguments);else if(f.length)for(var m=0;m<f.length;m++)f[m].apply(this,arguments)}finally{p.lc(g),
c(g)}return e};var l=a.success;l&&(a.success=function(a,b,e){p.ec(g);try{var f=d;if("function"==typeof l)f=l.apply(this,arguments);else if(l.length)for(var h=0;h<l.length;h++)l[h].apply(this,arguments)}finally{p.lc(g),c(g)}return f});var H=a.error;H&&(a.error=function(a,b,e){p.ec(g);var f=d;try{f=H.apply(this,arguments)}finally{p.lc(g),c(g)}return f});A=u.apply(this,arguments)}else{p.ec(g);try{A=u.apply(this,arguments)}finally{p.lc(g),c(g)}}return A}var E=n;
function F(b,a){var c=n,e=!1;switch(a){case "click":a="C";c="clk";break;case "dblclick":a="CC";c="dcl";break;case "mouseup":a="U";c="mup";break;case "mousedown":a="D";c="mdw";break;case "keyup":a="KU";c="kyu";break;case "keydown":a="KD";c="kyd";break;case "scroll":a="S";c="scr";break;case "touchstart":a="TS";c="tcs";break;case "touchend":a="TE";c="tce";break;case "autocomplete":a="A";break;default:e=k}var q;!E&&p.cfg("doNotDetect")&&(E=p.cfg("doNotDetect").split(","));q=E;if(c&&q)for(var h=0;h<q.length;h++)q[h]==
c&&(e=k);return b&&!e?(c=function(c){var e=p.gci(),h=d;if(0==a.indexOf("KD")||0==a.indexOf("KU")){var f=c.keyCode?c.keyCode:c.charCode;f&&(a=0==a.indexOf("KD")?"KD"+f:"KU"+f)}var f=a,l=c.target||c.currentTarget||c.srcElement||n;l&&(e||p.bi(l,f),h=b.apply(this,arguments));return h},c.dtHook=k,c.origHandler=b,c):b}function I(b,a){var c=b[a];if(c)for(var e=0;e<c.length;e++)c[e].handler&&!c[e].handler.dtHook&&(c[e].handler=F(c[e].handler,a))}
function J(b,a,c){var e=t.apply(this,arguments);"undefined"!=typeof e&&e&&"events"==a&&(I(e,"click"),I(e,"mouseup"),I(e,"mousedown"),I(e,"keydown"),I(e,"autocomplete"));return e}function K(b,a){if(a)for(var c=0;c<a.length;c++)a[c].handler&&!a[c].handler.dtHook&&(a[c].handler=F(a[c].handler,a[c].type));c=window.jQuery;if(s)return s.apply(this,arguments);if(c&&c.event.handlers&&c.event.handlers!=K)return c.event.handlers.apply(this,arguments)}
function L(){var b=arguments;3==b.length&&(b[2]&&"undefined"!==typeof b[2].origHandler)&&(b[2]=b[2].origHandler);return w.apply(this,b)}
function M(){var b=window.jQuery;p.rpl(b,"data");p.rpl(b,"ajax");p.rpl(window,"jQuery");!y&&N()&&(y=k,p.ti(),u=b.ajax,b.ajax=D,r=b.ajaxSetup,b.ajaxSetup=C,(s=b.event.handlers)?b.event.handlers=K:(t=b.data,b.data=J),b.fn&&(w=b.fn.off,b.fn.off=L),p.ael(window,"unload",function(){v||("undefined"!=typeof b&&(b.ajax=u,b.data=t,b.ajaxSetup=r,s&&(b.event.handlers=s),b.fn&&(b.fn.off=w)),r=w=s=t=u=n,v=k)}))}function O(){var b=window.jQuery;b&&(b.data&&b.ajax&&b.ajaxSetup)&&M()}
function N(){if("undefined"===typeof x){var b=window.jQuery().jquery.split(".");x=p.cvs("1.3 1.4 1.5 1.6 1.6 1.7 1.8 1.9 1.10 1.11 2.0 2.1".split(" "),b[0],b[1],"jQuery")}return x}p.smbi("j")&&(p.initJQuery=M,p.apl(window,"jQuery",n,function(){window.jQuery.ajax?M():z||(p.apl(window.jQuery,"ajax",n,O),p.apl(window.jQuery,"data",n,O),p.apl(window.jQuery,"ajaxSetup",n,O),z=k)}),p.all(function(){O()}));
})();(function() {
var b=window.dT_,h=window.performance,k={c:"redirectStart",d:"redirectEnd",e:"fetchStart",f:"domainLookupStart",g:"domainLookupEnd",h:"connectStart",i:"connectEnd",j:"secureConnectionStart",k:"requestStart",l:"responseStart",m:"responseEnd",n:"domLoading",o:"domInteractive",p:"domContentLoadedEventStart",q:"domContentLoadedEventEnd",r:"domComplete",s:"loadEventStart",t:"loadEventEnd"},m=!1;
b.smbi("n")&&b.asl(function(e,n){if(!n&&!m&&b.las())if(m=!0,"undefined"!=typeof h)if(b.gBI().ff&&9>=b.gBI().ff)e.a("nt","0");else{var a;a=h.timing||{};var d=h.navigation||{},f=a.navigationStart;if(f){var d=["a",d.type,"b",f],c;for(c in k){var g=a[k[c]];if(g&&g>=f){if("j"!=c&&"t"!=c){var l=a[k[String.fromCharCode(c.charCodeAt(0)+1)]];!(l&&l>=g)&&l&&b.pw("Browser reported inconsistent navigation timings! Durations might not be reliable.")}d.push(c);d.push(g-f)}}a=d.join("")}else a=null;a?e.a("nt",a):
e.a("nt","0")}else e.a("nt","0")});
})();(function() {
var e=!0,g=null,h=window.dT_,k=0,m=0,n=!1,p=0,q=0,r=h.vi=0,s=g;function t(a,c){var b={};if(document.getBoxObjectFor){var d=document.getBoxObjectFor(a);b.x=d.x;b.y=d.y}else a.getBoundingClientRect?(d=a.getBoundingClientRect(),b.x=d.left,b.y=d.top):(b.x=-1,b.y=-1);c&&window.self!=window.top&&(d=u(x()),b.x+=d.x,b.y+=d.y);return b}
function y(){if(document.images.length>p){for(var a=document.images,c=0===p?0:p-1;c<a.length;c++){var b=a[c];h.ael(b,"load",z);h.ael(b,"error",z);h.ael(b,"abort",z)}p=a.length}n||h.st(y,10)}function z(a){var c=a.target||a.srcElement,b=h.nw();h.abwsl(function(){A(c,b)})}function A(a,c){if(h!=s)s.abwsl(function(){var b=B(a),f=t(a,e),f=s.iws(a,f);C(b&f,c)});else{var b=B(a);C(b,c)}}function C(a,c){a&&h.vi++;a&&c>q&&(q=c)}
function B(a,c){if(!a)return!1;c||(c=t(a));if(0<=c.x&&5>=c.x&&0<=c.y&&5>=c.y)return e;var b=s.bwsW,d=s.bwsH,f=a.width||a.scrollWidth,l=a.height||a.scrollHeight;if(0>=c.x&&0>=c.y&&0<=c.x+f&&0<=c.y+l)return e;if(0>f||0>l||0>b||0>d)return!1;var v=c.x,w=c.y,f=f+v,l=l+w,b=b+k,d=d+m;return(f<v||f>k)&&(l<=w||l>=m)&&(b<k||b>v)&&(d<m||d>w)}function D(){0===r&&(r=h.nw());return r}function E(){D();n=e;var a=D();if(0===q||0===document.images.length)q=a}
function u(a){for(var c=0,b=0,d=window.self;d!==g&&s!=d.dT_;){c+=a?a.offsetLeft:0;b+=a?a.offsetTop:0;try{a=x(window.parent),d=d.parent}catch(f){d=g}}a={};a.x=c;a.y=b;return a}function x(a){a||(a=window);if(s===h)return g;try{for(var c=a.parent.frames,b=0;b<c.length;b++){var d=c[b];if(d==a)return d.frameElement}return g}catch(f){return g}}var F=!1;
h.smbi("p")&&(h.all(E),y(),h.iws=B,s=h.tdto(),h.asl(function(a,c){if(!c&&!F&&h.las()){F=e;var b,d=q;b=h.lst();var f=D(),d=d-b;0>=d&&(d=f-b);if(0>d||2147483647<=d)d=0;b=d;h===s?f=e:(f=x(),f=f===g?0<h.vi||0===window.frames.length:0===h.vi||0===document.images.length&&0<window.frames.length?!1:s.iws(f,u(f)));f&&a.a("p",b)}}));
})();(function() {
var d=window.dT_,g=void 0,m=null,n=null,p={};function q(b){b=m+b.startTime;b-=d.lst();return Math.round(b)}function r(){var b=d.gP();if(b&&b.timing){var h=b.getEntriesByType||b.webkitGetEntriesByType,k=b.getEntriesByName||b.webkitGetEntriesByName;h&&k&&(m=b.timing.navigationStart,g=function(){return h.call(b,"resource")},b.onresourcetimingbufferfull=function(){b.setResourceTimingBufferSize(g().length+100)},d.arti=s)}}
function s(b){if(g)for(var h=g(),k=0;k<h.length;k++){var c=h[k];if(!p[c.name]){var l=c.name;if(d.tpih(l)&&!(-1<l.indexOf(d.gAN()))&&!(-1<l.indexOf(d.cfg("reportUrl")))){var l=b,e={};e[0]=t(c);e[11]=Math.round(c.duration);e[5]=q(c);var v=e,f;0<c.responseEnd?(f=m+c.responseEnd,f-=d.lst(),f=Math.round(f)):(f=d.nw(),f=Math.round(f-d.lst()));v[6]=f;e[1]=c.name;n=d.gP().timing.loadEventEnd;e[2]=q(c)<=n?"_load_":"-";e[8]=0===c.responseEnd;e[7]=d.gh(c.name)==d.gh(document.location.href)&&d.gBI().ie?0!=c.requestStart:
0<c.responseEnd;e[9]=d.gBI().ch?0!=c.domainLookupStart&&0==c.requestStart:d.gh(c.name)!=d.gh(document.location.href)&&0===c.requestStart&&2>c.duration?!0:0>=c.responseEnd?!1:c.requestStart==c.fetchStart&&c.requestStart==c.responseStart&&c.responseStart!=c.responseEnd;l.push(e)}}}}
function t(b){b=b.name.toLowerCase();-1<b.indexOf("ScriptResource.axd")?b="js":(b=b.substr(1+b.lastIndexOf("/")),0<b.indexOf("?")&&(b=b.split("?")[0]),0<b.indexOf("#")&&(b=b.split("#")[0]),b=0<b.indexOf(".")?b.substring(b.lastIndexOf(".")+1):"-");switch(b){case "js":return"s";case "gif":case "png":case "jpg":case "jpeg":case "ico":case "tiff":case "bmp":case "xbm":case "svg":return"i";case "css":return"y";default:return"o"}}
if(d.smbi("r"))if(window.a)d.re_r=!1;else{var u=d.gP();if(u&&u.timing){var w=u.getEntriesByName||u.webkitGetEntriesByName;(u.getEntriesByType||u.webkitGetEntriesByType)&&w?(d.re_r=!0,r()):d.re_r=!1}else d.re_r=!1};
})();(function() {
var e=window.dT_,k=!1,p=30,q=500,s=3,t=!1,u=-1,v,w,x;function y(c,d,f){for(var b=2;b<arguments.length;b++)c.push(arguments[b]),(b<arguments.length-1||d)&&c.push("|")}function z(c,d){return c[12]<d[12]?1:c[12]==d[12]?0:-1}
function A(){this.head=null;this.add=function(c,d){if(c>d)throw"Error: Start("+c+") must be before stop ("+d+")";var f={start:c,stop:d},b=this.head,h=null;if(b){for(;b&&c>b.start;)h=b,b=b.next;h?(f.next=h.next,h.next=f):(f.next=this.head,this.head=f)}else this.head=f,f.next=null};this.reduce=function(){for(var c=this.head;c&&c.next;){for(;c.next&&c.stop+1>=c.next.start;)c.stop<=c.next.stop&&(c.stop=c.next.stop),c.next=c.next.next;c=c.next}};this.p=function(){this.reduce();for(var c=[],d=this.head;d;)0<
c.length&&y(c,0,"_"),y(c,0,d.start),y(c,0,"_"),y(c,0,d.stop),d=d.next;return c.join("")}}var B=[];function C(){if(e.re_t)for(var c=0,c=0;c<B.length;c++){var d=B[c];0===d[4]&&0<d[3]&&("i"===d[0]?(d[8]=!0,d[7]=!1,d[4]=e.nw()):(d[5]||(d[7]=!0),d[4]=d[3]));d[12]=d[4]?d[4]-d[3]:d[12]}}
function D(){var c=e.lst();C();if(0<B.length&&0<c){var d={},f;for(f=0;f<B.length;f++){var b=B[f],h=e.gh(b[1]);d[h]||(d[h]=[]);y(d[h],0,b)}var r={},l=null;for(l in d)if(d.hasOwnProperty(l)&&d[l].length){h=d[l];h.sort(z);var g={};for(f=0;f<h.length;f++){var b=h[f],a=g[b[0]];a||(a={g:0,q:0,n:0,m:0,h:0,j:0,r:new A,u:new A,k:0,e:c+99999999,b:0,l:0,f:c+99999999,d:0},g[b[0]]=a);if(b[3]&&b[4]){a.h++;var m=b[4]-b[3];a.e=a.e<m?a.e:m;a.b=a.b>m?a.b:m;a.k=e.pn((a.k*(a.h-1)+m)/a.h,10);a.r.add(b[3]-c,b[4]-c)}if(b[5]&&
b[6]){a.j++;m=b[11];0>m&&(m=b[6]-b[5]);if(0>m||3E5<m)m=0;a.f=a.f<m?a.f:m;a.d=a.d>m?a.d:m;a.l=e.pn((a.l*(a.j-1)+m)/a.j,10);a.u.add(b[5],b[6])}a.g+=b[7]?1:0;a.m+=b[9]?1:0;b[7]||(a.q+=b[8]?1:0,a.n+=b[8]?0:1)}r[l]={t:0};for(var n in g)g.hasOwnProperty(n)&&(a=g[n],r[l].t=Math.max(a.b,a.d),r[l][n]="i"==n||"s"==n?[a.g,a.n,a.q,a.m,a.h,a.j,a.r.p(),a.k,a.h?a.e:"0",a.b,a.u.p(),a.l,a.j?a.f:"0",a.d].join("|"):"o"==n||"y"==n?[a.g,a.n,a.q,a.m,a.u.p(),a.l,a.f,a.d].join("|"):[a.g,a.r.p(),a.k,a.e,a.b].join("|"))}n=
[];for(l in r)d.hasOwnProperty(l)&&y(n,0,l);0<u&&(h=n.sort(function(a,b){return r[b].t-r[a].t}),h.length>u&&(n=h.slice(0,u)));g=[];for(a=0;a<n.length;a++){l=n[a];h=d[l];f=r[l];0<g.length&&y(g,0,";");y(g,1,e.aesc(l),"featureHash");b=0;l=g.length-2;f.i&&(y(g,1,f.i),b+=2);f.s&&(y(g,1,f.s),b+=4);f.y&&(y(g,1,f.y),b+=8);f.o&&(y(g,1,f.o),b+=16);f.c&&(y(g,1,f.c),b+=32);g.pop();g[l]=b.toString(32);for(f=0;f<h.length&&f<s&&(h[f][12]>=q||h[f][11]>=q);f++)b=h[f],y(g,0,","),y(g,0,b[0]+(b[7]?"":b[8]?"i":"f"),b[3]?
b[3]-c:0,b[4]?b[4]-c:0,e.aesc(b[2]),e.tpesc(b[1])),b[5]&&y(g,0,"",b[5],b[6])}return e.esc(g.join(""))}return null}function E(c,d){if(!d&&!k&&e.las()){k=!0;var f;e.re_t&&(B=e.thirdPartyInfo);e.re_r&&e.arti(B);(f=D())&&c.a("3p",f);B=[]}}function F(c){var d=e.gh(c);return!(-1!=c.indexOf("chrome-extension://")||-1!=c.indexOf("chrome://")||-1!=c.indexOf("data:"))&&(t||d&&d!=v)}function G(){0<w&&2E3<e.nw()-w?(x=!1,e.asl(E),e.sMPS(5E3)):(e.re_t&&e.inttp(),e.st(G,p))}var H=e.cfg("tp")?e.cfg("tp"):"500,50,3";
if(e.smbi("2")){var I=H.split(","),J=I.length;3<=J&&5>=J&&(q=e.pn(I[0],10),p=e.pn(I[1],10),s=e.pn(I[2],10),4<=J&&(t=e.pn(I[3],10)),5==J&&(u=e.pn(I[4],10)),v=e.gh(document.location.href),e.tpih=F,e.apll(function(){e.asl(E)}),e.all(function(){w=e.nw()}),e.asl(function(){-1===w&&(w=e.nw())}),e.ca()&&!x&&(w=e.nw(),x=!0,G()),w=-1)};
})();(function() {
var c=!0,g=window.dT_;function h(a,b,d){for(var e=2;e<arguments.length;e++)a.push(arguments[e]),(e<arguments.length-1||b)&&a.push("|")}var k=[];g.thirdPartyInfo=k;function m(a,b){for(var d=g.nw(),e=0;e<k.length;e++)if(k[e][1]==b)return;var e=g.ca(),f={};f[0]=a;f[3]=d;f[4]=0;f[1]=b;f[2]=e?e.name:"-";f[9]=!1;h(k,0,f)}function n(a,b,d,e){for(var f=0;f<k.length;f++){var l=k[f];if(l[1]==a){2<arguments.length&&0<d&&(l[3]=d);l[4]=3<arguments.length&&0<e?e:g.nw();l[7]=b;b||(l[9]=!1,l[10]=c);break}}}
function p(a){n(a.target.src,c)}function q(){window&&window.event&&window.event.srcElement&&("loaded"==window.event.srcElement.readyState||"complete"==window.event.srcElement.readyState)&&n(window.event.srcElement.src,c)}function r(a){var b=null;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&n(b.src,c)}
function s(a){var b=null;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&b.src!=document.location.href&&n(b.src,!1)}function t(a){if(!a.a){a.a=g.nw();try{""!=a.src&&g.tpih(a.src)&&(m("i",a.src),!a.complete||"undefined"!=typeof a.naturalWidth&&0===a.naturalWidth?(g.ael(a,"load",r),g.ael(a,"error",s),a.src=a.src):n(a.src,c))}catch(b){}}}
function u(){var a=document.getElementsByTagName("img"),b,d;for(b=0;b<a.length;b++)d=a[b],t(d);a=document.getElementsByTagName("input");for(b=0;b<a.length;b++)d=a[b],d.type&&"SUBMIT"==d.type.toUpperCase()&&t(d);a=document.getElementsByTagName("script");for(b=0;b<a.length;b++)if(d=a[b],!d.a&&(d.a=g.nw(),""!=d.src&&g.tpih(d.src)&&(!d.attributes||!d.attributes["data-dtconfig"])))m("s",d.src),g.gBI().ie&&11>g.gBI().ie?g.ael(d,"readystatechange",q):g.ael(d,"load",p)}
if(g.smbi("3")){g.tpstr=m;g.tpsto=n;g.inttp=u;g.re_t=c;var v=g.gP();if(v&&v.timing){var w=v.getEntriesByName||v.webkitGetEntriesByName;if((v.getEntriesByType||v.webkitGetEntriesByType)&&w)g.re_t=!1}g.re_t&&u()};
})();