(function ensightenInit(){var ensightenOptions = {client: "amex", clientId: 218, publishPath: "amexhead", isPublic:0, serverComponentLocation: "nexus.ensighten.com/amex/amexhead/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/amex/amexhead/code/", ns: 'amexhead', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu Feb 25 06:11:54 GMT 2016", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=g.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:g.interval||100,erLoc:g.errorLocation||c.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||c.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||c.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,scUseCacheBuster:g.scUseCacheBuster,beaconSamplingSeedValue:g.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),f;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(f=0;f<h.length;f++)if(h[f].src===a&&h[f].readyState&&/loaded|complete/.test(h[f].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof d&&d.PageID&&(e=d.PageID,delete d.PageID);if("object"===typeof d)for(f in d){f=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,f.length?e.length-f.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+
f;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=
document.getElementsByTagName("script"),h;d=c[0];for(h=0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=
this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};
b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});
else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,
l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,f=b.dataDefinitionIds.length,g=0;g<f;g++)if(b.dataDefinitionIds[g]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var d=b.dataDefinitions[e];d||(d=new b.DataDefinition(e,a),b.dataDefinitions[e]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var g=0;g<c.length;g++)try{c[g].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,f=0;f<c.ruleList.length;++f)d=c.ruleList[f],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(g.client)+"/"+encodeURIComponent(g.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(g.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var g=window.performance;if(g){var g=g.timing||{},m="",n=g.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(g.navigationStart),b;for(b in c)void 0!==g[b]?(p=g[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||
"";m=g.indexOf(".com/");n=g.indexOf("/code/");g=g.substring(m+4,n)+"/perf.rnc";g+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+g)}}});
		amexhead.dataDefinitionIds = [];amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/acctserv/us/accountservices.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/acctserv/us/accountservices.do?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},968177,334375);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://www.americanexpress.com/us/small-business/openforum/articles/")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},975459,335213);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=
path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId;i>0;i--)if(!~p[i].indexOf("#")&&!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=
window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p)if(p=="act"&&~v.indexOf("$$$"))console.log(v);else console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),
b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],initialized:!1,disabled:~window.location.search.indexOf("ensTools\x3ddisable"),
cloak:!1,pageSpecificCompletion:!0,DOMParsed:!0,content:{map:{},target:function(o){if(o instanceof Array)for(var i=0,l=o.length;i<l;i++)this.add(o[i]);else this.add(o)},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u)){this.map[o.x]=o;this.map[o.x].t="map"}}else{this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.cloak)Bootstrapper.MVT.cover()}},getTimeout:function(){return 5},
addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");_log(h.tests.slice());Bootstrapper.MVT.initialized=!0;if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},cover:function(){this.cloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");
if(this.pageSpecificCompletion)Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("complete")});if(this.DOMParsed)Bootstrapper.bindDOMParsed(function(){Bootstrapper.MVT.uncover("parsed")});Bootstrapper.bindDOMLoaded(function(){Bootstrapper.MVT.uncover("loaded")});setTimeout(function(){Bootstrapper.MVT.uncover("timeout")},7E3)},uncover:function(l){if(this.cloak)if(this.delCSS(this.cloak)){this.cloak=!1;_log("*** Cloak:"+l)}},show:function(a){a.style.display=a.style.oldDisplay||
"block";a.style.visibility="visible"},done:function(){var a=this.hidden,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i])},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else _log("*** MVT:stop - not found \x3d "+o.x)},push:function(o){if(this.disabled)return;
if(typeof o=="object"){_log("*** MVT:push");_log(o);if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x){var d=document,s=d.createElement("style");if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);
s.styleSheet.cssText=x}else{s=d.createElement("style");s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,
a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);try{f.oldStyle=f.style.display,f.style.display="none",b.style.display=b.oldStyle}catch(g){}b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{if(b&&b.style)b.style.display=b.oldStyle||"block";_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,
c[0]):h.split(c,b)}};return i}();Bootstrapper._getServerComponent=Bootstrapper.getServerComponent;Bootstrapper.getServerComponent=function(){Bootstrapper.MVT.init();Bootstrapper._getServerComponent.apply(Bootstrapper,arguments)};Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");
setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p==
"replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p==
"after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a)}});window[ensightenOptions.ns].VTconfig=window[ensightenOptions.ns].VTconfig||
{};window[ensightenOptions.ns].VTconfig["MVT"]=this.deploymentId;Bootstrapper.MVT.addModule("tt",{init:function(){window.mboxWrite=function(a,b){var n=document.getElementById(a);if(n!==null)n.innerHTML+=b}},swap:function(a,b){if(typeof mboxFactoryDefault=="undefined"||!mboxFactoryDefault.isEnabled()){Bootstrapper.MVT.show(a,b);_log("*** MVT:show - T\x26T disabled");_log(a);_log(b)}else{_log("*** MVT:loaded");_log(a);_log(b);var i="_ensMbox"+(1E3*Math.random()).toFixed(0),f,p,s,o=!1;if(b.a=="replace"){o=
!0;if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA|BR/)){s=Bootstrapper.MVT.injectCSS("#"+i+"{visibility:hidden!important}",1);a.innerHTML='\x3cdiv id\x3d"'+i+'" class\x3d"mboxDefault"\x3e'+a.innerHTML+"\x3c/div\x3e"}else{b.a="element";setTimeout(function(){Bootstrapper.MVT.swap(a,b)},1);return}}else{d=document.createElement("div");d.id=i;d.className="mboxDefault";d.style.visibility="hidden";if(b.a=="prepend"){if(a.firstChild!==null)a.insertBefore(d,a.firstChild);Bootstrapper.MVT.done()}else if(b.a==
"append")a.appendChild(d,a);else if(b.a=="element"||typeof b.a=="undefined"){o=!0;var c=a.cloneNode(!0),s=Bootstrapper.MVT.injectCSS("#"+i+"{visibility:hidden!important}",1);d.appendChild(c);if(a.parentNode!==null)a.parentNode.replaceChild(d,a)}else if(b.a=="before"){if(a.parentNode!==null)a.parentNode.insertBefore(d,a)}else if(b.a=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling)}Bootstrapper.MVT.show(a,b);f=b.p||{};
p=[];for(k in f)p.push(k+"\x3d"+f[k]);var m=window.mboxDefine(i,b.i);p.unshift(b.i);window.mboxUpdate.apply(m,p);m=window.mboxFactories.get("default").get(b.i)||{};m._show=m.show;m._ens_init=!0;m.show=function(a,m,s){return function(){var r=m._show.call(m);if(r){m._ens_init=!1;clearTimeout(Bootstrapper["mboxTimeout_"+m.g]);if(m.getDefaultDiv()&&m.getDefaultDiv().style)m.getDefaultDiv().style.visibility="visible";Bootstrapper.MVT.delCSS(s)}return r}}(a,m,s);m.ac=function(Fb,bc){if(!m._ens_init)if(Fb&&
Fb.style)Fb.style.visibility=bc?"visible":"hidden";if(Fb&&Fb.style)Fb.style.display=bc?"block":"none"};Bootstrapper["mboxTimeout_"+m.g]=setTimeout(function(m){return function(){m.show=function(){};m.hide=function(){};if(m.getDefaultDiv()&&m.getDefaultDiv().style)m.getDefaultDiv().style.visibility="visible";Bootstrapper.MVT.done()}}(m),25E3)}}});Bootstrapper.ensConfigMboxJS=function(h){try{var f=h.clientCode||"",k=h.adminServer||"",l=h.expiration||1209600,t=h.timeout||15E3;if(""==f||""==k)return!1;
mboxCopyright="Copyright 1996-2012. Adobe Systems Incorporated. All rights reserved.";mboxUrlBuilder=function(a,b){this.a=a;this.b=b;this.c=[];this.d=function(a){return a};this.f=null};mboxUrlBuilder.prototype.addNewParameter=function(a,b){this.c.push({name:a,value:b});return this};mboxUrlBuilder.prototype.addParameterIfAbsent=function(a,b){if(b){for(var c=0;c<this.c.length;c++)if(this.c[c].name===a)return this;this.checkInvalidCharacters(a);return this.addNewParameter(a,b)}};mboxUrlBuilder.prototype.addParameter=
function(a,b){this.checkInvalidCharacters(a);for(var c=0;c<this.c.length;c++){var d=this.c[c];if(d.name===a)return d.value=b,this}return this.addNewParameter(a,b)};mboxUrlBuilder.prototype.addParameters=function(a){if(!a)return this;for(var b=0;b<a.length;b++){var c=a[b].indexOf("\x3d");-1!=c&&0!=c&&this.addParameter(a[b].substring(0,c),a[b].substring(c+1,a[b].length))}return this};mboxUrlBuilder.prototype.setServerType=function(a){this.m=a};mboxUrlBuilder.prototype.setBasePath=function(a){this.f=
a};mboxUrlBuilder.prototype.setUrlProcessAction=function(a){this.d=a};mboxUrlBuilder.prototype.buildUrl=function(){for(var a=("file:"==document.location.protocol?"http:":document.location.protocol)+"//"+this.a+(this.f?this.f:"/m2/"+this.b+"/mbox/"+this.m),b=-1!=a.indexOf("?")?"\x26":"?",c=0;c<this.c.length;c++)var d=this.c[c],a=a+(b+encodeURIComponent(d.name)+"\x3d"+encodeURIComponent(d.value)),b="\x26";return this.r(this.d(a))};mboxUrlBuilder.prototype.getParameters=function(){return this.c};mboxUrlBuilder.prototype.setParameters=
function(a){this.c=a};mboxUrlBuilder.prototype.clone=function(){var a=new mboxUrlBuilder(this.a,this.b);a.setServerType(this.m);a.setBasePath(this.f);a.setUrlProcessAction(this.d);for(var b=0;b<this.c.length;b++)a.addParameter(this.c[b].name,this.c[b].value);return a};mboxUrlBuilder.prototype.r=function(a){return a.replace(/\"/g,"\x26quot;").replace(/>/g,"\x26gt;")};mboxUrlBuilder.prototype.checkInvalidCharacters=function(a){if(/('|")/.exec(a))throw"Parameter '"+a+"' contains invalid characters";
};mboxStandardFetcher=function(){};mboxStandardFetcher.prototype.getType=function(){return"standard"};mboxStandardFetcher.prototype.fetch=function(a){a.setServerType(this.getType());document.write('\x3cscript src\x3d"'+a.buildUrl()+'" language\x3d"JavaScript"\x3e\x3c/script\x3e')};mboxStandardFetcher.prototype.cancel=function(){};mboxAjaxFetcher=function(){};mboxAjaxFetcher.prototype.getType=function(){return"ajax"};mboxAjaxFetcher.prototype.fetch=function(a){a.setServerType(this.getType());a=a.buildUrl();
this.w=document.createElement("script");this.w.src=a;document.body.appendChild(this.w)};mboxAjaxFetcher.prototype.cancel=function(){};mboxMap=function(){this.x={};this.y=[]};mboxMap.prototype.put=function(a,b){this.x[a]||(this.y[this.y.length]=a);this.x[a]=b};mboxMap.prototype.get=function(a){return this.x[a]};mboxMap.prototype.remove=function(a){this.x[a]=void 0};mboxMap.prototype.each=function(a){for(var b=0;b<this.y.length;b++){var c=this.y[b],d=this.x[c];if(d&&!1===a(c,d))break}};mboxFactory=
function(a,b,c){this.D=!1;this.B=a;this.C=c;this.E=new mboxList;mboxFactories.put(c,this);this.G=(this.F="undefined"!=typeof document.createElement("div").replaceChild&&"undefined"!=typeof document.getElementById&&"undefined"!=typeof(window.attachEvent||document.addEventListener||window.addEventListener)&&"undefined"!=typeof encodeURIComponent)&&null==mboxGetPageParameter("mboxDisable");var d="default"==c;this.I=new mboxCookieManager("mbox"+(d?"":"-"+c),mboxCookiePageDomain());this.G=this.G&&this.I.isEnabled()&&
null==this.I.getCookie("disable");this.isAdmin()&&this.enable();this.J();this.K=mboxGenerateId();this.L=mboxScreenHeight();this.M=mboxScreenWidth();this.N=mboxBrowserWidth();this.O=mboxBrowserHeight();this.P=mboxScreenColorDepth();this.Q=mboxBrowserTimeOffset();this.R=new mboxSession(this.K,"mboxSession","session",1860,this.I);this.S=new mboxPC("PC",l,this.I);this.v=new mboxUrlBuilder(a,b);this.T(this.v,d);this.V=this.U=(new Date).getTime();var e=this;this.addOnLoad(function(){e.V=(new Date).getTime()});
this.F&&(this.addOnLoad(function(){e.D=!0;e.getMboxes().each(function(a){a.setFetcher(new mboxAjaxFetcher);a.finalize()})}),this.G&&(this.limitTraffic(100,10368E3),this.Y(),this.Z=new mboxSignaler(function(a,b){return e.create(a,b)},this.I)))};mboxFactory.prototype.isEnabled=function(){return this.G};mboxFactory.prototype.getDisableReason=function(){return this.I.getCookie("disable")};mboxFactory.prototype.isSupported=function(){return this.F};mboxFactory.prototype.disable=function(a,b){"undefined"==
typeof a&&(a=3600);"undefined"==typeof b&&(b="unspecified");this.isAdmin()||(this.G=!1,this.I.setCookie("disable",b,a))};mboxFactory.prototype.enable=function(){this.G=!0;this.I.deleteCookie("disable")};mboxFactory.prototype.isAdmin=function(){return-1!=document.location.href.indexOf("mboxEnv")};mboxFactory.prototype.limitTraffic=function(a,b){};mboxFactory.prototype.addOnLoad=function(a){if(this.isDomLoaded())a();else{var b=!1,c=function(){b||(b=!0,a())};this.gb.push(c);this.isDomLoaded()&&!b&&c()}};
mboxFactory.prototype.getEllapsedTime=function(){return this.V-this.U};mboxFactory.prototype.getEllapsedTimeUntil=function(a){return a-this.U};mboxFactory.prototype.getMboxes=function(){return this.E};mboxFactory.prototype.get=function(a,b){return this.E.get(a).getById(b||0)};mboxFactory.prototype.update=function(a,b){if(this.isEnabled())if(this.isDomLoaded()){if(0==this.E.get(a).length())throw"Mbox "+a+" is not defined";this.E.get(a).each(function(a){a.getUrlBuilder().addParameter("mboxPage",mboxGenerateId());
a.load(b)})}else{var c=this;this.addOnLoad(function(){c.update(a,b)})}};mboxFactory.prototype.setVisitorIdParameters=function(a){};mboxFactory.prototype.create=function(a,b,c){if(!this.isSupported())return null;var d=this.v.clone();d.addParameter("mboxCount",this.E.length()+1);d.addParameters(b);this.setVisitorIdParameters(d);b=this.E.get(a).length();var e=this.C+"-"+a+"-"+b;if(c)c=new mboxLocatorNode(c);else{if(this.D)throw"The page has already been loaded, can't write marker";c=new mboxLocatorDefault(e)}try{var m=
this,g=new mbox(a,b,d,c,"mboxImported-"+e);this.G&&g.setFetcher(this.D?new mboxAjaxFetcher:new mboxStandardFetcher);g.setOnError(function(a,b){g.setMessage(a);g.activate();g.isActivated()||(m.disable(3600,a),window.location.reload(!1))});this.E.add(g)}catch(f){throw this.disable(),'Failed creating mbox "'+a+'", the error was: '+f;}a=new Date;d.addParameter("mboxTime",a.getTime()-6E4*a.getTimezoneOffset());return g};mboxFactory.prototype.getCookieManager=function(){return this.I};mboxFactory.prototype.getPageId=
function(){return this.K};mboxFactory.prototype.getPCId=function(){return this.S};mboxFactory.prototype.getSessionId=function(){return this.R};mboxFactory.prototype.getSignaler=function(){return this.Z};mboxFactory.prototype.getUrlBuilder=function(){return this.v};mboxFactory.prototype.T=function(a,b){a.addParameter("mboxHost",document.location.hostname).addParameter("mboxSession",this.R.getId());b||a.addParameter("mboxFactoryId",this.C);null!=this.S.getId()&&a.addParameter("mboxPC",this.S.getId());
a.addParameter("mboxPage",this.K);a.addParameter("screenHeight",this.L);a.addParameter("screenWidth",this.M);a.addParameter("browserWidth",this.N);a.addParameter("browserHeight",this.O);a.addParameter("browserTimeOffset",this.Q);a.addParameter("colorDepth",this.P);a.setUrlProcessAction(function(a){a+="\x26mboxURL\x3d"+encodeURIComponent(document.location);var b=encodeURIComponent(document.referrer);2E3>a.length+b.length&&(a+="\x26mboxReferrer\x3d"+b);return a+="\x26mboxVersion\x3d"+mboxVersion})};
mboxFactory.prototype.rb=function(){return""};mboxFactory.prototype.Y=function(){(function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s})(".mboxDefault{visibility:hidden}")};mboxFactory.prototype.isDomLoaded=function(){return this.D};mboxFactory.prototype.J=function(){if(null==this.gb){this.gb=
[];var a=this;(function(){var b=document.addEventListener?"DOMContentLoaded":"onreadystatechange",c=!1,d=function(){if(!c){c=!0;for(var b=0;b<a.gb.length;++b)a.gb[b]()}};if(document.addEventListener)document.addEventListener(b,function(){document.removeEventListener(b,arguments.callee,!1);d()},!1),window.addEventListener("load",function(){document.removeEventListener("load",arguments.callee,!1);d()},!1);else if(document.attachEvent)if(self!==self.top)document.attachEvent(b,function(){"complete"===
document.readyState&&(document.detachEvent(b,arguments.callee),d())});else{var e=function(){try{document.documentElement.doScroll("left"),d()}catch(a){setTimeout(e,13)}};e()}"complete"===document.readyState&&d()})()}};mboxSignaler=function(a,b){this.I=b;for(var c=b.getCookieNames("signal-"),d=0;d<c.length;d++){var e=c[d],f=b.getCookie(e).split("\x26");a(f[0],f).load();b.deleteCookie(e)}};mboxSignaler.prototype.signal=function(a,b){this.I.setCookie("signal-"+a,mboxShiftArray(arguments).join("\x26"),
2700)};mboxList=function(){this.E=[]};mboxList.prototype.add=function(a){null!=a&&(this.E[this.E.length]=a)};mboxList.prototype.get=function(a){for(var b=new mboxList,c=0;c<this.E.length;c++){var d=this.E[c];d.getName()==a&&b.add(d)}return b};mboxList.prototype.getById=function(a){return this.E[a]};mboxList.prototype.length=function(){return this.E.length};mboxList.prototype.each=function(a){if("function"!=typeof a)throw"Action must be a function, was: "+typeof a;for(var b=0;b<this.E.length;b++)a(this.E[b])};
mboxLocatorDefault=function(a){this.g="mboxMarker-"+a;document.write('\x3cdiv id\x3d"'+this.g+'" style\x3d"visibility:hidden;display:none"\x3e\x26nbsp;\x3c/div\x3e')};mboxLocatorDefault.prototype.locate=function(){for(var a=document.getElementById(this.g);null!=a;){if(1==a.nodeType&&"mboxDefault"==a.className)return a;a=a.previousSibling}return null};mboxLocatorDefault.prototype.force=function(){var a=document.createElement("div");a.className="mboxDefault";var b=document.getElementById(this.g);b.parentNode.insertBefore(a,
b);return a};mboxLocatorNode=function(a){this.Db=a};mboxLocatorNode.prototype.locate=function(){return"string"==typeof this.Db?document.getElementById(this.Db):this.Db};mboxLocatorNode.prototype.force=function(){return null};mboxCreate=function(a){var b=mboxFactoryDefault.create(a,mboxShiftArray(arguments));b&&b.load();return b};mboxDefine=function(a,b){return mboxFactoryDefault.create(b,mboxShiftArray(mboxShiftArray(arguments)),a)};mboxUpdate=function(a){mboxFactoryDefault.update(a,mboxShiftArray(arguments))};
mbox=function(a,b,c,d,e){this.Jb=null;this.Kb=0;this.lb=d;this.mb=e;this.Lb=null;this.Mb=new mboxOfferContent;this.Eb=null;this.v=c;this.message="";this.Nb={};this.Ob=0;this.Hb=b;this.g=a;this.Pb();c.addParameter("mbox",a).addParameter("mboxId",b);this.Qb=function(){};this.Rb=function(){};this.Sb=null};mbox.prototype.getId=function(){return this.Hb};mbox.prototype.Pb=function(){if(250<this.g.length)throw"Mbox Name "+this.g+" exceeds max length of 250 characters.";if(this.g.match(/^\s+|\s+$/g))throw"Mbox Name "+
this.g+" has leading/trailing whitespace(s).";};mbox.prototype.getName=function(){return this.g};mbox.prototype.getParameters=function(){for(var a=this.v.getParameters(),b=[],c=0;c<a.length;c++)0!=a[c].name.indexOf("mbox")&&(b[b.length]=a[c].name+"\x3d"+a[c].value);return b};mbox.prototype.setOnLoad=function(a){this.Rb=a;return this};mbox.prototype.setMessage=function(a){this.message=a;return this};mbox.prototype.setOnError=function(a){this.Qb=a;return this};mbox.prototype.setFetcher=function(a){this.Lb&&
this.Lb.cancel();this.Lb=a;return this};mbox.prototype.getFetcher=function(){return this.Lb};mbox.prototype.load=function(a){if(null==this.Lb)return this;this.setEventTime("load.start");this.cancelTimeout();this.Kb=0;a=a&&0<a.length?this.v.clone().addParameters(a):this.v;this.Lb.fetch(a);var b=this;this.Ub=setTimeout(function(){b.Qb("browser timeout",b.Lb.getType())},t);this.setEventTime("load.end");return this};mbox.prototype.loaded=function(){this.cancelTimeout();if(!this.activate()){var a=this;
setTimeout(function(){a.loaded()},100)}};mbox.prototype.activate=function(){if(this.Kb)return this.Kb;this.setEventTime("activate"+ ++this.Ob+".start");this.show()&&(this.cancelTimeout(),this.Kb=1);this.setEventTime("activate"+this.Ob+".end");return this.Kb};mbox.prototype.isActivated=function(){return this.Kb};mbox.prototype.setOffer=function(a){if(a&&a.show&&a.setOnLoad)this.Mb=a;else throw"Invalid offer";return this};mbox.prototype.getOffer=function(){return this.Mb};mbox.prototype.show=function(){this.setEventTime("show.start");
var a=this.Mb.show(this);this.setEventTime(1==a?"show.end.ok":"show.end");return a};mbox.prototype.showContent=function(a){if(null==a)return 0;if(null==this.Eb||!this.Eb.parentNode)if(this.Eb=this.getDefaultDiv(),null==this.Eb)return 0;this.Eb!=a&&(this.Wb(this.Eb),this.Eb.parentNode.replaceChild(a,this.Eb),this.Eb=a);this.Xb(a);this.Rb();return 1};mbox.prototype.hide=function(){this.setEventTime("hide.start");var a=this.showContent(this.getDefaultDiv());this.setEventTime(1==a?"hide.end.ok":"hide.end.fail");
return a};mbox.prototype.finalize=function(){this.setEventTime("finalize.start");this.cancelTimeout();null==this.getDefaultDiv()&&(null!=this.lb.force()?this.setMessage("No default content, an empty one has been added"):this.setMessage("Unable to locate mbox"));this.activate()||(this.hide(),this.setEventTime("finalize.end.hide"));this.setEventTime("finalize.end.ok")};mbox.prototype.cancelTimeout=function(){this.Ub&&clearTimeout(this.Ub);null!=this.Lb&&this.Lb.cancel()};mbox.prototype.getDiv=function(){return this.Eb};
mbox.prototype.getDefaultDiv=function(){null==this.Sb&&(this.Sb=this.lb.locate());return this.Sb};mbox.prototype.setEventTime=function(a){this.Nb[a]=(new Date).getTime()};mbox.prototype.getEventTimes=function(){return this.Nb};mbox.prototype.getImportName=function(){return this.mb};mbox.prototype.getURL=function(){return this.v.buildUrl()};mbox.prototype.getUrlBuilder=function(){return this.v};mbox.prototype.Zb=function(a){return"none"!=a.style.display};mbox.prototype.Xb=function(a){this._b(a,!0)};
mbox.prototype.Wb=function(a){this._b(a,!1)};mbox.prototype._b=function(a,b){a.style.visibility=b?"visible":"hidden";a.style.display=b?"block":"none"};mboxOfferContent=function(){this.Rb=function(){}};mboxOfferContent.prototype.show=function(a){a=a.showContent(document.getElementById(a.getImportName()));1==a&&this.Rb();return a};mboxOfferContent.prototype.setOnLoad=function(a){this.Rb=a};mboxOfferAjax=function(a){this.Vb=a;this.Rb=function(){}};mboxOfferAjax.prototype.setOnLoad=function(a){this.Rb=
a};mboxOfferAjax.prototype.show=function(a){var b=document.createElement("div");b.id=a.getImportName();b.innerHTML=this.Vb;a=a.showContent(b);1==a&&this.Rb();return a};mboxOfferDefault=function(){this.Rb=function(){}};mboxOfferDefault.prototype.setOnLoad=function(a){this.Rb=a};mboxOfferDefault.prototype.show=function(a){a=a.hide();1==a&&this.Rb();return a};mboxCookieManager=function(a,b){this.g=a;this.cc=""==b||-1==b.indexOf(".")?"":"; domain\x3d"+b;this.dc=new mboxMap;this.loadCookies()};mboxCookieManager.prototype.isEnabled=
function(){this.setCookie("check","true",60);this.loadCookies();return"true"==this.getCookie("check")};mboxCookieManager.prototype.setCookie=function(a,b,c){if("undefined"!=typeof a&&"undefined"!=typeof b&&"undefined"!=typeof c){var d={};d.name=a;d.value=escape(b);d.expireOn=Math.ceil(c+(new Date).getTime()/1E3);this.dc.put(a,d);this.saveCookies()}};mboxCookieManager.prototype.getCookie=function(a){return(a=this.dc.get(a))?unescape(a.value):null};mboxCookieManager.prototype.deleteCookie=function(a){this.dc.remove(a);
this.saveCookies()};mboxCookieManager.prototype.getCookieNames=function(a){var b=[];this.dc.each(function(c,d){0==c.indexOf(a)&&(b[b.length]=c)});return b};mboxCookieManager.prototype.saveCookies=function(){var a=[],b=0;this.dc.each(function(c,e){a[a.length]=c+"#"+e.value+"#"+e.expireOn;b<e.expireOn&&(b=e.expireOn)});var c=new Date(1E3*b);document.cookie=this.g+"\x3d"+a.join("|")+"; expires\x3d"+c.toGMTString()+"; path\x3d/"+this.cc};mboxCookieManager.prototype.loadCookies=function(){this.dc=new mboxMap;
var a=document.cookie.indexOf(this.g+"\x3d");if(-1!=a){var b=document.cookie.indexOf(";",a);-1==b&&(b=document.cookie.indexOf(",",a),-1==b&&(b=document.cookie.length));for(var a=document.cookie.substring(a+this.g.length+1,b).split("|"),b=Math.ceil((new Date).getTime()/1E3),c=0;c<a.length;c++){var d=a[c].split("#");if(b<=d[2]){var e={};e.name=d[0];e.value=d[1];e.expireOn=d[2];this.dc.put(e.name,e)}}}};mboxSession=function(a,b,c,d,e){this.sc=b;this.zb=c;this.tc=d;this.I=e;this.uc=!1;this.Hb="undefined"!=
typeof mboxForceSessionId?mboxForceSessionId:mboxGetPageParameter(this.sc);if(null==this.Hb||0==this.Hb.length)if(this.Hb=e.getCookie(c),null==this.Hb||0==this.Hb.length)this.Hb=a,this.uc=!0;e.setCookie(c,this.Hb,d)};mboxSession.prototype.getId=function(){return this.Hb};mboxSession.prototype.forceId=function(a){this.Hb=a;this.I.setCookie(this.zb,this.Hb,this.tc)};mboxPC=function(a,b,c){this.zb=a;this.tc=b;this.I=c;this.Hb="undefined"!=typeof mboxForcePCId?mboxForcePCId:c.getCookie(a);null!=this.Hb&&
c.setCookie(a,this.Hb,b)};mboxPC.prototype.getId=function(){return this.Hb};mboxPC.prototype.forceId=function(a){return this.Hb!=a?(this.Hb=a,this.I.setCookie(this.zb,this.Hb,this.tc),!0):!1};mboxGetPageParameter=function(a){var b=null;a=RegExp(a+"\x3d([^\x26]*)").exec(document.location);null!=a&&2<=a.length&&(b=a[1]);return b};mboxSetCookie=function(a,b,c){return mboxFactoryDefault.getCookieManager().setCookie(a,b,c)};mboxGetCookie=function(a){return mboxFactoryDefault.getCookieManager().getCookie(a)};
mboxCookiePageDomain=function(){var a=/([^:]*)(:[0-9]{0,5})?/.exec(document.location.host)[1];if(!/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/.exec(a)){var b=/([^\.]+\.[^\.]{3}|[^\.]+\.[^\.]+\.[^\.]{2})$/.exec(a);b&&(a=b[0])}return a?a:""};mboxShiftArray=function(a){for(var b=[],c=1;c<a.length;c++)b[b.length]=a[c];return b};mboxGenerateId=function(){return(new Date).getTime()+"-"+Math.floor(999999*Math.random())};mboxScreenHeight=function(){return screen.height};mboxScreenWidth=function(){return screen.width};
mboxBrowserWidth=function(){return window.innerWidth?window.innerWidth:document.documentElement?document.documentElement.clientWidth:document.body.clientWidth};mboxBrowserHeight=function(){return window.innerHeight?window.innerHeight:document.documentElement?document.documentElement.clientHeight:document.body.clientHeight};mboxBrowserTimeOffset=function(){return-(new Date).getTimezoneOffset()};mboxScreenColorDepth=function(){return screen.pixelDepth};"undefined"==typeof mboxVersion&&(mboxVersion=
44,mboxFactories=new mboxMap,mboxFactoryDefault=new mboxFactory(f+".tt.omtrdc.net",f,"default"));if(null!=mboxGetPageParameter("mboxDebug")||null!=mboxFactoryDefault.getCookieManager().getCookie("debug"))setTimeout(function(){"undefined"==typeof mboxDebugLoaded&&alert("Could not load the remote debug.\nPlease check your connection to Test\x26amp;Target servers")},3600),document.write('\x3cscript language\x3d"Javascript1.2" src\x3d"http://'+k+".testandtarget.omniture.com/admin/mbox/mbox_debug.jsp?mboxServerHost\x3d"+
f+".tt.omtrdc.net\x26clientCode\x3d"+f+'"\x3e\x3c/script\x3e');mboxVizTargetUrl=function(a){if(mboxFactoryDefault.isEnabled()){var b=mboxFactoryDefault.getUrlBuilder().clone();b.setBasePath("/m2/"+f+"/viztarget");b.addParameter("mbox",a);b.addParameter("mboxId",0);b.addParameter("mboxCount",mboxFactoryDefault.getMboxes().length()+1);var c=new Date;b.addParameter("mboxTime",c.getTime()-6E4*c.getTimezoneOffset());b.addParameter("mboxPage",mboxGenerateId());(c=mboxShiftArray(arguments))&&0<c.length&&
b.addParameters(c);b.addParameter("mboxDOMLoaded",mboxFactoryDefault.isDomLoaded());return b.buildUrl()}}}catch(n){mboxCreate=function(){},mboxDefine=function(){},mboxUpdate=function(){}}};mboxTrack=function(n,p){var m,u,i,l=location,f=mboxFactoryDefault;if(f.isEnabled()){if(f.getMboxes().length()>0){m=f.getMboxes().getById(0);u=m.getURL().replace("mbox\x3d"+escape(m.getName()),"mbox\x3d"+n).replace("/undefined","/ajax").replace("mboxPage","mP")}else{var c=function(){var c="",mFD=mboxFactoryDefault;
if(typeof window.TTclient=="undefined"){for(i in mFD)if(typeof mFD[i]=="object")for(j in mFD[i])if(typeof mFD[i][j]=="string")if(mFD[i][j].indexOf("omtrdc")>-1){c=mFD[i][j].split(".")[0];break}window.TTclient=c}return window.TTclient}();if(c!="")u=l.protocol+"//"+c+".tt.omtrdc.net/m2/"+c+"/ubox/image?mbox\x3d"+n;else mboxTrackForm(n,p)}i=new Image;i.style.display="none";i.src=u+"\x26mboxSession\x3d"+mboxFactoryDefault.getSessionId().getId()+"\x26mboxHost\x3d"+l.hostname+"\x26mboxDefault\x3d\x26mboxPage\x3d"+
mboxGenerateId()+"mboxURL\x3d"+encodeURIComponent(l.href)+"\x26"+p;document.body.appendChild(i)}};mboxTrackForm=function(n,p){var f=mboxFactoryDefault;if(f.isEnabled())mboxFactoryDefault.getSignaler().signal(n,n+"\x26"+p)};mboxTrackLink=function(n,p,url){mboxTrack(n,p);setTimeout("location\x3d'"+url+"'",500)};mboxTrackDefer=mboxTrackForm;mboxAddData=function(n,v){if(typeof mboxFactoryDefault=="object"){var a=[];if(v&&typeof n=="string"&&(typeof v=="string"||typeof v=="number"))a.push(n.replace(/\s/g,
"_")+"\x3d"+v);else if(typeof n=="object")for(i in n)a.push(i.replace(/\s/g,"_")+"\x3d"+n[i]);mboxFactoryDefault.getUrlBuilder().addParameters(a);if(console)console.log(a)}};Bootstrapper.ensConfigMboxJS({clientCode:"americanexpresscards",adminServer:"admin16",expiration:1209600,timeout:15E3})},335659,214006);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://personalsavings.americanexpress.com/index.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/explore-cd-rates-and-online-savings-accounts.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/application-process.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/deposits-and-withdrawals-information.html")!=
-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/savings-product.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/cd-product.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/manage-your-online-savings-or-cd-account.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/account-policies.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/contactus.html")!=
-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/open-account.html")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/application/edaoclient.jsp")!=-1||window.location.href.indexOf("https://personalsavings.americanexpress.com/Login-Security-and-Help.html")!=-1||window.location.href.indexOf("https://www.americanexpress.com/us/small-business/openforum/guides/")!=-1||window.location.href.indexOf("https://www.americanexpress.com/us/small-business/openforum/registration/")!=
-1||window.location.href.indexOf("https://e2sonline.americanexpress.com/myca/fuidfyp/us/action?")!=-1||window.location.href.indexOf("https://e2qonline.americanexpress.com/myca/fuidfyp/us/action?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/fuidfyp/us/action?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/fuidfyp/us/action?")!=-1||window.location.href.indexOf("qwww.americanexpress.com/us/small-business/openforum/guides/")!=-1||window.location.href.indexOf("https://www437.americanexpress.com/smartsearch/search/ssearch.jsp")!=
-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},788218,279937);
amexhead.bindDependencyImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("www.americanexpress.com/gift-cards/")!=-1){if(!Bootstrapper.hasDOMParsed())document.write('\x3cdiv class\x3d"mboxDefault"\x3e\x3c/div\x3e');mboxCreate("gc_homepage1_test");if(!Bootstrapper.hasDOMParsed())document.write('\x3cdiv class\x3d"mboxDefault"\x3e\x3c/div\x3e');mboxCreate("gc_homepage1_cms")}},568047,[335659],272505,[214006]);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(document.documentElement.clientWidth>831)if(window.location.href=="https://www.americanexpress.com/"||window.location.href.split("/").length<=5)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1102867,273123);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v3/payment/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/accountsummary/us/accounthome?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/acctmgmt/us/myaccountsummary.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/estmt/us/list.do?")!=
-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/accountprofile/us/view.do?")!=-1||window.location.href.indexOf("https://www.americanexpress.com/us/content/mobile/")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},917656,307814);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/lineofcredit/us/action?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1253525,370507);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/fuidfyp/us/action/fuidfyp?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/fuidfyp/us/action/fuidfyp?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/logon/us/action/LogonHandler?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/logon/us/action/LogonHandler?")!=
-1||window.location.href.indexOf("https://online.americanexpress.com/myca/logon/us/action/LogLogoffHandler?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/logon/us/action/LogLogoffHandler?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/logon/us/action/LogLogonHandler?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/logon/us/action/LogLogonHandler?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},
908480,326085);amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/statementimage/us/welcome.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/statementimage/us/welcome.do?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},595667,259339);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v2/payment/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v2/managebank/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v2/recurringpay/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v3/payment/inquiry.do?")!=
-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v3/managebank/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v3/recurringpay/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/v3/paymenthistory/inquiry.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/onlinepayment/us/paymentcenter.do?")!=-1||window.location.href.indexOf("https://www295.americanexpress.com/cards/home.do?")!=
-1||window.location.href.indexOf("https://www.americanexpress.com/us/credit-cards/benefits/view-all")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/accountsummary/us/accounthome?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/acctmgmt/us/myaccountsummary.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/estmt/us/list.do?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/estmt/us/1/list.do?")!=
-1||window.location.href.indexOf("https://online.americanexpress.com/myca/accountprofile/us/view.do?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},578358,267533);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/oce/us/action/register?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/oce/us/action/register?")!=-1||window.location.href.indexOf("https://online.americanexpress.com/myca/oce/us/action/activation?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/oce/us/action/activation?")!=
-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},604209,277274);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://e2business.americanexpress.com/us/")!=-1||window.location.href.indexOf("https://business.americanexpress.com/us/")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},796410,308082);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://www.corporatecardapplication.com/apply/us/")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1053246,345208);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href=="https://www.americanexpress.com/us/content/credit-cards/premier-rewards-gold/learn-more/index.html")document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1225724,367060);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/oce/us/action/accountPreferences")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1258447,371160);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://online.americanexpress.com/myca/rdmo/us/rdmoinquiry.do?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},889762,323589);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://amexglobalctuat.creditpointe.com/apply/us/")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},1090091,350220);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href=="https://business.americanexpress.com/us")document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},985382,336702);
amexhead.bindImmediate(function(){var Bootstrapper=window["amexhead"];var ensightenOptions=amexhead.ensightenOptions;if(window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v2/payment/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v2/managebank/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v2/recurringpay/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v3/payment/inquiry.do?")!=
-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v3/managebank/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v3/recurringpay/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/v3/paymenthistory/inquiry.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/onlinepayment/us/paymentcenter.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/accountsummary/us/accounthome?")!=
-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/acctmgmt/us/myaccountsummary.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/estmt/us/list.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/estmt/us/1/list.do?")!=-1||window.location.href.indexOf("https://slonline.americanexpress.com/myca/accountprofile/us/view.do?")!=-1)document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/americanexpress/js/mmcore.js"\x3e\x3c/script\x3e')},
1162101,359428);amexhead.getServerComponent(amexhead.getExtraParams ? amexhead.getExtraParams() : undefined);}})();