(function ensightenInit(){var ensightenOptions = {client: "sonyglobal", clientId: 263, publishPath: "stage", isPublic:0, serverComponentLocation: "nexus.ensighten.com/sonyglobal/stage/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/sonyglobal/stage/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Mon Feb 22 13:29:18 GMT 2016", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=g.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:g.interval||100,erLoc:g.errorLocation||c.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||c.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||c.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,scUseCacheBuster:g.scUseCacheBuster,beaconSamplingSeedValue:g.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),f;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(f=0;f<h.length;f++)if(h[f].src===a&&h[f].readyState&&/loaded|complete/.test(h[f].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof d&&d.PageID&&(e=d.PageID,delete d.PageID);if("object"===typeof d)for(f in d){f=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,f.length?e.length-f.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+
f;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=
document.getElementsByTagName("script"),h;d=c[0];for(h=0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=
this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};
b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});
else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,
l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,f=b.dataDefinitionIds.length,g=0;g<f;g++)if(b.dataDefinitionIds[g]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var d=b.dataDefinitions[e];d||(d=new b.DataDefinition(e,a),b.dataDefinitions[e]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var g=0;g<c.length;g++)try{c[g].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,f=0;f<c.ruleList.length;++f)d=c.ruleList[f],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(g.client)+"/"+encodeURIComponent(g.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(g.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var g=window.performance;if(g){var g=g.timing||{},m="",n=g.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(g.navigationStart),b;for(b in c)void 0!==g[b]?(p=g[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||
"";m=g.indexOf(".com/");n=g.indexOf("/code/");g=g.substring(m+4,n)+"/perf.rnc";g+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+g)}}});
	
if (!window[ensightenOptions.ns].data) {
	/*
	 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
	window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
	(function(){function e(a){return 10>a?"0"+a:a}function m(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(f,e){var b,g,p,d,h=k,u,q=e[f];q&&"object"===typeof q&&"function"===typeof q.toJSON&&(q=q.toJSON(f));"function"===typeof c&&(q=c.call(e,f,q));switch(typeof q){case "string":return m(q);case "number":return isFinite(q)?String(q):"null";case "boolean":case "null":return String(q);
	case "object":if(!q)return"null";k+=a;u=[];if("[object Array]"===Object.prototype.toString.apply(q)){d=q.length;for(b=0;b<d;b+=1)u[b]=l(b,q)||"null";p=0===u.length?"[]":k?"[\n"+k+u.join(",\n"+k)+"\n"+h+"]":"["+u.join(",")+"]";k=h;return p}if(c&&"object"===typeof c)for(d=c.length,b=0;b<d;b+=1)"string"===typeof c[b]&&(g=c[b],(p=l(g,q))&&u.push(m(g)+(k?": ":":")+p));else for(g in q)Object.prototype.hasOwnProperty.call(q,g)&&(p=l(g,q))&&u.push(m(g)+(k?": ":":")+p);p=0===u.length?"{}":k?"{\n"+k+u.join(",\n"+
	k)+"\n"+h+"}":"{"+u.join(",")+"}";k=h;return p}}var b=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d=
	/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,a,f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c;"function"!==typeof b.stringify&&(b.stringify=function(b,f,e){var g;a=k="";if("number"===typeof e)for(g=0;g<e;g+=1)a+=" ";else"string"===typeof e&&(a=e);if((c=f)&&"function"!==typeof f&&
	("object"!==typeof f||"number"!==typeof f.length))throw Error("JSON.stringify");return l("",{"":b})});"function"!==typeof b.parse&&(b.parse=function(a,c){function f(a,b){var e,g,d=a[b];if(d&&"object"===typeof d)for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(g=f(d,e),void 0!==g?d[e]=g:delete d[e]);return c.call(a,b,d)}var b;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
	"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),"function"===typeof c?f({"":b},""):b;throw new SyntaxError("JSON.parse");})})();
	window[ensightenOptions.ns].when=function(){function e(a,b,c,f){return l(a).then(b,c,f)}function m(a){this.then=a}function l(a){return b(function(b){b(a)})}function b(c){function e(a){n&&(t=d(a),f(n,t),n=v)}function g(a){e(k(a))}function p(b){n&&f(n,a(b))}var t,n=[];try{c(e,g,p)}catch(h){g(h)}return new m(function(a,c,f){return b(function(b,e,g){n?n.push(function(d){d.then(a,c,f).then(b,e,g)}):r(function(){t.then(a,c,f).then(b,e,g)})})})}function d(a){return a instanceof m?a:a!==Object(a)?h(a):b(function(b,
	c,f){r(function(){try{var e=a.then;"function"===typeof e?B(e,a,b,c,f):b(h(a))}catch(g){c(g)}})})}function h(a){var b=new m(function(c){try{return"function"==typeof c?d(c(a)):b}catch(f){return k(f)}});return b}function k(a){var b=new m(function(c,f){try{return"function"==typeof f?d(f(a)):b}catch(e){return k(e)}});return b}function a(b){var c=new m(function(f,e,g){try{return"function"==typeof g?a(g(b)):c}catch(d){return a(d)}});return c}function f(a,b){r(function(){for(var c,f=0;c=a[f++];)c(b)})}function c(a,
	c,f,g,d){p(2,arguments);return e(a,function(a){return b(function(b,f,g){function d(a){l(a)}function p(a){r(a)}var n,h,w,k,r,l,x,z;x=a.length>>>0;n=Math.max(0,Math.min(c,x));w=[];h=x-n+1;k=[];if(n)for(l=function(a){k.push(a);--h||(r=l=t,f(k))},r=function(a){w.push(a);--n||(r=l=t,b(w))},z=0;z<x;++z)z in a&&e(a[z],p,d,g);else b(w)}).then(f,g,d)})}function n(a,b,c,f){p(1,arguments);return w(a,x).then(b,c,f)}function w(a,c){return e(a,function(a){return b(function(b,f,g){var d,p,t,n,h;t=p=a.length>>>0;
	d=[];if(t)for(n=function(a,p){e(a,c).then(function(a){d[p]=a;--t||b(d)},f,g)},h=0;h<p;h++)h in a?n(a[h],h):--t;else b(d)})})}function r(a){1===A.push(a)&&D(g)}function g(){for(var a,b=0;a=A[b++];)a();A=[]}function p(a,b){for(var c,f=b.length;f>a;)if(c=b[--f],null!=c&&"function"!=typeof c)throw Error("arg "+f+" must be a function");}function t(){}function x(a){return a}e.defer=function(){var a,c,f;a={promise:v,resolve:v,reject:v,notify:v,resolver:{resolve:v,reject:v,notify:v}};a.promise=c=b(function(b,
	g,e){a.resolve=a.resolver.resolve=function(a){if(f)return l(a);f=!0;b(a);return c};a.reject=a.resolver.reject=function(a){if(f)return l(k(a));f=!0;g(a);return c};a.notify=a.resolver.notify=function(a){e(a);return a}});return a};e.resolve=l;e.reject=function(a){return e(a,k)};e.join=function(){return w(arguments,x)};e.all=n;e.map=w;e.reduce=function(a,b){var c=B(q,arguments,1);return e(a,function(a){var f;f=a.length;c[0]=function(a,c,g){return e(a,function(a){return e(c,function(c){return b(a,c,g,
	f)})})};return u.apply(a,c)})};e.any=function(a,b,f,g){return c(a,1,function(a){return b?b(a[0]):a[0]},f,g)};e.some=c;e.isPromise=function(a){return a&&"function"===typeof a.then};m.prototype={otherwise:function(a){return this.then(v,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return n(b,function(b){return a.apply(v,b)})})},always:function(a,b){return this.then(a,
	a,b)}};var u,q,B,D,A,E,y,C,v;A=[];E=setTimeout;D="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){E(a,0)};y=Function.prototype;C=y.call;B=y.bind?C.bind(C):function(a,b){return a.apply(b,q.call(arguments,2))};y=[];q=y.slice;u=y.reduce||function(a){var b,c,f,g;g=0;b=Object(this);f=b.length>>>0;c=arguments;if(1>=c.length)for(;;){if(g in b){c=b[g++];break}if(++g>=f)throw new TypeError;
	}else c=c[1];for(;g<f;++g)g in b&&(c=a(c,b[g],g,b));return c};return e}();
	(function(){function e(b,e){return l.all(e||[],function(e){return b.apply(null,e)})}function m(d){var h=b.call(arguments,1);return function(){return e(d,h.concat(b.call(arguments)))}}var l,b;l=window[ensightenOptions.ns].when;b=[].slice;l.apply=e;l.call=function(d){return e(d,b.call(arguments,1))};l.lift=m;l.bind=m;l.compose=function(d){var h=b.call(arguments,1);return function(){var k=b.call(arguments),k=e(d,k);return l.reduce(h,function(a,b){return b(a)},k)}}})();
	window[ensightenOptions.ns].data=function(e,m){function l(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var b={engines:{memory:{get:function(a){if(d.utils.isArray(a)){for(var f=[],c=0;c<a.length;c++)f.push(b.data[a[c]]);return e[ensightenOptions.ns].when.resolve(f)}f=b.dataDefinitions[a]||{storage:{get:function(){}}};f=f.storage.get(f);b.data[a]=f;return e[ensightenOptions.ns].when.resolve(b.data[a])},set:function(a,f){if(d.utils.isArray(a))for(var c in a)b.data[a[c]]=
	f[c];else b.data[a]=f;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(d.utils.isArray(a))for(var f in a)delete b.data[a[f]];else delete b.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){b.data={};b.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(b.data)}}},normalizeInputArgs:function(a,b){var c={key:[],val:m},e;if(d.utils.isPlainObject(a))for(e in c.val=[],a)c.key.push(e),c.val.push(a[e]);
	else d.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},d={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},h=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=
	l;b.DataDefinitionException=l;b.checkForInvalidDataDefinitions=function(a){d.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a)),!0):!1};b.collectAvailableDataDefinitions=function(a){for(var f=[],c=0;c<a.length;c++){var n=parseInt(a[c],10),h=e[ensightenOptions.ns].dataDefinitions[n];if(null===h||h===m)if(h=d.storage.session.get({id:n}),null!==h&&h!==m)d.set(n,h),b.dataDefinitions[n]={id:n,
	load:"visitor",storage:d.storage.visitor,missingDDFromCache:!0},f.push(e[ensightenOptions.ns].data.get(""+n));else return e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Invalid data definition used: "+n)),{promises:[],isInvalid:!0};else f.push(e[ensightenOptions.ns].data.get(a[c]))}return{promises:f,isInvalid:!1}};b.getSync=function(a){function f(a){var b=a.extract||h,f=a.transform||k,g=!1,e=null,d=null;try{e=b()}catch(p){e=null,g=!0}try{d=f(e)}catch(r){d=null,g=!0}g&&c.push(a.id);
	return d}var c=[],h=function(){return document},k=function(a){return null!==a&&a!==m?a.toString():null},r=parseInt(a);a="string"===typeof a?a.split("."):[];var g={},p="";isNaN(r)?3==a.length&&(g=d.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):g=d.getDataDefinitionById(r);p=g.load&&g.load.match(/(session|visitor)/i)&&g.storage&&g.storage.get?g.storage.get(g):f(g);0<c.length&&e[ensightenOptions.ns].reportException(new b.DataDefinitionException(c,"Error resolving data definitions synchronously: "+
	c));return p};b.dataDefinitions={};b.dataDefinitionsBySourceCollName={};d.defineEngine=function(a,f){var c,d=["get","set","remove","clear","all"];b.engines[a]=f;if(!f.returnsPromise)for(c=0;c<d.length;c++){var h=d[c];f[h]=e[ensightenOptions.ns].when.lift(f[h])}};d.storage={instance:{set:function(a,b){},get:function(a){return b.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return b.data[a.id]}},session:{set:function(a,b){var c=d.storage.session.get({id:a}),h=new Date,k=h.getTime();h.setTime(k+
	18E5);null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:h.toGMTString()});c={expires:h.getTime(),value:b};e[ensightenOptions.ns].data.local.utils.set(a,c)},get:function(a){var b=e[ensightenOptions.ns].data.cookie.utils.get(a.id),c=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON,c=c||{},d,h=new Date,h=h.getTime();if(null===b){try{d=c.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(k){d=null}null!=d&&(d.expires=+d.expires,h<=d.expires?b=d.value:""==
	d.expires&&d.value!=m?b=d.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var c=d.storage.session.get({id:a});null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return d.storage.session.get(a)}}};d.getEngine=d.engine=function(a){return a?b.engines[a]||{get:h,set:h,remove:h,clear:h,all:h}:b.engines};d.all=function(a){return e[ensightenOptions.ns].data.engine(a||
	"memory").all()};d.get=function(a,f,c){f=f||"memory";c=c||{};-1<a.indexOf(",")&&(a=a.split(","));a=b.normalizeInputArgs(a);return c.wait?b.getWait(a.key,e[ensightenOptions.ns].data.engine(f),c):b.data&&b.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(f).get(a.key):b.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(f),c)};b.getWait=function(a,b,c){var h=+new Date,k=e[ensightenOptions.ns].when.defer(),r=function(){var e=b.get(a);if(-1===c.wait)return e;e.then(function(a){c.setCheck(a)?
	k.resolve(a):setTimeout(g,c.interval)},function(a){setTimeout(g,c.interval)})},g=function(){var a=+new Date-h;-1!==c.wait&&a<c.wait?r():k.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;d.utils.isArray(a)?c.setCheck=c.setCheck||function(a){for(var b=!0,c=0;c<a.length;c++)b=b&&!!a[c];return b}:c.setCheck=c.setCheck||function(a){return!!a};r();return k.promise};b.getWaitForKey=function(a,f,c){var d=e[ensightenOptions.ns].when.defer(),h=function(){if(b.data&&b.data.hasOwnProperty(a)){var g=
	f.get(a);if(-1===c.wait)return g;g.then(function(a){d.resolve(a)},function(a){d.reject(a)})}else setTimeout(k,c.interval)},k=function(){h()};c.interval=c.interval||100;c.wait=c.wait||1;h();return d.promise};d.set=function(a,f,c){var d=b.normalizeInputArgs(a,f);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(c||"memory").set(d.key,d.val)};d.remove=function(a,b){return e[ensightenOptions.ns].data.engine(b||"memory").remove(a)};d.clear=function(a){return e[ensightenOptions.ns].data.engine(a||
	"memory").clear()};d.define=function(a,f){f&&(a.name=f.id||f.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var c=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=d.storage[c.toLowerCase()]||
	d.storage.page;var h=a.extract||function(){return document},k=a.transform||function(a){return a},r=function(b,c){var d=[];d.push(a.persist.set(b,c));a.storage.set(a.id,c);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(b,c,a.collection);e[ensightenOptions.ns].when.all(d).then(function(a){g.resolve(a)},function(a){g.reject(a)})},g=e[ensightenOptions.ns].when.defer();a.trigger().then(function(){g.resolve(e[ensightenOptions.ns].when.reduce([h(),k,r],function(b,
	c,g,e){if(1==g)return c(b);2==g&&c(a.name,b)}))},function(a){g.reject(a)});b.dataDefinitions[a.id]=a;b.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+"."+a.dataDefName]=a;return g.promise};d.checkConditions=function(a){var f,c={lt:function(a,c){var g=+a,d=+c;return isNaN(g)||isNaN(d)?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+c)),!1):g<d},gt:function(a,c){var g=+a,d=+c;return isNaN(g)||
	isNaN(d)?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+c)),!1):g>d},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==m||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(d){return!1}},starts:function(a,b,g){b=d.utils.escapeRegEx(b);return c.re(a,"^"+b,g)},ends:function(a,b,g){b=d.utils.escapeRegEx(b);return c.re(a,b+"$",g)},contains:function(a,
	b,g){b=d.utils.escapeRegEx(b);return c.re(a,".*"+b+".*",g)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=c.gt;c["is less than"]=c.lt;c.matches=c.re;for(f=0;f<a.values.length;f++){var h=(a.customComparator?a.customComparator[f]?a.customComparator[f]:c[a.comparators[f]]:c[a.comparators[f]])(a.values[f],a.compareTo[f],a.caseInsensitive?a.caseInsensitive[f]||!1:!1);a.not[f]&&(h=!h);if(!h)return!1}return!0};d.triggerPromise=function(a,b,c){c=c||5E3;var d=+new Date,h=
	e[ensightenOptions.ns].when.defer();(function(){var e=a();e!=b?h.resolve(e):+new Date-d<c?setTimeout(arguments.callee,200):h.reject("timed out")})();return h.promise};d.timeoutPromise=function(a,b){var c=e[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};d.delayTrigger=function(a){a=a||10;var b=e[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};d.delayUntilTrigger=
	function(a,b,c,d){c=c||null;d=d||200;var h=+new Date,k=e[ensightenOptions.ns].when.defer();(function(){var g=a();g!=b?k.resolve(g):c?+new Date-h<c?setTimeout(arguments.callee,d):k.reject("timed out"):setTimeout(arguments.callee,d)})();return k.promise};b.applyTrigger=function(a){var b=e[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};d.bottomOfBodyTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};d.afterEnsightenCompleteTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};
	d.afterElementsDownloadedTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};d.getAllDataDefinitionsOnCurrentPage=function(){return b.dataDefinitions};d.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return b.dataDefinitionsBySourceCollName};d.getDataDefinitionById=function(a){return b.dataDefinitions[a||-1]||{}};d.getDataDefinitionBySourceCollectionName=function(a,d,c){return b.dataDefinitionsBySourceCollName[""+a+"."+d+"."+c]||{}};d.getDataDefinitionByPercentSyntax=
	function(a){a=(""+a).split("_");return 1>a.length?{}:b.dataDefinitions[a[1]]||{}};d.resolve=function(a,f){var c=this,h=null;if(!b.checkForInvalidDataDefinitions(a))if(f)e[ensightenOptions.ns].bindDataDefinitionComplete(function(){var d=b.collectAvailableDataDefinitions(a);d.isInvalid||e[ensightenOptions.ns].when.all(d.promises).then(function(d){try{f.apply(c,d)}catch(g){e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+g))}},
	function(c){e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+c))})});else{var h=[],k=a;d.utils.isArray(a)||(k=[a]);for(var l=0;l<k.length;l++)h.push(b.getSync(k[l]));return h=d.utils.isArray(a)?h:h[0]}};d.extract=function(a,b){var c="",d=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",d=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(c?b.split("#")[0]:d?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==
	e&&0==d)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var g=a.firstChild;if(!g)return null;for(var f=0,d=0!=d?d-1:d;g;){if(1==g.nodeType){if(g.tagName.toLowerCase()==e&&""!=c&&g.id==c||g.tagName.toLowerCase()==e&&f==d&&""==c)return g;g.tagName.toLowerCase()==e&&f++}g=g.nextSibling}},h=function(a,b){a=a.split("/");for(var c=d(b||document,a[1]),g=2;g<a.length;g++){if(null==c)return null;c=d(c,a[g])}return c},k=function(){for(var a=
	{},b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var g=b[c].name||b[c].getAttribute("property")||"";0!==g.length&&(a[g]=b[c].content)}return a}(),g=function(a){var b=k[a];if(b)return b;for(var b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var g=b[c].name||b[c].getAttribute("property")||"";if(a==g)return b[c].content}},p=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(e.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},t=function(a){return(val=
	(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=m(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},m=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=h(a);else try{b=eval(a)}catch(c){b=""}return b};try{return b?"meta"==b?c=g(a):"cookie"==b?c=t(a):"param"==b?c=p(a):"content"==b?c=l(a):"event"==b?c=m(a):"var"==b&&(c=e[a]):c=g(a)||t(a)||p(a)||l(a)||m(a)||e[a]||
	"",c||""}catch(q){return""}};if("undefined"==typeof k)var k={exports:{}};return d}(window);
	window[ensightenOptions.ns].data.defineEngine("store",function(){var e={},m=window,l=m.document,b,d,h=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};e.set=function(a,b){};e.get=function(a){};e.remove=function(a){};e.clear=function(){};try{if("localStorage"in m&&m.localStorage)b=m.localStorage,e.set=function(a,c){var d,e,f=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(h(a))for(d=0,e=a.length;d<e;d++)b.setItem(a[d],"string"===
	typeof c[d]?c[d]:f.stringify(c[d]));else b.setItem(a,"string"===typeof c?c:f.stringify(c))},e.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b.getItem(a[d]);return c}return b.getItem(a)},e.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)b.removeItem(a[c])}else b.removeItem(a)},e.clear=function(){b.clear()},e.all=function(){return b};else if("globalStorage"in m&&m.globalStorage)b=m.globalStorage[m.location.hostname],e.set=function(a,c){if(h(a)){var d,e;d=0;
	for(e=a.length;d<e;d++)b[a[d]]=c[d]}else b[a]=c},e.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b[a[d]]&&b[a[d]].value;return c}return b[a]&&b[a].value},e.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)delete b[a[c]]}else delete b[a]},e.clear=function(){for(var a in b)delete b[a]},e.all=function(){return b};else if(l.documentElement.addBehavior){var k=function(a){return a.replace(n,"___")},m=function(c){return function(){var d=Array.prototype.slice.call(arguments,
	0);d.unshift(b);a.appendChild(b);b.addBehavior("#default#userData");b.load("localStorage");d=c.apply(store,d);a.removeChild(b);return d}},a,f;try{f=new ActiveXObject("htmlfile"),f.open(),f.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>'),f.close(),a=f.w.frames[0].document,b=a.createElement("div")}catch(c){b=l.createElement("div"),a=l.body}var n=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g");e.set=m(function(a,b,c){if(h(b)){var d,f;d=0;for(f=b.length;d<f;d++){fixedKey=
	k(b[d]);if(void 0===c[d])return e.remove(fixedKey);a.setAttribute(fixedKey,c[d]);a.save("localStorage")}}else{fixedKey=k(b);if(void 0===c)return e.remove(fixedKey);a.setAttribute(fixedKey,c);a.save("localStorage")}});e.get=m(function(a,b){if(h(b)){var c={},d,e,f;e=0;for(f=b.length;e<f;e++)d=k(b[e]),c[b[e]]=a.getAttribute(d);return c}b=k(b);return a.getAttribute(b)});e.remove=m(function(a,b){if(h(b)){var c,d;c=0;for(d=b.length;c<d;c++)a.removeAttribute(k(b[c])),a.save("localStorage")}else b=k(b),a.removeAttribute(b),
	a.save("localStorage")});e.clear=m(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var c=0,d;d=b[c];c++)a.removeAttribute(d.name);a.save("localStorage")});e.all=m(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},d=0,e;e=b[d];++d){var f=k(e.name);c[e.name]=a.getAttribute(f)}return c})}}catch(w){}var r={};for(d in e)r[d]=e[d];r.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());r.set(a,"test");if("test"===r.get(a))return r.remove(a),
	!0}catch(b){}return!1};e.utils=r;return window[ensightenOptions.ns].data.local=e}());
	window[ensightenOptions.ns].data.defineEngine("cookie",function(e,m){var l=function(){return l.get.apply(l,arguments)},b=l.utils={isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(b){return Array.prototype.slice.call(b)},getKeys:Object.keys||function(b){var e=[],k="";for(k in b)b.hasOwnProperty(k)&&e.push(k);return e},escape:function(b){return String(b).replace(/[,;"\\=\s%]/g,
	function(b){return encodeURIComponent(b)})},retrieve:function(b,e){return null==b?e:b},getAllCookies:function(){if(""===e.cookie)return{};for(var b=e.cookie.split("; "),h={},k=0,a=b.length;k<a;k++){var f=b[k].split("=");h[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return h},set:function(d,h,k){k=k||-1;if(b.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&l.set(a,d[a],h);else if(b.isArray(d)){var f;a=0;for(f=d.length;a<f;a++)l.set(d[a],h[a],k)}else{a=k.expires!==m?k.expires:l.defaults.expires||
	"";"number"===typeof a&&(a=new Date(a));a=b.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():b.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;f=(f=k.path||l.defaults.path)?";path="+f:"";var c=k.domain||l.defaults.domain,c=c?";domain="+c:"";k=k.secure||l.defaults.secure?";secure":"";e.cookie=b.escape(d)+"="+b.escape(h)+a+f+c+k}},get:function(d,e){e=e||m;var k=b.getAllCookies();if(b.isArray(d)){for(var a={},f=0,c=d.length;f<c;f++)a[d[f]]=b.retrieve(k[d[f]],
	e),a[d[f]]===m&&(a[d[f]]=null);return a}a=b.retrieve(k[d],e);return a===m?null:a},getGMTString:function(b){var e=new Date;e.setTime(e.getTime()+864E5*b);return e.toGMTString()}};l.defaults={path:"/",expires:b.getGMTString(90)};l.set=function(d,e){b.set(d,e)};l.remove=function(d){d=b.isArray(d)?d:b.toArray(arguments);for(var e=0,k=d.length;e<k;e++)b.set(d[e],"",{expires:-1})};l.clear=function(){return l.remove(b.getKeys(b.getAllCookies()))};l.get=function(d,e){return b.get(d,e)};l.all=function(){return b.getAllCookies()};
	l.utils=b;return window[ensightenOptions.ns].data.cookie=l}(document));
}
		
window[ensightenOptions.ns].ensEvent=function(l,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,g){if("[object Array]"===Object.prototype.toString.call(b)){for(var d=0;d<b.length;d++)k.pushTrigger(b[d],g);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof g&&this.queue[b].fn.push(g);return!0},callTrigger:function(b,g,d){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=b.fireOnFirstSet&&g==u||g!=u&&0!=b.fireOnUpdate))for(g=
0;g<b.fn.length;g++)b.fn[g].call(this)},setPollOptions:function(b,g,d){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=g;this.queue[b].fireOnUpdate=d},callPoll:function(b,g,d,l,t){if("string"==typeof b&&g&&g.length&&!(1>g.length)){for(var p=0;p<g.length;p++)k.setPollOptions(g[p],l,t);k.pushWatch(b,g,d)}},pushWatch:function(b,g,d){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,eventArr:[],valueFn:d});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(g);this.pollQueue[b].valueFn=
d},globalWatch:function(){setInterval(function(){for(key in k.pollQueue){var b=k.pollQueue[key],g=b.valueFn(key);if(b.previousVal!==g){for(var d=0;d<b.eventArr.length;d++)k.callTrigger.call(l,b.eventArr[d],b.previousVal,g);k.pollQueue[key].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,g){return k.pushTrigger(b,g)},get:function(b){return k.queue[b]},trigger:function(b,g){return k.callTrigger.call(g||l,b)},poll:function(b,g,d,u,t){t=t||l[ensightenOptions.ns].data.resolve;return k.callPoll(b,
g,t,d,u)}}}(window);
(function(l,u,k){u[l]=k()})("qwery",window[ensightenOptions.ns],function(){function l(){this.c={}}function u(a){return G.g(a)||G.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,e){for(var f=0,c=a.length;f<c;f++)e(a[f])}function b(a){for(var e=[],f=0,c=a.length;f<c;++f)s(a[f])?e=e.concat(a[f]):e[e.length]=a[f];return e}function g(a){for(var e=0,f=a.length,c=[];e<f;e++)c[e]=a[e];return c}function d(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function x(a){return a.match(N)}function t(a,e,f,
c,b,r,h,g,d,k,s){var n,y,l;if(1!==this.nodeType||e&&"*"!==e&&this.tagName&&this.tagName.toLowerCase()!==e||f&&(n=f.match(O))&&n[1]!==this.id)return!1;if(f&&(l=f.match(P)))for(a=l.length;a--;)if(!u(l[a].slice(1)).test(this.className))return!1;if(d&&m.pseudos[d]&&!m.pseudos[d](this,s))return!1;if(c&&!h)for(y in d=this.attributes,d)if(Object.prototype.hasOwnProperty.call(d,y)&&(d[y].name||y)==b)return this;return c&&!q(r,Q(this,b)||"",h)?!1:this}function p(a){return H.g(a)||H.s(a,a.replace(R,"\\$1"))}
function q(a,e,f){switch(a){case "=":return e==f;case "^=":return e.match(w.g("^="+f)||w.s("^="+f,"^"+p(f),1));case "$=":return e.match(w.g("$="+f)||w.s("$="+f,p(f)+"$",1));case "*=":return e.match(w.g(f)||w.s(f,p(f),1));case "~=":return e.match(w.g("~="+f)||w.s("~="+f,"(?:^|\\s+)"+p(f)+"(?:\\s+|$)",1));case "|=":return e.match(w.g("|="+f)||w.s("|="+f,"^"+p(f)+"(-|$)",1))}return 0}function v(a,e){var f=[],b=[],r,h,g,d,m,s=e,n=C.g(a)||C.s(a,a.split(I)),l=a.match(J);if(!n.length)return f;h=(n=n.slice(0)).pop();
n.length&&(r=n[n.length-1].match(K))&&(s=y(e,r[1]));if(!s)return f;d=x(h);g=s!==e&&9!==s.nodeType&&l&&/^[+~]$/.test(l[l.length-1])?function(a){for(;s=s.nextSibling;)1==s.nodeType&&(d[1]?d[1]==s.tagName.toLowerCase():1)&&(a[a.length]=s);return a}([]):s.getElementsByTagName(d[1]||"*");r=0;for(h=g.length;r<h;r++)if(m=t.apply(g[r],d))f[f.length]=m;if(!n.length)return f;k(f,function(a){c(a,n,l)&&(b[b.length]=a)});return b}function c(a,e,f,c){function b(a,c,d){for(;d=S[f[c]](d,a);)if(r(d)&&t.apply(d,x(e[c])))if(c){if(h=
b(d,c-1,d))return h}else return d}var h;return(h=b(a,e.length-1,a))&&(!c||A(h,c))}function r(a,e){return a&&"object"===typeof a&&(e=a.nodeType)&&(1==e||9==e)}function h(a){var e=[],f,c;f=0;a:for(;f<a.length;++f){for(c=0;c<e.length;++c)if(e[c]==a[f])continue a;e[e.length]=a[f]}return e}function s(a){return"object"===typeof a&&isFinite(a.length)}function y(a,e,f){return 9===a.nodeType?a.getElementById(e):a.ownerDocument&&((f=a.ownerDocument.getElementById(e))&&A(f,a)&&f||!A(a,a.ownerDocument)&&E('[id="'+
e+'"]',a)[0])}function m(a,e){var f,c,h;h=e?"string"==typeof e?m(e)[0]:!e.nodeType&&s(e)?e[0]:e:z;if(!h||!a)return[];if(a===window||r(a))return!e||a!==window&&r(h)&&A(a,h)?[a]:[];if(a&&s(a))return b(a);if(f=a.match(T)){if(f[1])return(c=y(h,f[1]))?[c]:[];if(f[2])return g(h.getElementsByTagName(f[2]));if(U&&f[3])return g(h.getElementsByClassName(f[3]))}return E(a,h)}function n(a,e){return function(f){var c,b;L.test(f)?9!==a.nodeType&&((b=c=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),
e(a.parentNode||a,'[id="'+b+'"]'+f,!0),c||a.removeAttribute("id")):f.length&&e(a,f,!1)}}var z=document,D=z.documentElement,E,O=/#([\w\-]+)/,P=/\.[\w\-]+/g,K=/^#([\w\-]+)$/,V=/^([\w]+)?\.([\w\-]+)$/,L=/(^|,)\s*[>~+]/,W=/^\s+|\s*([,\s\+\~>]|$)\s*/g,B=/[\s\>\+\~]/,M=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,R=/([.*+?\^=!:${}()|\[\]\/\\])/g,T=new RegExp(K.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),J=new RegExp("("+B.source+")"+M.source,"g"),I=new RegExp(B.source+
M.source),N=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),S={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,e){return a&&a.parentNode==e.parentNode&&a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,e,f,c){return a?(f=d(a))&&(c=d(e))&&f==c&&f:!1}};l.prototype={g:function(a){return this.c[a]||
void 0},s:function(a,e,f){e=f?new RegExp(e):e;return this.c[a]=e}};var G=new l,H=new l,w=new l,C=new l,A="compareDocumentPosition"in D?function(a,e){return 16==(e.compareDocumentPosition(a)&16)}:"contains"in D?function(a,e){e=9===e.nodeType||e==window?D:e;return e!==a&&e.contains(a)}:function(a,e){for(;a=a.parentNode;)if(a===e)return 1;return 0},Q=function(){var a=z.createElement("p");return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,f){return"class"===f?
a.className:"href"===f||"src"===f?a.getAttribute(f,2):a.getAttribute(f)}:function(a,f){return a.getAttribute(f)}}(),U=!!z.getElementsByClassName,X=z.querySelector&&z.querySelectorAll,Y=function(a,e){var f=[],c,b;try{if(9===e.nodeType||!L.test(a))return g(e.querySelectorAll(a));k(c=a.split(","),n(e,function(a,e){b=a.querySelectorAll(e);1==b.length?f[f.length]=b.item(0):b.length&&(f=f.concat(g(b)))}));return 1<c.length&&1<f.length?h(f):f}catch(r){}return F(a,e)},F=function(a,e){var f=[],c,b,r,d;a=a.replace(W,
"$1");if(c=a.match(V)){d=u(c[2]);c=e.getElementsByTagName(c[1]||"*");b=0;for(r=c.length;b<r;b++)d.test(c[b].className)&&(f[f.length]=c[b]);return f}k(c=a.split(","),n(e,function(a,c,h){d=v(c,a);b=0;for(r=d.length;b<r;b++)if(9===a.nodeType||h||A(d[b],e))f[f.length]=d[b]}));return 1<c.length&&1<f.length?h(f):f},B=function(a){"undefined"!==typeof a.useNativeQSA&&(E=a.useNativeQSA?X?Y:F:F)};B({useNativeQSA:!0});m.configure=B;m.uniq=h;m.is=function(a,e,f){if(r(e))return a==e;if(s(e))return!!~b(e).indexOf(a);
for(var h=e.split(","),d;e=h.pop();)if(d=C.g(e)||C.s(e,e.split(I)),e=e.match(J),d=d.slice(0),t.apply(a,x(d.pop()))&&(!d.length||c(a,d,e,f)))return!0;return!1};m.pseudos={};return m});
(function(){function l(c,b,h){var d;x||(x=window[ensightenOptions.ns].qwery);d=x;if((d=d.call(h,b,h))&&0<d.length){if("_root"==b)c=h;else if(c===h)c=void 0;else{b:{for(var g=d.length,m=0;m<g;m++)if(c===d[m]){d=!0;break b}d=!1}d||(c.parentNode?(t++,c=l(c.parentNode,b,h)):c=void 0)}return c}return!1}function u(c,b,d,g){q[c.id]||(q[c.id]={});q[c.id][b]||(q[c.id][b]={});q[c.id][b][d]||(q[c.id][b][d]=[]);q[c.id][b][d].push(g)}function k(c,b,d,g){if(g||d)if(g)for(var k=0;k<q[c.id][b][d].length;k++){if(q[c.id][b][d][k]===
g){q[c.id][b][d].pop(k,1);break}}else delete q[c.id][b][d];else q[c.id][b]={}}function b(c,b,h){if(q[c][h]){var g=b.target||b.srcElement,k,m,n={},p=m=0;t=0;for(k in q[c][h])q[c][h].hasOwnProperty(k)&&(m=l(g,k,v[c].element))&&d.matchesEvent(h,v[c].element,m,"_root"==k,b)&&(t++,q[c][h][k].match=m,n[t]=q[c][h][k]);b.stopPropagation=function(){b.cancelBubble=!0};for(m=0;m<=t;m++)if(n[m])for(p=0;p<n[m].length;p++){if(!1===n[m][p].call(n[m].match,b)){d.cancel(b);return}if(b.cancelBubble)return}}}function g(c,
g,h,l){function p(c){return function(d){b(m,d,c)}}c instanceof Array||(c=[c]);h||"function"!=typeof g||(h=g,g="_root");var m=this.id,n;for(n=0;n<c.length;n++)q[m]&&q[m][c[n]]||d.addEvent(this,c[n],p(c[n])),l?k(this,c[n],g,h):u(this,c[n],g,h);return this}function d(b,g,h,k){if("string"==typeof b&&"function"==typeof g||"string"==typeof g)d(document).on(b,g,h,k||!1);if(!(this instanceof d)){for(var l in v)if(v[l].element===b)return v[l];p++;v[p]=new d(b,p);v[p]._on=v[p].on;v[p].on=function(b,c,d,g){var h=
"function"==typeof c?c:d;if("function"==typeof c?d:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,d)};return v[p]}this.element=b;this.id=g}var x,t=0,p=0,q={},v={};d.prototype.on=function(b,
d,h){return g.call(this,b,d,h)};d.prototype.off=function(b,d,h){return g.call(this,b,d,h,!0)};d.cancel=function(b){b.preventDefault();b.stopPropagation()};d.addEvent=function(b,d,g){b.element.addEventListener(d,g,"blur"==d||"focus"==d)};d.matchesEvent=function(){return!0};d.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||
""),750)};window[ensightenOptions.ns].Delegate=d})();(function(l){var u=l.addEvent;l.addEvent=function(k,b,g){if(k.element.addEventListener)return u(k,b,g);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+b,g)};l.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}})(window[ensightenOptions.ns].Delegate);window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate;
Bootstrapper.dataDefinitionIds = [776];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(document.URL.toLowerCase().indexOf("uat-pdp.sony.ca/en/electronics/televisions/xbr-x910c-x900c-series")>-1||document.URL.toLowerCase().indexOf("uat-pdp.sony.ca/en")>-1){window.GWT_AB_TESTING=true;Bootstrapper.bindOnGetServerComponent(function(){var proj_id="5017682518";var cust_tags_obj={};var local_keys=Object.keys(cust_tags_obj);window.optimizely=window.optimizely||
[];if(local_keys[0]!=="")if(local_keys.length===1)window.optimizely.push(["customTag",local_keys[0],cust_tags_obj[local_keys[0]]]);else window.optimizely.push(["customTag",cust_tags_obj]);document.write('\x3cscript type\x3d"text/javascript" src\x3d"//cdn.optimizely.com/js/'+proj_id+'.js"\x3e\x3c/script\x3e')})}},1245859,369463);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(document.URL.toLowerCase().indexOf("sony.com.au/electronics/mobile-world-congress")>-1||document.URL.toLowerCase().indexOf(".sony.com.au")>-1&&document.location.pathname==="/"){window.GWT_AB_TESTING=true;Bootstrapper.bindOnGetServerComponent(function(){var proj_id="3019501443";var cust_tags_obj={};var local_keys=Object.keys(cust_tags_obj);window.optimizely=window.optimizely||
[];if(local_keys[0]!=="")if(local_keys.length===1)window.optimizely.push(["customTag",local_keys[0],cust_tags_obj[local_keys[0]]]);else window.optimizely.push(["customTag",cust_tags_obj]);document.write('\x3cscript type\x3d"text/javascript" src\x3d"//cdn.optimizely.com/js/'+proj_id+'.js"\x3e\x3c/script\x3e')})}},1252383,368724);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var vIDSetup=function(){var trackingServer="sonyglobal.d1.sc.omtrdc.net";var trackingServerSecure="sonyglobal.d1.sc.omtrdc.net";var marketingCloudServer="";var marketingCloudServerSecure="";window.Visitor=Visitor;var visitor=new Visitor("7286403D53B6AA9A0A490D4C@AdobeOrg");if(trackingServer!=="")visitor.trackingServer=trackingServer;if(trackingServerSecure!=="")visitor.trackingServerSecure=
trackingServerSecure;if(marketingCloudServer!=="")visitor.marketingCloudServer=marketingCloudServer;if(marketingCloudServerSecure!=="")visitor.marketingCloudServerSecure=marketingCloudServerSecure;if(document.location.host.toLowerCase().indexOf("sony.com.ar")>-1)visitor.cookieDomain=".sony.com.ar";else if(document.location.host.toLowerCase().indexOf("sony.com.bo")>-1)visitor.cookieDomain=".sony.com.bo";else if(document.location.host.toLowerCase().indexOf("sony.com.br")>-1)visitor.cookieDomain=".sony.com.br";
else if(document.location.host.toLowerCase().indexOf("sony.com.co")>-1)visitor.cookieDomain=".sony.com.co";else if(document.location.host.toLowerCase().indexOf("sony.com.do")>-1)visitor.cookieDomain=".sony.com.do";else if(document.location.host.toLowerCase().indexOf("sony.com.ec")>-1)visitor.cookieDomain=".sony.com.ec";else if(document.location.host.toLowerCase().indexOf("sony.com.sv")>-1)visitor.cookieDomain=".sony.com.sv";else if(document.location.host.toLowerCase().indexOf("sony.com.gt")>-1)visitor.cookieDomain=
".sony.com.gt";else if(document.location.host.toLowerCase().indexOf("sony.com.hn")>-1)visitor.cookieDomain=".sony.com.hn";else if(document.location.host.toLowerCase().indexOf("sony.com.mx")>-1)visitor.cookieDomain=".sony.com.mx";else if(document.location.host.toLowerCase().indexOf("sony.com.ni")>-1)visitor.cookieDomain=".sony.com.ni";else if(document.location.host.toLowerCase().indexOf("sony.com.pa")>-1)visitor.cookieDomain=".sony.com.pa";else if(document.location.host.toLowerCase().indexOf("sony.com.pe")>
-1)visitor.cookieDomain=".sony.com.pe";else if(document.location.host.toLowerCase().indexOf("sony.com.py")>-1)visitor.cookieDomain=".sony.com.py";else if(document.location.host.toLowerCase().indexOf("sony.com.pr")>-1)visitor.cookieDomain=".sony.com.pr";else if(document.location.host.toLowerCase().indexOf("sony.com.mk")>-1)visitor.cookieDomain=".sony.com.mk";else if(document.location.host.toLowerCase().indexOf("sony.com.tr")>-1)visitor.cookieDomain=".sony.com.tr";else if(document.location.host.toLowerCase().indexOf("sony.com.ve")>
-1)visitor.cookieDomain=".sony.com.ve";else if(document.location.host.toLowerCase().indexOf("sony.co.uk")>-1)visitor.cookieDomain=".sony.co.uk";else if(document.location.host.toLowerCase().indexOf("sony.co.id")>-1)visitor.cookieDomain=".sony.co.id";else if(document.location.host.toLowerCase().indexOf("sony.co.ir")>-1)visitor.cookieDomain=".sony.co.ir";else if(document.location.host.toLowerCase().indexOf("sony.co.kr")>-1)visitor.cookieDomain=".sony.co.kr";else if(document.location.host.toLowerCase().indexOf("sony.co.nz")>
-1)visitor.cookieDomain=".sony.co.nz";else if(document.location.host.toLowerCase().indexOf("sony.co.th")>-1)visitor.cookieDomain=".sony.co.th";else if(document.location.host.toLowerCase().indexOf("sony.co.za")>-1)visitor.cookieDomain=".sony.co.za";else if(document.location.host.toLowerCase().indexOf("sony.com.au")>-1)visitor.cookieDomain=".sony.com.au";else if(document.location.host.toLowerCase().indexOf("sony.com.cn")>-1)visitor.cookieDomain=".sony.com.cn";else if(document.location.host.toLowerCase().indexOf("sony.com.my")>
-1)visitor.cookieDomain=".sony.com.my";else if(document.location.host.toLowerCase().indexOf("sony.com.ph")>-1)visitor.cookieDomain=".sony.com.ph";else if(document.location.host.toLowerCase().indexOf("sony.com.sg")>-1)visitor.cookieDomain=".sony.com.sg";else if(document.location.host.toLowerCase().indexOf("sony.com.tw")>-1)visitor.cookieDomain=".sony.com.tw";else if(document.location.host.toLowerCase().indexOf("sony.com.vn")>-1)visitor.cookieDomain=".sony.com.vn";else if(document.location.host.toLowerCase().indexOf("sony.co.in")>
-1)visitor.cookieDomain=".sony.co.in";else if(document.location.host.toLowerCase().indexOf("sony.com.hk")>-1)visitor.cookieDomain=".sony.com.hk";window.visitor=visitor;function Visitor(m,s){if(!m)throw"Visitor requires Adobe Marketing Cloud Org ID";var a=this;a.version="1.5.3";var l=window,j=l.Visitor;j.version=a.version;l.s_c_in||(l.s_c_il=[],l.s_c_in=0);a._c="Visitor";a._il=l.s_c_il;a._in=l.s_c_in;a._il[a._in]=a;l.s_c_in++;a.pa={Ka:[]};var n=l.document,h=j.Ma;h||(h=null);var x=j.Na;x||(x=void 0);
var i=j.ja;i||(i=!0);var k=j.La;k||(k=!1);a.S=function(a){var c=0,b,e;if(a)for(b=0;b<a.length;b++)e=a.charCodeAt(b),c=(c<<5)-c+e,c&=c;return c};a.q=function(a){var c="0123456789",b="",e="",f,g=8,i=10,h=10;if(1==a){c+="ABCDEF";for(a=0;16>a;a++)f=Math.floor(Math.random()*g),b+=c.substring(f,f+1),f=Math.floor(Math.random()*g),e+=c.substring(f,f+1),g=16;return b+"-"+e}for(a=0;19>a;a++)f=Math.floor(Math.random()*i),b+=c.substring(f,f+1),0==a&&9==f?i=3:(1==a||2==a)&&10!=i&&2>f?i=10:2<a&&(i=10),f=Math.floor(Math.random()*
h),e+=c.substring(f,f+1),0==a&&9==f?h=3:(1==a||2==a)&&10!=h&&2>f?h=10:2<a&&(h=10);return b+e};a.ma=function(){var a;!a&&l.location&&(a=l.location.hostname);if(a)if(/^[0-9.]+$/.test(a))a="";else{var c=a.split("."),b=c.length-1,e=b-1;1<b&&2>=c[b].length&&(2==c[b-1].length||0>",ac,ad,ae,af,ag,ai,al,am,an,ao,aq,ar,as,at,au,aw,ax,az,ba,bb,be,bf,bg,bh,bi,bj,bm,bo,br,bs,bt,bv,bw,by,bz,ca,cc,cd,cf,cg,ch,ci,cl,cm,cn,co,cr,cu,cv,cw,cx,cz,de,dj,dk,dm,do,dz,ec,ee,eg,es,et,eu,fi,fm,fo,fr,ga,gb,gd,ge,gf,gg,gh,gi,gl,gm,gn,gp,gq,gr,gs,gt,gw,gy,hk,hm,hn,hr,ht,hu,id,ie,im,in,io,iq,ir,is,it,je,jo,jp,kg,ki,km,kn,kp,kr,ky,kz,la,lb,lc,li,lk,lr,ls,lt,lu,lv,ly,ma,mc,md,me,mg,mh,mk,ml,mn,mo,mp,mq,mr,ms,mt,mu,mv,mw,mx,my,na,nc,ne,nf,ng,nl,no,nr,nu,nz,om,pa,pe,pf,ph,pk,pl,pm,pn,pr,ps,pt,pw,py,qa,re,ro,rs,ru,rw,sa,sb,sc,sd,se,sg,sh,si,sj,sk,sl,sm,sn,so,sr,st,su,sv,sx,sy,sz,tc,td,tf,tg,th,tj,tk,tl,tm,tn,to,tp,tr,tt,tv,tw,tz,ua,ug,uk,us,uy,uz,va,vc,ve,vg,vi,vn,vu,wf,ws,yt,".indexOf(","+
c[b]+","))&&e--;if(0<e)for(a="";b>=e;)a=c[b]+(a?".":"")+a,b--}return a};a.cookieRead=function(a){var a=encodeURIComponent(a),c=(";"+n.cookie).split(" ").join(";"),b=c.indexOf(";"+a+"\x3d"),e=0>b?b:c.indexOf(";",b+1);return 0>b?"":decodeURIComponent(c.substring(b+2+a.length,0>e?c.length:e))};a.cookieWrite=function(d,c,b){var e=a.cookieLifetime,f,c=""+c,e=e?(""+e).toUpperCase():"";b&&"SESSION"!=e&&"NONE"!=e?(f=""!=c?parseInt(e?e:0,10):-60)?(b=new Date,b.setTime(b.getTime()+1E3*f)):1==b&&(b=new Date,
f=b.getYear(),b.setYear(f+2+(1900>f?1900:0))):b=0;return d&&"NONE"!=e?(n.cookie=encodeURIComponent(d)+"\x3d"+encodeURIComponent(c)+"; path\x3d/;"+(b?" expires\x3d"+b.toGMTString()+";":"")+(a.cookieDomain?" domain\x3d"+a.cookieDomain+";":""),a.cookieRead(d)==c):0};a.g=h;a.O=function(a,c){try{"function"==typeof a?a.apply(l,c):a[1].apply(a[0],c)}catch(b){}};a.ra=function(d,c){c&&(a.g==h&&(a.g={}),a.g[d]==x&&(a.g[d]=[]),a.g[d].push(c))};a.o=function(d,c){if(a.g!=h){var b=a.g[d];if(b)for(;0<b.length;)a.O(b.shift(),
c)}};a.j=h;a.oa=function(d,c,b){var e=0,f=0,g;if(c&&n){for(g=0;!e&&2>g;){try{e=(e=n.getElementsByTagName(0<g?"HEAD":"head"))&&0<e.length?e[0]:0}catch(i){e=0}g++}if(!e)try{n.body&&(e=n.body)}catch(j){e=0}if(e)for(g=0;!f&&2>g;){try{f=n.createElement(0<g?"SCRIPT":"script")}catch(k){f=0}g++}}!c||!e||!f?b&&b():(f.type="text/javascript",f.setAttribute("async","async"),f.src=c,e.firstChild?e.insertBefore(f,e.firstChild):e.appendChild(f),a.pa.Ka.push(c),b&&(a.j==h&&(a.j={}),a.j[d]=setTimeout(b,a.loadTimeout)))};
a.ka=function(d){a.j!=h&&a.j[d]&&(clearTimeout(a.j[d]),a.j[d]=0)};a.T=k;a.U=k;a.isAllowed=function(){if(!a.T&&(a.T=i,a.cookieRead(a.cookieName)||a.cookieWrite(a.cookieName,"T",1)))a.U=i;return a.U};a.a=h;a.d=h;var z=j.$a;z||(z="MC");var q=j.eb;q||(q="MCMID");var A=j.ab;A||(A="MCCIDH");var B=j.cb;B||(B="MCSYNCS");var D=j.bb;D||(D="MCIDTS");var y=j.Ya;y||(y="A");var o=j.Va;o||(o="MCAID");var w=j.Za;w||(w="AAM");var v=j.Xa;v||(v="MCAAMLH");var p=j.Wa;p||(p="MCAAMB");var r=j.fb;r||(r="NONE");a.B=0;a.R=
function(){if(!a.B){var d=a.version;a.audienceManagerServer&&(d+="|"+a.audienceManagerServer);a.audienceManagerServerSecure&&(d+="|"+a.audienceManagerServerSecure);a.B=a.S(d)}return a.B};a.V=k;a.f=function(){if(!a.V){a.V=i;var d=a.R(),c=k,b=a.cookieRead(a.cookieName),e,f,g,j=new Date;a.a==h&&(a.a={});if(b&&"T"!=b){b=b.split("|");b[0].match(/^[\-0-9]+$/)&&(parseInt(b[0],10)!=d&&(c=i),b.shift());1==b.length%2&&b.pop();for(d=0;d<b.length;d+=2)e=b[d].split("-"),f=e[0],g=b[d+1],e=1<e.length?parseInt(e[1],
10):0,c&&(f==A&&(g=""),0<e&&(e=j.getTime()/1E3-60)),f&&g&&(a.c(f,g,1),0<e&&(a.a["expire"+f]=e,j.getTime()>=1E3*e&&(a.d||(a.d={}),a.d[f]=i)))}if(!a.b(o)&&(b=a.cookieRead("s_vi")))b=b.split("|"),1<b.length&&0<=b[0].indexOf("v1")&&(g=b[1],d=g.indexOf("["),0<=d&&(g=g.substring(0,d)),g&&g.match(/^[0-9a-fA-F\-]+$/)&&a.c(o,g))}};a.ta=function(){var d=a.R(),c,b;for(c in a.a)!Object.prototype[c]&&a.a[c]&&"expire"!=c.substring(0,6)&&(b=a.a[c],d+=(d?"|":"")+c+(a.a["expire"+c]?"-"+a.a["expire"+c]:"")+"|"+b);
a.cookieWrite(a.cookieName,d,1)};a.b=function(d,c){return a.a!=h&&(c||!a.d||!a.d[d])?a.a[d]:h};a.c=function(d,c,b){a.a==h&&(a.a={});a.a[d]=c;b||a.ta()};a.na=function(d,c){var b=a.b(d,c);return b?b.split("*"):h};a.sa=function(d,c,b){a.c(d,c?c.join("*"):"",b)};a.Sa=function(d,c){var b=a.na(d,c);if(b){var e={},f;for(f=0;f<b.length;f+=2)e[b[f]]=b[f+1];return e}return h};a.Ua=function(d,c,b){var e=h,f;if(c)for(f in e=[],c)Object.prototype[f]||(e.push(f),e.push(c[f]));a.sa(d,e,b)};a.l=function(d,c){var b=
new Date;b.setTime(b.getTime()+1E3*c);a.a==h&&(a.a={});a.a["expire"+d]=Math.floor(b.getTime()/1E3);0>c?(a.d||(a.d={}),a.d[d]=i):a.d&&(a.d[d]=k)};a.Q=function(a){if(a&&("object"==typeof a&&(a=a.d_mid?a.d_mid:a.visitorID?a.visitorID:a.id?a.id:a.uuid?a.uuid:""+a),a&&(a=a.toUpperCase(),"NOTARGET"==a&&(a=r)),!a||a!=r&&!a.match(/^[0-9a-fA-F\-]+$/)))a="";return a};a.i=function(d,c){a.ka(d);a.h!=h&&(a.h[d]=k);if(d==z){var b=a.b(q);if(!b){b="object"==typeof c&&c.mid?c.mid:a.Q(c);if(!b){if(a.u){a.getAnalyticsVisitorID(h,
k,i);return}b=a.q()}a.c(q,b)}if(!b||b==r)b="";"object"==typeof c&&((c.d_region||c.dcs_region||c.d_blob||c.blob)&&a.i(w,c),a.u&&c.mid&&a.i(y,{id:c.id}));a.o(q,[b])}if(d==w&&"object"==typeof c){b=604800;c.id_sync_ttl!=x&&c.id_sync_ttl&&(b=parseInt(c.id_sync_ttl,10));var e=a.b(v);e||((e=c.d_region)||(e=c.dcs_region),e&&(a.l(v,b),a.c(v,e)));e||(e="");a.o(v,[e]);e=a.b(p);if(c.d_blob||c.blob)(e=c.d_blob)||(e=c.blob),a.l(p,b),a.c(p,e);e||(e="");a.o(p,[e]);!c.error_msg&&a.s&&a.c(A,a.s);a.idSyncDisableSyncs?
t.ba=i:(t.ba=k,b={},b.ibs=c.ibs,b.subdomain=c.subdomain,t.Ia(b))}if(d==y){b=a.b(o);b||((b=a.Q(c))?a.l(p,-1):b=r,a.c(o,b));if(!b||b==r)b="";a.o(o,[b])}};a.h=h;a.r=function(d,c,b,e){var f="",g;if(a.isAllowed()&&(a.f(),f=a.b(d),!f&&(d==q?g=z:d==v||d==p?g=w:d==o&&(g=y),g))){if(c&&(a.h==h||!a.h[g]))a.h==h&&(a.h={}),a.h[g]=i,a.oa(g,c,function(){if(!a.b(d)){var b="";d==q?b=a.q():g==w&&(b={error_msg:"timeout"});a.i(g,b)}});a.ra(d,b);c||a.i(g,{id:r});return""}if((d==q||d==o)&&f==r)f="",e=i;b&&e&&a.O(b,[f]);
return f};a._setMarketingCloudFields=function(d){a.f();a.i(z,d)};a.setMarketingCloudVisitorID=function(d){a._setMarketingCloudFields(d)};a.u=k;a.getMarketingCloudVisitorID=function(d,c){if(a.isAllowed()){a.marketingCloudServer&&0>a.marketingCloudServer.indexOf(".demdex.net")&&(a.u=i);var b=a.A("_setMarketingCloudFields");return a.r(q,b,d,c)}return""};a.qa=function(){a.getAudienceManagerBlob()};j.AuthState={UNKNOWN:0,AUTHENTICATED:1,LOGGED_OUT:2};a.p={};a.P=k;a.s="";a.setCustomerIDs=function(d){if(a.isAllowed()&&
d){a.f();var c,b;for(c in d)if(!Object.prototype[c]&&(b=d[c]))if("object"==typeof b){var e={};b.id&&(e.id=b.id);b.authState!=x&&(e.authState=b.authState);a.p[c]=e}else a.p[c]={id:b};var d=a.getCustomerIDs(),e=a.b(A),f="";e||(e=0);for(c in d)Object.prototype[c]||(b=d[c],f+=(f?"|":"")+c+"|"+(b.id?b.id:"")+(b.authState?b.authState:""));a.s=a.S(f);a.s!=e&&(a.P=i,a.qa())}};a.getCustomerIDs=function(){a.f();var d={},c,b;for(c in a.p)Object.prototype[c]||(b=a.p[c],d[c]||(d[c]={}),b.id&&(d[c].id=b.id),d[c].authState=
b.authState!=x?b.authState:j.AuthState.UNKNOWN);return d};a._setAnalyticsFields=function(d){a.f();a.i(y,d)};a.setAnalyticsVisitorID=function(d){a._setAnalyticsFields(d)};a.getAnalyticsVisitorID=function(d,c,b){if(a.isAllowed()){var e="";b||(e=a.getMarketingCloudVisitorID(function(){a.getAnalyticsVisitorID(d,i)}));if(e||b){var f=b?a.marketingCloudServer:a.trackingServer,g="";a.loadSSL&&(b?a.marketingCloudServerSecure&&(f=a.marketingCloudServerSecure):a.trackingServerSecure&&(f=a.trackingServerSecure));
f&&(g="http"+(a.loadSSL?"s":"")+"://"+f+"/id?d_visid_ver\x3d"+a.version+"\x26callback\x3ds_c_il%5B"+a._in+"%5D._set"+(b?"MarketingCloud":"Analytics")+"Fields\x26mcorgid\x3d"+encodeURIComponent(a.marketingCloudOrgID)+(e?"\x26mid\x3d"+e:"")+(a.idSyncDisable3rdPartySyncing?"\x26d_coppa\x3dtrue":""));return a.r(b?q:o,g,d,c)}}return""};a._setAudienceManagerFields=function(d){a.f();a.i(w,d)};a.A=function(d){var c=a.audienceManagerServer,b="",e=a.b(q),f=a.b(p,i),g=a.b(o),g=g&&g!=r?"\x26d_cid_ic\x3dAVID%01"+
encodeURIComponent(g):"";a.loadSSL&&a.audienceManagerServerSecure&&(c=a.audienceManagerServerSecure);if(c){var b=a.getCustomerIDs(),h,j;if(b)for(h in b)Object.prototype[h]||(j=b[h],g+="\x26d_cid_ic\x3d"+encodeURIComponent(h)+"%01"+encodeURIComponent(j.id?j.id:"")+(j.authState?"%01"+j.authState:""));d||(d="_setAudienceManagerFields");b="http"+(a.loadSSL?"s":"")+"://"+c+"/id?d_visid_ver\x3d"+a.version+"\x26d_rtbd\x3djson\x26d_ver\x3d2"+(!e&&a.u?"\x26d_verify\x3d1":"")+"\x26d_orgid\x3d"+encodeURIComponent(a.marketingCloudOrgID)+
"\x26d_nsid\x3d"+(a.idSyncContainerID||0)+(e?"\x26d_mid\x3d"+e:"")+(a.idSyncDisable3rdPartySyncing?"\x26d_coppa\x3dtrue":"")+(f?"\x26d_blob\x3d"+encodeURIComponent(f):"")+g+"\x26d_cb\x3ds_c_il%5B"+a._in+"%5D."+d}return b};a.getAudienceManagerLocationHint=function(d,c){if(a.isAllowed()&&a.getMarketingCloudVisitorID(function(){a.getAudienceManagerLocationHint(d,i)})){var b=a.b(o);b||(b=a.getAnalyticsVisitorID(function(){a.getAudienceManagerLocationHint(d,i)}));if(b)return b=a.A(),a.r(v,b,d,c)}return""};
a.getAudienceManagerBlob=function(d,c){if(a.isAllowed()&&a.getMarketingCloudVisitorID(function(){a.getAudienceManagerBlob(d,i)})){var b=a.b(o);b||(b=a.getAnalyticsVisitorID(function(){a.getAudienceManagerBlob(d,i)}));if(b)return b=a.A(),a.P&&a.l(p,-1),a.r(p,b,d,c)}return""};a.m="";a.t={};a.C="";a.D={};a.getSupplementalDataID=function(d,c){!a.m&&!c&&(a.m=a.q(1));var b=a.m;a.C&&!a.D[d]?(b=a.C,a.D[d]=i):b&&(a.t[d]&&(a.C=a.m,a.D=a.t,a.m=b=!c?a.q(1):"",a.t={}),b&&(a.t[d]=i));return b};var u={k:!!l.postMessage,
ha:1,N:864E5};a.Oa=u;a.X={postMessage:function(a,c,b){var e=1;c&&(u.k?b.postMessage(a,c.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):c&&(b.location=c.replace(/#.*$/,"")+"#"+ +new Date+e++ +"\x26"+a))},J:function(a,c){var b;try{if(u.k)if(a&&(b=function(b){if("string"===typeof c&&b.origin!==c||"[object Function]"===Object.prototype.toString.call(c)&&!1===c(b.origin))return!1;a(b)}),window.addEventListener)window[a?"addEventListener":"removeEventListener"]("message",b,!1);else window[a?"attachEvent":"detachEvent"]("onmessage",
b)}catch(e){}}};var E={Y:function(){if(n.addEventListener)return function(a,c,b){a.addEventListener(c,function(a){"function"===typeof b&&b(a)},k)};if(n.attachEvent)return function(a,c,b){a.attachEvent("on"+c,function(a){"function"===typeof b&&b(a)})}}(),map:function(a,c){if(Array.prototype.map)return a.map(c);if(void 0===a||a===h)throw new TypeError;var b=Object(a),e=b.length>>>0;if("function"!==typeof c)throw new TypeError;for(var f=Array(e),g=0;g<e;g++)g in b&&(f[g]=c.call(c,b[g],g,b));return f},
za:function(a,c){return this.map(a,function(a){return encodeURIComponent(a)}).join(c)}};a.Ta=E;var t={ia:3E4,M:649,fa:k,id:h,H:h,aa:function(a){if("string"===typeof a)return a=a.split("/"),a[0]+"//"+a[2]},e:h,url:h,Aa:function(){var d="http://fast.",c="?d_nsid\x3d"+a.idSyncContainerID+"#"+encodeURIComponent(n.location.href);this.e||(this.e="nosubdomainreturned");a.loadSSL&&(d=a.idSyncSSLUseAkamai?"https://fast.":"https://");d=d+this.e+".demdex.net/dest5.html"+c;this.H=this.aa(d);this.id="destination_publishing_iframe_"+
this.e+"_"+a.idSyncContainerID;return d},va:function(){var d="?d_nsid\x3d"+a.idSyncContainerID+"#"+encodeURIComponent(n.location.href);"string"===typeof a.z&&a.z.length&&(this.id="destination_publishing_iframe_"+(new Date).getTime()+"_"+a.idSyncContainerID,this.H=this.aa(a.z),this.url=a.z+d)},ba:h,G:k,L:k,v:h,gb:h,Ga:h,hb:h,K:k,w:[],Ea:[],Fa:[],ca:u.k?15:100,I:[],Ca:[],$:i,da:k,Z:function(){function a(){e=document.createElement("iframe");e.id=b.id;e.style.cssText="display: none; width: 0; height: 0;";
e.src=b.url;b.Ga=i;c();document.body.appendChild(e)}function c(){E.Y(e,"load",function(){e.className="aamIframeLoaded";b.v=i;b.n()})}this.L=i;var b=this,e=document.getElementById(this.id);e?"IFRAME"!==e.nodeName?(this.id+="_2",a()):"aamIframeLoaded"!==e.className?c():(this.v=i,this.n()):a();this.Ba=e},n:function(d){var c=this;d===Object(d)&&this.I.push(d);if((this.da||!u.k||this.v)&&this.I.length)this.Ha(this.I.shift()),this.n();!a.idSyncDisableSyncs&&this.v&&this.w.length&&!this.K&&(this.fa||(this.fa=
i,setTimeout(function(){c.ca=u.k?15:150},this.ia)),this.K=i,this.ea())},Ha:function(a){var c=encodeURIComponent,b,e,f,g,h;if((b=a.ibs)&&b instanceof Array&&(e=b.length))for(f=0;f<e;f++)g=b[f],h=[c("ibs"),c(g.id||""),c(g.tag||""),E.za(g.url||[],","),c(g.ttl||""),"","",g.fireURLSync?"true":"false"],this.$?this.F(h.join("|")):g.fireURLSync&&this.wa(g,h.join("|"));this.Ca.push(a)},wa:function(d,c){a.f();var b=a.b(B),e=k,f=k,g=Math.ceil((new Date).getTime()/u.N);if(b){if(b=b.split("*"),f=this.Ja(b,d.id,
g),e=f.xa,f=f.ya,!e||!f)this.F(c),b.push(d.id+"-"+(g+Math.ceil(d.ttl/60/24))),this.Da(b),a.c(B,b.join("*"))}else this.F(c),a.c(B,d.id+"-"+(g+Math.ceil(d.ttl/60/24)))},Ja:function(a,c,b){var e=k,f=k,g,h,j;for(h=0;h<a.length;h++)g=a[h],j=parseInt(g.split("-")[1],10),g.match("^"+c+"-")?(e=i,b<j?f=i:(a.splice(h,1),h--)):b>=j&&(a.splice(h,1),h--);return{xa:e,ya:f}},Da:function(a){if(a.join("*").length>this.M)for(a.sort(function(a,b){return parseInt(a.split("-")[1],10)-parseInt(b.split("-")[1],10)});a.join("*").length>
this.M;)a.shift()},F:function(d){var c=encodeURIComponent;this.w.push((a.Qa?c("---destpub-debug---"):c("---destpub---"))+d)},ea:function(){var d=this,c;this.w.length?(c=this.w.shift(),a.X.postMessage(c,this.url,this.Ba.contentWindow),this.Ea.push(c),setTimeout(function(){d.ea()},this.ca)):this.K=k},J:function(a){var c=/^---destpub-to-parent---/;"string"===typeof a&&c.test(a)&&(c=a.replace(c,"").split("|"),"canSetThirdPartyCookies"===c[0]&&(this.$="true"===c[1]?i:k,this.da=i,this.n()),this.Fa.push(a))},
Ia:function(d){this.url===h&&(this.e="string"===typeof a.W&&a.W.length?a.W:d.subdomain||"",this.url=this.Aa());d.ibs instanceof Array&&d.ibs.length&&(this.G=i);if(!a.idSyncDisable3rdPartySyncing&&(this.G||a.la)&&this.e&&"nosubdomainreturned"!==this.e&&!this.L)(j.ga||"complete"===n.readyState||"loaded"===n.readyState)&&this.Z();"function"===typeof a.idSyncIDCallResult?a.idSyncIDCallResult(d):this.n(d);"function"===typeof a.idSyncAfterIDCallResult&&a.idSyncAfterIDCallResult(d)},ua:function(d,c){return a.Ra||
!d||c-d>u.ha}};a.Pa=t;0>m.indexOf("@")&&(m+="@AdobeOrg");a.marketingCloudOrgID=m;a.cookieName="AMCV_"+m;a.cookieDomain=a.ma();a.cookieDomain==l.location.hostname&&(a.cookieDomain="");a.loadSSL=0<=l.location.protocol.toLowerCase().indexOf("https");a.loadTimeout=500;a.marketingCloudServer=a.audienceManagerServer="dpm.demdex.net";if(s&&"object"==typeof s){for(var C in s)!Object.prototype[C]&&(a[C]=s[C]);a.idSyncContainerID=a.idSyncContainerID||0;a.f();C=a.b(D);var F=Math.ceil((new Date).getTime()/u.N);
!a.idSyncDisableSyncs&&t.ua(C,F)&&(a.l(p,-1),a.c(D,F));a.getMarketingCloudVisitorID();a.getAudienceManagerLocationHint();a.getAudienceManagerBlob()}if(!a.idSyncDisableSyncs){t.va();E.Y(window,"load",function(){var d=t;j.ga=i;!a.idSyncDisable3rdPartySyncing&&(d.G||a.la)&&d.e&&"nosubdomainreturned"!==d.e&&d.url&&!d.L&&d.Z()});try{a.X.J(function(a){t.J(a.data)},t.H)}catch(G){}}}Visitor.getInstance=function(m,s){var a,l=window.s_c_il,j;0>m.indexOf("@")&&(m+="@AdobeOrg");if(l)for(j=0;j<l.length;j++)if((a=
l[j])&&"Visitor"==a._c&&a.marketingCloudOrgID==m)return a;return new Visitor(m,s)};(function(){function m(){s.ga=a}var s=window.Visitor,a=s.ja;a||(a=!0);window.addEventListener?window.addEventListener("load",m):window.attachEvent&&window.attachEvent("onload",m)})()};vIDSetup.call(window)},1235897,286038);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var val="";try{val=(new SonyAnalytics).build().analytics.page.section}catch(e){window.e1=e}return val},transform:function(val){return val?val.toLowerCase():""},load:"",dataDefName:"Page_Section",collection:"dataPage",source:"Manage",priv:"false"},{id:"776"})},776)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=n.length-1;i>=0;i--)for(var j=0;j<
detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.getQueryParam=function(key,loc){if(!this.params||
loc){var search=loc||window.location.search;var params=search.replace(/^\?/,""),paramObj={};params=params.split("\x26");for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=paramObj;else return paramObj[key]||""}return this.params[key]||""};Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==
_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:
e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=
Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};
Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<
a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:(true||!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),
content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=
false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL not available")}},store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set","_ensCloak",o)}_log("*** Cloak:Storage updated")},load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");
for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=
o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=
true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=
!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},
500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);
this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");
this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=
!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");
for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},
traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),
25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");
setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p==
"replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p==
"after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=
this.deploymentId;try{if(typeof jQuery!=="undefined"&&typeof jQuery.extend!=="undefined")window._originalLocation=jQuery.extend(true,{},window.location);else{window._originalLocation=JSON.parse(JSON.stringify(window.location));window._originalLocation.search=window.location.search||"";window._originalLocation.href=window.location.href||"";window._originalLocation.hostname=window.location.hostname||"";window._originalLocation.hash=window.location.hash||"";window._originalLocation.host=window.location.host||
"";window._originalLocation.origin=window.location.origin||"";window._originalLocation.pathname=window.location.pathname||"";window._originalLocation.protocol=window.location.protocol||"";window._originalLocation.port=window.location.port||""}}catch(e){}},998348,272400);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();