(function ensightenInit(){var ensightenOptions = {client: "harryanddavid", clientId: 866, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/harryanddavid/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/harryanddavid/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Fri Feb 05 19:08:54 GMT 2016", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===
a.dependencies[b]())return;a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&
c.allDeploymentIds.push(e),!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,
b){c.ensightenVariables[a]=b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+
encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=
function(){this.executionData.runTime.push(new Date);b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==
a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=
document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+
"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=
function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===
this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};
b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});
else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,
l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";
a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+
"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
	
if (!window[ensightenOptions.ns].data) {
	/*
	 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
	window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
	(function(){function e(a){return 10>a?"0"+a:a}function m(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(f,e){var b,g,p,d,h=k,u,q=e[f];q&&"object"===typeof q&&"function"===typeof q.toJSON&&(q=q.toJSON(f));"function"===typeof c&&(q=c.call(e,f,q));switch(typeof q){case "string":return m(q);case "number":return isFinite(q)?String(q):"null";case "boolean":case "null":return String(q);
	case "object":if(!q)return"null";k+=a;u=[];if("[object Array]"===Object.prototype.toString.apply(q)){d=q.length;for(b=0;b<d;b+=1)u[b]=l(b,q)||"null";p=0===u.length?"[]":k?"[\n"+k+u.join(",\n"+k)+"\n"+h+"]":"["+u.join(",")+"]";k=h;return p}if(c&&"object"===typeof c)for(d=c.length,b=0;b<d;b+=1)"string"===typeof c[b]&&(g=c[b],(p=l(g,q))&&u.push(m(g)+(k?": ":":")+p));else for(g in q)Object.prototype.hasOwnProperty.call(q,g)&&(p=l(g,q))&&u.push(m(g)+(k?": ":":")+p);p=0===u.length?"{}":k?"{\n"+k+u.join(",\n"+
	k)+"\n"+h+"}":"{"+u.join(",")+"}";k=h;return p}}var b=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d=
	/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,a,f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c;"function"!==typeof b.stringify&&(b.stringify=function(b,f,e){var g;a=k="";if("number"===typeof e)for(g=0;g<e;g+=1)a+=" ";else"string"===typeof e&&(a=e);if((c=f)&&"function"!==typeof f&&
	("object"!==typeof f||"number"!==typeof f.length))throw Error("JSON.stringify");return l("",{"":b})});"function"!==typeof b.parse&&(b.parse=function(a,c){function f(a,b){var e,g,d=a[b];if(d&&"object"===typeof d)for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(g=f(d,e),void 0!==g?d[e]=g:delete d[e]);return c.call(a,b,d)}var b;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
	"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),"function"===typeof c?f({"":b},""):b;throw new SyntaxError("JSON.parse");})})();
	window[ensightenOptions.ns].when=function(){function e(a,b,c,f){return l(a).then(b,c,f)}function m(a){this.then=a}function l(a){return b(function(b){b(a)})}function b(c){function e(a){n&&(t=d(a),f(n,t),n=v)}function g(a){e(k(a))}function p(b){n&&f(n,a(b))}var t,n=[];try{c(e,g,p)}catch(h){g(h)}return new m(function(a,c,f){return b(function(b,e,g){n?n.push(function(d){d.then(a,c,f).then(b,e,g)}):r(function(){t.then(a,c,f).then(b,e,g)})})})}function d(a){return a instanceof m?a:a!==Object(a)?h(a):b(function(b,
	c,f){r(function(){try{var e=a.then;"function"===typeof e?B(e,a,b,c,f):b(h(a))}catch(g){c(g)}})})}function h(a){var b=new m(function(c){try{return"function"==typeof c?d(c(a)):b}catch(f){return k(f)}});return b}function k(a){var b=new m(function(c,f){try{return"function"==typeof f?d(f(a)):b}catch(e){return k(e)}});return b}function a(b){var c=new m(function(f,e,g){try{return"function"==typeof g?a(g(b)):c}catch(d){return a(d)}});return c}function f(a,b){r(function(){for(var c,f=0;c=a[f++];)c(b)})}function c(a,
	c,f,g,d){p(2,arguments);return e(a,function(a){return b(function(b,f,g){function d(a){l(a)}function p(a){r(a)}var n,h,w,k,r,l,x,z;x=a.length>>>0;n=Math.max(0,Math.min(c,x));w=[];h=x-n+1;k=[];if(n)for(l=function(a){k.push(a);--h||(r=l=t,f(k))},r=function(a){w.push(a);--n||(r=l=t,b(w))},z=0;z<x;++z)z in a&&e(a[z],p,d,g);else b(w)}).then(f,g,d)})}function n(a,b,c,f){p(1,arguments);return w(a,x).then(b,c,f)}function w(a,c){return e(a,function(a){return b(function(b,f,g){var d,p,t,n,h;t=p=a.length>>>0;
	d=[];if(t)for(n=function(a,p){e(a,c).then(function(a){d[p]=a;--t||b(d)},f,g)},h=0;h<p;h++)h in a?n(a[h],h):--t;else b(d)})})}function r(a){1===A.push(a)&&D(g)}function g(){for(var a,b=0;a=A[b++];)a();A=[]}function p(a,b){for(var c,f=b.length;f>a;)if(c=b[--f],null!=c&&"function"!=typeof c)throw Error("arg "+f+" must be a function");}function t(){}function x(a){return a}e.defer=function(){var a,c,f;a={promise:v,resolve:v,reject:v,notify:v,resolver:{resolve:v,reject:v,notify:v}};a.promise=c=b(function(b,
	g,e){a.resolve=a.resolver.resolve=function(a){if(f)return l(a);f=!0;b(a);return c};a.reject=a.resolver.reject=function(a){if(f)return l(k(a));f=!0;g(a);return c};a.notify=a.resolver.notify=function(a){e(a);return a}});return a};e.resolve=l;e.reject=function(a){return e(a,k)};e.join=function(){return w(arguments,x)};e.all=n;e.map=w;e.reduce=function(a,b){var c=B(q,arguments,1);return e(a,function(a){var f;f=a.length;c[0]=function(a,c,g){return e(a,function(a){return e(c,function(c){return b(a,c,g,
	f)})})};return u.apply(a,c)})};e.any=function(a,b,f,g){return c(a,1,function(a){return b?b(a[0]):a[0]},f,g)};e.some=c;e.isPromise=function(a){return a&&"function"===typeof a.then};m.prototype={otherwise:function(a){return this.then(v,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return n(b,function(b){return a.apply(v,b)})})},always:function(a,b){return this.then(a,
	a,b)}};var u,q,B,D,A,E,y,C,v;A=[];E=setTimeout;D="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){E(a,0)};y=Function.prototype;C=y.call;B=y.bind?C.bind(C):function(a,b){return a.apply(b,q.call(arguments,2))};y=[];q=y.slice;u=y.reduce||function(a){var b,c,f,g;g=0;b=Object(this);f=b.length>>>0;c=arguments;if(1>=c.length)for(;;){if(g in b){c=b[g++];break}if(++g>=f)throw new TypeError;
	}else c=c[1];for(;g<f;++g)g in b&&(c=a(c,b[g],g,b));return c};return e}();
	(function(){function e(b,e){return l.all(e||[],function(e){return b.apply(null,e)})}function m(d){var h=b.call(arguments,1);return function(){return e(d,h.concat(b.call(arguments)))}}var l,b;l=window[ensightenOptions.ns].when;b=[].slice;l.apply=e;l.call=function(d){return e(d,b.call(arguments,1))};l.lift=m;l.bind=m;l.compose=function(d){var h=b.call(arguments,1);return function(){var k=b.call(arguments),k=e(d,k);return l.reduce(h,function(a,b){return b(a)},k)}}})();
	window[ensightenOptions.ns].data=function(e,m){function l(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var b={engines:{memory:{get:function(a){if(d.utils.isArray(a)){for(var f=[],c=0;c<a.length;c++)f.push(b.data[a[c]]);return e[ensightenOptions.ns].when.resolve(f)}f=b.dataDefinitions[a]||{storage:{get:function(){}}};f=f.storage.get(f);b.data[a]=f;return e[ensightenOptions.ns].when.resolve(b.data[a])},set:function(a,f){if(d.utils.isArray(a))for(var c in a)b.data[a[c]]=
	f[c];else b.data[a]=f;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(d.utils.isArray(a))for(var f in a)delete b.data[a[f]];else delete b.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){b.data={};b.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(b.data)}}},normalizeInputArgs:function(a,b){var c={key:[],val:m},e;if(d.utils.isPlainObject(a))for(e in c.val=[],a)c.key.push(e),c.val.push(a[e]);
	else d.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},d={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},h=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=
	l;b.DataDefinitionException=l;b.checkForInvalidDataDefinitions=function(a){d.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a)),!0):!1};b.collectAvailableDataDefinitions=function(a){for(var f=[],c=0;c<a.length;c++){var n=parseInt(a[c],10),h=e[ensightenOptions.ns].dataDefinitions[n];if(null===h||h===m)if(h=d.storage.session.get({id:n}),null!==h&&h!==m)d.set(n,h),b.dataDefinitions[n]={id:n,
	load:"visitor",storage:d.storage.visitor,missingDDFromCache:!0},f.push(e[ensightenOptions.ns].data.get(""+n));else return e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Invalid data definition used: "+n)),{promises:[],isInvalid:!0};else f.push(e[ensightenOptions.ns].data.get(a[c]))}return{promises:f,isInvalid:!1}};b.getSync=function(a){function f(a){var b=a.extract||h,f=a.transform||k,g=!1,e=null,d=null;try{e=b()}catch(p){e=null,g=!0}try{d=f(e)}catch(r){d=null,g=!0}g&&c.push(a.id);
	return d}var c=[],h=function(){return document},k=function(a){return null!==a&&a!==m?a.toString():null},r=parseInt(a);a="string"===typeof a?a.split("."):[];var g={},p="";isNaN(r)?3==a.length&&(g=d.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):g=d.getDataDefinitionById(r);p=g.load&&g.load.match(/(session|visitor)/i)&&g.storage&&g.storage.get?g.storage.get(g):f(g);0<c.length&&e[ensightenOptions.ns].reportException(new b.DataDefinitionException(c,"Error resolving data definitions synchronously: "+
	c));return p};b.dataDefinitions={};b.dataDefinitionsBySourceCollName={};d.defineEngine=function(a,f){var c,d=["get","set","remove","clear","all"];b.engines[a]=f;if(!f.returnsPromise)for(c=0;c<d.length;c++){var h=d[c];f[h]=e[ensightenOptions.ns].when.lift(f[h])}};d.storage={instance:{set:function(a,b){},get:function(a){return b.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return b.data[a.id]}},session:{set:function(a,b){var c=d.storage.session.get({id:a}),h=new Date,k=h.getTime();h.setTime(k+
	18E5);null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:h.toGMTString()});c={expires:h.getTime(),value:b};e[ensightenOptions.ns].data.local.utils.set(a,c)},get:function(a){var b=e[ensightenOptions.ns].data.cookie.utils.get(a.id),c=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON,c=c||{},d,h=new Date,h=h.getTime();if(null===b){try{d=c.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(k){d=null}null!=d&&(d.expires=+d.expires,h<=d.expires?b=d.value:""==
	d.expires&&d.value!=m?b=d.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var c=d.storage.session.get({id:a});null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return d.storage.session.get(a)}}};d.getEngine=d.engine=function(a){return a?b.engines[a]||{get:h,set:h,remove:h,clear:h,all:h}:b.engines};d.all=function(a){return e[ensightenOptions.ns].data.engine(a||
	"memory").all()};d.get=function(a,f,c){f=f||"memory";c=c||{};-1<a.indexOf(",")&&(a=a.split(","));a=b.normalizeInputArgs(a);return c.wait?b.getWait(a.key,e[ensightenOptions.ns].data.engine(f),c):b.data&&b.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(f).get(a.key):b.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(f),c)};b.getWait=function(a,b,c){var h=+new Date,k=e[ensightenOptions.ns].when.defer(),r=function(){var e=b.get(a);if(-1===c.wait)return e;e.then(function(a){c.setCheck(a)?
	k.resolve(a):setTimeout(g,c.interval)},function(a){setTimeout(g,c.interval)})},g=function(){var a=+new Date-h;-1!==c.wait&&a<c.wait?r():k.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;d.utils.isArray(a)?c.setCheck=c.setCheck||function(a){for(var b=!0,c=0;c<a.length;c++)b=b&&!!a[c];return b}:c.setCheck=c.setCheck||function(a){return!!a};r();return k.promise};b.getWaitForKey=function(a,f,c){var d=e[ensightenOptions.ns].when.defer(),h=function(){if(b.data&&b.data.hasOwnProperty(a)){var g=
	f.get(a);if(-1===c.wait)return g;g.then(function(a){d.resolve(a)},function(a){d.reject(a)})}else setTimeout(k,c.interval)},k=function(){h()};c.interval=c.interval||100;c.wait=c.wait||1;h();return d.promise};d.set=function(a,f,c){var d=b.normalizeInputArgs(a,f);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(c||"memory").set(d.key,d.val)};d.remove=function(a,b){return e[ensightenOptions.ns].data.engine(b||"memory").remove(a)};d.clear=function(a){return e[ensightenOptions.ns].data.engine(a||
	"memory").clear()};d.define=function(a,f){f&&(a.name=f.id||f.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var c=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=d.storage[c.toLowerCase()]||
	d.storage.page;var h=a.extract||function(){return document},k=a.transform||function(a){return a},r=function(b,c){var d=[];d.push(a.persist.set(b,c));a.storage.set(a.id,c);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(b,c,a.collection);e[ensightenOptions.ns].when.all(d).then(function(a){g.resolve(a)},function(a){g.reject(a)})},g=e[ensightenOptions.ns].when.defer();a.trigger().then(function(){g.resolve(e[ensightenOptions.ns].when.reduce([h(),k,r],function(b,
	c,g,e){if(1==g)return c(b);2==g&&c(a.name,b)}))},function(a){g.reject(a)});b.dataDefinitions[a.id]=a;b.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+"."+a.dataDefName]=a;return g.promise};d.checkConditions=function(a){var f,c={lt:function(a,c){var g=+a,d=+c;return isNaN(g)||isNaN(d)?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+c)),!1):g<d},gt:function(a,c){var g=+a,d=+c;return isNaN(g)||
	isNaN(d)?(e[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+c)),!1):g>d},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==m||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(d){return!1}},starts:function(a,b,g){b=d.utils.escapeRegEx(b);return c.re(a,"^"+b,g)},ends:function(a,b,g){b=d.utils.escapeRegEx(b);return c.re(a,b+"$",g)},contains:function(a,
	b,g){b=d.utils.escapeRegEx(b);return c.re(a,".*"+b+".*",g)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=c.gt;c["is less than"]=c.lt;c.matches=c.re;for(f=0;f<a.values.length;f++){var h=(a.customComparator?a.customComparator[f]?a.customComparator[f]:c[a.comparators[f]]:c[a.comparators[f]])(a.values[f],a.compareTo[f],a.caseInsensitive?a.caseInsensitive[f]||!1:!1);a.not[f]&&(h=!h);if(!h)return!1}return!0};d.triggerPromise=function(a,b,c){c=c||5E3;var d=+new Date,h=
	e[ensightenOptions.ns].when.defer();(function(){var e=a();e!=b?h.resolve(e):+new Date-d<c?setTimeout(arguments.callee,200):h.reject("timed out")})();return h.promise};d.timeoutPromise=function(a,b){var c=e[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};d.delayTrigger=function(a){a=a||10;var b=e[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};d.delayUntilTrigger=
	function(a,b,c,d){c=c||null;d=d||200;var h=+new Date,k=e[ensightenOptions.ns].when.defer();(function(){var g=a();g!=b?k.resolve(g):c?+new Date-h<c?setTimeout(arguments.callee,d):k.reject("timed out"):setTimeout(arguments.callee,d)})();return k.promise};b.applyTrigger=function(a){var b=e[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};d.bottomOfBodyTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};d.afterEnsightenCompleteTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};
	d.afterElementsDownloadedTrigger=function(){return b.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};d.getAllDataDefinitionsOnCurrentPage=function(){return b.dataDefinitions};d.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return b.dataDefinitionsBySourceCollName};d.getDataDefinitionById=function(a){return b.dataDefinitions[a||-1]||{}};d.getDataDefinitionBySourceCollectionName=function(a,d,c){return b.dataDefinitionsBySourceCollName[""+a+"."+d+"."+c]||{}};d.getDataDefinitionByPercentSyntax=
	function(a){a=(""+a).split("_");return 1>a.length?{}:b.dataDefinitions[a[1]]||{}};d.resolve=function(a,f){var c=this,h=null;if(!b.checkForInvalidDataDefinitions(a))if(f)e[ensightenOptions.ns].bindDataDefinitionComplete(function(){var d=b.collectAvailableDataDefinitions(a);d.isInvalid||e[ensightenOptions.ns].when.all(d.promises).then(function(d){try{f.apply(c,d)}catch(g){e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+g))}},
	function(c){e[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+c))})});else{var h=[],k=a;d.utils.isArray(a)||(k=[a]);for(var l=0;l<k.length;l++)h.push(b.getSync(k[l]));return h=d.utils.isArray(a)?h:h[0]}};d.extract=function(a,b){var c="",d=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",d=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(c?b.split("#")[0]:d?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==
	e&&0==d)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var g=a.firstChild;if(!g)return null;for(var f=0,d=0!=d?d-1:d;g;){if(1==g.nodeType){if(g.tagName.toLowerCase()==e&&""!=c&&g.id==c||g.tagName.toLowerCase()==e&&f==d&&""==c)return g;g.tagName.toLowerCase()==e&&f++}g=g.nextSibling}},h=function(a,b){a=a.split("/");for(var c=d(b||document,a[1]),g=2;g<a.length;g++){if(null==c)return null;c=d(c,a[g])}return c},k=function(){for(var a=
	{},b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var g=b[c].name||b[c].getAttribute("property")||"";0!==g.length&&(a[g]=b[c].content)}return a}(),g=function(a){var b=k[a];if(b)return b;for(var b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var g=b[c].name||b[c].getAttribute("property")||"";if(a==g)return b[c].content}},p=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(e.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},t=function(a){return(val=
	(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=m(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},m=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=h(a);else try{b=eval(a)}catch(c){b=""}return b};try{return b?"meta"==b?c=g(a):"cookie"==b?c=t(a):"param"==b?c=p(a):"content"==b?c=l(a):"event"==b?c=m(a):"var"==b&&(c=e[a]):c=g(a)||t(a)||p(a)||l(a)||m(a)||e[a]||
	"",c||""}catch(q){return""}};if("undefined"==typeof k)var k={exports:{}};return d}(window);
	window[ensightenOptions.ns].data.defineEngine("store",function(){var e={},m=window,l=m.document,b,d,h=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};e.set=function(a,b){};e.get=function(a){};e.remove=function(a){};e.clear=function(){};try{if("localStorage"in m&&m.localStorage)b=m.localStorage,e.set=function(a,c){var d,e,f=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(h(a))for(d=0,e=a.length;d<e;d++)b.setItem(a[d],"string"===
	typeof c[d]?c[d]:f.stringify(c[d]));else b.setItem(a,"string"===typeof c?c:f.stringify(c))},e.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b.getItem(a[d]);return c}return b.getItem(a)},e.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)b.removeItem(a[c])}else b.removeItem(a)},e.clear=function(){b.clear()},e.all=function(){return b};else if("globalStorage"in m&&m.globalStorage)b=m.globalStorage[m.location.hostname],e.set=function(a,c){if(h(a)){var d,e;d=0;
	for(e=a.length;d<e;d++)b[a[d]]=c[d]}else b[a]=c},e.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b[a[d]]&&b[a[d]].value;return c}return b[a]&&b[a].value},e.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)delete b[a[c]]}else delete b[a]},e.clear=function(){for(var a in b)delete b[a]},e.all=function(){return b};else if(l.documentElement.addBehavior){var k=function(a){return a.replace(n,"___")},m=function(c){return function(){var d=Array.prototype.slice.call(arguments,
	0);d.unshift(b);a.appendChild(b);b.addBehavior("#default#userData");b.load("localStorage");d=c.apply(store,d);a.removeChild(b);return d}},a,f;try{f=new ActiveXObject("htmlfile"),f.open(),f.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>'),f.close(),a=f.w.frames[0].document,b=a.createElement("div")}catch(c){b=l.createElement("div"),a=l.body}var n=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g");e.set=m(function(a,b,c){if(h(b)){var d,f;d=0;for(f=b.length;d<f;d++){fixedKey=
	k(b[d]);if(void 0===c[d])return e.remove(fixedKey);a.setAttribute(fixedKey,c[d]);a.save("localStorage")}}else{fixedKey=k(b);if(void 0===c)return e.remove(fixedKey);a.setAttribute(fixedKey,c);a.save("localStorage")}});e.get=m(function(a,b){if(h(b)){var c={},d,e,f;e=0;for(f=b.length;e<f;e++)d=k(b[e]),c[b[e]]=a.getAttribute(d);return c}b=k(b);return a.getAttribute(b)});e.remove=m(function(a,b){if(h(b)){var c,d;c=0;for(d=b.length;c<d;c++)a.removeAttribute(k(b[c])),a.save("localStorage")}else b=k(b),a.removeAttribute(b),
	a.save("localStorage")});e.clear=m(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var c=0,d;d=b[c];c++)a.removeAttribute(d.name);a.save("localStorage")});e.all=m(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},d=0,e;e=b[d];++d){var f=k(e.name);c[e.name]=a.getAttribute(f)}return c})}}catch(w){}var r={};for(d in e)r[d]=e[d];r.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());r.set(a,"test");if("test"===r.get(a))return r.remove(a),
	!0}catch(b){}return!1};e.utils=r;return window[ensightenOptions.ns].data.local=e}());
	window[ensightenOptions.ns].data.defineEngine("cookie",function(e,m){var l=function(){return l.get.apply(l,arguments)},b=l.utils={isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(b){return Array.prototype.slice.call(b)},getKeys:Object.keys||function(b){var e=[],k="";for(k in b)b.hasOwnProperty(k)&&e.push(k);return e},escape:function(b){return String(b).replace(/[,;"\\=\s%]/g,
	function(b){return encodeURIComponent(b)})},retrieve:function(b,e){return null==b?e:b},getAllCookies:function(){if(""===e.cookie)return{};for(var b=e.cookie.split("; "),h={},k=0,a=b.length;k<a;k++){var f=b[k].split("=");h[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return h},set:function(d,h,k){k=k||-1;if(b.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&l.set(a,d[a],h);else if(b.isArray(d)){var f;a=0;for(f=d.length;a<f;a++)l.set(d[a],h[a],k)}else{a=k.expires!==m?k.expires:l.defaults.expires||
	"";"number"===typeof a&&(a=new Date(a));a=b.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():b.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;f=(f=k.path||l.defaults.path)?";path="+f:"";var c=k.domain||l.defaults.domain,c=c?";domain="+c:"";k=k.secure||l.defaults.secure?";secure":"";e.cookie=b.escape(d)+"="+b.escape(h)+a+f+c+k}},get:function(d,e){e=e||m;var k=b.getAllCookies();if(b.isArray(d)){for(var a={},f=0,c=d.length;f<c;f++)a[d[f]]=b.retrieve(k[d[f]],
	e),a[d[f]]===m&&(a[d[f]]=null);return a}a=b.retrieve(k[d],e);return a===m?null:a},getGMTString:function(b){var e=new Date;e.setTime(e.getTime()+864E5*b);return e.toGMTString()}};l.defaults={path:"/",expires:b.getGMTString(90)};l.set=function(d,e){b.set(d,e)};l.remove=function(d){d=b.isArray(d)?d:b.toArray(arguments);for(var e=0,k=d.length;e<k;e++)b.set(d[e],"",{expires:-1})};l.clear=function(){return l.remove(b.getKeys(b.getAllCookies()))};l.get=function(d,e){return b.get(d,e)};l.all=function(){return b.getAllCookies()};
	l.utils=b;return window[ensightenOptions.ns].data.cookie=l}(document));
}
		Bootstrapper.dataDefinitionIds = [15623];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=
path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId;i>0;i--)if(!~p[i].indexOf("#")&&!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};Bootstrapper.dataManager=function(){var _private=
{data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];return _private.data},getDataElement:function(i,e){if(typeof this.data[i]=="undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod==
"string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=
d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,
o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.eventManager=function(){var _private={events:{},
pushTrack:function(name,fn){if(typeof name!="string")return false;this.events[name]=this.events[name]||[];if(typeof fn=="function")this.events[name].push(fn);return true},callTrack:function(name){if(typeof name!="string")return false;var l=_private.events[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)},bind:function(layer,name,fn){var node=Bootstrapper.dataManager.getDataElement(layer,name),event=name.split("#")[1],name=name.split("#")[0],bound=typeof this.events[name]!=
"undefined"?true:false;if(typeof node.nodeName!="undefined"){this.pushTrack(name,fn);if(!bound)if((event=="onelementvisible"||event=="onelementexists")&&typeof Bootstrapper.propertyWatcher!="undefined"){Bootstrapper.eventManager.watch=Bootstrapper.eventManager.watch||{};if(~event.indexOf("vis")){Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(n!="none")Bootstrapper.eventManager.track(name,
this)}}else{Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(o=="undefined")Bootstrapper.eventManager.track(name,this)}}}else Bootstrapper.unobtrusiveAddEvent(node,event,function(){Bootstrapper.eventManager.track(name,this)})}else if(typeof node=="object"&&typeof node.length!="undefined"){this.pushTrack(name,fn);if(!bound)for(i=0,l=node.length;i<l;i++)Bootstrapper.unobtrusiveAddEvent(node[i],
event,function(){Bootstrapper.eventManager.track(name,this)})}},debug:function(name,ref){if(~window.location.search.indexOf("ensightenDebug"))console.log("::eventManager - Name:"+name+" ::eventManager - Scope:"+ref)}},_public={bindTracker:function(layer,name,fn){return _private.bind(layer,name,fn)},getEvent:function(name){return _private.events[name]},getAll:function(){return _private.events},track:function(name,ref){var $this=ref||window;_private.debug(name,$this);return _private.callTrack.call($this,
name)}};return _public}();Bootstrapper.dataManager.map=function(){var _private={gD:{},mD:function(g){var e=window.document.getElementsByTagName("META")||[];for(var m=0,l=e.length;m<l;m++){var n=e[m].name||e[m].getAttribute("property")||"";if(n==g)return e[m].content}},gP:function(p){var s;return(s=(new RegExp("\x26"+p+"\x3d([^\x26]*)")).exec(window.location.search.replace(/^\?/,"\x26")))?s[0].split("\x3d")[1]:""},gC:function(c){var v;return(v=(new RegExp("^"+c+"\x3d.*|;\\s*"+c+"\x3d.*")).exec(window.document.cookie))?
v[0].split("\x3d")[1].split(";")[0]:""},gT:function(g){try{return this.mD(g)||this.gC(g)||this.gP(g)||window[g]||""}catch(e){return""}},dF:function(n,d){this.gD={};for(i in d){var val=typeof d[i]=="string"?this.gT(d[i]):d[i]();if(~window.location.href.indexOf("ensightenDebug"))console.log(i+": "+val);this.gD[i]={name:i,get:'(function(){return("'+val+'")})()'}}Bootstrapper.dataManager.push({name:n,id:n,data:this.gD})}},_public={define:function(n,d){_private.dF(n,d)},get:function(g){return _private.gT(g)}};
return _public}();window.$data=function(n,d){try{return Bootstrapper.dataManager.getDataElement(n,d)}catch(e){return""}};window.$getData=function(d){return Bootstrapper.dataManager.map.get(d)};Bootstrapper.dataManager.dataImport=function(O,N,T){var DM=Bootstrapper.dataManager;if(typeof DM.getObj()[N]=="undefined")DM.push({name:N,id:N,data:{}});for(i in O)if(T!="simple"&&typeof O[i]=="object"){DM.dataImport(O[i],T=="flattened"?N:i,T);console.log(T)}else if(typeof O[i]!="object"||O[i]==null)try{eval('Bootstrapper.dataManager.addDataElement(N,i,{name:i,get:function(){try{return "'+
O[i]+"\"}catch(e){return'error'}}})")}catch(e){}};Bootstrapper.targetingExtension=function(){var o=ensightenOptions,DL=typeof Bootstrapper.dataManager!="undefined"?Bootstrapper.dataManager.getData():false;if(DL)delete DL["_d"];if(~document.cookie.indexOf("VTP:enabled")){if(!DL)DL={};DL["ensightenVT"]=1}if(typeof Bootstrapper.getExtraParams!="undefined"){var p=Bootstrapper.getExtraParams();if(typeof p=="object"){if(!DL)DL={};for(i in p)DL[i]=p[i]}}Bootstrapper.insertScript("//"+(typeof ensightenOptions.serverComponentLocation!=
"undefined"?ensightenOptions.serverComponentLocation:o.nexus+"/"+o.client+"/serverComponent.php"),false,DL)};if(typeof Bootstrapper._getServerComponent!="undefined")Bootstrapper._getServerComponent=Bootstrapper.targetingExtension;else Bootstrapper.getServerComponent=Bootstrapper.targetingExtension;Bootstrapper.propertyWatcher=function(f){var g={watchers:[]},p={};g.options=f||{};g.options.interval=g.options.interval||50;g.Watcher=function(c,d){var e={};e.propertyFn=c;e.lastValue=undefined;e.options=
d;e.change=function(a,b){};return e};g.doChecks=function(){for(var i=0;i<g.watchers.length;i++){var w=g.watchers[i],p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}g.resetTimer()};g.resetTimer=function(){window.setTimeout(function(){g.doChecks()},g.options.interval)};g.addWatcher=function(a,b){var w=g.Watcher(a,b);g.watchers.push(w);return w};p={create:g.addWatcher};g.doChecks();return p}();Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["DM"]=
this.deploymentId;window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<
d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],
initialized:!1,disabled:~window.location.search.indexOf("ensTools\x3ddisable"),cloak:!1,pageSpecificCompletion:!0,DOMParsed:!0,content:{map:{},target:function(o){if(o instanceof Array)for(var i=0,l=o.length;i<l;i++)this.add(o[i]);else this.add(o)},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u)){this.map[o.x]=o;this.map[o.x].t="map"}}else{this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.cloak)Bootstrapper.MVT.cover()}},
getTimeout:function(){return 5},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");_log(h.tests.slice());Bootstrapper.MVT.initialized=!0;if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},cover:function(){this.cloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");
if(this.pageSpecificCompletion)Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("complete")});if(this.DOMParsed)Bootstrapper.bindDOMParsed(function(){Bootstrapper.MVT.uncover("parsed")});Bootstrapper.bindDOMLoaded(function(){Bootstrapper.MVT.uncover("loaded")});setTimeout(function(){Bootstrapper.MVT.uncover("timeout")},7E3)},uncover:function(l){if(this.cloak)if(this.delCSS(this.cloak)){this.cloak=!1;_log("*** Cloak:"+l)}},show:function(a){a.style.display=a.style.oldDisplay||
"block";a.style.visibility="visible"},done:function(){var a=this.hidden,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i])},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else _log("*** MVT:stop - not found \x3d "+o.x)},push:function(o){if(this.disabled)return;
if(typeof o=="object"){_log("*** MVT:push");_log(o);if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x){var d=document,s=d.createElement("style");if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);
s.styleSheet.cssText=x}else{s=d.createElement("style");s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,
a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);try{f.oldStyle=f.style.display,f.style.display="none",b.style.display=b.oldStyle}catch(g){}b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{if(b&&b.style)b.style.display=b.oldStyle||"block";_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,
c[0]):h.split(c,b)}};return i}();Bootstrapper._getServerComponent=Bootstrapper.getServerComponent;Bootstrapper.getServerComponent=function(){Bootstrapper.MVT.init();Bootstrapper._getServerComponent.apply(Bootstrapper,arguments)};Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");
setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p==
"replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p==
"after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=
this.deploymentId;Bootstrapper.dataManager.pushObject=function(obj,id,name){Bootstrapper.dataManager.push({name:name||id,id:id,data:{}});for(var k in obj)if(obj[k]&&typeof obj[k]!=="function")Bootstrapper.dataManager.addDataElement(id,k,{name:k,get:function(o,key){return function(){return o[key]}}(obj,k)})}},379140,238638);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return dojo.cookie("MBPseg")},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"MBPSeg Cookie",collection:"Global",source:"Manage",priv:"false"},{id:"15623"})},15623)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.toAscii=function(cmChar){var symbols=" !\"#$%\x26'()*+'-./0123456789:;\x3c\x3d\x3e?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";var loc;loc=symbols.indexOf(cmChar);if(loc>-1)return 32+loc;return 0};Bootstrapper.dec2Hex=function(Decimal){var hexChars="0123456789ABCDEF";var a=Decimal%16;var b=(Decimal-a)/16;hex=""+hexChars.charAt(b)+hexChars.charAt(a);
L=hexChars.charAt(a);H=hexChars.charAt(b);return hex};Bootstrapper.getParameterByName=function(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?\x26]"+name+"\x3d([^\x26#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "))};Bootstrapper.cleanProductNames=function(strHTML){var html=strHTML;try{var strMarkedUp=html.replace(/&lt;([^&]*)&gt;/g,"\x3c$1\x3e");html=strMarkedUp.replace(/<[^>]*>/g,"");html=
html.replace("NEW\x26nbsp;","");html=html.replace("\x26nbsp;"," ");html=html.replace(/&(?:[a-z]+|#\d+);/g,"");html=html.replace("'","");html=html.replace(/[^\x00-\x7F]/g,"");html=dojo.trim(html)}catch(e){console.error("Unable to strip HTML tags.")}return html};Bootstrapper.cleanUpConnects=function(connectsArray){dojo.forEach(connectsArray,dojo.disconnect)}},864989,286336);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.dataManager.pushObject(tmParams,"tmParams_edl","TM Params EDL");Bootstrapper.dataManager.addDataElement("tmParams_edl","site",{name:"Site data",get:function(){var site={};var u=window.location.hostname;if(u.indexOf("harryanddavid.com")>=0){site.domain="www.harryanddavid.com";site.context="h"}if(u.indexOf("wolfermans.com")>=0){site.domain="www.wolfermans.com";
site.context="w"}if(u.indexOf("wolf.atst.bcohome.bco.com")>=0){site.domain="wolf.atst.bcohome.bco.com";site.context="w"}if(u.indexOf("hand.atst.bcohome.bco.com")>=0){site.domain="hand.atst.bcohome.bco.com";site.context="h"}return site}});Bootstrapper.dataManager.addDataElement("tmParams_edl","ga_accountID",{name:"Google Analytics Account ID",get:function(){var u=window.location.hostname;var uaid="ua-xxxxxxxx-x";if(u.indexOf("harryanddavid.com")>=0)uaid="UA-43044033-5";if(u.indexOf("wolfermans.com")>=
0)uaid="UA-43044033-3";if(u.indexOf("wolf.atst.bcohome.bco.com")>=0)uaid="UA-43044033-8";if(u.indexOf("hand.atst.bcohome.bco.com")>=0)uaid="UA-43044033-7";return uaid}});try{Bootstrapper.dataManager.addDataElement("tmParams_edl","userId",{name:"User ID",get:function(){var a;if(typeof becUser!=="undefined"&&becUser!=="")if(becUser.customerType){var customerType=becUser.customerType;if(customerType=="G"){var userId=null;var userPhone1=typeof becUser.phoneNumber!=="undefined"&&becUser.phoneNumber!==
""?becUser.phoneNumber:"";var firstName=typeof becUser.firstName!=="undefined"&&becUser.firstName!==""?becUser.firstName:"";if(userPhone1.length>0)userId=firstName+userPhone1;else userId=firstName+becUser.userId;var tmpCustId=userId;var tmpDecCustId="";var tmpCustIdLength=tmpCustId.length;userId=userId=="-1002"?userId:"";i=0;while(tmpCustIdLength>0){tmpDecCustId=Bootstrapper.toAscii(tmpCustId.charAt(i));userId=userId+Bootstrapper.dec2Hex(tmpDecCustId);i=i+1;tmpCustIdLength=tmpCustIdLength-1}a=userId}else a=
becUser.userId}return a}})}catch(e){console.error("Failed to capture UserID.",e)}try{Bootstrapper.dataManager.addDataElement("tmParams_edl","customerType",{name:"Customer Type",get:function(){var a;if(typeof becUser!=="undefined"&&becUser!=="")a=becUser.customerType?becUser.customerType:"NA";return a}})}catch(e){console.error("Failed to capture customer type.",e)}Bootstrapper.dataManager.addDataElement("tmParams_edl","ga_domainName",{name:"Google Analytics Domain Name",get:function(){var u=window.location.hostname;
var gaHost="atst.bcohome.bco.com";if(u.indexOf("harryanddavid.com")>=0)gaHost="harryanddavid.com";else if(u.indexOf("wolfermans.com")>=0)gaHost="wolfermans.com";return gaHost}});Bootstrapper.dataManager.addDataElement("tmParams_edl","deviceType",{name:"Device Type",get:function(){var a=Bootstrapper.dataManager.getDataElement("tmParams_edl","isMobile_int");if(a==="0")a="Desktop";else if(a==="1")a="Mobile";else if(a==="2")a="Tablet";else a="no value provided";return a}});Bootstrapper.dataManager.addDataElement("tmParams_edl",
"shoppingCartItems",{name:"Cart Items",get:function(){var cItems=Bootstrapper.dataManager.getDataElement("tmParams_edl","cartItems");var a=cItems.split("|");return a}});Bootstrapper.dataManager.addDataElement("tmParams_edl","4citeAccountID",{name:"4Cite Account ID (TITLE_CID)",get:function(){var u=window.location.hostname;var TITLE_CID="XXXX_XXXXX";if(u.indexOf("harryanddavid.com")>=0)TITLE_CID="0145_03634";if(u.indexOf("wolfermans.com")>=0)TITLE_CID="0145_03635";if(u.indexOf("wolf.atst.bcohome.bco.com")>=
0)TITLE_CID="0145_03635";if(u.indexOf("hand.atst.bcohome.bco.com")>=0)TITLE_CID="0145_03634";return TITLE_CID}});Bootstrapper.dataManager.addDataElement("tmParams_edl","categoryPath",{name:"Category Path",get:function(){var categoryPath="";var category=Bootstrapper.dataManager.getDataElement("tmParams_edl","category");if(category){var l1=category.level1!==""?category.level1:null;var l2=category.level2!==""?category.level2:null;var l3=category.level3!==""?category.level3:null;if(l1&&!l2&&!l3)categoryPath=
l1;else if(l1&&l2&&!l3)categoryPath=l1+"/"+l2;else if(l1&&l2&&l3)categoryPath=l1+"/"+l2+"/"+l3;else if(!l1&&!l2&&l3)categoryPath=l3;else if(l1&&!l2&&l3)categoryPath=l1+"/"+l3}return categoryPath}});Bootstrapper.dataManager.addDataElement("tmParams_edl","sfPIClientInfo",{name:"Predictive Intelligence Client ID",get:function(){var u=window.location.hostname;var sfPIClientInfo={"clientName":"6368700","client":"6368700"};if(u.indexOf("harryanddavid.com")>=0){sfPIClientInfo.clientName="6368700";sfPIClientInfo.client=
"6368700"}if(u.indexOf("wolfermans.com")>=0){sfPIClientInfo.clientName="6368704";sfPIClientInfo.client="6368704"}if(u.indexOf("wolf.atst.bcohome.bco.com")>=0||u.indexOf("wolfauth")>=0){sfPIClientInfo.clientName="6368704";sfPIClientInfo.client="6368704"}if(u.indexOf("hand.atst.bcohome.bco.com")>=0||u.indexOf("handauth")>=0){sfPIClientInfo.clientName="6368700";sfPIClientInfo.client="6368700"}return sfPIClientInfo}});Bootstrapper.dataManager.addDataElement("tmParams_edl","searchTerm",{name:"Search Term",
get:function(){var searchTerm="";var pathName=window.location.pathname;if(pathName.indexOf("search/go")>-1)searchTerm=Bootstrapper.getParameterByName("w");return searchTerm}});Bootstrapper.dataManager.addDataElement("tmParams_edl","sfcUserId",{name:"Salesforce Collect User ID",get:function(){var userId="";if(typeof becUser!=="undefined"&&becUser.customerType==="R")userId=becUser.userId;return userId}});Bootstrapper.dataManager.addDataElement("tmParams_edl","RKG",{name:"RKG",get:function(){var u=window.location.hostname;
var rkgObject={"mid":"harryanddavid"};if(u.indexOf("harryanddavid.com")>=0)rkgObject.mid="harryanddavid";if(u.indexOf("hand.atst.bcohome.bco.com")>=0)rkgObject.mid="harryanddavidTest";if(u.indexOf("wolfermans.com")>=0)rkgObject.mid="wolfermans";if(u.indexOf("wolf.atst.bcohome.bco.com")>=0)rkgObject.mid="wolfermansTest";return rkgObject}});Bootstrapper.dataManager.addDataElement("tmParams_edl","tmsPersistentCookie",{name:"TMS Persistent Cookie",get:function(){var tmsCookie=null;if(dojo.cookie("BEC_TMS_PERSISTENT"))tmsCookie=
dojo.cookie("BEC_TMS_PERSISTENT");return tmsCookie}})},1128775,[379140,864989],238645,[238638,286336]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(typeof window.tmParams!="undefined"&&typeof window.tmParams.pageType!="undefined"){var a=window.tmParams.pageType;if(/^$/i.test(a))a="blank";Bootstrapper.getExtraParams=function(){var dl=Bootstrapper.dataManager?Bootstrapper.dataManager.getData():{};var b={"EEP_pageType":a,"EEP_deviceType":dl.deviceType};return b}}},379139,240511);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var BEC_TMS_PERSISTENT_COOKIE_LENGTH=2555;var BEC_TMS_PERSISTENT_COOKIE_NAME="BEC_TMS_PERSISTENT";if(!dojo.cookie(BEC_TMS_PERSISTENT_COOKIE_NAME)){var uuid=generateUUID();if(uuid){var cookieParams={"expires":BEC_TMS_PERSISTENT_COOKIE_LENGTH,"path":"/"};dojo.cookie(BEC_TMS_PERSISTENT_COOKIE_NAME,uuid,cookieParams)}}function generateUUID(){var d=(new Date).getTime();if(window.performance&&
typeof window.performance.now==="function")d+=performance.now();var uuid="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=(d+Math.random()*16)%16|0;d=Math.floor(d/16);return(c=="x"?r:r&3|8).toString(16)});return uuid}},1113468,352671);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var a=window.location.hostname;if(a==="www.wolfermans.com"||a==="wolf.atst.bcohome.bco.com")document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/harryanddavid/wolfermans/js/mmcore.js"\x3e\x3c/'+"script\x3e");if(a==="www.harryanddavid.com"||a==="hand.atst.bcohome.bco.com")document.write('\x3cscript type\x3d"text/javascript" src\x3d"//service.maxymiser.net/cdn/harryanddavid/js/mmcore.js"\x3e\x3c/'+
"script\x3e")},712909,249925);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();