(function(){if(window.dT_)return;var f=!0,h=null,m=!1;function n(){try{return window.performance.timing.navigationStart+Math.floor(window.performance.now())}catch(a){return(new Date).getTime()}}var aa=n(),p=window,s=p.setTimeout,ba=p.XMLHttpRequest,ca=p.ActiveXObject,t=p.parent,u={version:[6,2,1,"1027"]};u.version[3]=parseInt(u.version[3]);p.dT_||(document.dT_=window.dT_,p.dT_=u);
function da(){if("string"!==typeof document.title){var a=document.getElementsByTagName("title")[0];return a.innerText||a.textContent}return document.title}function v(a,b){var c=-1;b&&(c=a.indexOf(b));return c}function ea(){return ba?new ba:ca?new ca("MSXML2.XMLHTTP.3.0"):window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("MSXML2.XMLHTTP.3.0")}function w(a,b){return parseInt(a,b||10)}
function fa(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=v(e[b],"\x3d"),d=e[b].substring(0,c),c=e[b].substring(c+1),d=d.replace(/^\s+|\s+$/g,""),d===a)return"DTSA"===a.toUpperCase()?decodeURIComponent(c):c;return""}function ga(a){document.cookie=a+'\x3d"";path\x3d/'+(x.domain?";domain\x3d"+x.domain:"")+"; expires\x3dThu, 01-Jan-70 00:00:01 GMT;"}
function ha(a,b){b||0==b?(b="DTSA"===a.toUpperCase()?ia(b):b,document.cookie=a+"\x3d"+b+";path\x3d/"+(x.domain?";domain\x3d"+x.domain:"")):ga(a)}function y(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}u.dC=ga;u.io=v;u.sC=ha;u.gC=fa;u.gx=ea;u.st=function(a,b){return s(a,b)};u.nw=n;u.pn=w;var z=[],A=navigator.userAgent;
try{var ja=/Firefox[\/\s](\d+\.\d+)/,ka=/(iPod|iPhone|iPad)/,la=/AppleWebKit/;if(0<=v(A,"MSIE"))z.ie=w(A.substr(A.lastIndexOf("MSIE")+5,3));else if(0<=v(A,"Trident"))0<=v(A,"rv:")?z.ie=w(A.substr(A.lastIndexOf("rv:")+3,2)):0<=v(A,"rv ")&&(z.ie=w(A.substr(A.lastIndexOf("rv ")+3,2)));else if(0<=v(A,"Android"))z.ab=parseFloat(A.substr(v(A,"Android")+8,1));else if(A.match(ka)&&A.match(la)){var ma=/Version\/([0-9]*\.[0-9]*)/;A.match(ma)||(ma=/OS ([0-9]*_[0-9]*)/);z.msf=parseFloat(A.match(ma)[1])}else if(("Safari"===
navigator.appName||-1<v(A,"Safari"))&&-1===v(A,"Chrom"))z.sf=w(A.substr(A.lastIndexOf("Version/")+8,1));else if(p.opera)z.op=w(p.opera.version().split(".")[0]);else if(0<=v(A,"OPR/"))z.op=w(A.match(/OPR\/([0-9]*\.[0-9]*)/)[1]);else if(ja.test(A)){var na=w(A.match(ja)[1]);z.ff=-1===na?0:na}else{var oa=v(A,"Chrom");-1<oa&&(z.ch=w(A.substring(oa+7,oa+9)))}}catch(pa){}u.gBI=function(){return z};u.hyb=function(){return 0===v(document.location.href,"file")};
var x={reportUrl:"dynaTraceMonitor",n:"",csu:"dtagent",domainOverride:m},qa=document.getElementsByTagName("script"),sa=ra(qa);
if(0<sa)for(var ta,ua=sa-1;0<=ua;ua--)if(ta=qa[ua],ta.attributes){var va=ta.attributes.getNamedItem("data-dtconfig");if(va){var wa=ta.src,xa=va.value;if(wa){var ya=/([a-zA-Z]*)[0-9]{0,3}_[a-zA-Z_0-9]*_[0-9]+/g.exec(wa);if(ya&&ya.length){var za=ya[0];x.csu=ya[1];x.featureHash=za.split("_")[1];x.dtVersion=u.version[0]+""+u.version[1]}}if(xa)for(var Aa=xa.split("|"),Ba=0;Ba<Aa.length;Ba++){var Ca=v(Aa[Ba],"\x3d");-1===Ca?x[Aa[Ba]]="1":x[Aa[Ba].substring(0,Ca)]=Aa[Ba].substring(Ca+1,Aa[Ba].length)}break}}
u.gAN=function(){return x.csu};u.smbi=function(a){var b=p.dT_;if(b.ism(a)&&-1===v(b.iMod(),a))return b.iMod(a),f;b.ism(a)&&p.console&&p.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return m};u.isc=function(a){var b;if("object"==typeof a){b=[6,2,0,0];for(var c=0;c<b.length;c++){if(a[c]<b[c])return m;if(a[c]>b[c])break}return f}return a&&383<=a};u.cfg=function(a){return x[a]};u.ism=function(a){return!a||1!==a.length||"undefined"===typeof x.featureHash?m:-1!==v(x.featureHash,a)};
u.iMod=function(a){a&&(x.n+=a);return x.n};var Da="\t\n\r";function Ea(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):h}function Fa(a,b){if(a.indexOf)return a.indexOf(b);for(var c=a.length;c--;)if(a[c]===b)return c;return-1}var B=[];function C(a,b,c){a.addEventListener?a.addEventListener(b,c,f):a.attachEvent&&a.attachEvent("on"+b,c);for(var d=m,e=B.length;0<=--e;){var g=B[e];if(g.object===a&&g.event===b&&g.m===c){d=f;break}}d||y(B,{object:a,event:b,m:c})}
function Ga(a,b,c){for(var d=B.length;0<=--d;){var e=B[d];if(e.object===a&&e.event===b&&e.m===c){B.splice(d,1);break}}a.removeEventListener?a.removeEventListener(b,c,f):a.detachEvent&&a.detachEvent("on"+b,c)}function Ha(a){try{var b=a.tagUrn;return b&&-1!==v(b,"schemas-microsoft-com:vml")}catch(c){return f}}function Ia(a){var b=0;if(a)for(var c=a.length,d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}function Ja(a,b){try{p.sessionStorage[a]=b}catch(c){ha(a,b)}}
function Ka(a){try{if(p.sessionStorage)return p.sessionStorage[a]}catch(b){}return fa(a)}var La={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Oa={"^":"^^","|":"^p",",":"^c",";":"^s"};function ia(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=La[d];e?y(b,e):y(b,d)}return b.join("")}function D(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Oa[d];e?y(b,e):y(b,d)}return b.join("")}
function ra(a){var b=a.length;if("number"===typeof b)a=b;else{for(var b=0,c=2048;a[c-1];)b=c,c+=c;for(var d=7;1<c-b;)d=(c+b)/2,a[d-1]?b=d:c=d;a=a[d]?c:b}return a}function Pa(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c),e=x.spc;e||(e="");e+=Da;-1===v(e,d)&&y(b,d)}a=b.join("")}return a}function Qa(){var a=document.location.href,b=v(a,"#");0<=b&&(a=a.substr(0,b));return a}function Ra(a,b){a=Math.floor(a);(b||Sa)&&a&&ha("dtLatC",a)}
function Ta(){return p.performance&&p.performance.timing&&(!z.ff||9<z.ff)?p.performance:h}var Ua={};function Va(a,b,c,d){if(Object.defineProperty&&(!z.ie||8<z.ie)){Ua[b]=a[b];var e=function(c){Ua[b]=c;d&&d.apply(a,[c]);return Ua[b]};try{Object.defineProperty(a,b,{get:function(){return c?c.apply(a,h):Ua[b]},set:e,configurable:f})}catch(g){}}}
function Wa(a,b){if(a[b]&&Object.defineProperty&&(!z.ie||8<z.ie)){var c=a[b];try{delete a[b],Ua[b]=h,a[b]=c}catch(d){Object.defineProperty(a,b,{get:function(){return Ua[b]},configurable:f})}}}function Xa(a){var b=document.createElement("a");b.href=a;return b.cloneNode(f).href}
function Ya(a){try{var b=window;if(!b.location)return a;var c=b.location,d=c.origin;if(!d){if(!c.protocol||!c.host)return a;d=c.protocol+"//"+c.host}var e=Xa(a);return e.substr(0,d.length+1).toLowerCase()===(d+"/").toLowerCase()?e.substr(d.length):e}catch(g){return a}}u.tau=Xa;u.icr=function(a){return(0==v(a,"http")||0==v(a,"//"))&&v(location.href,location.host)!=v(a,location.host)};u.aIOf=Fa;u.ael=C;u.rel=Ga;u.lv=Ka;u.sv=Ja;u.gh=function(a){return!a||-1===a.indexOf("://")?h:a.split("/")[2].split(":")[0].toLowerCase()};
u.cvs=function(a,b,c,d){if(x.ffi)return f;for(var e=m,g=e,k=e,l=0;l<a.length&&(!e||!g);l++)a[l]=a[l].split("."),e=a[l][0]==b,g=a[l][1]==c,!k&&e&&(k=f);a=e&&g||k;if(!e||!g)k?Za(d+" version ("+b+"."+c+") official not supported. Instrumentation active nonetheless, because major version is supported."):Za(d+" not instrumented because version ("+b+"."+c+") not supported.");return a};u.esc=ia;u.aesc=D;u.rsc=Pa;u.tpesc=function(a){a=a.replace(/_/g,"_5F").replace(/%/g,"_25");return D(a)};u.ulc=Ra;u.gP=Ta;
u.apl=Va;u.rpl=Wa;u.dbg=function(a){ha("dtUseDebugAgent",a)};u.dbc=function(a){ha("dt_dbg_console",a)};u.gEL=ra;var $a=6E8,ab="dtPC",bb="dtCookie",F=n()%$a+"_"+w(1E3*Math.random());u.c=F;function cb(){var a=fa(ab),b=[];if(a&&"-"!==a)for(var a=a.split("p"),c=0;c<a.length;c++){var d=a[c].split("h");if(2===d.length&&d[0]&&d[1]){var e=d[0],g=w(e.split("_")[0]),k=n()%$a;k<g&&(k+=$a);g+9E5>k&&y(b,{c:e,b:d[1]})}}return b}
function db(){var a=cb();if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].c!==F&&y(b,a[c]);eb(b)}}function eb(a){var b="";if(a){for(var b=[],c=0;c<a.length;c++)0<c&&0<b.length&&y(b,"p"),y(b,a[c].c),y(b,"h"),y(b,a[c].b);b=b.join("")}b||(b="-");ha(ab,b)}u.gFId=function(){return F};u.gDtc=function(){var a=fa(bb);if(a){var b=a.indexOf("|");-1!==b&&(a=a.substring(0,b))}return a};u.gPAH=function(a){a=F+"h"+u.esc(a);var b=fa(ab);return b&&0<=v(b,a)&&!u.hyb()?h:a};u.g=h;u.o=h;u.F=0;var fb=h,gb,hb,ib={};
function jb(){var a=t.dT_.version,b=u.version;if("string"===typeof a)return a===b;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return m;return f}try{t&&(t!==self&&t.dT_&&jb())&&(hb=t.dT_,fb=t.dT_.tdto())}catch(kb){}fb?(u.g=fb.g,u.o=fb.o,gb=hb.c,hb.F++):(u.g=F,u.o=da());function lb(){try{for(var a=t;a&&a!==self;){if(a.dT_)return a.dT_.tdto();a=a!==a.parent?a.parent:m}}catch(b){}return u}u.tp=function(){return!fb};u.tdto=lb;u.aFU=function(a){a=D(a);ib[a]||(ib[a]="1")};u.iRO=function(a){return"1"===ib[a]};
function mb(a,b,c,d){function e(a){var c=n()-d;nb(b)||Ra(c/2);for(var c=a&&a.split("|"),e=1;e<c.length;e++){var q=c[e].split("\x3d");if("dtCookie"==q[0])ha("dtCookie",decodeURIComponent(q[1]));else if("name"==q[0])try{p.localStorage&&p.localStorage.setItem(x.csu+"_"+x.app+"_Store",a)}catch(r){}else"enabled"==q[0]&&"false"==q[1]&&(Ja("dtDisabled",f),u.disabled=f)}}"onreadystatechange"in a||(a.onload=function(){e(a.responseText)});a.onreadystatechange=function(){a&&4==a.readyState&&(200==a.status?e(a.responseText):
ob&&z.sf&&pb.push({path:b,data:c}),a=h)}}function qb(a,b,c,d,e){for(var g=3,k=0;0<g;)try{var l,q=x.cors,r;if(q){var E=ea();"withCredentials"in E||(E=window.XDomainRequest?new XDomainRequest:h);r=E}else r=ea();l=r;if(!l)break;k=n();a&&a(l,b,d,k);"onreadystatechange"in l?l.open("POST",b,c):l.open("POST",b);"setRequestHeader"in l&&(l.setRequestHeader("Content-Type","text/plain;charset\x3dUTF-8"),e&&!q&&l.setRequestHeader("x-dtreferer",e));l.send(d);g=0}catch(I){g--}}
function rb(a,b){try{x.markSendBeacon&&(a+=(0<=v(a,"?")?"\x26":"?")+"VIASENDBEACON\x3d1"),navigator.sendBeacon(a,b||"")}catch(c){}}var sb=navigator&&"sendBeacon"in navigator;function tb(a){return sb&&!x.app&&!x.cors&&!x.dsndb&&!x.spl&&!a}var H=h,ub=[],vb=m,wb,yb=f,zb=m,Ab,Bb,pb=[];function Cb(){var a=this;a.f=[];a.a=function(b,c){y(a.f,[b,c])}}function Db(a,b,c){a=Eb(a,b,m);H&&Fb(m,c,a)}
function Eb(a,b,c){var d="",e=h;if(a){e="";Gb=0;var g=m;b="";for(var k in J)if(J.hasOwnProperty(k))if(d=J[k],Hb(d))g||(g=f,Za("Maximum open actions exceeded configured amount of "+(x.moa||30)+", dropping action "+d));else{var e=e?e+",":e,l=Ib(J[k],m,m,f);l&&!b&&(b=d.j());e+=l}}else if(e="",k=K.length,b&&(J=[]),b="",0<k){for(d=0;d<k;d++)if((l=Ib(K[d],f,c,m))&&0<l.length)b||(b=K[d].j()),"_load_"==K[d].type&&(Sa=f,L&&(e=L.B?"d|"+L.b+"|"+L.name+"|"+L.type+"|"+L.info+"|"+L.c+"|"+L.start+"|"+L.location+
"|"+L.title:"s|"+L.b+"|"+L.name+"|"+L.type+"|"+L.info+"|"+L.c+"|"+L.start,L=h)),0<e.length&&(e+=","),e+=l;K=[];for(g in J)J.hasOwnProperty(g)&&y(K,J[g])}e={actions:e,referer:b};d=e.actions;e=e.referer;H=h;if(0<d.length){H=new Cb;H.a("a",ia(d));H.a("v",x.dtVersion);H.a("fId",F);a&&H.a("PV",1);u.g!==F&&H.a("pId",u.g);gb&&H.a("pFId",gb);H.a("rId",x.rid);H.a("rpId",x.rpid);if(!a){u.las()&&H.a("title",ia(Pa(da()).substring(0,100)));a:{k=(g=Ta())?g.timing:m;if(g&&k&&(g=k.domComplete,k=k.domContentLoaded,
g||k)){k=g?g:k;break a}k=wb}k&&H.a("domR",k)}Jb(c)&&H.a("unload","xhr");Kb(a);yb=m}else yb===m&&(H||(H=new Cb),c=H.f.length,Kb(a),H.f.length>c?(H.a("fId",F),H.a("v",x.dtVersion)):H=h);return e}function Kb(a){for(var b=0;b<ub.length;b++)ub[b](H,a)}function Lb(){for(var a=[],b=0;b<H.f.length;b++)0<b&&y("$"),y(a,"$",H.f[b][0],"\x3d",H.f[b][1]);return a.join("")}function Mb(){var a=Lb(),b=z.ie?1500:7E3;x.msl&&(b=Math.min(b,w(x.msl)));return 0===a.length%b?w(a.length/b):w(a.length/b)+1}
function Nb(a,b,c){var d=document.createElement("img");d.onerror=function(){Ra((n()-b)/2)};d.setAttribute("src",c+"?"+a)}
function Fb(a,b,c){var d;if(!u.disabled){var e=location.href;c==e&&(c="");var g=n();H.a("time",g);u.hyb()&&H.a("url",encodeURIComponent(e));d=z;var k,l,q=a&&tb(!!c);if(q)k=f,b=m;else{var r=x.fsc;k=x.fso;var E=d.op&&15<=d.op&&!k;l=Mb();k=!a||a&&!(d.sf||d.op&&!E||d.ff&&(1<l||x.sffs||17<d.ff)||d.ie&&(9>d.ie||x.sies)||d.msf||d.ab||d.ch&&(22<d.ch||r));b&&(k=m);(b=(1==l||E)&&a&&(d.ie&&9>d.ie||d.ch&&!r||E))&&x.cors&&(b=k=m)}a=k;d=b;b=x.cors;k=Lb();r=h;if((x.spl||d)&&!b){l=z.ie?1500:7E3;x.msl&&(l=Math.min(l,
w(x.msl)));var E=Mb(),I,Ma=n(),G=0;if(1<E){if(100>E)for(var r=[],Na=0;Na<E;Na++){var xb="sid\x3d"+Ma+"\x26p"+(Na+1)+"_"+E+"\x3d";x.app&&(xb="app\x3d"+x.app+"\x26"+xb);G+l<=k.length?(I=k.slice(G,G+l),"%"==I.charAt(I.length-1)&&k.length>=G+l+1&&(I+=k.charAt(G+l),I+=k.charAt(G+l+1),G+=2),"%"==I.charAt(I.length-2)&&k.length>=G+l+2&&(I+=k.charAt(G+l),G+=1)):I=k.slice(G);y(r,xb+I);G+=l}}else r=[k]}else r=[k];k=r;if(k!==h)if(r=x.reportUrl?x.reportUrl:"dynaTraceMonitor",d&&!c)for(c=0;c<k.length;c++)Nb(k[c],
g,r);else if(g=r,d=k[0],r=m,b?(g=g+"?"+("dtCookie\x3d"+(encodeURIComponent(fa(bb))||"null")),g+=";dtLatC\x3d"+fa("dtLatC"),g+=";referer\x3d"+encodeURIComponent(c||e),r=f):q&&c&&(g+="?referer\x3d"+encodeURIComponent(c),r=f),x.spl&&!b)for(e=0;e<k.length;e++)b=g,d=h,r||(b+="?"),b+=k[e],q&&!c?rb(b,d):qb(mb,b,a,d,c);else x.app&&(g+=(r?";":"?")+"app\x3d"+x.app),q&&!c?rb(g,d):qb(mb,g,a,d,c)}}
function Ob(a){if(vb){var b=m;a?n()+a<Bb&&(b=f):b=f;b&&(clearTimeout(Ab),vb=m)}vb||(Bb=n()+(a||0),a?(Ab=s(Pb,a||0),vb=f):Pb())}function Pb(){vb=m;Db(m,m,m)}u.id=function(){return!!u.disabled};u.ss=function(a,b,c){Db(b,c,a)};u.asl=function(a){y(ub,a)};u.sMPS=function(a){Ob(a)};var M=h,Qb=h,K=[],J=[],Gb=0,Rb=0,N=[],O=[],P,Sa=m,Sb=z.msf?500:0,Tb=1;u.L=Ub;var Vb=[];function Q(){for(var a=0;a<Vb.length;a++)Vb[a]()}function Ub(){return J}
function Wb(a,b,c,d,e,g,k,l,q){var r={b:Tb++,start:c,stop:d,type:a,name:b,info:k,i:e,next:[],e:h,q:h,s:h,t:h,p:h,K:h,r:g?w(2147483647*Math.random())+1:0,parent:h,H:location.href,z:l,A:q,j:function(){return r.parent?r.parent.j():r.H},add:function(a){a&&a.name&&y(r.next,a)}};r.v=s(function(){r&&(r.J=f,!r.stop&&!Xb(r)&&R(r.b))},1E3*w(x.oat||180));return r}function Xb(a){for(var b=m,c=0;c<a.next.length;c++)if(!a.next[c].stop||Xb(a.next[c])){b=f;break}return b}
function Yb(){var a=m,b=[],c;for(c in J)if(J.hasOwnProperty(c)){var d=J[c];0<d.q&&(n()>d.e&&(d.e+=6E4,y(b,d)),a=f)}0<b.length&&Db(f,f,m);for(c=0;c<b.length;c++)b[c].q--;a&&s(Yb,1E3)}function Zb(a,b){if(a)for(var c=h,d=0;d<a.length;d++){c=a[d];if(c.b==b)return c;if(c.next&&(c=Zb(c.next,b),c!==h))return c}return h}function $b(a){var b=h;K&&(b=Zb(K,a));return b}
function ac(a,b,c,d,e,g,k,l){c||(c=n());a=Wb(b,a,c,h,h,e,g,k,l);"boolean"==typeof d&&d&&(d=M);if(d){if(b=h,b="number"==typeof d?$b(d):"object"==typeof d?d:M){b.add(a);a.parent=b;bc(a);for(var q in J)J.hasOwnProperty(q)&&(J[q]&&J[q].e>a.start+1E4)&&(J[q].e=a.start+1E4)}}else bc(a),cc(a),y(J,a),M=a,y(K,a),a.e=a.start+1E4,a.q=100,s(Yb,5E3);return a}
function bc(a){if(M!=a)if(M&&(Qb=M),M=a){a=a.b;for(var b=cb(),c=m,d=0;d<b.length;d++)b[d].c===F&&(b[d].b=ia(a),c=f);c||y(b,{c:F,b:ia(a)});eb(b)}else db()}
function R(a,b,c){b||(b=n());var d=[];if(K)for(var e=0;e<K.length;e++){var g=dc(K[e],a,b,c);"string"!==typeof g&&(d[e]=g)}a=m;c=[];for(b=0;b<K.length;b++)d[b]?a=d[b]:(Xb(K[b])||y(c,K[b].b),S=h);d=[];for(b in J)J.hasOwnProperty(b)&&(e=J[b],0<=Fa(c,e.b)?y(d,b):P&&(g=hb.gca(),e.t=t&&g[g.length-1]==P?"S":"A",P=h));for(b=0;b<d.length;b++)c=d[b],e=J,e.splice(c,c-(c||NaN)+1||e.length);d=a;Ob();bc(d)}
function dc(a,b,c,d){var e,g,k=a.b==b;if(k){a.stop=c;d&&(a.start=d);a.i=ra(document.getElementsByTagName("*"));a.v&&window.clearTimeout&&window.clearTimeout(a.v);var l=a.parent;if(l&&!l.stop&&l.J){var q=m;for(g=0;g<l.next.length;g++)if(!l.next[g].stop&&l.next[g].b!=b){q=f;break}q||s(function(){l.stop||R(l.b,c)},0)}}else a.stop||(e=a);q=m;if(a.next&&a.next.length)for(g=1;g<=a.next.length;g++){var r=dc(a.next[a.next.length-g],b,c,d),E="string"===typeof r,q=q||E||r&&r.D===b;E||(e=r||e);if((q||k)&&e)break}if(k||
q)"object"===typeof e?e.D=b:e="found";return e}function Ib(a,b,c,d){if(a.p){var e=[],g=["0"];g[1]=a.s;g[2]=a.p;g[3]=a.t;e[0]=g.join("|");e[1]=ec(a,1,b,c,d).result;return!e[1]?h:e.join(",")}return ec(a,1,b,c,d).result||h}
function ec(a,b,c,d,e){a.i||(a.i=ra(document.getElementsByTagName("*")));var g=[];if(a.next&&0<a.next.length){for(var k=0;k<a.next.length;k++){var l=a.next[k],l=ec(l,b+1,c,d,e),q=l.result;if(q)g.push(q);else if(!l.C)return{}}if(c)for(k=0;k<a.next.length;k++)if(l=a.next[k],l.stop)a.stop&&l.stop>a.stop&&(a.stop=l.stop);else{a.stop=m;break}}if(!d&&!e&&(!a.stop||0==a.stop))return{};c=[];c[0]=b.toString();c[1]=a.b;c[2]=D(a.K||a.name);c[3]=D(a.type);c[4]=a.info?D(a.info):"-";c[5]=a.start;c[6]=a.stop||0;
c[7]=a.i;c[8]="-";c[9]="-";c[10]="-";c[11]="-";e=8;1==b&&a.h&&(c[8]=a.h,e=9);a.r&&(c[9]=a.r,e=10);if(a.z&&(!z.ie||7<z.ie))c[10]=D(a.z),e=11;a.A&&(c[11]="1",e=12);c.splice(e,c.length-e);b=m;a.stop||d||a.next&&a.next.length||!Hb(a)?(g.unshift(c.join("|")),Gb++):Hb(a)&&(b=f);a={C:b};1<g.length?a.result=g.join(","):g[0]&&(a.result=g[0]);return a}function Hb(a){var b=["_warning_","_error_","_log_","_rv_","_rs_"];return Gb+1>(w(x.moa)||30)&&-1==Fa(b,a.type)}
function Jb(a){if(0<Rb||a&&0<N.length)if(a=N.length,0<a)return N[a-1];return h}function fc(a,b,c,d,e){var g=h;b||(b=3);var k=gc(),l="";k&&(k.info=a||"-",l=k.info);var q=Jb(m);!q&&(k&&k.b)&&(q=k.b);d=d?Ya(d):h;q?g=hc(q):k?3<=b&&(g=ic(k.getName(),k.type,k.start,h,c,l,d,e),k.b=g):M?1<=b&&(g=hc(M.b,a,"xhr",n(),c,l,d,e)):x.cux&&(g=ic("Unlinked XHR","xhr",n(),h,c,l,d,e));return g}function ic(a,b,c,d,e,g,k,l){a=ac(a,b,c,d,e,g,k,l);a.l=1;O[a.b]=a;return a.b}
function hc(a,b,c,d,e,g,k,l){a=O[a];var q=-1;a?(a.l++,q=a.b):M&&(q=ic(b,c,d,M.b,e,g,k,l));return q}function nb(a){try{if(a&&jc&&jc.getEntriesByName){var b=Xa(a);0==v(b,"/")?b=location.protocol+"//"+location.host+b:0!=v(b,"http")&&(b=location.href.substr(0,location.href.lastIndexOf("/")+1)+b);var c=jc.getEntriesByName(b);if(c.length){var d=c[c.length-1];Ra((d.requestStart-d.startTime)/2);return f}}}catch(e){}return m}
function kc(){var a=0,b;for(b in O)if(b&&O.hasOwnProperty(b))try{a+=O[b].l}catch(c){}return a}function cc(a){P=h;if(hb){var b=hb.gca();if(P=b[b.length-1])a.s=P.b,a.p=P.name,P.h?P.h++:P.h=1}}function T(a,b,c){var d=n();a=Pa(a);b=Wb(b,a,d,d,-1);(c=lc(b,c))&&Ob();return c}function lc(a,b){var c;if(c="undefined"==typeof b?M:$b(b))return c.add(a),m;cc(a);y(K,a);return f}function Za(a,b){T(a,"_warning_",b)}function mc(){return M?M.name:h}
function nc(a){var b=a==mc();if(!Qb)return!b;a=a===Qb.name&&3E3>=n()-Qb.start;return!b&&!a}u.ea=function(a,b,c,d,e,g,k){if(4>arguments.length||"undefined"==typeof d)d=f;return ac(a,b,c,d,h,e,g,k).b};u.la=function(a,b,c){Q();R(a,b,c)};u.aa=lc;u.cra=Wb;u.lx=function(a,b,c,d){c?s(function(){nb(b)},0):nb(b);d=d||n();s(function(){var b=d,c=0;if(c=O[a])c.l--,c=c.l,0>=c&&(R(a,b),O[a]=h,delete O[a])},Sb);return 1>=kc()?(Q(),f):m};u.ex=fc;u.ec=function(a){a&&(y(N,a),Rb++)};
u.lc=function(a){a&&(Rb--,s(function(){for(var b=-1,c=N.length-1;-1==b&&0<=c;)N[c]==a&&(b=c),c--; -1!=b&&(b==N.length-1?N.pop():N.splice(b,1))},0))};u.irs=Ob;u.eV=function(){T("visit end","_endVisit_")};u.pe=function(a,b){if(oc<=(u.cfg("mepp")||10))oc++,T(a,"_error_",b)};u.pw=Za;u.pl=function(a,b){T(a,"_log_",b)};u.rv=function(a,b){var c=n(),c=Wb("_rv_",a+"\x3d"+b,c,c,0);lc(c);Ob()};u.rs=function(a,b,c){var d=n();a=Wb("_rs_",a+"\x3d"+b,d,d,0);lc(a,c);Ob()};u.pcn=T;
u.ewa=function(a){a=fc(a,3,f);return!a?h:$b(a)};u.gWRI=function(a){return a.r};u.gAID=function(a){return a.b};u.ca=function(){return M};u.can=mc;u.isci=nc;u.noa=function(){return!M||0<M.stop};u.ti=Q;u.las=function(){return Sa};u.gca=Ub;u.gAR=function(a){isNaN(a)||(a=O[a]);return a?a.j():h};u.gAA=function(a){return O[a]};var pc,qc=m,rc=x.mepp,sc;isNaN(rc)||(sc=w(rc));!rc&&0!=sc&&(sc=10);var oc=0;
function tc(a){try{if(p.event.errorUrl||a.filename)oc++,oc<=sc&&(11>z.ie?T(p.event.type+":"+p.event.errorUrl+"["+p.event.errorLine+"] Code: "+p.event.errorCode+": "+p.event.errorMessage,"_error_"):T(a.type+":"+a.filename+"["+a.lineno+":"+a.colno+"] "+a.message,"_error_"))}catch(b){}}
function uc(a,b,c){var d=m;if(!qc){qc=f;try{pc&&(pc!=uc&&"function"==typeof pc)&&(d=pc(a,b,c));var e=h;if(e="object"==typeof a?a.srcElement?a.srcElement.outerHTML&&200>a.srcElement.outerHTML.length?document.URL.split("#")[0]+"[-]: Error at '"+a.srcElement.outerHTML+"'":document.URL.split("#")[0]+"[-]: Error at tag: '"+a.srcElement.tagName+"'":"unknown error":"undefined"==typeof b||"undefined"==b?a:b+"["+c+"]: "+a){var g=gc();g&&(e+=", user action: "+g.getName());oc++;oc<=sc&&!d&&T(e,"_error_")}}catch(k){}qc=
m}return d}z.ie?C(p,"error",tc):p.onerror!=uc&&(p.onerror&&(pc=p.onerror),p.onerror=uc);try{z.ie||Va(window,"onerror",function(){return uc},function(a){pc=a})}catch(vc){}C(p,"unload",function(){Wa(window,"onerror");p.onerror=h});u.gne=function(){return oc};u.iet=function(){oc++};
var wc="BUTTON",xc="INPUT",yc="HIDDEN",zc="SUBMIT",Ac="RESET",Bc="IMAGE",Cc="IMG",Dc="A",Ec="FORM",Fc="#DOCUMENT",Gc="HTML",Hc="BODY",Ic="HEAD",Jc="SELECT",Kc="unknown",Lc="TEXTAREA",Nc=Mc(p.location.href),Oc=h,Pc=0,Qc=1,Rc=2,Sc=3,Tc=4,Uc=0;function Vc(a){if(a)for(var b=document.getElementsByTagName("LABEL"),c=ra(b),d=0;d<c;d++)if(b[d].htmlFor==a)return a=b[d],U(a.innerText,a.textContent);return h}
function U(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&"string"==typeof c&&Ea(c))return Ea(c)}return h}function Wc(a){if(a){if(0===v(a,"data:"))return h;a=a.split("/");if(0<a.length)return a[a.length-1].split(".")[0]}return h}function Mc(a){if(a){var b=a.split("/");if(0<b.length&&(b=Ea(b[b.length-1]),b!==h))return b}return a}
function Xc(a,b){var c=b.nodeName?b.nodeName.toUpperCase():Kc,d=b.type&&"string"===typeof b.type?b.type.toUpperCase():h,e=h;switch(a){case Pc:c==xc&&d!=yc&&(c=d&&(d==wc||d==zc||d==Ac||d==Bc)?b.value:h,e=Vc(b.id),e=d&&(d==wc||d==zc||d==Ac)?U(c,e):U(e,c));e||(e=U(b.textContent,b.innerText));break;case Qc:if(c==xc&&d!=yc||c==wc)e=U(b.name,b.title,d&&d==Bc?b.alt:h);break;case Rc:c==xc&&d==Bc?e=Wc(b.src):c==Dc?e=U(b.title,Mc(b.href)):c==Cc?e=U(b.name,b.title,b.alt,Wc(b.src)):c==Ec&&(e=U(b.name,b.id,b.action));
e||(e=U(b.title,b.data,b.wholeText,b.id));break;case Sc:e="object"==typeof b.className?b.baseVal||b.animVal:b.className;break;case Tc:c==xc&&d!=yc?e=xc+": "+d:c==Dc?e="LINK":Oc||(Oc=e=c)}return e}function Yc(a){if(!a)return h;try{if(z.ie&&Ha(a))return"VML Node";var b=a.nodeName?a.nodeName.toUpperCase():Kc;if(b==Gc||b==Hc||b==Ic||b==Fc)return Oc;for(b=0;4>=b;b++){var c=Xc(b,a);if(c&&c!==Oc)return c}return Yc(a.parentNode)}catch(d){}return h}
function Zc(a,b){if(!b)return h;var c=ra(b);if(0>=c||20<Uc)return h;for(var d=0;d<c;d++){var e=b[d];if(z.ie&&Ha(e))return"VML Node";var g=h;Uc++;if(g=Zc(a,e.childNodes))return g;Uc--;if(g=Xc(a,e))return g}return h}
function $c(a){Oc=h;try{if(z.ie&&Ha(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtName"];if(b&&b.value)return b.value}var c=a.nodeName?a.nodeName.toUpperCase():Kc;if(c==Gc||c==Hc||c==Ic||c==Fc)return"Page: "+Nc;if(c==Jc){var d;if(a){var e=a.nodeName?a.nodeName.toUpperCase():h;if(e!=Jc)d=h;else{var g=Vc(a.id),k=U(g,a.name,e),l=h;if(!a.multiple){var q=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:h;q&&(l=U(q.label,q.innerText,q.textContent))}d=
l?"["+k+"] to value ["+l+"]":k}}else d=h;return d}if(c==Lc){var r;if(a){var E=a.nodeName?a.nodeName.toUpperCase():h;if(E!=Lc)r=h;else{var I=Vc(a.id);r=U(I,a.name,E)||a.nodeName}}else r=h;return r}var Ma=Ea(U(a.innerText,a.textContent));if(Ma)return Ma;Uc=0;if(a.childNodes&&0<ra(a.childNodes)){a:{d=[a];k=Zc;for(q=0;4>=q;q++){var G=k(q,d);if(G){l=G;break a}}l=h}return l}}catch(Na){}return Yc(a)}var V,ad=h,bd=0,cd=f,W=u.tdto();
function dd(a,b,c,d){if(u!=W)return W.bi(a,b,c,d);try{d||(d=30);var e={id:bd++,d:a,name:h,type:b,info:c?c:"-",start:n(),u:m,w:n()+d,getName:function(){if(!e.name){var a="";(a=x.uam?"dTMasked_"+e.d.nodeName:Pa($c(e.d)))||(a="-");var b=x.sl||100;a.length>b&&(a=a.substring(0,b-3)+"...");e.name=a}return e.name},G:function(){return e.u},I:function(){var a=e;do a.u=f,a=a.next;while(a)}};cd&&(e.next=V,e.next&&(e.next.k=e),V=e);return e}finally{e&&(a=e.w-n(),0>=a?ed(e):s(function(){ed(e)},a))}}
function gc(){if(u!=W)return W.gci();try{if(V){for(var a=V,b=V.next;b;){var c;if(c=b.d!=a.d)a:{try{for(var d=b.d.parentNode;d;){if(d==a.d){c=f;break a}d=d.parentNode}}catch(e){}c=m}c&&(a=b);b=b.next}return a}return h}catch(g){return h}}function fd(){return u!=W?W.ci():gc()?V.getName():h}function gd(){return u!=W?W.gpi():ad}function hd(){return u!=W?W.pi():gd()?ad.getName():h}function id(){return u!=W?W.piv():gd()?ad.w:h}function jd(){for(var a=V;a;)a.d=h,a=a.next;V=h}
function ed(a){if(u!=W)return W.ei(a);if(V){for(var b=V;b.next&&b!==a;)b=b.next;b===a&&(fd()&&(ad=V),b.d=h,b.k?b.k.next=b.next:V=b.next,b.next&&(b.next.k=b.k))}}
function X(a,b,c){var d=m,e=x.doNotDetect?x.doNotDetect.split(","):h;if(c&&e)for(var g=0;g<e.length;g++)e[g]==c&&(d=f);d||(b||(b=a),C(document,a,function(a){var c=h;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if(("KD"==d||"KU"==d)&&"password"!==c.type)if(a=a.keyCode?a.keyCode:a.charCode)if(x.uam){var e=String.fromCharCode(a);"a"<=e&&"z">=e||("A"<=e&&"Z">=e||"0"<=e&&"9">=e)||(d+=a)}else d+=a;dd(c,d,h,30)}))}X("click","C","clk");X("mousedown","D","mdw");X("mouseup","U","mup");
X("dblclick","CC","dcl");X("keydown","KD","kyd");X("keyup","KU","kyu");X("scroll","S","scr");X("touchstart","TS","tcs");X("touchend","TE","tce");if(x.ade){var kd=x.ade.split(",");if(kd&&0<kd.length)for(var ld=0;ld<kd.length;ld++)X(kd[ld])}u.bi=dd;u.ei=ed;u.gci=gc;u.ci=fd;u.cit=function(){return u!=W?W.cit():gc()?V.type:h};u.cih=function(){return u!=W?W.cih():gc()?V.d:h};u.gpi=gd;u.pi=hd;u.pit=function(){return u!=W?W.pit():gd()?ad.type:h};u.piv=id;u.aad=function(a){(cd=a)||jd()};
var md=m,nd=m,od=m,L=h,S=h,pd=Ka("dtSa");Ja("dtSa","-");if(pd&&"-"!=pd){var Y=pd.split("|");if(9==Y.length){var qd={B:"true"==Y[0],type:Y[1],b:Y[2],name:Y[3],info:Y[4],start:Y[5],c:Y[6],location:Y[7],title:Y[8]},rd=m;u!=u.tdto()&&(rd=u.tdto().iRO(qd.location));if(!document.referrer||qd.location==D(document.referrer)||qd.location==D(document.location)||rd)S=L=qd}}var sd=h,td=m,ud=[],vd=[],ob=m,wd=m,xd=1;u.tdto().aFU(document.location.href);
if(!x.rid){var yd=x.ridPath,zd=yd?yd:p.location.pathname,Ad=p.location.search;Ad&&(Ad.length&&"?"===Ad.charAt(0))&&(Ad=Ad.substring(1));var Bd=Ad,Cd=1,Cd=31*Cd+Ia(zd),Cd=31*Cd+Ia(Bd),Cd=Cd&Cd;x.rid="RID_"+Cd}var Z=h,Dd,jc=Ta();jc&&(Z=jc.timing)&&Ra((Z.requestStart-Z.navigationStart)/2,f);function Ed(){var a=aa;if(Z){if(5E3<Math.abs(Z.responseStart-aa))return aa;var b=Z.redirectStart,c=Z.navigationStart,d=Z.fetchStart,e=c+6E4;c&&(b?a=e>b?c:b:d&&(a=e>d?c:d))}return Math.floor(a)}
function Fd(){xd--;if(0==xd&&sd)for(var a=0;a<ud.length;a++)try{ud[a]()}catch(b){}if(0>=xd){var a=Z?Z.loadEventEnd:0,c;c=Z?Z.loadEventStart:0;c=c<Ed()?0:c;if(sd){if(a&&c&&a>c){var d=n()-a;if(5E3<(0>d?-1*d:d))a+=d;R(sd.b,a,c)}else R(sd.b);sd=m}Dd||Gd()}a=lb();a!=u&&a.sole()}function Gd(a){if(Hd){var b=0;jc&&!a&&(b=Z?Z.loadEventEnd:0);b?R(Hd.b,b):R(Hd.b);Hd=h;Q()}}function Id(){Hd&&!sd&&(sd=ac("_onload_","_load_",h,Hd))}u.sls=function(){};u.sole=Fd;u.iolm=function(){xd++};u.solb=Id;
u.slem=function(){Dd=f};u.lst=Ed;function Jd(){if(!nd||0<xd)nd=f,Q(),Fd()}function Kd(){Q();if(!md){var a=lb();a!=u&&a.iolm();Id();md=f;s(Jd,0)}}function Ld(){Q();md||("complete"==document.readyState?od?Db(m,f,m):(od=f,s(Ld,3E3)):s(Ld,3E3))}
function Md(a,b,c,d){var e=Jb(f);c=c||n();!e&&a&&b&&c?Ja("dtSa","true|"+D(b)+"|-1|"+D(a)+"|"+D(d||"-")+"|"+c+"|"+F+"|"+D(Qa())+"|"+D(Pa(da()).substring(0,100))):e&&S?(Ja("dtSa","false|"+S.type+"|"+S.b+"|"+S.name+"|"+S.info||"-|"+c+"|"+S.c+"|"+D(Qa())+"|"+D(Pa(da()).substring(0,100))),S=h):M&&"_load_"!=M.name&&Ja("dtSa","false|"+D(M.type)+"|"+M.b+"|"+D(M.name)+"|"+D(M.info||"-")+"|"+c+"|"+F+"|"+D(Qa())+"|"+D(Pa(da()).substring(0,100)))}function Nd(){Od()}
function Od(a){var b=n();if(!ob){ob=!a;for(a=0;a<vd.length;a++)vd[a](ob);a=Eb(m,f,f);var c=gc();if(!c){var d=gd();d&&(nc(hd())&&3E3>=n()-id())&&(c=d)}c&&c.G()===m?(c.I(),Md(c.getName(),c.type,c.start,c.info)):Md(h,h,b,h);if(z.sf&&p.frames)for(b=0;b<p.frames.length;b++)try{p.frames[b].dT_&&p.frames[b].dT_.obc()}catch(e){}H&&Fb(f,m,a)}}C(p,"beforeunload",Nd);
C(p,"unload",function(){Od();var a;if(0<pb.length){a=tb(m);for(var b=0;b<pb.length;b++)try{var c=pb[b];a?rb(c.path,c.data):qb(h,c.path,m,c.data)}catch(d){}}if(!wd)try{jd();a=B;for(var e=a.length;0<=--e;){var g=a[e];Ga(g.object,g.event,g.m)}B=[];jc=Z=ca=ba=h;wd=f}catch(k){}td||(td=f,db())});C(p,"pagehide",function(){Od(f);td||(td=f,db())});C(document,"readystatechange",function(){"loaded"==document.readyState&&Q();"complete"==document.readyState&&Kd()});s(Ld,3E3);C(p,"load",Kd);
(function(){zb||(zb=document.createElement("doc:rdy"));if(zb.doScroll){var a=function(){try{zb.doScroll("left"),zb=h,wb=n(),Q()}catch(b){s(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){wb=n();Q()},m)})();var Hd=ac("_load_","_load_",Ed(),h);Q();u.all=function(a){y(ud,a)};u.ail=function(a){y(Vb,a)};u.apll=function(a){y(vd,a)};u.sle=function(){Gd(1)};u.obc=Nd;u.ile=function(){return 0>=xd};var $=window.dT_,Pd=[],Qd=m;function Rd(a){Qd?a($.bwsW,$.bwsH):y(Pd,a)}
$.all(function(){var a=document,b=a.documentElement,c=0,d=0,e=a.body;if("number"===typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(e&&(e.clientWidth||e.clientHeight))c=e.clientWidth,d=e.clientHeight;if(0<c&&0<d)a=screen.availWidth,b=screen.availHeight,c=c<a?c:a,d=d<b?d:b;else{var g;$.gBI().ie?g=140:g=10;c=Math.max(c,g);d=Math.max(d,10)}$.bwsW=c;$.bwsH=d;Qd=f;for(a=0;a<Pd.length;a++)Pd[a](c,d)});
$.abwsl||($.abwsl=Rd);var Sd=m;$.asl(function(a,b){if(!b&&!Sd&&$.las()){Sd=f;var c=$.tdto(),d=function(a){return 0>a||2147483647<=a||isNaN(a)?0:a};c?(a.a("w",d(c.bwsW)),a.a("h",d(c.bwsH))):(a.a("w",d($.bwsW)),a.a("h",d($.bwsH)))}});
$.asl(function(){var a=$.gC("dtCookie");if("undefined"!=typeof window.sessionStorage)try{var b="";try{b=window.sessionStorage.dtCookie}catch(c){}if(b&&"null"!=b&&a!=b){var d,e=b;if(e){var g=v(e,"|");-1!=g&&(e=e.substring(0,g))}d=e;var k;if("undefined"!=typeof a&&a!=h&&""!=a&&(b=a)&&d)var l=v(b,"|"),b=-1!=l?d+b.substring(l):d;a=k=b}if(a!=h&&a){$.dC("dtCookie");$.sC("dtCookie",a);try{window.sessionStorage.setItem("dtCookie",a)}catch(q){}}}catch(r){}});
})();(function() {
var d=!0,k=null,n=!1,p=window.dT_,r=k,s=k,t=k,u=k,v=n,w=k,x,y,z=n,A=n,C={};function D(b){for(var a in b)b.hasOwnProperty(a)&&(C[a]=b[a]);return r.apply(this,arguments)}
function E(b,a){function c(a){q||(q=d,p.st(function(){p.lx(a,e)},0))}var e=b,q=n;"object"===typeof b&&(a=b,e=(a.url||C.url)+"");a=a||{};for(var g in C)C.hasOwnProperty(g)&&!a.hasOwnProperty(g)&&(a[g]=C[g]);"function"===typeof a.data&&(a.type=a.type||a.callback,a.callback=a.data,a.data=n);"string"===typeof a.success&&(a.success=n);var h=p.ex("j"+y,3,void 0,e),B,H=a.beforeSend;a.beforeSend=function(a,b){if(h){var f=document.location.href,m=p.gPAH(h);m&&(p.icr(e)||a.setRequestHeader("x-dtPC",m),p.hyb()&&
(a.setRequestHeader("x-dtreferer",f),a.setRequestHeader("X-Host",p.gh(e))));(m=p.gAR(h))&&(m!=f&&!p.icr(e))&&a.setRequestHeader("x-dtreferer",m)}if(H){var l;try{l=H.apply(this,arguments)}catch(g){throw"TypeError"==g.name&&c(h),g;}return l}};if("undefined"===typeof a.async||a.async){var f=a.complete;a.complete=function(a,b){"success"!=b&&p.pw('jQuery reported "'+b+'"');p.ec(h);var e;try{if(f)if("function"==typeof f)e=f.apply(this,arguments);else if(f.length)for(var m=0;m<f.length;m++)f[m].apply(this,
arguments)}finally{p.lc(h),c(h)}return e};var l=a.success;l&&(a.success=function(a,b,e){p.ec(h);try{var f;if("function"==typeof l)f=l.apply(this,arguments);else if(l.length)for(var g=0;g<l.length;g++)l[g].apply(this,arguments)}finally{p.lc(h),c(h)}return f});var I=a.error;I&&(a.error=function(a,b,e){p.ec(h);var f;try{f=I.apply(this,arguments)}finally{p.lc(h),c(h)}return f});B=u.apply(this,arguments)}else{p.ec(h);try{B=u.apply(this,arguments)}finally{p.lc(h),c(h)}}return B}var F=k;
function G(b,a){var c=k,e=n;switch(a){case "click":a="C";c="clk";break;case "dblclick":a="CC";c="dcl";break;case "mouseup":a="U";c="mup";break;case "mousedown":a="D";c="mdw";break;case "keyup":a="KU";c="kyu";break;case "keydown":a="KD";c="kyd";break;case "scroll":a="S";c="scr";break;case "touchstart":a="TS";c="tcs";break;case "touchend":a="TE";c="tce";break;case "autocomplete":a="A";break;default:e=d}var q;!F&&p.cfg("doNotDetect")&&(F=p.cfg("doNotDetect").split(","));q=F;if(c&&q)for(var g=0;g<q.length;g++)q[g]==
c&&(e=d);return b&&!e?(c=function(c){var e=p.gci(),g;if(0==a.indexOf("KD")||0==a.indexOf("KU")){var f=c.keyCode?c.keyCode:c.charCode;f&&(a=0==a.indexOf("KD")?"KD"+f:"KU"+f)}var f=a,l=c.target||c.currentTarget||c.srcElement||k;l&&(e||p.bi(l,f),g=b.apply(this,arguments));return g},c.dtHook=d,c.origHandler=b,c):b}function J(b,a){var c=b[a];if(c)for(var e=0;e<c.length;e++)c[e].handler&&!c[e].handler.dtHook&&(c[e].handler=G(c[e].handler,a))}
function K(b,a,c){var e=t.apply(this,arguments);"undefined"!=typeof e&&e&&"events"==a&&(J(e,"click"),J(e,"mouseup"),J(e,"mousedown"),J(e,"keydown"),J(e,"autocomplete"));return e}function L(b,a){if(a)for(var c=0;c<a.length;c++)a[c].handler&&!a[c].handler.dtHook&&(a[c].handler=G(a[c].handler,a[c].type));c=window.jQuery;if(s)return s.apply(this,arguments);if(c&&c.event.handlers&&c.event.handlers!=L)return c.event.handlers.apply(this,arguments)}
function M(){var b=arguments;3==b.length&&(b[2]&&"undefined"!==typeof b[2].origHandler)&&(b[2]=b[2].origHandler);return w.apply(this,b)}
function N(){var b=window.jQuery;p.rpl(b,"data");p.rpl(b,"ajax");p.rpl(window,"jQuery");y=b().jquery;!z&&O()&&(z=d,p.ti(),u=b.ajax,b.ajax=E,r=b.ajaxSetup,b.ajaxSetup=D,(s=b.event.handlers)?b.event.handlers=L:(t=b.data,b.data=K),b.fn&&(w=b.fn.off,b.fn.off=M),p.ael(window,"unload",function(){v||("undefined"!=typeof b&&(b.ajax=u,b.data=t,b.ajaxSetup=r,s&&(b.event.handlers=s),b.fn&&(b.fn.off=w)),r=w=s=t=u=k,v=d)}))}function P(){var b=window.jQuery;b&&(b.data&&b.ajax&&b.ajaxSetup)&&N()}
function O(){if("undefined"===typeof x){var b=y.split(".");x=p.cvs("1.3 1.4 1.5 1.6 1.6 1.7 1.8 1.9 1.10 1.11 2.0 2.1".split(" "),b[0],b[1],"jQuery")}return x}p.smbi("j")&&(p.initJQuery=N,p.apl(window,"jQuery",k,function(){!window.jQuery||!window.jQuery.ajax?A||(p.apl(window.jQuery,"ajax",k,P),p.apl(window.jQuery,"data",k,P),p.apl(window.jQuery,"ajaxSetup",k,P),A=d):N()}),p.all(function(){P()}));
})();(function() {
var b=window.dT_,f=window.performance,k={c:"redirectStart",d:"redirectEnd",e:"fetchStart",f:"domainLookupStart",g:"domainLookupEnd",h:"connectStart",i:"connectEnd",j:"secureConnectionStart",k:"requestStart",l:"responseStart",m:"responseEnd",n:"domLoading",o:"domInteractive",p:"domContentLoadedEventStart",q:"domContentLoadedEventEnd",r:"domComplete",s:"loadEventStart",t:"loadEventEnd"},l=!1;
b.smbi("n")&&b.asl(function(d,m){if(!m&&!l&&b.las())if(l=!0,"undefined"!=typeof f)if(b.gBI().ff&&9>=b.gBI().ff)d.a("nt","0");else{var a;a=f.timing||{};var c=f.navigation||{},e=a.navigationStart;if(0<e){var c=["a",c.type,"b",e],g;for(g in k){var h=a[k[g]];h&&h>=e&&(c.push(g),c.push(h-e))}a=c.join("")}else a=null;a?d.a("nt",a):d.a("nt","0")}else d.a("nt","0")});
})();