var urlsArray=[];function getIndex(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return c;return-1}
function sendAjaxRequest(a,b,c,d,g,f,m,n,h,k,p,q,r,s){if(!(0<urlsArray.length&&0<=getIndex(urlsArray,b))){urlsArray.push(b);var e;if(window.ActiveXObject)try{e=new ActiveXObject("Microsoft.XMLHTTP")}catch(t){try{e=new ActiveXObject("Msxml2.XMLHTTP")}catch(u){}}else window.XMLHttpRequest&&(e=new XMLHttpRequest,e.overrideMimeType&&e.overrideMimeType("text/html"));e.open("POST",b,a);h&&showAJAXLoadMessage(k,p,q,r,s);var l=function(){if(4==e.readyState){if(200==e.status){var a=e.responseText,c="";if("string"==
typeof d){var f=parseAjaxDataForDiv(d,a);null!=f&&(dynamicDivPopulate(d,f),c=d)}else for(c=Array(d.length),i=0;i<d.length;i++){var g=d[i],f=parseAjaxDataForDiv(g,a);c[i]=null;null!=f&&(dynamicDivPopulate(g,f),c[i]=g)}}h&&hideAJAXLoadMessage(k);a=getIndex(urlsArray,b);-1<a&&urlsArray.splice(a,1);!0==m&&(eval(n),callBackFunc(c))}};a=function(){l(e)};try{e.onload=function(a){a=window.event?window.event:a;l(a.target?a.target:a.srcElement)}}catch(v){e.onreadystatechange=a}e.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");e.setRequestHeader("Content-length",0);a=null;null!=c?(c=loopThroughElements(c,g,f),null!=c&&(a=c.substring(1,c.length),!0==g&&(a=null!=a?a+("\x26"+f+"\x3dtrue"):f+"\x3dtrue"),null!=a&&e.setRequestHeader("Content-length",a.length))):!0==g&&(a=f+"\x3dtrue",e.setRequestHeader("Content-length",a.length));e.setRequestHeader("Connection","close");null!=a?e.send(a):e.send("")}}
function dynamicDivPopulate(a,b){if(document.getElementById(a)){document.getElementById(a).innerHTML=b;var c=document.getElementById("if_"+a);if(null!=c){var d=document.getElementById(a);c.style.display="block";c.style.width=d.offsetWidth;c.style.height=d.offsetHeight;c.style.left=d.offsetLeft;c.style.top=d.offsetTop}}}function parseAjaxDataForDiv(a,b){var c=b.split("\x3csplit name\x3d'"+a+"'\x3e");if(null!=c&&3<=c.length)return c[1]}
function showAJAXLoadMessage(a,b,c,d,g){b=document.getElementById(b.id);nLeftPos=findPosX(b);nTopPos=findPosY(b);nextAvailableMessage="ajaxLoadMessage_"+a;a=document.getElementById("if_"+nextAvailableMessage);a.src="/include/load_ajax_refresh_img.jsp";b=!1;/MSIE (\d+\.\d+);/.test(navigator.userAgent)&&(b=!0);a.style.width=d;a.style.height=g;a.style.left=nLeftPos-30;a.style.top=nTopPos-6;b&&(a.style.top=nTopPos-12);a.style.display="block";do_disable_buttons(!0)}
function hideAJAXLoadMessage(a){nextAvailableMessage="ajaxLoadMessage_"+a;document.getElementById(nextAvailableMessage).style.display="none";document.getElementById("if_"+nextAvailableMessage).style.display="none";do_disable_buttons(!1)}function loopThroughElements(a,b,c){for(var d="",g=a.elements.length-1,f=0;f<a.elements.length;f++)!0==b&&(1==f?d+="\x26bmSubmit\x3d"+c:f==g&&(d+="\x26bmSubmit\x3d"+c)),""!=a.elements[f].name&&(d+=generateNameValuePair(a.elements[f]));return d}
function generateNameValuePair(a){var b=a.type,c="\x26"+encodeURI(a.name);if("text"==b||"textarea"==b||"hidden"==b){var b=a.value.indexOf("\x3c"),b=a.value.indexOf("\x3e")-b,d=[],d=a.value.split("\x3c\x3e"),d=d[0];if(1!=b||0==d.length)a.value=a.value.replace(RegExp("((%3C)|\x3c)|((\\%3E)|\x3e)","g"),"");b=encodeURI(a.value);return c+"\x3d"+b}return"select-one"==b?0<=a.selectedIndex?(b=a.options[a.selectedIndex].value,c+"\x3d"+b):"":"checkbox"==b?(b="false",a.checked&&(b="true"),c+"\x3d"+b):"radio"==
b&&a.checked?(b=encodeURI(a.value),c+"\x3d"+b):""}function findPosX(a){var b=0;if(a.offsetParent)for(;;){b+=a.offsetLeft;if(!a.offsetParent)break;a=a.offsetParent}else a.x&&(b+=a.x);return b}function findPosY(a){var b=0;if(a.offsetParent)for(;;){b+=a.offsetTop;if(!a.offsetParent)break;a=a.offsetParent}else a.y&&(b+=a.y);return b}
function do_disable_buttons(a){if("undefined"!=typeof disableButtons){var b=disableButtons.length;for(i=0;i<b;i++)"undefined"!=typeof disableButtons[i]&&"undefined"!=disableButtons[i]&&(disableButtons[i].disabled=a)}}
function __dynamicFunction(a,b){var c=typeof b,d=a+"(";if("undefined"==c||null==c)d=a+"();";else if("string"==c||"number"==c)d=a+"('"+b+"');";else{d=a+"(";for(i=0;i<b.length-1;i++)d+="functionParameters["+i+"],";d+="functionParameters["+(b.length-1)+"]);"}try{eval(d)}catch(g){alert("method not available")}}function toggleDiv(a){if(a=document.getElementById(a))a.style.display="block"==a.style.display?"none":"block"};