                                                                                                                   
                              
   
  
                                                     
                 
	                                                                                                                  
	                            
		window.checkHertzNameSpace=function(){var a=arguments,b=0,c=0,d=null,e=null,f=null;ref=[];for(b=0;b<a.length;b++){d=window;e=a[b].split(".");for(c=0;c<e.length;c++)f=e[c],d[f]=d[f]||{},d=d[f];ref[b]=d}return ref};window.checkHertzNameSpace("htz.utils");
var Utils=Utils||function(){return{exportToNameSpace:function(a,b){a&&b&&(checkHertzNameSpace(a)[0]=b)},isIE8:function(){return $("body").hasClass("lt-ie9")&&!$("body").hasClass("lt-ie8")},isUseStoragePolyfill:function(){return $("body").hasClass("lt-ie8")},storeItemIE:function(a,b,c){var d=new Backbone.Model({id:a});d.url=htz.config.rootContext+"/rest/home/save-ie/"+a;a={};c&&(a=$.extend(a,c));a.type="POST";d.save(b,a)},fetchItemIE:function(a,b){var c=new Backbone.Model;c.url=htz.config.rootContext+
"/rest/home/retrieve-ie/"+a;var d={};b&&(d=$.extend(d,b));d.type="POST";c.fetch(d)},removeItemIE:function(a){var b=new Backbone.Model({id:a});b.url=htz.config.rootContext+"/rest/home/clear-ie/"+a;b.save({},{type:"POST"})},showSelects:function(){$.browser.msie&&"6.0"==$.browser.version&&$("select").each(function(a,b){$(b).css({visibility:"visible"})})},hideSelects:function(){$.browser.msie&&"6.0"==$.browser.version&&($("select").each(function(a,b){$(this).hasClass("noHide")||$(b).css({visibility:"hidden"})}),
$("#lboxDivLBContent")&&$("#lboxDivLBContent select").each(function(a,b){$(this).hasClass("noHide")||$(b).css({visibility:"visible"})}))},sessionTimedOut:function(a){return this.hasSessionTimedOut(a,null)?(window.location.href=a.getResponseHeader("Location"),!0):!1},hasSessionTimedOut:function(a){return a&&"true"==a.getResponseHeader("Ajax-Session-Timeout")&&a.getResponseHeader("Location")},displayBootStrappedErrors:function(a){if(a&&a.message&&(a.message.fieldErrors||a.message.messages||a.message.systemErrors||
a.message.errorData))Utils.trackError(a.message),htz.helpers.SessionHelper.setItem("errors",JSON.stringify(a.message))},displayErrorMessage:function(a,b){var c=this.buildNonFieldErrors(a);c&&(c="<ul>"+c+"</ul>",htz.config.isApp?Utils.showErrors(c,b):b?$(b).html(c).show():$("#error-list").html(c).show())},displayFieldErrors:function(a,b){var c=this.buildFieldErrors(a);c&&(c="<ul>"+c+"</ul>",b?$(b).html(c).show():$("#error-list").html(c).show())},displayAllErrors:function(a,b){if(a){var c=this.buildNonFieldErrors(a),
d=this.buildFieldErrors(a.fieldErrors);if(c||d){var e="<ul>";c&&(e+=c);d&&(e+=d);e+="</ul>";htz.config.isApp?Utils.showErrors(e,b):b?$(b).html(e).show():$("#error-list").html(e).show()}}},buildNonFieldErrors:function(a){if(!a.messages&&!a.systemErrors)return null;var b="";if(a.messages)for(var c=0;c<a.messages.length;c++)b+="<li>"+a.messages[c]+"</li>";if(a.systemErrors)for(c=0;c<a.systemErrors.length;c++)b+="<li>"+a.systemErrors[c]+"</li>";return b},buildFieldErrors:function(a){if(!a||0==a.length)return null;
var b=[],c="";try{for(var d in a)for(var e in a[d][1])b[a[d][1][e]]=""}catch(f){}for(var g in b)c+="<li>"+g+"</li>";return c},clearErrorMessage:function(a){a||(a="#error-list");$(a).empty().hide()},showErrorFromSession:function(){var a=htz.helpers.SessionHelper.getItem("errors");a&&(Utils.displayAllErrors(JSON.parse(a)),htz.helpers.SessionHelper.removeItem("errors"))},findErrorCodes:function(a){if(!a)return"";var b="",c="",d;for(d in a)if(a.fieldErrors)for(var e in a[d])for(var f in a[d][e][1])c=
a[d][e][1][f],b+=c.substring(c.lastIndexOf("[")+1,c.lastIndexOf("]"))+",";else for(f in a[d])"string"==typeof a[d][f]?(c=a[d][f],b+=c.substring(c.lastIndexOf("[")+1,c.lastIndexOf("]"))+","):(c=a[d][f].errorCode,b+=c+",");0<b.length&&(b=b.substring(0,b.length-1));return b},trackError:function(a,b){var c=this.findErrorCodes(a);c&&"undefined"!==typeof WebTracking&&WebTracking.setError(c,b)},clearReservationSession:function(){htz.helpers.SessionHelper.removeItem("homeModel")},isHexColorCode:function(a){return/^#[0-9a-f]{3}([0-9a-f]{3})?$/i.test(a)},
getUrlVars:function(){for(var a=[],b,c=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),d=0;d<c.length;d++)b=c[d].split("="),a.push(b[0]),a[b[0]]=decodeURIComponent(b[1]);return a},getUrlVar:function(a){return Utils.getUrlVars()[a]},formatPrice:function(a,b){if(!a&&0!==a)return"";if(!b||0>b)b=2;var c;(c="string"==typeof a?parseFloat(a).toFixed(b):a.toFixed(b))&&0==c.indexOf(".")&&(c="0"+c);return c},padNumber:function(a,b,c){if(!a)return"";a+="";return a.length>=b?a:Array(b-
a.length+1).join(c||"0")+a},mergeErrors:function(a,b){if(!a||!a.message)return b;if(!b||!b.message)return a;var c={message:{}};if(a.message.messages||b.message.messages)c.message.messages=[],a.message.messages&&(c.message.messages=$.merge(c.message.messages,a.message.messages)),b.message.messages&&(c.message.messages=$.merge(c.message.messages,b.message.messages));if(a.message.systemErrors||b.message.systemErrors)c.message.systemErrors=[],a.message.systemErrors&&(c.message.systemErrors=$.merge(c.message.systemErrors,
a.message.systemErrors)),b.message.systemErrors&&(c.message.systemErrors=$.merge(c.message.systemErrors,b.message.systemErrors));if(a.message.fieldErrors||b.message.fieldErrors)c.message.fieldErrors=[],a.message.fieldErrors&&(c.message.fieldErrors=$.merge(c.message.fieldErrors,a.message.fieldErrors)),b.message.fieldErrors&&(c.message.fieldErrors=$.merge(c.message.fieldErrors,b.message.fieldErrors));return c},buildDropdown:function(a,b,c){var d="";c&&(d+='<option value="">'+c+"</option>");if(0<a.length)for(var e in a)d=
a[e].value===b?d+('<option selected="selected" value="'+a[e].value+'">'+a[e].name+"</option>"):d+('<option value="'+a[e].value+'">'+a[e].name+"</option>");return d},createElm:function(a,b,c,d,e){d=d?$("#"+d):$("body");b||(b="div");var f=d.find("#"+a);if(0==f.length){a=$("<"+b+"/>").attr("id",a);if(e)for(var g in e)val=e[g],a.attr(g,val);c&&a.hide();d.append(a);return a}return f.eq(0)},touchScrollElem:function(a){if(Modernizr&&Modernizr.touch){var b=navigator.userAgent,c=!1;if(0<=b.indexOf("Android"))2.3>=
parseFloat(b.slice(b.indexOf("Android")+8))&&(c=!0);else if(0<=b.indexOf("Silk"))c=!0;else return;if(c){var d=0,e=0;$("body").on("touchstart",a,function(a){d=this.scrollTop+a.originalEvent.touches[0].pageY;e=this.scrollLeft+a.originalEvent.touches[0].pageX});$("body").on("touchmove",a,function(a){(this.scrollTop<this.scrollHeight-this.offsetHeight&&this.scrollTop+a.originalEvent.touches[0].pageY<d-5||0!=this.scrollTop&&this.scrollTop+a.originalEvent.touches[0].pageY>d+5)&&a.preventDefault();(this.scrollLeft<
this.scrollWidth-this.offsetWidth&&this.scrollLeft+a.originalEvent.touches[0].pageX<e-5||0!=this.scrollLeft&&this.scrollLeft+a.originalEvent.touches[0].pageX>e+5)&&a.preventDefault();this.scrollTop=d-a.originalEvent.touches[0].pageY;this.scrollLeft=e-a.originalEvent.touches[0].pageX})}}},browserDeviceType:function(){var a="Other",b="Unknown",c="Other",d="Other OS",e;try{a=$.browser.msie?"IE":$.browser.mozilla?"Mozilla":$.browser.opera?"Opera":$.browser.webkit?"Webkit":"Other",b=$.browser.version,
e=navigator.userAgent,-1!=e.indexOf("Win")?(c=e.slice(e.indexOf("Windows NT")).split(" "),d="Windows NT "+c[2]):-1!=e.indexOf("Mac")?(c=e.slice(e.indexOf("Mac OS X")).split(" "),d="MacOSX "+c[3]):-1!=e.indexOf("x11")?d="UNIX":-1!=e.indexOf("linux")&&(d="Linux")}catch(f){}return htz.config.deviceGroup+"-"+a+"-"+b+"-"+d},getUniqueErrorKey:function(){try{var a=new Date;return"UE-"+this.padNumber(a.getUTCMonth()+1,2)+""+this.padNumber(a.getUTCDate(),2)+""+this.padNumber(a.getUTCHours(),2)+""+this.padNumber(a.getUTCMinutes(),
2)+"-"+a.getTimezoneOffset()+"-"+a.getSeconds()+"-"+a.getMilliseconds()*(Math.floor(100*Math.random())+1)}catch(b){return""}},isPrivateMode:function(){try{sessionStorage.setItem("private-mode","test"),sessionStorage.removeItem("private-mode")}catch(a){return!0}return!1}}}();"function"==typeof define&&define.amd&&define("utils/utils",[],function(){return Utils});htz.utils.Utils=Utils;
define("config/app-config",["utils/sessionhelper","json","reservation/process-config/core/reservation-constants"],function(a,c,b){if(htz&&htz.config)try{a.getItem(b.APP_CONFIG)||a.setItem(b.APP_CONFIG,c.stringify(htz.config))}catch(d){}return htz});
define("config/app-info",["config/app-config"],function(){var a=footerRef=null;return{setHeader:function(b){a=b},getHeader:function(){return a},setFooter:function(a){footerRef=a},getFooter:function(){return footerRef},doCleanup:function(){a=footerRef=null}}});
window.checkHertzNameSpace("htz.framework");htz.framework.DependencyManager=function(){var b=[];return{addDependencies:function(a,c){a&&(c&&0<c.length)&&(b[a]=c)},removeDependencies:function(a){a&&(b[a]=null)},getDependencies:function(a){return a?b[a]:null},reset:function(){b=[]}}}();getDependencies=htz.framework.DependencyManager.getDependencies;addDependencies=htz.framework.DependencyManager.addDependencies;
"function"==typeof define&&define.amd&&define("framework/dependency-injection/dependency-manager",[],function(){return htz.framework.DependencyManager});
define("framework/view/abstract-view",["backbone"],function(c){return c.View.extend({optional:!1,preInitialize:function(){},postInitialize:function(){},preSubmit:function(){return!0},preRender:function(){},postRender:function(){},doCleanup:function(){},refresh:function(){},renderView:function(a){try{return this.preRender(),this.renderYourself(a),this.postRender(),this}catch(b){if(this.isOptional())this.handleRenderFailure(b,a);else throw b;}},renderYourself:function(){},handleRenderFailure:function(){},
setOptional:function(a){this.optional=a},isOptional:function(){return this.optional}})});
define("utils/utils-proxy",["config/utilconfig"],function(c){var e={};return{getLightbox:function(){var a=e.lightbox;a||(a=[],e.lightbox=a);for(var b=null,d=0;d<a.length;d++)if(b=a[d],null!=b&&!b.isInUse())return b;b=new (c.getLightbox());a.push(b);return b},getSpinner:function(){return c.getSpinner()},getNotifier:function(){return c.getNotifier()},getSlider:function(){return c.getSlider()},getAciveLightboxes:function(){var a=e.lightbox,b=[];if(a&&0<a.length)for(var d=null,c=0;c<a.length;c++)d=a[c],
null!=d&&d.isInUse()&&b.push(d);return b},doCleanup:function(){e={}}}});
define("utils/tracker",[],function(){return{track:function(a){a&&(Global&&"function"===typeof Global.track)&&Global.track(a)}}});
(function(){navigator.cookieEnabled||(window.location.href=htz.config.rootContext+"/errors/jsCookieErrorPage?noCookie=true")})();                                                                                                                                                                                          
var RestModel=Backbone.Model.extend({initialize:function(){this.on("error",this.syncError,this);this.on("sync",this.syncSuccess,this)},parse:function(a,b){if(Utils.hasSessionTimedOut(b,null))this.trackSessionTimeout(),this.handleSessionTimeout(b.getResponseHeader("Location"));else return a?a.data?this.parseModel(a.data):this.parseModel(a):this.parseModel({})},parseModel:function(a){return a},syncSuccess:function(a,b){b&&(b.message&&(b.message.fieldErrors||b.message.messages||b.message.systemErrors)?
(Utils.trackError(b.message,this.getPage()),this.get("preventErrorStorage")||(htz.helpers.SessionHelper.setItem("errors",JSON.stringify(b.message)),Utils.isUseStoragePolyfill()&&Utils.storeItemIE("ieErrors",b.message))):this.get("preventErrorStorage")||htz.helpers.SessionHelper.removeItem("errors"))},getErrors:function(a){try{return"string"==typeof a?null:JSON.parse(a.responseText)}catch(b){try{var c=window.location.hash,c=c?c.substring(1):"itinerary",d=""+a.responseText;0<d.length&&(d=d.replace(/(\r\n|\n|\r)/gm,
""),100<d.length&&(d=d.substring(0,100)));WebTracking.setError("debug-error-"+Utils.browserDeviceType()+"-"+c+"-"+this.get("href")+"-"+d+"-"+b.message,c)}catch(e){}return null}},syncError:function(a,b,c){a=b&&b.status?b.status:null;htz.helpers.SessionHelper.removeItem("errors");this.handleStatus(a,b,c);Loader.hideLoader()},handleStatus:function(a,b,c){if(htz.config.isApp&&(500==a||403==a))try{$.publish("error-"+a)}catch(d){}else 500===a?this.handleError500():403===a?this.handleError403():this.checkForErrors(this.getErrors(b),
c)},handleError500:function(){window.location.href=htz.config.rootContext+"/error/index.jsp"},handleError403:function(){window.location.href=htz.config.rootContext+"/reservation/"},handleSessionTimeout:function(a){a&&(window.location.href=a)},checkForErrors:function(a,b){if(a){if(a.message){this.trigger("message",this,a.message);a.message.fieldErrors&&this.trigger("fieldError",this,a.message.fieldErrors,b);if(a.message.messages||a.message.systemErrors||a.message.errorData){"phone"===htz.config.deviceGroup?
window.scrollTo(0,60):window.scrollTo(0,0);var c=b||this.get("errorLocation")||this.getErrorLocation();Utils.displayErrorMessage(a.message,c);a.message.messages?this.trigger("messages",this,a.message.messages):this.trigger("systemErrors",this,a.message.systemErrors);a.message.errorData&&this.trigger("errorData",this,a.message.errorData)}Utils.trackError(a.message,this.getPage())}a.data&&this.trigger("errordata",this,a.data)}},saveChanged:function(a,b,c){var d;_.isObject(a)||null==a?(d=a,c=b):(d={},
d[a]=b);a=this.changedAttributes()?_.extend(this.changedAttributes(),d):d;a=this.isNew()?a:_.extend(a,{id:this.get("id")});c=c?_.clone(c):{};c=_.extend(c,{data:JSON.stringify(a),contentType:"application/json"});this.save(d,c)},url:function(){return this.get("href")},getPage:function(){return null},getErrorLocation:function(){return null},trackSessionTimeout:function(){try{"undefined"!==typeof WebTracking&&WebTracking.trackData({eVar22:"NZX305"})}catch(a){}}});
"function"==typeof define&&define.amd&&define("utils/restmodel",["backbone"],function(){return RestModel});                                                          
/**
    @description  jQuery Cookie plugin - https://github.com/carhartl/jquery-cookie. 
    Dual licensed under the MIT and GPL licenses:
 	http://www.opensource.org/licenses/mit-license.php
	http://www.gnu.org/licenses/gpl.html
    @requires Jquery
 */ 
(function(g){g.cookie=function(h,b,a){if(1<arguments.length&&(!/Object/.test(Object.prototype.toString.call(b))||null===b||void 0===b)){a=g.extend({},a);if(null===b||void 0===b)a.expires=-1;if("number"===typeof a.expires){var d=a.expires,c=a.expires=new Date;c.setDate(c.getDate()+d)}b=""+b;return document.cookie=[encodeURIComponent(h),"=",a.raw?b:encodeURIComponent(b),a.expires?"; expires="+a.expires.toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":
""].join("")}for(var a=b||{},d=a.raw?function(a){return a}:decodeURIComponent,c=document.cookie.split("; "),e=0,f;f=c[e]&&c[e].split("=");e++)if(d(f[0])===h)return d(f[1]||"");return null}})(jQuery);                                                                                                                                                       
window.checkHertzNameSpace("htz.utils");
var LightBox=LightBox||function(){var c=function(){c.OVERLAYSEQUENCE+=1;this.id="light-box-"+c.OVERLAYSEQUENCE;this.zIndex+=10*c.OVERLAYSEQUENCE;c.INSTANCES.push(this)};c.OVERLAYSEQUENCE=0;c.INSTANCES=[];c.adjust=function(){for(var a=0;a<c.INSTANCES.length;a++){var b=c.INSTANCES[a];b&&b.isInUse()&&b.adjustBackground()}};var d=null;c.prototype={inUse:!1,zIndex:1050,backBreak:600,avlWidth:0,pageContainer:null,id:"",background:null,foreground:null,dataContainer:null,orginalWidth:0,setDefaults:function(){this.params=
{url:"",top:0,left:0,width:500,height:"auto",hCenter:!0,vCenter:!1,scroll:!1,darkness:0.4,dismiss:!0,complete:null,error:null,close:null,zIndex:0,closeLabel:null,title:null,footNote:null,sourceElement:null,sourceElementOffset:null,bgSourceElement:null,plain:!1,referrer:null,hMargin:80,backButton:!0,showBackButton:!0,suppressClose:!1,autoScrollAdjust:!0}},getDisplayWidth:function(){return $("body").width()},ajaxError:function(a){try{this.showContent(htz.content.ajaxFail)}catch(b){}"function"==typeof this.params.error&&
this.params.error(a)},ajaxComplete:function(a){"function"==typeof this.params.complete&&this.params.complete(a)},renderTemplate:function(){var a=[];a.push('<div class="lb-background"></div>');a.push('<div class="lb-foreground">');this.params.backButton&&(this.params.showBackButton&&!htz.config.isApp)&&a.push('<div class="lb-back lb-close"><div><div class="icons-back_icon"></div></div><div>'+this.params.backLabel+"</div></div>");a.push('<div class="lb-foreground-cont">');this.params.plain||(this.params.suppressClose?
a.push('<header class="lb-header clearfix"><span class="swoosh multiline"><section>'+this.params.title+'</section></span><span class="lb-close lb-deny"></span></header>'):this.params.title&&this.params.closeLabel?(a.push('<header class="lb-header clearfix"><span class="swoosh multiline"><section>'+this.params.title+'</section></span><span class="lb-close lb-deny">'+this.params.closeLabel+'<div class="icons-yellow_x lb-close-icon"></div></span></header>'),htz.config.isApp&&(a.push('<a id="lbBackButton" onclick="$(&apos;.lb-back&apos;).trigger(&apos;click&apos;);"><span></span></a>'),
a.push('<a id="lbCloseButton" onclick="$(&apos;.lb-back&apos;).trigger(&apos;click&apos;);"><span></span></a>'))):this.params.closeLabel&&this.backBreak<=this.avlWidth&&a.push('<header class="lb-header-plain clearfix"><span class="lb-close lb-deny">'+this.params.closeLabel+'<div class="icons-yellow_x lb-close-icon"></div></span></header>'));a.push('<div class="lb-content-box"></div>');this.params.footNote&&a.push('<footer class="lb-footer">'+this.params.footNote+"</footer>");a.push("</div>");this.params.backButton&&
(this.params.showBackButton&&htz.config.isApp)&&a.push('<div class="lb-back lb-close"><div class="lb-back-btn"><div><div class="icons-back_icon"></div></div><div>'+this.params.backLabel+"</div></div></div>");a.push("</div>");return a.join("")},initTemplate:function(){this.params.backLabel=this.params.closeLabel;if(!this.params.closeLabel)try{this.params.closeLabel=htz.content.close,this.params.backLabel=htz.content.back}catch(a){}this.params.closeLabel||(this.params.dismiss=!0);0<this.params.zIndex&&
(this.zIndex=this.params.zIndex);var b=this.renderTemplate();0==$("#"+this.id).length?(0<$(".tmplPageContainer").length?this.pageContainer=$(".tmplPageContainer"):0<$("#container").length&&(this.pageContainer=$("#container")),this.pageContainer.after($("<div />").attr("id",this.id).html(b))):$("#"+this.id).html(b);this.background=$("#"+this.id+" .lb-background").css({"z-index":this.zIndex});this.foreground=$("#"+this.id+" .lb-foreground").css({"z-index":this.zIndex+5});this.dataContainer=$("#"+this.id+
" .lb-content-box");0==this.params.darkness?this.foreground.addClass("lb-foreground-shadow"):this.foreground.removeClass("lb-foreground-shadow");htz.config.isApp&&$("#"+this.id).show();this.adjustBackground()},closeOverlay:function(a){this.isInUse()&&(!a&&"function"==typeof this.params.close&&(this.params.referrer?this.params.close.call(this.params.referrer):this.params.close()),this.hide(),htz.config.isApp&&$("#"+this.id).hide())},makeRequest:function(){var a=this;a.showLightbox();a.showProgress();
$.ajax({type:"post",url:a.params.url,success:function(b,c,d){"undefined"!=typeof Utils&&Utils.sessionTimedOut(d)||a.showContent(b)},error:function(b,c,d){a.ajaxError(d)},complete:function(b){a.ajaxComplete(b)}})},adjustScroll:function(){d&&(window.scrollTo(d.x,d.y),d=null)},hide:function(){this.foreground.hide();this.background.hide();this.pageContainer.show();"undefined"!=typeof Utils&&Utils.showSelects();this.unbindEvents();this.inUse=!1;"phone"===htz.config.deviceGroup&&this.params.autoScrollAdjust&&
this.adjustScroll()},show:function(a){this.showLightbox();this.showContent(a)},showLightbox:function(){this.params.backButton&&this.avlWidth<this.backBreak?(this.pageContainer.hide(),this.background.css({opacity:this.params.darkness})):("undefined"!=typeof Utils&&Utils.hideSelects(),this.background.css({opacity:this.params.darkness}).show());this.foreground.show();"phone"===htz.config.deviceGroup&&window.scrollTo(0,0)},showProgress:function(){this.dataContainer.html($("<div />").addClass("lb-progress"))},
showContent:function(a){this.isInUse()?("auto"===this.params.height?this.dataContainer.css({"overflow-y":"auto"}):this.dataContainer.css({height:this.params.height,"overflow-y":"scroll"}),this.dataContainer.html(a)):this.dataContainer.html("")},setPosition:function(){"phone"===htz.config.deviceGroup&&(this.params.autoScrollAdjust&&!d)&&(d={x:void 0!==window.pageXOffset?window.pageXOffset:(document.documentElement||document.body.parentNode||document.body).scrollLeft,y:void 0!==window.pageYOffset?window.pageYOffset:
(document.documentElement||document.body.parentNode||document.body).scrollTop});this.avlWidth=this.getDisplayWidth();if(this.params.backButton&&this.avlWidth<this.backBreak)this.params.width=this.avlWidth-20,this.pageContainer.hide(),this.background.hide(),this.foreground.css({top:0,left:0,width:this.params.width}),htz.config.isApp&&this.foreground.css("max-width",this.params.width+20);else{this.pageContainer.show();this.background.show();this.params.backButton||(this.foreground.addClass("fullWidth"),
this.params.hMargin=10);this.params.width=this.avlWidth-this.params.hMargin<this.orginalWidth?this.avlWidth-this.params.hMargin:this.orginalWidth;0<this.params.left?this.params.left+this.params.width>this.avlWidth&&(this.params.hCenter=!0):this.params.hCenter=!0;if(this.params.sourceElement){var a=$(this.params.sourceElement).offset();this.params.left=this.params.hCenter?Math.round((this.avlWidth-this.params.width)/2):$("body").width()>a.left+this.params.width+25?a.left+25:a.left>this.params.width+
5?a.left-this.params.width-5:a.left-this.params.width/2;this.params.top=this.params.sourceElementOffset?a.top+this.params.sourceElementOffset:a.top;this.params.dismiss&&this.background.removeClass("lb-close-ncursor")}else this.params.hCenter&&(this.params.left=Math.round((this.avlWidth-this.params.width)/2)),0==this.params.top&&(this.params.top=$(document).scrollTop()+100),this.params.dismiss&&this.background.addClass("lb-close-ncursor");this.background.css({width:$(document).width(),height:$(document).height()});
this.foreground.css({width:this.params.width,top:this.params.top,left:this.params.left})}},adjustBackground:function(){this.params.bgSourceElement?this.background.css({width:$(document).width(),height:$(document).height(),top:$(this.params.sourceElement).offset().top}):this.background.css({width:$(document).width(),height:$(document).height()})},showPageData:function(){var a="string"==typeof this.params.url?$("#"+this.params.url).get(0):this.params.url;this.show($(a).html())},bindEvents:function(){var a=
this;a.params.hCenter&&($(window).bind("resize.lightBox",function(){a.setPosition();a.params.bgSourceElement&&a.adjustBackground()}),$(window).bind("orientationchange.lightBox",function(){a.setPosition();a.params.bgSourceElement&&a.adjustBackground()}));a.params.scroll&&$(window).bind("scroll.lightBox",function(){a.setPosition()});a.params.dismiss&&$(document).bind("keyup.lightBox",function(b){27==b.keyCode&&a.closeOverlay()});a.params.dismiss?a.background.addClass("lb-close-ncursor"):a.background.removeClass("lb-close-ncursor");
$("#"+a.id+" .lb-close, #"+a.id+" .lb-close-ncursor").bind("click",function(){a.closeOverlay()})},unbindEvents:function(){$(window).unbind(".lightBox");this.background.unbind("click");$(document).unbind("keyup.lightBox");$("#"+this.id+" .lb-close, #"+this.id+" .lb-close-ncursor").unbind("click")},init:function(){this.avlWidth=this.getDisplayWidth();this.orginalWidth=this.params.width;this.initTemplate();this.bindEvents();this.setPosition()},getDataContainer:function(){return this.dataContainer},isInUse:function(){return this.inUse},
overlay:function(a,b){this.inUse=!0;this.setDefaults();this.params=$.extend(this.params,a);this.init();b?this.show(b):"string"==typeof this.params.url&&0<=this.params.url.indexOf("/")?this.makeRequest():this.showPageData()}};return c}();htz.utils.LightBox=LightBox;"function"==typeof define&&define.amd&&define("utils/lightbox",[],function(){return LightBox});                                                                                                                                                                                                 
var LazyLoad=function(){var a=[],c=[];return{init:function(){a=a.concat(c);a.length&&function(b){var e=arguments.callee,d=a[b],c=d.complete;d.complete=function(d,f){c&&c(d,f);b+1<a.length&&e(b+1)};$.ajax(d)}(0)},queueJS:function(b,e){"high"==e?a.push(b):c.push(b)}}}();                                                                                                                                                                                                                                    
window.checkHertzNameSpace("htz.utils");
var Loader=Loader||function(){function d(a,e){var b=$("body").width(),c=$(window).height();htz&&htz.config&&"desktop"===htz.config.deviceGroup?a.css({left:b/2,top:$(document).scrollTop()+100}):a.css({left:b/2,top:$(document).scrollTop()+(c-40)/2});e.css({opacity:0.4,background:"#000","z-index":99999,position:"fixed",top:0,left:0,right:0,bottom:0})}var c,b;$(document).ready(function(){$("input[type='submit'], button.submit").click(function(){Loader.showLoader()});$(window).bind("resize.loader",Loader.resize);
window.onorientationchange=function(){Loader.resize()}});return{resize:function(){var a=$("#loading-fg"),b=$("#loading_bg");a.length&&b.length&&d(a,b)},spin:function(a){a||(a={});a.timeout||(a.timeout=25E3);this.showLoader(a)},showLoader:function(a){Loader.reset();var b=$("<div />").attr("id","loading_bg"),c=$("<div />").attr("id","loading-fg").addClass("loading-fg");d(c,b);b.appendTo($("body")).show();c.appendTo($("body")).show();Loader.setTimer(a)},setTimer:function(a){a&&a.timeout&&(b&&window.clearTimeout(b),
b=window.setTimeout(Loader.hideLoader,a.timeout),(a=a.callback)&&"function"==typeof a&&(c=a))},reset:function(){c=null;this.resetTimer();Loader.hideLoader()},resetTimer:function(){b&&window.clearTimeout(b);b=null},stop:function(){this.hideLoader()},hideLoader:function(){try{this.resetTimer()}catch(a){}$("#loading_bg, #loading-fg").remove();c&&(c(),c=null)}}}();htz.utils.Spinner=Loader;"function"==typeof define&&define.amd&&define("utils/loader",[],function(){return htz.utils.Spinner});                                                                                                           
if(typeof window.localStorage=="undefined"||typeof window.sessionStorage=="undefined")(function(){var e=function(e){function t(e,t,n){var r,i;if(n){r=new Date;r.setTime(r.getTime()+n*24*60*60*1e3);i="; expires="+r.toGMTString()}else{i=""}document.cookie=e+"="+t+i+"; path=/"}function n(e){var t=e+"=",n=document.cookie.split(";"),r,i;for(r=0;r<n.length;r++){i=n[r];while(i.charAt(0)==" "){i=i.substring(1,i.length)}if(i.indexOf(t)==0){return i.substring(t.length,i.length)}}return null}function r(n){var r=[],i,s,o;for(o in n){i=n[o];s=typeof i;if(s=="string"){r.push("'"+o+"':"+String(i))}}n="{"+String(r)+"}";if(e=="session"){window.name=n}else{t("localStorage",n,365)}}function i(){if(e=="session"){window.name=""}else{t("localStorage","",365)}}function s(){var t=e=="session"?window.name:n("localStorage");try{var r=jQuery.parseJSON(t);return r!=null?r:{}}catch(i){return{}}}var o=s();return{length:0,clear:function(){o={};this.length=0;i()},getItem:function(e){return o[e]===undefined?null:o[e]},key:function(e){var t=0;for(var n in o){if(t==e)return n;else t++}return null},removeItem:function(e){delete o[e];this.length--;r(o)},setItem:function(e,t){o[e]=t+"";this.length++;r(o)}}};if(typeof window.localStorage=="undefined")window.localStorage=new e("local");if(typeof window.sessionStorage=="undefined")window.sessionStorage=new e("session")})();var HStorage=function(e,t){var n=[];return{setItem:function(r,i,s,o){var u;if(s){u='{"data":"'+i+'", "exp":'+((new Date).getTime()+s*24*60*60*1e3)+"}"}else{u='{"data":"'+i+'"}'}if(o=="s"){if(typeof e!="undefined"){try{e.setItem(r,u)}catch(a){n[r]=u}}else{n[r]=u}}else{if(typeof t!="undefined"){try{t.setItem(r,u)}catch(a){}}}},removeItem:function(r,i){if(i=="s"){if(typeof e!="undefined"){try{e.removeItem(r);n[r]=null}catch(s){n[r]=null}}else{n[r]=null}}else{if(typeof t!="undefined"){try{t.removeItem(r)}catch(s){}}}},getItem:function(r,i){if(i=="s"){if(typeof e!="undefined"){var s=null;try{s=e.getItem(r);if(!s){s=n[r]}}catch(o){s=n[r]}if(s!=null){try{return jQuery.parseJSON(s).data}catch(o){return null}}else{return null}}else{if(n[r]!=null){try{return jQuery.parseJSON(n[r]).data}catch(o){return null}}else{return null}}}else{if(typeof t!="undefined"){try{var u=t.getItem(r);var a=jQuery.parseJSON(u);if(a&&a.exp){if((new Date).getTime()>a.exp){HStorage.removeItem(r);return null}}return a!=null?a.data:null}catch(o){return null}}else{return null}}}}}(window.sessionStorage,window.localStorage)      
window.checkHertzNameSpace("htz.utils");
htz.utils.Tracking=function(){function i(a){a&&(a.process&&a.step)&&$(window).trigger("track-"+a.process+"-"+a.step)}function h(a){var g={cache:!1,dataType:"html",success:function(b,c,d){if(!htz.utils.Utils.sessionTimedOut(d)){c=$("#web-tracking-container");0<c.length?c.unbind().empty():(c=$("<div/>").attr("id","web-tracking-container").hide(),$("body").append(c));try{c.html(b)}catch(e){}try{"Y"==a.dataonly&&"N"!=a.omniture&&htz.utils.OmnitureHelper.track(htz.omniture,c)}catch(h){}if(!a||!(a.bt&&
"N"==a.bt))for(var f=$(b).filter("script"),b=document.createElement("script"),c=0;c<f.length;c++)if(d=$(f).eq(c).text(),!0===RegExp("site","g").test(d)){f=$("script[type*=javascript]");for(c=0;c<f.length;c++){var g=$(f[c]);if(g&&"//s.btstatic.com/tag.js"===g.attr("src")){i(a);return}}b.setAttribute("type","text/javascript");b.setAttribute("src","//s.btstatic.com/tag.js");b.setAttribute("async","true");b.innerHTML=d;a&&($(window).off("btReady"),$(window).on("btReady",function(){setTimeout(function(){i(a)},
0)}));document.body.appendChild(b);break}}}},b=[];a&&(a.bt&&b.push("bt="+a.bt),a.ga&&b.push("ga="+a.ga),a.tags&&b.push("tags="+a.tags),a.omniture&&b.push("omniture="+a.omniture),a.dataonly&&b.push("dataonly="+a.dataonly));0<b.length?(b=b.join("&"),b="&"+b):b="";var d=a&&a.step?a.step:document.location.hash;try{d&&0<=d.indexOf("#")&&(d=d.substring(d.indexOf("#")+1))}catch(h){}var e="webTracking.jsp";try{"Y"==a.dataonly&&"N"!=a.omniture&&(e="omnitureTracking.jsp")}catch(j){}e=a.rootContext+"/templates/framework/"+
e+"?";e+="targetPage="+a.targetPage+b+"&hashValue="+d+"&originatingUrl="+document.location.href;g.url=e;return g}return{track:function(a){a&&(a.isApp&&(a.bt=a.ga=a.tags="N",a.dataonly="Y"),$.ajax(h(a)))}}}();                                                                                                                                                      
window.checkHertzNameSpace("htz.utils");
var Global=htz.utils.Global=function(){function d(a){a||(a={});a.rootContext=htz.config.rootContext;a.isApp=htz.config.isApp;var b="",b=a&&a.targetPage?a.targetPage:htz.config.legacyPage&&""!==htz.config.legacyPage?htz.config.legacyPage:htz.config.targetPage;a.targetPage=b;htz.utils.Tracking.track(a)}document.addEventListener?document.addEventListener("touchstart",function(){},!1):document.attachEvent&&document.attachEvent("touchstart",function(){});try{$.subscribe("resource-load-failure",function(a,
b){htz.utils.Global.trackResourceLoadFailure(b)})}catch(f){}var e=function(){-1===window.location.href.indexOf("manage-cookies")&&(this.cookieOverlay=new LightBox,this.cookieOverlay.overlay({url:htz.config.rootContext+"/templates/integrated/cookielaw/cookiePopup.jsp?rootContext="+htz.config.rootContext,title:"&nbsp;",width:584,dismiss:!1,center:!0,close:function(){$.cookie("cookie_pref","1_2_3_4",{path:"/",expires:1E3});$("body").trigger("euCookieSaved")}}));$("body").bind("euCookieSaved",function(){d()})};
return{initiateTracking:function(a){htz.config.isOmnitureToLoad&&(!htz.config.isCountryinEuropeUnion||htz.config.isCountryinEuropeUnion&&-1!=document.cookie.indexOf("cookie_pref"))&&d(a)},track:function(a){this.initiateTracking(a)},loadManifest:function(){"IRAC"===htz.config.subSystemId&&!$.browser.mozilla&&$("<iframe />",{id:"cache-manifest",src:htz.config.rootContext+"/templates/manifest.jsp?deviceGroup="+htz.config.orgDeviceGroup}).appendTo("body")},showEstara:function(a,b){if(!htz.config.isApp&&
a.length&&"phone"!==htz.config.deviceGroup&&"tablet"!==htz.config.deviceGroup){var c={cache:!1,dataType:"script"};b||(b=htz.eStara.url);c.url=htz.config.protocol+"://"+b;window.eStaraText=a;$(".tmplLayoutLeftColumn").empty().append('<div id="eStaraDiv" style="height:88px;margin-top:10px;"></div>');$.ajax(c)}},removeEstara:function(){$(".tmplLayoutLeftColumn").empty().hide();var a=this.getEstaraId();a&&$("#"+a).remove();$("#estara-text").remove()},getEstaraId:function(){try{return wv_vars.timeout336323_layerid}catch(a){}return null},
initiateFooterMisc:function(){if(0<$("#footer-container").length){var a={cache:!1,dataType:"html",success:function(){htz.integrated.footer.controller.FooterController.showFooterPage()},complete:function(){LightBox.adjust()}};a.url=htz.config.rootContext+"/framework/globalLazyLoad.jsp?targetPage="+htz.config.targetPage;LazyLoad.queueJS(a,"high")}},handleCookieLaw:function(){htz.config.isCountryinEuropeUnion&&-1==document.cookie.indexOf("cookie_pref")&&e()},initiate:function(){this.bindRequireJSListener();
htz.config.isApp?(Utils.showErrorFromSession(),setTimeout("LazyLoad.init()",1)):(this.handleCookieLaw(),this.loadManifest(),this.showEstara(htz.eStara.text,htz.eStara.url),this.initiateFooterMisc(),htz.config.isSPP||this.initiateTracking(),setTimeout("LazyLoad.init()",1),"Y"!=htz.browser.upgradeWarningShown&&(Modernizr.mq("only all")||(new LightBox).overlay({url:htz.config.rootContext+"/customersupport/templates/browserUpgradeWarningView.jsp",width:560,center:!0,scroll:!1,screen:70})),Utils.showErrorFromSession())},
trackResourceLoadFailure:function(a){try{var b=Utils.browserDeviceType(),c=window.location.hash,c=c?c.substring(1):"itinerary";a.requireModules&&WebTracking.setError("debug-resource-failure-"+(a.requireType||"unknown")+"-"+(b+"-"+c+"-"+a),c)}catch(d){}},bindRequireJSListener:function(){var a=Utils.browserDeviceType();try{if("undefined"===typeof requirejs||null===requirejs){WebTracking.setError("debug-resource-requirejs-missing-"+a);return}}catch(b){}requirejs.onError=htz.utils.Global.trackResourceLoadFailure}}}();
$(window).load(function(){htz.utils.Global.initiate()});        
var ErrorHelper=function(){function u(c){if(!c)return null;var a=null,d;for(d in c)null==a&&(a=""),a+="<li>"+d+"</li>";a&&(a="<ul class='"+n+"'>"+a+"</ul>");return a}var n="field-error-list",l=[],r=[],o=[],i=null,k=null,s=[],t=!0,p=null;return{displayErrors:function(c,a){if(c){var d;a&&a.context?this.reset(a.context):this.reset();a&&(d=a.mappings,i=a.context,k=a.allErrTarget,"undefined"!=typeof a.showErrorWithField&&(t=a.showErrorWithField),p=a.genericError);if(d&&0!=d.length)for(var j=0;j<d.length;j++)for(var f=
d[j],e=f.target,f=f.fields.split(","),m=0;m<f.length;m++)s[f[m]]=e;for(d=0;d<c.length;d++)if((e=c[d])&&0<e.length){j=e[0];f=null;1<e.length&&(f=e[1]);e=f;f=t;m=k;if(f&&e&&0<e.length){var h=s[j];h||(h=j+"_ut-err");var q=l[h];q||(q=[],l[h]=q);for(h=0;h<e.length;h++)f&&(q[e[h]]=""),!p&&m&&(o[e[h]]="")}p&&(o[p]="");r[j]=""}var b;i&&(b="string"==typeof i?$(i).eq(0):i);b||$(document);for(var g in l)(b=u(l[g]))&&(0<g.indexOf("_ut-err")?$("#"+g.substring(0,g.length-7)).closest("label").prepend(b):$("#"+g).html(b).show());
for(var n in r)g=null,b=$("#"+n),0<b.length&&(g=b.eq(0)),g&&((b=g.parent("label"))&&0<b.length?b.addClass("error"):(b=g.prop("tagName").toLowerCase(),("input"==b||"select"==b||"textarea"==b)&&g.addClass("error-input")));k&&(b=u(o))&&$(k).html(b).show()}else this.reset()},reset:function(c){var a;c?a=c:i&&(a=i);a&&(a="string"==typeof a?$(a).eq(0):a);a||(a=$(document));a.find(".error").removeClass("error");a.find(".error-input").removeClass("error-input");a.find("."+n).remove();c=$(k);0<c.length&&c.eq(0).empty().hide();
l=[];r=[];o=[];i=k=null;s=[];t=!0}}}();"function"==typeof define&&define.amd&&define("utils/errorutil",[],function(){return ErrorHelper});
var RightNow=function(a){path="US"==$("#return-pos").val()?"app/answers/list/kw/":"/kw/";"function"==typeof LightBox&&htz.rightNow.display&&(lbRightNow=new LightBox,domain=htz.rightNow.URL,url=-1!=$.inArray($("#return-pos").val(),["DE","ES","FR","IT","GB"])?domain+path+a.value+"/search/1":domain+path+a.value,a='<iframe id="ifrRightNow" style="border:0px;" frameborder="0" width="760" height="460" src="'+url+'"></iframe>',lbRightNow.overlay({width:"780",title:htz.rightNow.overlayTitle},a))}; 
window.checkHertzNameSpace("htz.helpers");htz.helpers.SessionHelper=function(d){var c=[];return{getItem:function(a){if("undefined"!=typeof d){var b=null;try{(b=d.getItem(a))||(b=c[a])}catch(e){b=c[a]}return b}return c[a]},setItem:function(a,b){if("undefined"!=typeof d)try{d.setItem(a,b)}catch(e){c[a]=b}else c[a]=b},removeItem:function(a){if("undefined"!=typeof d)try{d.removeItem(a),c[a]=null}catch(b){c[a]=null}else c[a]=null},removeListedItems:function(a){if(a&&0!=a.length)for(var b=0;b<a.length;b++)this.removeItem(a[b])}}}(window.sessionStorage);
"function"==typeof define&&define.amd&&define("utils/sessionhelper",[],function(){return htz.helpers.SessionHelper});             
window.checkHertzNameSpace("htz.helpers");
htz.helpers.ResourceLoader=function(i,o,l){function m(a,c,b){for(var e,d=0;d<c.length;d++)if(e=c[d],e===u)a[d]?b.css=a[d]:delete b.css;else if(e===n){e=a[d];try{i.setItem(b.content,l.stringify(e))}catch(f){}b.content=e}else e===p?b.template=a[d]:e===q&&(a[d]?b.js=a[d]:delete b.js);b.callback&&b.callback(b)}function r(a){for(var a=a.requireModules,c=0;c<a.length-1;c++)requirejs.undef(a[c])}function j(a,c){a&&c&&(c[a]=null,c["is"+a+"loaderror"]=!0)}function s(a,c,b){require(a.toLoad,function(b,d,f){m(arguments,
a.order,c)},function(e){r(e);if(b){var d=e.requireModules;if(d)for(var f=a.toLoad,i=a.order,g=0;g<=d.length-1;g++)for(var h=0;h<=f.length-1;h++)if(0<=f[h].indexOf(d[g])){f.splice(h,1);h=i.splice(h,1);j(h,c);break}0<a.toLoad.length?require(a.toLoad,function(b,d,e){m(arguments,a.order,c)},function(b){r(b);for(var b=a.order,d=0;d<b.length-1;d++)j(b[d],c);c.callback&&c.callback(c)}):t(c);try{o.publish("resource-load-failure",e)}catch(k){}}else window.setTimeout(function(){s(a,c,!0)},v)})}function t(a){if(a){if(a.content){var c=
i.getItem(a.content);if(c)try{c=l.parse(c),a.content=c}catch(b){i.removeItem(a.content),a.content=null,j(n,a)}}a.callback&&a.callback(a)}}var u="css",q="js",p="template",n="content",v=500;return{load:function(a){if(a){if(a.css){var c=a.css,b=document.getElementsByTagName("head").item(0),e=o(b).find("link"),d=!1;e.each(function(a){if(c==e.eq(a).attr("href"))return d=!0,!1});if(!d){var f=document.createElement("link");f.setAttribute("href",c);f.setAttribute("type","text/css");f.setAttribute("rel","stylesheet");
b.appendChild(f)}delete a.css}b=[];if(a){var f=[],j=a.template,g=a.content,h=a.js;if(g){var k=i.getItem(g);if(k)try{a.content=l.parse(k)}catch(m){i.removeItem(g),k=null}k||(g=0<g.indexOf("?")?g+"&callback=define":g+"?callback=define",f.push(n),b.push(g))}j&&(f.push(p),b.push("text!"+j));h&&(f.push(q),b.push(h));b={toLoad:b,order:f}}else b={toLoad:b};0<b.toLoad.length?s(b,a,!1):t(a)}}}}(htz.helpers.SessionHelper,$,JSON);"function"==typeof define&&define.amd&&define("helpers/resource-loader",[],function(){return htz.helpers.ResourceLoader});
window.checkHertzNameSpace("htz.utils.config");
htz.utils.config.UtilConfig=function(){var b,c,d,e,f,g,h,i,j;return{configure:function(a){a.spinner&&(b=a.spinner);a.lightBox&&(c=a.lightBox);a.networkHelper&&(d=a.networkHelper);a.navigator&&(e=a.navigator);a.rotar&&(f=a.rotar);a.domHelper&&(g=a.domHelper);a.router&&(h=a.router);a.notifier&&(i=a.notifier);a.slider&&(j=a.slider)},getSpinner:function(){return b},getLightbox:function(){return c},getNetworkHelper:function(){return d},getNavigator:function(){return e},getRotar:function(){return f},getDomHelper:function(){return g},
getRouter:function(){return h},getNotifier:function(){return i},getSlider:function(){return j}}}();"function"==typeof define&&define.amd&&define("config/utilconfig",[],function(){return htz.utils.config.UtilConfig}); 
var Tooltip=function(){};
Tooltip.prototype={defaults:{height:200,width:300,contentBgcolor:"#FEFED9",border:"3px solid #FFD60D",scroll:!1,closeLabel:!0,footerBgcolor:"#FFD60D",close:!0,closeLabel:htz.content.close},id:null,els:{},config:{},inUse:!1,show:function(a){this.inUse=!0;var b=$(a),a=b.parent().find(".tooltip-link:eq(0)"),b=b.parent().find(".tooltip-container:eq(0)");b.is(":hidden")?($(".tooltip-container").hide(),this.displayTooltip(b,a)):this.hide(b);return this},hide:function(a){$(a).hide()},create:function(a){this.config=
$.extend(!0,{},this.defaults,a);a=[];a.push('<div class="tooltip-container">');a.push('<div class="tooltip-content">');a.push('<div class="user-content">');a.push("</div> ");a.push("</div>");this.config.close&&(a.push('<div class="tooltip-footer learnMoreLink"> <span class="icons-close_lg close-pointer"> </span> <span class="close-pointer">'),this.config.closeLabel&&a.push(this.config.closeLabel),a.push("</span></div>"));a.push("</div>");a.join("");a=(a+"").replace(/\,/g,"");this.els.container=$(a).appendTo("#"+
this.config.containerID);this.els.tooltipContainer=this.els.container.find(".tooltip-container");this.els.innerContainer=this.els.container.find(".tooltip-content");this.els.close=this.els.container.find(".close-pointer");this.els.content=this.els.container.find(".user-content");this.els.content.append(""==this.config.content?defaults.content:this.config.content);this.els.overylay=this.els.container.find(".tooltip-container");this.els.footer=this.els.container.find(".tooltip-footer");this.els.innerContainer.css({width:""==
this.config.width?defaults.width:this.config.width,height:""==this.config.height?defaults.height:this.config.height,backgroundColor:""==this.config.contentBgcolor?defaults.contentBgcolor:this.config.contentBgcolor,overflow:"hidden",border:""==this.config.border?defaults.border:this.config.border,"overflow-y":!0==this.config.scroll?"scroll":"hidden"});this.els.footer.css({backgroundColor:""==this.config.footerBgcolor?defaults.footerBgcolor:this.config.footerBgcolor,width:""==this.config.width?defaults.width:
this.config.width});this.bindEvents();return this},displayTooltip:function(a,b){var a=$(a),b=$(b),f=b.offset().top,g=b.offset().left,h=$(window).height(),c=$(window).width(),d=b.position().top,e=b.position().left,d=f+a.height()>h+$(window).scrollTop()?b.position().top-a.height():b.position().top+b.height(),e=600<=c+$(window).scrollLeft()?g+a.width()+50>c+$(window).scrollLeft()?b.position().left-a.width():b.position().left+b.width():50;a.css({top:d,left:e});a.show();return this},bindEvents:function(){var a=
this;this.els.close.bind("click",function(b){target=$(b.target);b=target.closest(".tooltip-container");a.hide(b)})},isInUse:function(){return this.inUse}};

$(function(){window.checkHertzNameSpace("htz.integrated.header.views");htz.integrated.header.views.HeaderView=Backbone.View.extend({el:$("header"),events:{"click .logo-box":"logoClick","click .ra-logo-large":"raLogoClick","click .ra-logo-small":"raLogoClick","click #pos-change":"changePos","change #pos":"selectedCountry","keyup #pos":"pressedCountry","focus #search-input":"searchOnFocus","blur #search-input":"searchOnBlur","keydown #search-input":"searchOnKeyPress","click button.icons-magnifying_glass_icon":"searchBtnClick",
"click .mob-nav button":"mobMenuBtnOnClick","click .mob-sub-menu":"mobSubMenuOnClick","click .mob-back":"mobBackToMenu"},logoClick:function(a){a.stopPropagation();window.location.href=htz.navigation.homeURL},raLogoClick:function(a){a.stopPropagation();window.location.href="www.ryanair.com"},changePos:function(a){a.stopImmediatePropagation();$(".pos-tab").is(":visible")?$(".pos-box").slideUp("1000",function(){$(a.target).closest("li").removeClass("pos-tab")}):($(a.target).closest("li").addClass("pos-tab"),
$(".pos-box").slideDown("1000"));$(".pos-box #pos").val(htz.config.pos);$(".pos-tab").is(":visible")&&htz.config.pos!=$(".pos-box #pos").val()&&this.selectedCountry()},pressedCountry:function(a){13==a.keyCode&&this.selectedCountry()},selectedCountry:function(){var a;a=$("#pos").val();$.ajax({type:"post",url:htz.config.rootContext+"/PointOfSaleHandler",data:""!=a?"selectedPOS="+a:"",success:function(a){$("#language").empty().html(a)},error:function(){alert(htz.content.ajaxFail)}})},unbindBodyClick:function(a){$(".pos-tab").is(":visible")&&
!$.contains($(".pos-tab").get(0),a.target)&&$("#header-container .pos-box").slideUp("1000",function(){$("#header-container .change-link").removeClass("pos-tab")})},searchOnFocus:function(){$("#search-input").addClass("highlight");$("#search-input").val()==$("#default-search").val()?$("#search-input").val(""):$("#search-input").val(this.value)},searchOnBlur:function(){""==$("#search-input").val()&&($("#search-input").removeClass("highlight"),$("#search-input").val($("#default-search").val()))},searchOnKeyPress:function(a){if(13==
a.keyCode)return window.location.href=""!=$("#search-input").val()?htz.config.rootContext+"/customersupport/index.jsp?targetPage=faqsRightNow.jsp&search="+$("#search-input").val():htz.config.rootContext+"/customersupport/index.jsp?targetPage=faqsRightNow.jsp",!1},searchBtnClick:function(){$("#search-input").first().val()==$("#default-search").val()&&$("#search-input").first().val("");window.location.href=""!=$("#search-input").first().val()?htz.config.rootContext+"/customersupport/index.jsp?targetPage=faqsRightNow.jsp&search="+
$("#search-input").first().val():htz.config.rootContext+"/customersupport/index.jsp?targetPage=faqsRightNow.jsp";return!1},hideMemberFeature:function(){this.$el.find(".emember-container").hide()},showMemberFeature:function(){this.$el.find(".emember-container").show()},hidePosFeature:function(){this.$el.find(".pos-container ul").hide()},showPosFeature:function(){this.$el.find(".pos-container ul").show()},showSearchMini:function(){},showSearchFull:function(){this.$el.find(".search-box #search-input").show()},
navMenuTouchEnd:function(){var a=$(this);"undefined"!=typeof a.attr("href")&&""!=a.attr("href")&&(a=a.attr("href"),window.location=a)},navMenuMouseEnter:function(){$(this).find("dl").addClass("menu-show");$(this).closest("td:last-child").find("dl").addClass("last-menu-show");$(this).find("> a").addClass("menu-hover");$(this).find("> span").addClass("menu-hover");$(this).find("dd").first().children().addClass("no-pipe");var a=$(this).width()-1,b=$(this).find("dl").outerWidth();a>=b&&null!=b&&$(this).find("dl").width(a)},
navMenuMouseLeave:function(){$(this).find("dl").removeClass("menu-show");$(this).find("dl").removeClass("last-menu-show");$(this).find("> a").removeClass("menu-hover");$(this).find("> span").removeClass("menu-hover");$(this).find("dl").removeAttr("class");$(this).find("> a").removeAttr("class");$(this).find("> span").removeAttr("class")},navMenuMouseEnterIE:function(){$(this).find("dl").addClass("menu-show");$(this).closest("td:last-child").find("dl").addClass("last-menu-show");$(this).find("> a").addClass("menu-hover");
$(this).find("> span").addClass("menu-hover");$(this).find("> a").closest("td").addClass("menu-hover");$(this).find("> span").closest("td").addClass("menu-hover");$(this).find("dd").first().children().addClass("no-pipe");$.browser.msie&&"7">=$.browser.version.substring(0,1)&&($("#container").outerHeight(),$("#page").outerHeight(),$("#container > footer").outerHeight(),$(this).closest(".nav-menu").css("position","static"),$("#nav-container").css("position","static"));var a=$(this).width()-1,b=$(this).find("dl").outerWidth();
a>=b&&null!=b&&$(this).find("dl").width(a);a=$(this).find("dl").width();$(this).find("dl dd").width(a)},navMenuMouseLeaveIE:function(){$(this).find("dl").removeClass("menu-show");$(this).removeClass("menu-hover");$(this).find("dl").removeAttr("class");$(this).removeAttr("class");$(this).find("> a").removeAttr("class");$(this).find("> span").removeAttr("class")},navMenuOnClickIE:function(){0<!$(this).find("dl").length&&0<$(this).find("> a").length&&(window.location.href=$(this).find("> a").attr("href"))},
mobMenuBtnOnClick:function(){var a=$(".mob-menu div").outerHeight();$(".mob-nav-menu div").slideToggle(700,"swing",function(){$(this).is(":hidden")?$(".mob-nav-menu").height(0):$(".mob-nav-menu").height(a)});return!1},mobSubMenuOnClick:function(a){a.stopPropagation();a=$("#container").width();$(this).closest(".mob-menu").animate({left:"-"+a+"px"},"1000",function(){});$(".mob-sub-menu ul").hide();$(".mob-nav-menu").height($(this).children("ul").outerHeight());var b=$(this).offset().top-$(".mob-menu div").offset().top,
a=a-10;$(this).children("ul").show().width($(this).parent().width()).css({top:"-"+b+"px",left:a+"px"})},mobBackToMenu:function(a){a.stopPropagation();$("#container").width();a=$(".mob-menu div").outerHeight();$(this).closest(".mob-menu").animate({left:0},"1000",function(){});$(".mob-nav-menu").height(a);$(".mob-sub-menu ul").hide()},navigationItems:function(a){function b(a){var c=[];_.each(a,function(a){var d={};d.displayText=a.displayText;d.url=a.url;a.subMenus&&0<a.subMenus.length?(d.subMenus=b(a.subMenus),
d.isLeaf=!1):d.isLeaf=!0;c.push(d)});return c}var c=htz.template.topNavJson.data.navigationInfoMap,e=[];$.each(a?c.navigationItemsMobile:c.navigationItems,function(a,c){e=e.concat(b(c.subMenus))});return e},isLoggedIn:function(){var a=!1,b=htz.template.topNavJson.data.navigationInfoMap;b.navigationItems&&b.navigationItems[0]?a=b.navigationItems[0].loggedIn:b.navigationItemsMobile&&b.navigationItemsMobile[0]&&(a=b.navigationItemsMobile[0].loggedIn);return a},initialize:function(){topNavInitialized=
!0;var a=this.navigationItems(),b=this.navigationItems(!0),c=this.isLoggedIn();this.data={navigation:htz.template.topNavJson.data.content.navigation,topNav:htz.template.topNavJson.data.topNavigationInfo,member:htz.template.topNavJson.data,menuItems:a,menuItemsMobile:b,loggedIn:c};htz.config.renderHtml&&this.render()},render:function(){var a,b,c={};!0==RegExp("&search=","g").test(location.href)&&($.each(document.location.search.substr(1).split("&"),function(a,b){var f=b.split("=");c[f[0].toString()]=
f[1].toString()}),$("#search-input").val(c.search));b=this.data.topNav;b.rootContext=htz.config.rootContext;b.headerImageUrl=htz.config.protocol+"://images.hertz.com"+b.logoUrl;b.ryanairHeaderImage=htz.config.protocol+"://images.hertz.com"+b.raLargeLogoUrl;b.ryanairHeaderImageSmall=htz.config.protocol+"://images.hertz.com"+b.raSmallLogoUrl;$.each(b.nvpCountries,function(a,c){if(c.value===htz.config.pos)return b.countrySelectedName=c.name,-1});$.each(b.nvpLanguages,function(a,c){if(c.value===b.nvpLanguageSelected)return b.languageSelectedName=
c.name,-1});$("#nav-container").empty().append(_.template($("#nav-tpl").html(),this.data));a=_.template($("#header-tpl").html());$("#header-container").html(a(this.data));memNavloginModel=new sdlLoginModel;memNavloginView=new sdlLoginView({el:"header",model:memNavloginModel});if(Modernizr&&Modernizr.touch)$(".nav-menu a").on("touchend",this.navMenuTouchEnd);$.browser.msie&&"8">=$.browser.version.substring(0,1)?($(".nav-menu td").on("mouseenter",this.navMenuMouseEnterIE),$(".nav-menu td").on("mouseleave",
this.navMenuMouseLeaveIE),$(".nav-menu td").on("click",this.navMenuOnClickIE)):($(".nav-menu td").on("mouseenter",this.navMenuMouseEnter),$(".nav-menu td").on("mouseleave",this.navMenuMouseLeave));$("body, html").on("click",this.unbindBodyClick);return this}});var g=new htz.integrated.header.views.HeaderView;"function"==typeof define&&("function"==typeof require&&define.amd)&&require(["config/app-info"],function(a){a.setHeader(g)})});
var sdlLoginModel=Backbone.Model.extend({defaults:{loggedIn:!1,firstInit:"",firstName:"",lastName:"",prefix:"",suffix:"",legacyPage:htz.config.legacyPage,fullContext:htz.config.fullContext},url:htz.config.rootContext+"/member/authentication"}),sdlLoginView=Backbone.View.extend({events:{"click #loginLink":"toggleLoginForm","click #myaccount":"toggleLoginForm","click #cookieLink":"toggleLoginForm","click #loginButton":"homePageloginSubmit","click #logOut":"logOut","click #forgotMemberNumberLink":"forgotMemberNumberLink",
"click #forgotPwdLink":"forgotPwdLink","click .learnMoreLink":"infoOverlay","mouseover #loginButton":"lockBlack","mouseout #loginButton":"lockWhite","touchstart #loginButton":"lockWhite","touchend #loginButton":"lockWhite","mousedown #loginButton":"lockBlack","mouseup #loginButton":"lockWhite","click #loginCreateUserId":"loginCreateUserId","keypress #loginFormContainer ":"onEnterLogin","mouseover .loginLink":"yellowChange","mouseout .loginLink":"blueChange","touchstart .loginLink":"yellowChange",
"click #upgradeToGold":"upgradeToGold"},initialize:function(){_.bindAll(this,"renderTopNav","isCookied","renderLogin","toggleLoginForm","showLogin","hideLogin","homePageloginSubmit","logOut","forgotPwdLink","forgotMemberNumberLink","loginCreateUserId");this.isCookied();this.useridInfo=new Tooltip},onEnterLogin:function(a){target=a.keyCode;13==target&&(a.preventDefault(),$("#loginButton").trigger("click"))},isCookied:function(){var a=this;$.ajax({url:htz.config.rootContext+"/member/top/navigation",
dataType:"json",cache:!1,contentType:"application/json",beforeSend:function(){},success:function(b){a.model.set({prefix:b.data.prefix,firstName:b.data.firstName,lastName:b.data.lastName,suffix:b.data.suffix,loggedIn:b.data.loggedIn,cookieLaw:htz.config.isCountryinEuropeUnion});null!=a.model.get("firstName")&&""!=a.model.get("firstName")&&a.model.set("firstInit",a.model.get("firstName").substring(0,1));b.data.displayLogin&&(a.renderTopNav(),a.renderLogin());"N"==b.data.displayJoin&&($("#logIn").parent().css("display",
"none"),$("#loginLink").css("border-right","none"));"t"==a.getParameterByName("mN")&&(a.model.attributes.lastName?$("#cookieLink").trigger("click"):$("#loginLink").trigger("click"))},error:function(){}})},hideDropdowns:function(){$("#loginFormContainer").hide();$(".loginLink, .myaccount, .cookieLink").removeClass("loginActive").addClass("loginInActive");$(".loginLink")&&($(".loginLink").blur(),$(".loginLink").addClass("topNavPrimary"))},renderTopNav:function(){this.templateNav=_.template($("#topNavLinks").html());
this.$(".emember-container").html(this.templateNav(this.model.attributes));return this},renderLogin:function(){this.template=_.template($("#sdlLoginFromTemplate").html());this.$("#loginFormContainer").html(this.template(this.model.attributes));this.model.attributes.loggedIn&&$.ajax({url:htz.config.rootContext+"/member/account/navigation",dataType:"json",cache:!1,contentType:"application/json",beforeSend:function(){},success:function(a){var b=!1;if("undefined"!==typeof a.data){"1"!=a.data.clubType&&
"express"!=a.data.clubType&&$("#upgradeToGold").hide();"goldnotallowed"==a.data.goldPermission&&$("#upgradeToGold").hide();clubType=a.data.clubType;clubTier=a.data.clubTier;switch(clubType){case "G":b=!0;"PC"==clubTier?$("#memberNavClubHeader").html($("#numberOneClubPresidentCircle").html()):"FS"==clubTier?$("#memberNavClubHeader").html($("#numberOneClubFiveStar").html()):$("#memberNavClubHeader").html($("#numberOneClubGold").html());break;case "P":b=!0;$("#memberNavClubHeader").html($("#numberOneClubPlatinum").html());
break;case "1":b=!0;$("#memberNavClubHeader").html($("#numberOneClub").html());break;case "TA":a.data.displayExactlyRewardsLink&&$(".taNavLink").attr("href",a.data.hertzPartnersLink).html(a.data.hertzPartnersText).show(),$("#loggedInMember").hide(),$("#loggedInTravelAgent").show()}0==a.data.rewardsPoints?$("#mobileNavAwards").hide():$("#mobileGoldPoints").html(a.data.rewardsPoints);"IRAC"!=htz.config.subSystemId&&$("#mobileNavAwards").hide();for(i=0;i<a.data.items.length;i++)$("#loggedUserDetails").append("<li><a href="+
htz.config.rootContext+a.data.items[i].url+">"+("/emember/modify/awardsTab.do"==a.data.items[i].url?a.data.items[i].displayText+":"+a.data.rewardsPoints:a.data.items[i].displayText)+"</a></li>");b&&$("#myaccount").show()}else $("#myaccount").hide()},error:function(){}});return this},lockWhite:function(){$("#loginButton span").addClass("icons-white_lock").removeClass("icons-lock")},lockBlack:function(){$("#loginButton span").removeClass("icons-white_lock").addClass("icons-lock")},yellowChange:function(){$(".loginLink").hasClass("topNavPrimary")&&
$(".loginLink").addClass("topNavPrimaryHover");var a=this;"ontouchstart"in document.documentElement&&$("body").bind("touchmove",function(b){!$("#loginFormContainer").is(":visible")&&$(".loginLink").hasClass("topNavPrimaryHover")&&(a.blueChange(),$("body").unbind(b))})},blueChange:function(){$(".loginLink").hasClass("topNavPrimary")&&$(".loginLink").removeClass("topNavPrimaryHover")},toggleLoginForm:function(a){a.preventDefault();var b=this;if("https"===htz.config.protocol){var c="ontouchstart"in document.documentElement?
"touchstart":"click";if($("#loginFormContainer").is(":visible"))b.hideLogin();else{var d=$(a.target);!b.model.get("loggedIn")&&(null!=b.model.get("lastName")&&""!=b.model.get("lastName"))&&(d=d.closest("#cookieLink"));b.showLogin(d);$("#pos-change").bind("click",function(){b.hideLogin()});$(window).bind("resize",function(){clearTimeout(this.resizeEventHandler);resizeEventHandler=setTimeout(function(){$("#loginFormContainer").is(":visible")&&b.showLogin(d)},100)});$("body").not(a.currentTarget).not("#loginFormContainer").bind(c,
{originEle:a.currentTarget.id},function(a){var c=$("#"+a.data.originEle);$("#loginFormContainer").is(":visible")&&(0==c.has(a.target).size()&&a.target.id!=a.data.originEle&&0==$("#loginFormContainer").has(a.target).size())&&(b.hideLogin(),$("body").unbind(a))})}}else{"ontouchstart"in document.documentElement&&$(".loginLink")&&b.blueChange();var a=location.hash,c=document.URL.split(a)[0],e=-1==document.URL.indexOf("?")?"?":"&";window.location.href=c.replace("http:","https:")+e+"mN=t"+a}},showLogin:function(a){$(".tmplPageContainer").length&&
$(".tmplPageContainer").css({position:"static"});!a.is(":visible")&&$(".loginActive:visible")&&(a=$(".loginActive:visible"));var b=a.offset(),c=a.outerWidth(),d=a.outerHeight(),e=$("#loginFormContainer").outerWidth(),d=b.top+d,b=b.left+c-e;this.$("#loginFormContainer").css({top:d,left:b});$(".loginLink")&&$(".loginLink").removeClass("topNavPrimary").removeClass("topNavPrimaryHover");a.removeClass("loginInActive").addClass("loginActive");this.$("#loginFormContainer").slideDown("1000")},hideLogin:function(){this.$("#loginFormContainer").slideUp("1000",
function(){$(".loginLink, .myaccount, .cookieLink").removeClass("loginActive").addClass("loginInActive");$(".loginLink")&&($(".loginLink").blur(),$(".loginLink").addClass("topNavPrimary"))})},logOut:function(){Utils.clearReservationSession()},forgotMemberNumberLink:function(){window.location.href=htz.config.rootContext+"/emember/reset/memberNumberRetrieval.do"},forgotPwdLink:function(){$("#loginForgotPasswordNav").val("forgotPassword");this.homePageloginSubmit()},loginCreateUserId:function(){$("#loginCreateUserId").val("true");
this.homePageloginSubmit()},infoOverlay:function(a){a=$(a.target);this.useridInfo.isInUse()||this.useridInfo.create({containerID:"userid-info",content:this.$("#username-desc").html(),width:"inherit"});this.useridInfo.show(a)},homePageloginSubmit:function(){Loader.showLoader();var a=this;this.model.attributes.lastName?(this.model.clear(),this.model.set({cookieMemberOnLogin:!0,loginId:"cookie",password:$("#homePagePassword").val(),loginForgotPassword:$("#loginForgotPasswordNav").val()})):(this.model.clear(),
this.model.set({loginCreateUserID:$("#loginCreateUserId").val(),loginId:$("#homePageloginId").val(),password:$("#homePagePassword").val(),cookieMemberOnLogin:$("#cookieMemberOnLogin").is(":checked"),loginForgotPassword:$("#loginForgotPasswordNav").val()}));this.model.save(this.model.attributes,{success:function(a,c){var d=c.resultInfo.result;Loader.hideLoader();"input"==d||"login"==d?window.location.href=-1!=c.resultInfo.url.indexOf(htz.config.rootContext)?c.resultInfo.url:htz.config.rootContext+
c.resultInfo.url:"success"===d?0<window.location.href.indexOf("join")||0<window.location.href.indexOf("legacy")||0<window.location.href.indexOf("reset")||0<window.location.href.indexOf("enrollment")?window.location.href=c.resultInfo.url:window.location.reload():"success_to_profile"==d||"success_to_upgrade"==d?window.location.href=-1!=c.resultInfo.url.indexOf(htz.config.rootContext)?c.resultInfo.url+"?curPage="+c.resultInfo.result:htz.config.rootContext+c.resultInfo.url+"?curPage="+c.resultInfo.result:
null!=c.resultInfo.url&&void 0!==c.resultInfo.url?window.location.href=-1!=c.resultInfo.url.indexOf(htz.config.rootContext)?c.resultInfo.url+"?curPage="+c.resultInfo.result:htz.config.rootContext+c.resultInfo.url+"?curPage="+c.resultInfo.result:window.location.hreg=htz.config.rootContext+"?curPage="+c.resultInfo.result},error:function(b,c){var d=$.parseJSON(c.responseText).message;Utils.isUseStoragePolyfill()?Utils.storeItemIE("ieLoginError",d):(d=JSON.stringify(d),htz.helpers.SessionHelper.setItem("errorData",
d));b.set({errorLocation:"#homePageloginBox #error-list"},{silent:!0});a.model.trigger("error",b,c);Loader.hideLoader();d=$.parseJSON(c.responseText);window.location.href=null!=d.resultInfo.url&&void 0!==d.resultInfo.url?htz.config.rootContext+d.resultInfo.url+"?curPage="+d.resultInfo.result:htz.config.rootContext+"?curPage="+d.resultInfo.result}})},getParameterByName:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.search);return null==
a?"":decodeURIComponent(a[1].replace(/\+/g," "))},upgradeToGold:function(){$.ajax({url:htz.config.rootContext+"/rest/member/upgrade/gold",dataType:"json",cache:!1,contentType:"application/json",beforeSend:function(){},success:function(a){window.location.href="https://"+window.location.hostname+htz.config.rootContext+a.resultInfo.url},error:function(){}})}});
$(document).ready(function(){void 0===window.topNavInitialized&&(memNavloginModel=new sdlLoginModel,memNavloginView=new sdlLoginView({el:"header",model:memNavloginModel}))});
memberViewUtil=Backbone.View.extend({events:{},initialize:function(){_.bindAll(this,"infoMessage","closeOverlay","displayOverlay","hideLightBoxCloseBtn")},hideLightBoxCloseBtn:function(){$(".lb-close").hide()},infoMessage:function(a){var b=$(a),a=b.closest(".overlayPopup").find(".overlayPopupLink:eq(0)"),b=b.closest(".overlayPopup").find(".overlayPopupContent:eq(0)");b.is(":hidden")?($(".overlayPopupContent").hide(),this.displayOverlay(b,a,!1)):this.closeOverlay(b,!1)},displayOverlay:function(a,b,
c){a=$(a);b=$(b);$.browser.msie&&6==parseInt($.browser.version)&&$("select").css("visibility","hidden");var d=$(document).width(),e=$(document).height(),h=b.offset().top,j=b.offset().left,k=$(window).height(),l=$(window).width(),f=b.position().top,g=b.position().left,f=h+a.height()>k+$(window).scrollTop()?b.position().top-a.height():b.position().top+b.height(),g=j+a.width()+50>l+$(window).scrollLeft()?b.position().left-a.width():b.position().left+b.width();a.css({top:f,left:g});c&&(b=$("#overlayScreen"),
0==b.length&&(b=$("<div>").attr("id","overlayScreen").css({width:d,height:e}).addClass("overlayScreen").appendTo(document.body)),b.show());a.show()},closeOverlay:function(a,b){$.browser.msie&&6==parseInt($.browser.version)&&$("select").css("visibility","visible");b&&($(".overlayPopupContent").hide(),$("#overlayScreen").hide());$(a).hide()}});window.memUtil=new memberViewUtil({el:"body"});
function loginAndCreateUserIdSubmit(a){a.attr("method","post");a.attr("action",htz.config.rootContext+"/emember/submitLogin");$("#loginCreateUserID").val("true");a.submit()}; 
var passwordStrengthView=Backbone.View.extend({initialize:function(){this.template=this.options.template;this.passwordLevel="";this.setPasswordLevel();this.setElement(this.options.el)},render:function(a){var b=_.template($(this.template).html(),{deviceGroup:htz.config.deviceGroup});$(this.options.el).html(b);this.display(this.getPasswordStrength(a))},setPasswordLevel:function(){this.passwordLevel=[{indicator:$("#passwordInvalid").html(),cssClass:"passwordInvalid"},{indicator:$("#passwordShort").html(),
cssClass:"passwordShort"},{indicator:$("#passwordWeak").html(),cssClass:"passwordWeak"},{indicator:$("#passwordGood").html(),cssClass:"passwordStrong"}]},display:function(a){var b=this;if(0<=a){var c=b.passwordLevel[a].cssClass;$(this.options.el).find("#passwordMeter .progress").children().each(function(d){d<a?($(this).removeClass(b.oldCssClass),$(this).addClass(c),$(this).addClass("bar"),b.oldCssClass=c):($(this).removeClass(b.oldCssClass+"Bar"),$(this).addClass(c+"Bar"),b.oldCssClass=c+"Bar")});
$(this.options.el).find("#strength").html(this.passwordLevel[a].indicator);$(this.options.el).find("#strength").attr("class",this.passwordLevel[a].cssClass+"Meter");$(this.options.el).find("#strength").show();0==a?($(this.options.el).find(".invalidPasswordMessage").html($("#passwordAdvice").html()),$(this.options.el).find(".invalidPasswordMessage").show()):($(this.options.el).find(".invalidPasswordMessage").html(""),$(this.options.el).find(".invalidPasswordMessage").hide());$(this.options.el).show()}else $(this.options.el).find("#strength").html(""),
$(this.options.el).find("#strength").attr("class",""),$(this.options.el).find("#strength").hide(),$(this.options.el).hide()},getPasswordStrength:function(a){if(0!=a.length){if(-1==a.indexOf("*")){var b=/[a-z]/.test(a),c=/[0-9]/.test(a),d=/[^a-zA-Z0-9]/.test(a),e=/[A-Z]/.test(a);return 8<=a.length?b&&c&&d&&e?3:2:1}return 0}return-1}}); 
var resetConfirmationView=Backbone.View.extend({events:{"click #home-btn":"redirectHome","click #profile-btn":"gotoProfile","click #continue-res":"continueRes","click #oci-review-ok":"handleOCIandReview"},initialize:function(){_.bindAll(this,"renderResetConfirmation","redirectHome","gotoProfile");this.renderResetConfirmation()},renderResetConfirmation:function(){var a=_.template($("#pinResetConfirmationTemplate").html(),{});$(this.el).html(a);isRes||isOCI||isResReview?($("#profile-btn, #home-btn").hide(),
$("#pinResetConfirmationSection").css("width","auto"),$(".containerTableThickBorder, .containerTableBorder").css("border","none"),isOCI||isResReview?$("#continue-res").hide():$("#oci-review-ok").hide(),memUtil.hideLightBoxCloseBtn()):($("#navLogout").css("display","block"),$("#navLogin").hide(),$("#continue-res, #oci-review-ok").hide(),memNavloginView.isCookied())},redirectHome:function(){document.location.href=htz.config.rootContext+"/reservation/"},gotoProfile:function(){document.location.href=
htz.config.rootContext+"/emember/modify/profile"},continueRes:function(){HomePage.bookAsMemberSubmitRes()},handleOCIandReview:function(){if(isOCI)window.location.reload();else if(isResReview){var a=this.handleMemberRes||handleMemberRes;a&&"function"===typeof a?a():window.location.href=htz.config.rootContext+"/reservation/"}}}),resetPwdModel=RestModel.extend({url:htz.config.rootContext+"/member/reset/password"}),resetPwdView=Backbone.View.extend({defaults:{isRes:!1,isOCI:!1,isResReview:!1,clearError:!1},
events:{"click #resetSubmit":"resetPwdSubmit","keyup #password":"checkPassword","click .learnMoreLink":"learnMoreoverlay","click .bookAsGuest,#bookAsGuest":"bookAsGuestFromresetPage","click #strong-password-info":"showStrongPasswordInformation","blur #password":"hideStrongPasswordInformation"},initialize:function(){_.bindAll(this,"renderResetPwd","resetPwdSubmit","checkPassword","learnMoreoverlay");this.renderResetPwd();this.resetPassTooltip=new LightBox;this.model.on("fieldError",this.highlight,
this);this.passwordStrengthView=new passwordStrengthView({el:"#membershipDetailsPasswordIndicatorSection",template:"#password-strength-indicator"})},renderResetPwd:function(){var a=_.template($("#pinResetSectionTemplate").html(),{deviceGroup:htz.config.deviceGroup});$(this.el).html(a);if(isRes||isOCI||isResReview)if($("#pinResetSection").css("width","auto"),$(".containerTableThickBorder, .containerTableBorder").css("border","none"),$(".overlayPopup").hide(),isOCI||isResReview)$(".bookAsGuest").hide(),
$("#bookAsGuest").hide();this.IsUserClosed=this.IsUserExpanded=this.collapsed=this.isClickedOutside=!1},bookAsGuestFromresetPage:function(a){$(a.target).closest(".lb-close").triggerHandler("click");HomePage.bookAsGuestSubmitRes()},learnMoreoverlay:function(){this.resetPassTooltip.isInUse()||this.resetPassTooltip.overlay({title:this.$("#password-tooltip-label").html()},this.$("#instruction-content").html())},resetPwdSubmit:function(){var a=this;a.hidePasswordIndicator();Loader.showLoader();clearError&&
this.model.clear();this.model.set({password:$("#password").val(),passwordVerify:$("#passwordVerify").val()});this.model.save(this.model.attributes,{success:function(a,c){clearError=!1;var b=c.resultInfo.result;"success"==b?$.ajax({url:htz.config.rootContext+c.resultInfo.url,cache:!1,beforeSend:function(){},success:function(a){isRes||isOCI||isResReview?$(".lb-content-box").html("").html(a):$(".sectionWidthSmall").html("").html(a);(a=sessionStorage.getItem("platinum"))?(sessionStorage.removeItem("platinum"),
sessionStorage.setItem("resetPasswordConfirmationMessage",!0),document.location.href=htz.config.rootContext+a):new resetConfirmationView({el:"#pinResetConfirmationSection"})},error:function(){}}):"success_platinum"==b&&(sessionStorage.setItem("resetPasswordConfirmationMessage",!0),window.location.href=htz.config.rootContext+c.resultInfo.url);Loader.hideLoader()},error:function(d,c){clearError=!0;a.model.clear();d.set({errorLocation:"#pinResetSection .error-list"},{silent:!0});a.model.trigger("error",
d,c);Loader.hideLoader()}})},checkPassword:function(a){a=$(a.target).val();this.passwordStrengthView.render(a);this.checkIndicatorStatus()},highlight:function(a,d){ErrorHelper.reset();ErrorHelper.displayErrors(d,{mappings:[{fields:"password",target:"errorPassword"},{fields:"passwordVerify",target:"errorPasswordVerify"}],allErrTarget:"#pinResetSection .error-list"})},showStrongPasswordInformation:function(a){a=$(a.target);this.isClickedOutside?this.isClickedOutside=!1:(this.$(".password-info").slideToggle(),
a.hasClass("icons-blue-plus-box")?(a.addClass("icons-grey-minus-box").removeClass("icons-blue-plus-box"),this.IsUserExpanded=!0,this.IsUserClosed=!1):(a.removeClass("icons-grey-minus-box").addClass("icons-blue-plus-box"),this.IsUserClosed=!0,this.IsUserExpanded=!1))},hideStrongPasswordInformation:function(){this.collapsed||($(".password-info").slideToggle(),$("#strong-password-info").removeClass("icons-grey-minus-box").addClass("icons-blue-plus-box"),this.isClickedOutside=this.collapsed=!0);this.bindClickEvent()},
checkIndicatorStatus:function(){if(this.collapsed&&!this.IsUserExpanded||this.collapsed&&this.IsUserClosed)$(".password-info").slideToggle(),$("#strong-password-info").removeClass("icons-grey-minus-box").addClass("icons-blue-plus-box"),$(".password-info").hide()},hidePasswordIndicator:function(){var a=$("#strong-password-info");a.hasClass("icons-grey-minus-box")&&($(".password-info").slideToggle(),a.removeClass("icons-grey-minus-box").addClass("icons-blue-plus-box"),$(".password-info").hide())},bindClickEvent:function(){var a=
this;$("body").bind("click",function(d){$(d.target);a.isClickedOutside=!1;$("body").unbind("click")})}}),CardType=Backbone.Model.extend(),CardTypes=Backbone.Collection.extend({url:htz.config.rootContext+"/rest/member/creditcard-list",model:CardType}),CardTypeView=Backbone.View.extend({tagName:"option",initialize:function(){_.bindAll(this,"render")},render:function(){$(this.el).attr("value",this.model.value).html(this.model.name);return this}}),CardTypesView=Backbone.View.extend({initialize:function(){var a=
this.collection.model.length;for(i=0;i<a;i++)this.addOne(this.collection.model[i]);_.bindAll(this,"addOne","addAll")},addOne:function(a){$(this.el).append((new CardTypeView({model:a})).render().el)},addAll:function(){this.collection.each(this.addOne)}}),Country=Backbone.Model.extend(),Countries=Backbone.Collection.extend({url:htz.config.rootContext+"/rest/member-drivers-license/country-list",model:Country}),CountryView=Backbone.View.extend({tagName:"option",initialize:function(){_.bindAll(this,"render")},
render:function(){$(this.el).attr("value",this.model.value).html(this.model.name);return this}}),CountriesView=Backbone.View.extend({initialize:function(){var a=this.collection.model.length;for(i=0;i<a;i++)this.addOne(this.collection.model[i]);_.bindAll(this,"addOne","addAll")},addOne:function(a){$(this.el).append((new CountryView({model:a})).render().el)},addAll:function(){this.collection.each(this.addOne)}}),FPModel=RestModel.extend({defaults:{},url:htz.config.rootContext+"/member/reset/authentication"}),
forgotPasswordView=Backbone.View.extend({defaults:{isRes:!1,isOCI:!1,isResReview:!1,clearError:!1},events:{"click #fpSubmit":"fpSubmit","click #forgotPasswordSection input":"memberAuthentication","change #forgotPasswordSection select":"memberAuthentication","click .captchaRefresh":"getImage","click .learnMoreLink":"learnMoreoverlay","click .bookAsGuest,#bookAsGuest":"bookAsGuestFromFp"},initialize:function(){_.bindAll(this,"renderFP","fpSubmit");this.options.attempts=0;this.options.limit=10;this.forgotPasswordTooltip=
new LightBox;this.renderFP();this.model.on("fieldError",this.highlight,this)},renderFP:function(){var a=_.template($("#forgotPasswordTemplate").html(),{});$(this.el).html(a);if(isRes||isOCI||isResReview)if($("#forgotPasswordContainer .sectionWidthSmall").css("width","auto"),$(".containerTableThickBorder, .containerTableBorder").css("border","none"),isOCI||isResReview)$(".bookAsGuest").hide(),$("#bookAsGuest").hide();(new Countries).fetch({success:function(a,c){new CountriesView({el:$("#driversLicenseCountryState"),
collection:c.data})}});(new CardTypes).fetch({success:function(a,c){new CardTypesView({el:$("#cardType"),collection:c.data})}})},fpSubmit:function(){var a=this;Loader.showLoader();clearError&&this.model.clear();this.model.set({resetMemberNumber:$("#resetMemberNumber").val(),authenticationType:$("input:radio[name=authenticationType]:checked").val(),driversLicense:$("#driversLicense").val(),driversLicenseCountryState:$("#driversLicenseCountryState").val(),cardNumber:$("#cardNumber").val(),cardType:$("#cardType").val(),
captchaCode:$("#captchaCode").val()});this.model.save(this.model.attributes,{success:function(d,c){clearError=!1;var b=c.resultInfo.result;if("success"==b)$.ajax({url:htz.config.rootContext+c.resultInfo.url+"/overlay",cache:!1,beforeSend:function(){},success:function(a){isRes||isOCI||isResReview?$(".lb-content-box").html("").html(a):$(".sectionWidthSmall").html("").html(a);a=new resetPwdModel;new resetPwdView({el:"#pinResetSection",model:a,passwordLevel:""})},error:function(){}});else if("locked"==
b)a.getLockedPage();else if("login"==b||"login_platinum"==b)window.location.href=htz.config.rootContext+c.resultInfo.url;Loader.hideLoader();$("#captchaCode").val("")},error:function(d,c){if(c&&c.responseText){var b=JSON.parse(c.responseText);b&&b.data&&(b.data.resetMemberNumber&&$("#resetMemberNumber").val(b.data.resetMemberNumber),b.data.driversLicense&&$("#driversLicense").val(b.data.driversLicense),b.data.cardNumber&&$("#cardNumber").val(b.data.cardNumber))}clearError=!0;a.model.clear();d.set({errorLocation:"#forgotPasswordContainer .error-list"},
{silent:!0});a.model.trigger("error",d,c);$(".captchaRefresh").eq(0).trigger("click");$("#captchaCode").val("");Loader.hideLoader()}})},getLockedPage:function(){$.ajax({url:htz.config.rootContext+"/member/locked/overlay",cache:!1,beforeSend:function(){},success:function(a){isRes||isOCI||isResReview?$(".lb-content-box").html("").html(a):$(".sectionWidthSmall").html("").html(a);new lockedView({el:"#lockedSection"})},error:function(){}})},memberAuthentication:function(a){a=$(a.target);$(a).closest(".memberAuthenticationRadioRow").find(".memberAuthenticationRadioInput:eq(0)").attr("checked",
!0)},getImage:function(){attempts=this.options.attempts++;limit=this.options.limit;attempts<limit?$("#memberAuthenticationCaptchaImage").attr("src",$("#memberAuthenticationWebContextRoot").html()+"/emember/displayCaptcha.do?img="+(new Date).getTime()+".jpg"):this.getLockedPage()},learnMoreoverlay:function(){this.forgotPasswordTooltip.isInUse()||this.forgotPasswordTooltip.overlay({title:this.$("#captcha-tooltip-title").html()},this.$("#imagedec-content").html())},bookAsGuestFromFp:function(a){$(a.target).closest(".lb-close").triggerHandler("click");
HomePage.bookAsGuestSubmitRes()},highlight:function(a,d){ErrorHelper.reset();ErrorHelper.displayErrors(d,{mappings:[{fields:"resetMemberNumber",target:"errorresetMemberNumber"},{fields:"driversLicense",target:"errorDriversLicense"},{fields:"driversLicenseCountryState",target:"errorDriversLicenseCountryState"},{fields:"cardNumber",target:"errorCardNumber"},{fields:"cardType",target:"errorCardType"},{fields:"captchaCode",target:"errorCaptchaCode"},{fields:"personalAddress1",target:"errorPersonalAddress1"},
{fields:"personalZipCode",target:"errorPersonalZipCode"}],allErrTarget:"#forgotPasswordContainer .error-list"})}}),loginModel=RestModel.extend({defaults:{loggedIn:!1,firstName:"",lastName:"",prefix:"",suffix:"",cookieLaw:htz.config.isCountryinEuropeUnion,memberNumberDisplay:""},url:htz.config.rootContext+"/member/authentication"});
loginView=Backbone.View.extend({defaults:{isRes:!1,isOCI:!1,isResReview:!1,clearError:!1},events:{"click #loginBtn":"loginSubmit","click #forgotPasswordLink":"forgotPassword","click #forgotMemberNumberLink":"forgotMembernumber","click #bookAsGuest":"bookAsGuest","click #inPageUserIDTooltipLink":"infoOverlay","mouseover #loginBtn":"lockBlack","mouseout #loginBtn":"lockWhite","touchstart #loginBtn":"lockWhite","touchend #loginBtn":"lockWhite","mouseup #loginBtn":"lockWhite","mousedown #loginBtn":"lockBlack",
"click #loginCreate":"loginCreate","keydown #loginBox ":"onEnterLogin"},initialize:function(a){_.bindAll(this,"render","loginSubmit","createBlocker","href","forgotPassword","forgotMembernumber","bookAsGuest","isCookied","infoOverlay","loginCreate","onEnterLogin");isRes=this.options.isRes;isOCI=this.options.isOCI;isResReview=this.options.isResReview;this.loginTooltip=new LightBox;clearError=!1;handleMemberRes=this.handleMemberRes=a.handleMemberRes;this.isCookied();"phone"===htz.config.deviceGroup&&
($(".lb-foreground-cont, .lb-content-box").css("background","none"),$("header.lb-header").hide());this.model.on("fieldError",this.highlight,this);a=window.location.toString().split("=")[1];if("reset_locked"==a||"reset_platinum_clublink_locked"==a)new lockedView({el:"#lockedSection"});else if("reset_question"==a||"reset_platinum_clublink_question"==a)new forgotPasswordView({el:"#forgotPasswordContainer",model:new FPModel,limit:10,attempts:0});else if("input"===a||"login"===a)Utils.isUseStoragePolyfill()?
this.showErrorsFromSession(!1,!1,!0):htz.helpers.SessionHelper.getItem("errorData")&&this.showErrorsFromSession(!1,!1,!0)},onEnterLogin:function(a){target=a.keyCode;13==target&&(a.preventDefault(),$("#loginBtn").trigger("click"))},lockWhite:function(){$("#loginBtn span").addClass("icons-white_lock").removeClass("icons-lock")},lockBlack:function(){$("#loginBtn span").removeClass("icons-white_lock").addClass("icons-lock")},isCookied:function(){var a=this;$.ajax({url:htz.config.rootContext+"/member/top/navigation",
dataType:"json",cache:!1,contentType:"application/json",beforeSend:function(){},success:function(d){a.model.set({prefix:d.data.prefix,firstName:d.data.firstName,lastName:d.data.lastName,suffix:d.data.suffix,loggedIn:d.data.loggedIn,memberNumberDisplay:d.data.memberNumberDisplay});isUserCookied=""!=d.data.lastName&&"undefined"!=typeof d.data.lastName?!0:!1;a.render()},error:function(){}})},render:function(){$("#homePageloginTemplate").length&&(this.template=_.template($("#homePageloginTemplate").html()),
$(this.el).html(this.template(this.model.attributes)));isUserCookied&&("tablet"==htz.config.deviceGroup||"desktop"==htz.config.deviceGroup||"all"==htz.config.deviceGroup)&&$(".loginBoxColumn1").css("float","left");0<$.trim(this.model.get("memberNumberDisplay")).length&&$("#loginId").val(this.model.get("memberNumberDisplay"));isRes?$("#bookAsGuest").show():$("#bookAsGuest").hide();document.cookie&&$(".rememberMe").removeClass("mobileHide")},loginSubmit:function(){var a=this;Utils.clearReservationSession();
Loader.showLoader();clearError&&this.model.clear();this.model.attributes.lastName?(this.model.clear(),this.model.set({cookieMemberOnLogin:!0,loginId:"cookie",password:$("#password").val(),loginForgotPassword:$("#loginForgotPassword").val()})):(this.model.clear(),$("#cookieMemberOnLoginInPage").is(":hidden")?this.model.set({loginCreateUserID:$("#loginCreateUserID").val(),loginId:$("#loginId").val(),password:$("#password").val(),cookieMemberOnLogin:!1,loginForgotPassword:$("#loginForgotPassword").val()}):
this.model.set({loginCreateUserID:$("#loginCreateUserID").val(),loginId:$("#loginId").val(),password:$("#password").val(),cookieMemberOnLogin:$("#cookieMemberOnLoginInPage").is(":checked"),loginForgotPassword:$("#loginForgotPassword").val()}));this.model.save(this.model.attributes,{success:function(d,c){var b=c.resultInfo.result;clearError=!1;if("reset_question"==b||"reset_locked"==b||"reset_platinum_clublink_question"==b||"reset_platinum_clublink_locked"==b)$.ajax({url:htz.config.rootContext+c.resultInfo.url+
"/overlay",cache:!1,beforeSend:function(){},success:function(a){isRes||isOCI||isResReview?$(".lb-content-box").html("").html(a):$("#loginSection").html("").html(a);if("reset_question"==b||"reset_platinum_clublink_question"==b)FPm=new FPModel,new forgotPasswordView({el:"#forgotPasswordContainer",model:FPm,limit:10,attempts:0}),Loader.hideLoader();if("reset_locked"==b||"reset_platinum_clublink_locked"==b)new lockedView({el:"#lockedSection"}),Loader.hideLoader()},error:function(){}}),Loader.hideLoader();
else if("phone"==htz.config.deviceGroup)if("success_econsent_required"==b||"success_to_profile"==b||"success_to_erenewal"==b||"login_sms_failed"==b||"success"==b||"success_to_upgrade"==b)if(isRes)HomePage.bookAsMemberSubmitRes();else if(isOCI)window.location.reload();else if(isResReview){var e=a.handleMemberRes||handleMemberRes;e&&"function"===typeof e?e():window.location.href=htz.config.rootContext+c.resultInfo.url}else window.location.href=htz.config.rootContext+c.resultInfo.url;else window.location.href=
htz.config.rootContext+c.resultInfo.url;else"success"==b&&(isRes||isOCI||isResReview)?isRes?HomePage.bookAsMemberSubmitRes():isResReview?(e=a.handleMemberRes||handleMemberRes)&&"function"===typeof e?e():window.location.href=htz.config.rootContext+"/reservation/":window.location.reload():window.location.href=-1!=c.resultInfo.url.indexOf(htz.config.rootContext)?c.resultInfo.url:htz.config.rootContext+c.resultInfo.url},error:function(d,c){clearError=!0;a.model.clear();isUserCookied?a.showErrorsFromSession(d,
c,!1):(d.set({errorLocation:"#homePageloginBox .error-list"},{silent:!0}),a.model.trigger("error",d,c));$("#loginId").val("");$("#password").val("");Loader.hideLoader()}})},showErrorsFromSession:function(a,d,c){var b="",e="";c||(a=$.parseJSON(d.responseText).message,Utils.isUseStoragePolyfill()?Utils.storeItemIE("ieLoginError",a):(a=JSON.stringify(a),htz.helpers.SessionHelper.setItem("errorData",a)),this.initialize());loadLogin=function(){if(0<$("#loginId").length){if(Utils.isUseStoragePolyfill())$.ajax({url:htz.config.rootContext+
"/rest/home/retrieve-ie/ieLoginError",cache:!1,type:"POST",beforeSend:function(){},success:function(a,d,c){e=$.parseJSON(c.responseText);if(null!=e&&""!=e){if(e.fieldErrors&&"undefined"!==typeof e.fieldErrors)for(i=0;i<e.fieldErrors.length;i++)b+="<li>"+e.fieldErrors[i][1]+"</li>";if(e.systemErrors&&"undefined"!==typeof e.systemErrors&&""!=e)for(j=0;j<e.systemErrors.length;j++)b+="<li>"+e.systemErrors[j]+"</li>";$("<ul></ul>").append(b).appendTo(".error-list");$("#homePageloginBox .error-list").show()}},
error:function(){}}),Utils.removeItemIE("ieLoginError");else{var a=htz.helpers.SessionHelper.getItem("errorData");e=JSON.parse(a);if(null!=e&&""!=e){if(e.fieldErrors&&"undefined"!==typeof e.fieldErrors)for(i=0;i<e.fieldErrors.length;i++)b+="<li>"+e.fieldErrors[i][1]+"</li>";if(e.systemErrors&&"undefined"!==typeof e.systemErrors&&""!=e)for(j=0;j<e.systemErrors.length;j++)b+="<li>"+e.systemErrors[j]+"</li>";$("<ul></ul>").append(b).appendTo(".error-list");$("#homePageloginBox .error-list").show();htz.helpers.SessionHelper.removeItem("errorData")}}clearInterval(f)}};
var f=setInterval(loadLogin,100)},bookAsGuest:function(a){$(a.target).closest(".lb-close").triggerHandler("click");$("#redeem").prop("checked",!1);this.options.metaModel.set({isRedeemPoints:!1});HomePage.bookAsGuestSubmitRes()},createBlocker:function(a){a=$(a).blur();$("<div></div>").addClass("formSubmitterOverlay").css({width:a.outerWidth()+25,height:a.outerHeight()+10,top:a.offset().top-5,left:a.offset().left-10}).appendTo("body")},href:function(a,d){this.createBlocker(a);location.href=d},loginCreate:function(){$("#loginCreateUserID").val("true");
this.loginSubmit()},forgotPassword:function(){Loader.showLoader();clearError&&(clearError=!1,this.model.clear());$("#loginForgotPassword").val("forgotPassword");this.loginSubmit()},forgotMembernumber:function(a){this.createBlocker($(a.target));this.href($(a.target),htz.config.rootContext+"/emember/reset/memberNumberRetrieval.do")},infoOverlay:function(){this.loginTooltip.isInUse()||this.loginTooltip.overlay({title:this.$("#userIdTitleContent").html()},this.$("#inPage-useridInfo").html())},highlight:function(a,
d){ErrorHelper.reset();ErrorHelper.displayErrors(d,{mappings:[{fields:"loginId",target:"errorLoginId"},{fields:"password",target:"errorPassword"}],allErrTarget:"#homePageloginBox .error-list"})}});
var warningView=Backbone.View.extend({el:"#loginSection",events:{"click button#warningButton":"hideMe"},initialize:function(){_.bindAll(this,"render","hideMe");this.render()},render:function(){memNavloginModel=new sdlLoginModel;memNavloginView=new sdlLoginView({el:"header",model:memNavloginModel});$("#navLogin").hide();$("#navLogout").css("display","block");var a=_.template($("#warningMessageTemplate").html(),{});Loader.hideLoader();$(this.el).html(a)},hideMe:function(){Loader.showLoader();window.location.href=
htz.config.rootContext+"/reservation/"}}),lockedView=Backbone.View.extend({events:{"click #forgotPassword":"gotoForgotPassword","click .bookAsGuest, #bookAsGuest":"bookAsGuestFromlockPage"},initialize:function(){_.bindAll(this,"render","gotoForgotPassword");this.render()},render:function(){var a=_.template($("#lockedSectionTemplate").html(),{});$(this.el).html(a);if(isRes||isOCI||isResReview){if($("#lockedSection").css("width","auto"),$(".containerTableThickBorder, .containerTableBorder").css("border",
"none"),$("#bookAsGuest").show(),isOCI||isResReview)$(".bookAsGuest").hide(),$("#bookAsGuest").hide()}else $("#bookAsGuest").hide()},bookAsGuestFromlockPage:function(a){$(a.target).closest(".lb-close").triggerHandler("click");HomePage.bookAsGuestSubmitRes()},gotoForgotPassword:function(){$.ajax({url:htz.config.rootContext+"/member/reset/overlay",cache:!1,beforeSend:function(){},success:function(a){Loader.showLoader();isRes||isOCI||isResReview?$(".lb-content-box").html("").html(a):$(".sectionWidthSmall").html("").html(a);
FPm=new FPModel;new forgotPasswordView({el:"#forgotPasswordContainer",model:FPm});Loader.hideLoader()},error:function(){Loader.hideLoader()}});Loader.hideLoader()}});        


window.checkHertzNameSpace("htz.integrated.footer.model");
htz.integrated.footer.model.FooterModel=RestModel.extend({initialize:function(){this.constructor.__super__.initialize.apply(this,arguments)},defaults:{taLoggedIn:!1,isDisplayExternalFooter:!1,isIncludeExternalFooter:!1,isIncludeHertzLinkFooter:!1,externalFooterHeight:0,footerContentHTML:"",twitterUserInfo:{followersCount:""},footerContent:{"footer.footerHide":"","footer.copyRightLine":"","footer.mobFooter.footerHide":"","footer.mobFooter.head":[{sublinks:[{footerLinks:"",footerUrl:""}],footerHeader:""}],
"footer.mobFooter.footerMore":"","footer.column":[{link:[{link:[{url:"",label:""}],header:""}]}],"footer.footerMore":"","footer.mobSite":""},seoPageFooter:"",seoPageTitle:""},url:htz.config.partnerId?htz.config.rootContext+"/rest/footer/pos/"+htz.config.pos+"/dialect/"+htz.config.dialect+"/id/"+htz.config.partnerId+"?systemId="+htz.config.systemId+"&subSystemId="+htz.config.subSystemId:htz.config.rootContext+"/rest/footer/pos/"+htz.config.pos+"/dialect/"+htz.config.dialect+"?systemId="+htz.config.systemId+
"&subSystemId="+htz.config.subSystemId});    
window.checkHertzNameSpace("htz.integrated.footer.views");
htz.integrated.footer.views.FooterView=Backbone.View.extend({el:"#footer-container",events:{"click #title-links .tab":"tabToggleLinks","click #mob-links .tab":"mobToggleLinks","click #social-bar button":"emailSignUpButton","focus #social-email":"emailSignUpFocus","blur #social-email":"emailSignUpBlur","keydown #social-email":"emailSignUpKeyPress"},tabToggleLinks:function(a){$(a.target)!==$(".tab")?($(a.target).closest(".tab").toggleClass("highlight"),$(a.target).closest(".tab").siblings("dl").slideToggle("1000")):
($(a.target).toggleClass("highlight"),$(a.target).siblings("dl").slideToggle("1000"));return!1},mobToggleLinks:function(a){$(a.target)!=$(".tab")?($(a.target).closest(".tab").toggleClass("highlight"),$(a.target).closest(".tab").siblings("dl").slideToggle("1000")):($(a.target).toggleClass("highlight"),$(a.target).siblings("dl").slideToggle("1000"));return!1},emailSignUpButton:function(){var a,b;a=htz.config.dialect;b=$.trim($("#social-email").val());b==HStorage.getItem("signUpVal","s")&&(b="");a="//email.hertz.com/apps/JoinMarketing?lang="+
a.substring(0,2)+"&pos="+htz.config.pos+(""!==b?"&email="+b:b);$("#social-bar form").attr("target","_blank");$("#social-bar form").attr("method","POST");$("#social-bar form").attr("action",a);$("#social-bar form").submit();return!1},emailSignUpFocus:function(){$("#social-email").addClass("highlight");$("#social-email").val("")},emailSignUpBlur:function(){""==$("#social-email").val()&&($("#social-email").removeClass("highlight"),$("#social-email").val(HStorage.getItem("signUpVal","s")))},emailSignUpKeyPress:function(a){if(13===
a.keyCode){var b,a=htz.config.dialect;b=$.trim($("#social-email").val());b==HStorage.getItem("signUpVal","s")&&(b="");a="//email.hertz.com/apps/JoinMarketing?lang="+a.substring(0,2)+"&pos="+htz.config.pos+(""!==b?"&email="+b:b);$("#social-bar form").attr("target","_blank");$("#social-bar form").attr("method","POST");$("#social-bar form").attr("action",a);$("#social-bar form").submit();return!1}},resizeDocument:function(){$(window).on("resize",function(){var a=$("#container").width();992<=a&&($("#title-links dl").show(),
$("#title-links .tab").addClass("highlight"));600<=a&&992>a&&($("#title-links dl").hide(),$("#title-links .tab").removeClass("highlight"))})},initialize:function(){this.template=this.options.template;this.data=this.options.model;this.render()},render:function(){"IRAC"===htz.config.subSystemId&&(this.footerContentView=new htz.integrated.footer.views.FooterContentView({el:"#footer-container",template:"#footer-tpl",data:this.data.get("footerContentHTML")}),$("#bottom-links li:last-child").addClass("no-pipe"),
HStorage.setItem("signUpVal",$("#social-email").val(),"","s"),this.resizeDocument());if("RYANAIR"===htz.config.subSystemId){var a=this.data.get("footerContent");this.footerDesktopView=new htz.integrated.footer.views.FooterDesktopView({el:"#title-links",template:"#desk-tpl",data:a["footer.column"],more:a["footer.footerMore"],hide:a["footer.footerHide"]});this.footerMobileView=new htz.integrated.footer.views.FooterMobileView({el:"#mob-links",template:"#mob-tpl",data:a["footer.mobFooter.head"],more:a["footer.mobFooter.footerMore"],
hide:a["footer.mobFooter.footerHide"]});this.footerCopyrightView=new htz.integrated.footer.views.FooterCopyrightView({el:"#copyright-content",template:"#copyright-tpl",copyright:a["footer.copyRightLine"]});this.footerSeoView=new htz.integrated.footer.views.FooterSeoView({el:"#mixed-content",template:"#mixed-tpl",data:this.data.attributes.data})}return this}});
htz.integrated.footer.views.FooterContentView=Backbone.View.extend({initialize:function(){this.render()},iconMouseEnter:function(){this.src=this.src.replace("origin","hover")},iconMouseLeave:function(){this.src=this.src.replace("hover","origin")},render:function(){try{this.$el.append(_.template($(this.options.template).html(),{footerContent:this.options.data}))}catch(a){}var b=$("#social-bar li img");"reservationOnHomepage.jsp"!==htz.config.legacyPage&&$("#footer-container #seo-content").empty().hide();
b.length&&(b.on("mouseenter",this.iconMouseEnter),b.on("mouseleave",this.iconMouseLeave));return this}});
htz.integrated.footer.views.FooterDesktopView=Backbone.View.extend({initialize:function(){this.render()},render:function(){this.$el.append(_.template($(this.options.template).html(),{deskList:this.options.data,more:this.options.more,hide:this.options.hide}));var a=$("#title-links a"),b=this;a.each(function(c){-1!=$(a).eq(c).attr("href").search("lightBox")||-1!=$(a).eq(c).attr("href").search("openPopup")?(b.$el.find(a).eq(c).attr("name",$(a).eq(c).attr("href")),b.$el.find(a).eq(c).attr("href","javascript: void(0);")):
(-1!=$(a).eq(c).attr("href").search("legalView.jsp")||-1!=$(a).eq(c).attr("href").search("privacyPolicyView.jsp"))&&b.$el.find(a).eq(c).attr("target","_blank")});return this}});htz.integrated.footer.views.FooterMobileView=Backbone.View.extend({initialize:function(){this.render()},render:function(){this.$el.append(_.template($(this.options.template).html(),{mobList:this.options.data,more:this.options.more,hide:this.options.hide}));return this}});
htz.integrated.footer.views.FooterCopyrightView=Backbone.View.extend({initialize:function(){this.render()},render:function(){this.$el.append(_.template($(this.options.template).html(),{copyright:this.options.copyright}));return this}});htz.integrated.footer.views.FooterSeoView=Backbone.View.extend({initialize:function(){this.render()},render:function(){this.$el.append(_.template($(this.options.template).html(),{data:this.options.data}));return this}});
htz.integrated.footer.views.footerUtilityView=Backbone.View.extend({el:"#footer-container",initialize:function(){this.template=this.options.template},openLightBox:function(a,b){lbFooter=new LightBox;lbFooter.overlay({width:600,url:a,title:b,center:!0})},openPopUp:function(a,b){wo=window.open(a,b,"toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=480,height=440,left="+(window.screen.width/2-240));wo.focus()}});Footer=new htz.integrated.footer.views.footerUtilityView;            
window.checkHertzNameSpace("htz.integrated.footer.controller");htz.integrated.footer.controller.FooterController=function(){return{showFooterPage:function(){var b=$.Deferred(),c=new htz.integrated.footer.model.FooterModel;c.fetch({cache:!1,dataType:"json",success:function(a){b.resolve(a)},error:function(){new htz.integrated.footer.views.FooterView({model:c})}});$.when(b).done(function(a){new htz.integrated.footer.views.FooterView({model:a})})}}}(); 


var Slider=function(){function h(){if($(window).width()>k){l.find(".pagination-prev, .pagination-next").hide();for(var a=0;a<b.length;a++)b[a].pageCont.show()}else if(!(0>g||g>b.length-1))for(a=0;a<b.length;a++)a==g?(b[a].pageCont.show(),b[a].pageCont.find(".pagination-prev, .pagination-next").show(),window.scrollTo(0,0)):b[a].pageCont.hide()}function e(a){if(!b||1>=b.length||0>a||a>b.length-1)return!1;g=a;return!0}var g=0,b=null,k=480,l=null,n=k;return{goTo:function(a){e(a)&&h()},previous:function(){var a=
b[g],c=a.handler;c&&"function"==typeof c?c(a.pageCont,"P")&&e(g-1)&&h():e(g-1)&&h()},next:function(){var a=b[g],c=a.handler;c&&"function"==typeof c?c(a.pageCont,"N")&&e(g+1)&&h():e(g+1)&&h()},first:function(){e(0)&&h()},last:function(){e(b.length-1)&&h()},currentSlide:function(){return b&&0<b.length&&$(window).width()<=k?b[g]:null},checkWidth:function(){var a=$(window).width();if(n>=k&&a<=k||n<=k&&a>=k)n=a,h()},startWithConfig:function(a,c){if(a&&!(1>=a.length||Modernizr&&!Modernizr.mq("only screen and (min-width: 0px)"))){c&&
(c.context&&(l="string"==typeof c.context?$(c.context).eq(0):c.context),c.maxWidth&&(n=k=c.maxWidth));l||(l=$("body").eq(0));for(var i=[],e=0;e<a.length;e++){var f=a[e],d=l.find("#"+f.id);0<d.length&&(f.cont=d.eq(0),i.push(f))}if(i&&!(1>=i.length)){g=0;b=[];for(var e=i.length,j,m,f=0;f<e;f++){j=i[f];0==f?(d=null,m=i[f+1]):f==e-1?(d=i[f-1],m=null):(d=i[f-1],m=i[f+1]);d&&(j.prevLabel=d.title?d.title:htz.content.previous);m&&(j.nextLabel=m.title?m.title:htz.content.next);if(d=j)d.prevLabel&&$("<div />").addClass("pagination-prev").html("<div><div class='icons-ft_arrow_left'></div></div><div>"+
d.prevLabel+"</div>").prependTo(d.cont).hide(),d.nextLabel&&$("<div />").addClass("pagination-next").html("<div>"+d.nextLabel+"</div><div><div class='icons-ft_arrow_right'></div></div>").appendTo(d.cont).hide();b[b.length]=j.handler?{pageCont:j.cont,handler:j.handler}:{pageCont:j.cont};j.isActive&&(g=f)}0<b.length&&($(window).bind("resize.slider",Slider.checkWidth),l.find(".pagination-prev").click(function(){Slider.previous()}),l.find(".pagination-next").click(function(){Slider.next()}),h())}}}}}(); 
window.checkHertzNameSpace("htz.utils.helpers");htz.utils.helpers.NetworkHelper=function(){return{isOnline:function(){return!0}}}();   
window.checkHertzNameSpace("htz.utils.web.helpers");htz.utils.web.helpers.Navigator=function(b){var a;return{navigate:function(c){var d=b(c);0<d.length&&(a&&b(a).hide(),d.show(),a=c)},getCurrentPage:function(){return a}}}($);     
window.checkHertzNameSpace("htz.utils.web.helpers");htz.utils.web.helpers.Rotar=function(b){return{rotateTo:function(a){a&&(b.href=a)}}}(window.location);  
window.checkHertzNameSpace("htz.utils.web");htz.utils.web.DOMHelper=function(a){return{createPageElm:function(b,c,d){return a.createElm(c+"-"+b+"-page-container","div",!0,d)}}}(htz.utils.Utils);
(function(a){a.configure({spinner:htz.utils.Spinner,lightBox:htz.utils.LightBox,networkHelper:htz.utils.helpers.NetworkHelper,navigator:htz.utils.web.helpers.Navigator,rotar:htz.utils.web.helpers.Rotar,domHelper:htz.utils.web.DOMHelper,notifier:window,slider:Slider})})(htz.utils.config.UtilConfig); 
               
	      
	  
	  
	                
		
	 
	                                                  
	                          
	           
	     
	      
	           
	
	
	 
	 
	
	 
	
	
	
	
	
	
	
	
	
     

       

	
	

	             
	      
	      

	
	
	                                                                
	                                                        
	                                                        
	                 
	  
	
	
	                  
	
	      
	     
	
	
	
    
	
	
	
    
	

	
	
	   


/* EOF */
